### ISSUE TITLE
Change cluster serializer to not use the class manifest in the message.

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#13654]
imported from https://www.assembla.com/spaces/akka/tickets/3654

The cluster messages use the class manifest in the message envelope leading to fully serialized class names in every message.

**Comment by hepin1989** [comment]
this would be nice.
please take a look how ```kryo``` is doing for registration
https://github.com/EsotericSoftware/kryo#registration

after registration,only need send the registered class ID.

**Comment by drewhk** [comment]
One of the planned features is that remoting builds a dictionary of these during runtime, assigning a short ID for the most common manifests encountered. I.e. it is similar to the registration approach, only it is built dynamically at runtime.

**Comment by hepin1989** [comment]
one concern about this,if you generate dynamically,you may want to using MurmurHash3 to mapping clazz'name to id or something like this,otherwise,if the id mismatch between peers for the same class,then may cause problem.another approach may doing this at compile time, we could mark the message which may send cross wire with a annotation or extends a special trait.

**Comment by hepin1989** [comment]
https://github.com/lukehutch/fast-classpath-scanner this lib is very handy to find all subclass

**Comment by patriknw** [comment]
SerializerWithStringManifest improves this, but we cannot change without breaking compatibility (e.g. 2.4 sending to 2.3 node)

**Comment by patriknw** [comment]
This is not mandatory to complete for 2.6.0. It should be possible to change this whenever, as an optimization. Requires two step roll out.
1. Include the new serializers (or knowledge about the new manifests) but not use them in toBinary yet
1. Use them in toBinary

It could actually be good to do it in 2.6.1 or later, since otherwise we would have to backport it to 2.5.x to be able to support rolling update from 2.5.x to 2.6.0.

**Comment by patriknw** [comment]
First step done. Keeping ticket open until next step is completed.

**Comment by patriknw** [comment]
Second step forgotten for 2.6.4, so moving to 2.6.5.
