### ISSUE TITLE
Add tracing SPI / hooks to akka-http

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13817]
imported from https://www.assembla.com/spaces/akka/tickets/3817

**Comment by henrikno** [comment]
Why was this closed?

**Comment by ktoso** [comment]
Because we're not working on it ;)
Feel free to submit PRs if you're interested.

**Comment by henrikno** [comment]
I just got here by a series of other issues "closed in favor of" this one, and wondered what's the current state. Specifically, the first post that got me here was [re-add log tagging](https://github.com/spray/spray/issues/266) (request/correlation id), which apparently was a feature in spray.
> "It was available up until we moved spray-io into akka for the new akka-io. "

There was a an [old PR](https://github.com/akka/akka/pull/1865) related to this, but I couldn't see it being merged. So I'm wondering, has there been any more recent improvements on anything related to this, or has it been dormant since then?

**Comment by ktoso** [comment]
That PR is unrelated to this ticket kind of actually. That was Actor tracing, this here would be more about HTTP tracing (so X-Trace etc).

Tracing in actors is in a limited form implemented in Lightbend Monitoring, but not the complete thing too (yet)
