### ISSUE TITLE
Inbox docs incomplete

### ISSUE THREAD

**Issue by jboner** [akka/akka#13876]
imported from https://www.assembla.com/spaces/akka/tickets/3876

Missing imports. Not clear where 'inbox()' is coming from.
Perhaps also show that one can create it through 'new Inbox(system)'.
http://doc.akka.io/docs/akka/snapshot/scala/actors.html#The_Inbox

**Comment by jczuchnowski** [comment]
I've stumbled upon this old ticket while going through the documentation. The Inbox example is indeed not unclear when it comes to imports. The problem is the `inbox()` comes from `ActorDSL` which is deprecated at this point, although the reson for deprecation is not directly connected to the Inbox.
So what's the course of action here? Just add the import to the docs? Or is there some refactoring involved - like creating an `InboxDSL` object so that nobody will have to use `ActorDSL` anymore?

**Comment by patriknw** [comment]
@jczuchnowski If it's just a matter of adding some imports to the documentation a pull request would be welcome. Otherwise we plan to deprecate Inbox and don't want to spend major time on improving it.

**Comment by jczuchnowski** [comment]
@patriknw ok, so from what you say it's not really worth it to spend much time on this. I just added the missing import to the code snippet. Unless you think we should have a warning in this part of documentation that the Inbox is going to be deprecated?
