### ISSUE TITLE
Exclude unreachable observations from downed node in convergence check

### ISSUE THREAD

**Issue by patriknw** [akka/akka#13875]
imported from https://www.assembla.com/spaces/akka/tickets/3875

Investigate if unreachable observations from downed node can be excluded in the convergence check.
Discussed in context of the failure in SurviveNetworkInstabilitySpec [3871](https://www.assembla.com/spaces/akka/tickets/3871).

**Comment by patriknw** [comment]
SurviveNetworkInstabilitySpec sometimes fails because of this issue.
It is expected that a quarantined node is to be removed from the cluster. The test sometimes fails because the quarantined node is not removed by the leader.

    Set(akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth) contained element akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second (SurviveNetworkInstabilitySpec.scala:292)

The reason for that is that it is not convergence, and the reason for that is that the quarantined node (`second`) has marked another node (`sixth`) as unreachable and been able to spread that information.

See the second row in the below reachability table.

    unreachable: Set(Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth, status = Up), Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second, status = Down))


    reachability: 
    akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second: Unreachable [Terminated] (7)
    akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (13)
    akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second: Unreachable [Terminated] (25)
    akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Reachable [Reachable] (12)
    akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Reachable [Unreachable] (13)
    akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second: Terminated [Terminated] (11)
    akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second: Unreachable [Terminated] (13)
    akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@second: Unreachable [Terminated] (11)

The proposed solution is to exclude reachability observations from Downed nodes in the convergence check. Note that quarantined (Terminated) nodes are immediately and automatically Downed.

**Comment by jbergfi** [comment]
Eagerly waiting for the next 2.3.x release, I think I've experienced this issue when testing network failures in our system using Akka 2.3.9.

I have 4 nodes and firewalling the connection between node 1 and 2, this causes 1 and 2 to see each other as unreachable. I would have expected this could be resolved by downing one of the nodes (through the akka-cluster script) but that has no immediate effect. Apparently I have to down both nodes and then they both go away from unreachable but that is exactly what I don't want to do. Node 1 and 2 are copies of each other to keep redundancy so I can't resolve the situation by taking both of them down and since no Gossip convergence happen while nodes are unreachable I'm stuck.

I feel this is a quite critical issue so I'm happy to see it's already on it's way out. When can I expect to have my hands on the next official 2.3.x release?
