### ISSUE TITLE
BalancingPool should not support Broadcast message

### ISSUE THREAD

**Issue by patriknw** [akka/akka#15030]
Just confusing. Discussed here: https://groups.google.com/d/msg/akka-user/D-qVGymeIKw/irpb1uIqtdEJ

**Comment by nlw0** [comment]
I am learning Akka, and I have just lost a whole day of work because of this. The documentation seems to be quite emphatic that each and every worker would get the Broadcast message, and the BalancingPool documentation does mention that they share the same box, but it would be nice to have a hint that something like that might happen. This router should just not support the Broadcast message, while I get now why that happens, it'a clear contradiction of the message semantics.

**Comment by patriknw** [comment]
agreed, thanks
