### ISSUE TITLE
Rethink PersistentBatch - do we need to force atomic batch writes onto plugins?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#15377]
Based on a discussion from: https://github.com/akka/akka/pull/15339/files#r13540786

This task is about rethinking, and possibly loosening up requirements given to journals, about writing a batch as atomic "blob" of data. More details below.

**Comment by michaelom** [comment]
After reading this thread, I still wonder if you should relax the requirement of atomic batch writes, or at least clarify the what it means in the context of event sourcing. The word “atomic” is very prone to misinterpretation, depending if you approach the problem on database-level or on API-level.

Let’s take a look at Greg’s “1-command, N-events” scenario. I would argue you can archive all this without “atomic” writes. The requirements from an API-perspective are:

* a) PersistentActor: during recovery, replay the persistent batch (or up to a sequence number) and include events of an "event-batch" if and only if all events of the persistent batch have been written successfully to the underlying storage implementation. 

* b) PersistentView: same as PersistentActor, as PersistentView is effectively always in recovery mode.

* c) Deletion: it must be possible to mark individual events of an event-batch as deleted, without breaking a) and b)

For most data stores an atomic write (a transaction) is the most natural way to achieve a), b), and c).

I imagine a document based-storage (such as MongoDB) could achieve all of this with “marker-documents” at the start and the end of the batch. Not sure if this is a feasible approach, but at least I would not have to squash a batch of events into a single document in order to satisfy atomicity. From an API level it is conceived as atomic (all or nothing) but it does not require atomic transactions from a database point of view.

**Comment by gregoryyoung** [comment]
A batch has no meaning in reads only in terms of an atomic write. There
should be no knowledge that something was in a batch when it was written.

On Friday, January 23, 2015, michaelom <notifications@github.com> wrote:

> After reading this thread, I still wonder if you should relax the
> requirement of atomic batch writes, or at least clarify the what it means
> in the context of event sourcing. The word “atomic” is very prone to
> misinterpretation, depending if you approach the problem on database-level
> or on API-level.
>
> Let’s take a look at Greg’s “1-command, N-events” scenario. I would argue
> you can archive all this without “atomic” writes. The requirements from an
> API-perspective are:
>
>    -
>
>    a) PersistentActor: during recovery, replay the persistent batch (or
>    up to a sequence number) and include events of an "event-batch" if and only
>    if all events of the persistent batch have been written successfully to the
>    underlying storage implementation.
>    -
>
>    b) PersistentView: same as PersistentActor, as PersistentView is
>    effectively always in recovery mode.
>    -
>
>    c) Deletion: it must be possible to mark individual events of an
>    event-batch as deleted, without breaking a) and b)
>
> For most data stores an atomic write (a transaction) is the most natural
> way to achieve a), b), and c).
>
> I imagine a document based-storage (such as MongoDB) could achieve all of
> this with “marker-documents” at the start and the end of the batch. Not
> sure if this is a feasible approach, but at least I would not have to
> squash a batch of events into a single document in order to satisfy
> atomicity. From an API level it is conceived as atomic (all or nothing) but
> it does not require atomic transactions from a database point of view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/issues/15377#issuecomment-71129729>.
>


-- 
Studying for the Turing test

**Comment by ktoso** [comment]
Resolved in https://github.com/akka/akka/issues/17818
