### ISSUE TITLE
Provide Persistence TestKit

### ISSUE THREAD

**Issue by ktoso** [akka/akka#15571]
I think there are some uses of prepping events and then testing an PersistentActor / PersistentView.

We could provide a TestKit for akka persistence that would ease Journal interaction.
Esp. prepping and cleaning up, as in "given these Events, what will my actor do".

Whishlist (I will keep it updated as new comments come into this thread):
- [ ] journal setup ("given these events...")
- [ ] journal cleanup
- [ ] assertions on journal event writes "expect event E persisted" ???
- [ ] helping out with forcing replay kill+restart ???
- [ ] fail / recover simulator? It would be given a sequence of messages and one assertion, then fail the actor between arbitrary messages, and check the assertion. Coining the term RecoveryCheck?

We once mentioned it in discussions but didn't see a ticket yet.
Related https://groups.google.com/forum/#!topic/akka-user/FNOGnAFej9Y

**Comment by fractaloop** [comment]
:+1:

**Comment by patriknw** [comment]
This will unfortunately not make it into 2.4.0. We can add it in a minor 2.4.x release. Help from community would be great.

**Comment by patriknw** [comment]
I think this is an excellent thing for someone in the community to contribute with. Perhaps not very easy, but there are some starting points, such as in-memory journal implementations.

**Comment by rkuhn** [comment]
Not to mention that akka-testkit was my own entry point into the Akka universe!

**Comment by filosganga** [comment]
About Journal clean-up and cleanup we have implemented it in a naive way: assuming the ActorSystem is restarted every test, we provide a new couple of temporary folder each test.

**Comment by ktoso** [comment]
With Akka Streams now we could provide a "journal writer sink (for given persistence id)" which would help here a bit too.

**Comment by tonicsoft** [comment]
@filosganga In order to retain maximum flexibility, I think the persistence test kit should remain fully in memory, at least for unit tests. The file system is static global state which is a no-no for tests in general, (hence the existence of [jimfs](https://github.com/google/jimfs)). Also when developing locally it's a pain because if I kill the tests halfway through then the PersistenceTestKit would not be able to clean up and leave rubbish lying around.

It would also make the following use cases more difficult as you assumed the actor system will be restarted after each test:

- restart (i.e. create new) ActorSystem within a single test but keep the same journal. 
- start two ActorSystems that share the same journal.

A better approach would be to allow the journal or journal factory/test kit to be injected into the ActorSystem at creation time, or even to the Actor via Props like any other dependecy instead of automagically looked up from config and presumably instantiated via reflection. The Journal is an external dependency of the ActorSystem so think Dependency Injection. This allows the author of the test to decide exactly how and when the journal is cleaned up, and which Actors/ActorSystems share the same journal. Most of the time journal clean would not even be required because each test would create fresh instances.

If Dependency Injection principles had been followed from day 1 this would be easier and for example [this](https://github.com/akka/akka/issues/15587) would never have been an issue.

**Comment by filosganga** [comment]
@tonicsoft I think swapping the journal implementation is out of the scope of this issue. 

The reason I said that is because the JournalReader is tight coupled with the implementation and so it is not supposed to be an abstraction. Running some test on the LevelDb and running production on Cassandra does not provide enough confidence as the two plugin implementation are completely difference.

The Journal is part of the ActorSystem and cannot be injected. It would go against the Akka principle. If we inject it from outside, who is going to control the Journal Lifecycle? What if the Journal become unavailable? The ActorSystem cannot do anything and just failing continuously because the Journal is failing. IMHO Dependency Injection and Actor just does not work together.

**Comment by tonicsoft** [comment]
@filosganga I see, I did not realise that. I take your point that as the implementations vary, using the real journal implementation is essential for acceptance/integration tests. For unit tests though, I'm not 100% convinced. Are you suggesting setting up a Cassandra node for every unit test (if using Cassandra in production)?

I'm too new to Akka to fully appreciate the explanation in your last paragraph - it sounds interesting and I will think on it as I learn more about Akka, but without DI testing is always awkward. Based on it I will water down my suggestion somewhat: 

I would love to be able to play around with an in memory journal that I controlled the scope of (the provided inmem implementation seems tied to the life-cycle of the ActorSystem as you mentioned, and therefore does not allow testing of restarts or clusters).

**Comment by zaharidichev** [comment]
@ktoso @patriknw 
Is this still alive and wanted ? Looks like a neat feature and something that I would love to pick up. I forsee that i will have a bit more free time in the following weeks so I can invest it in getting that going. 

To begin with I intend to setup the foundations and provide a facility that would allow to setup the state of the journal (without assertions, RecoveryCheck and all the other nice things). I hope that while doing that we can come to conclusion on the whole question regarding injection and lifecycle of the "test journal". To be honest I am a bit unclear on these last points. 

Maybe something akin to a Fixture like class can be thought of that will contain all the basic necessities for interacting with the journal. And then that could be instantiated for every test. The only not cumbersome way of wiring in the test journal I see at this point is to  have some kind of a pre - configured actor system within this fixture that makes use of the in-memory test journal. What do you think about these points ?

**Comment by patriknw** [comment]
@zaharidichev That would be great. It would be very useful to have Testkit for Persistence.

Remember that the utilities shouldn't be for a specific testing framework (like Scalatest or Junit).

**Comment by zaharidichev** [comment]
@patriknw Yes certainly, It will be free of any bound to any test libraries. I am just a bit ambivalent about the question of injection. It feels hi-jacking the actor system to make it use an alternative journal implementation  robs the user of some controll. Any thoughts ?

**Comment by patriknw** [comment]
I think you can start with a configured in-memory journal. It’s possible to access the journal via the Persistence extension (internal api), so it shouldn’t be any problem populating or clearing it.

**Comment by manonthegithub** [comment]
I've done some experimenting for this feature in my [branch](https://github.com/manonthegithub/akka/tree/wip-akka-persistence-testkit/akka-persistence-testkit). I assumed that persistence testkit can extend actor testkit and have similar method semantics. So I used approach similar to that in TestKit where we have shared state that is injected into journal. This can be useful to you.

**Comment by zaharidichev** [comment]
@manonthegithub certainly looks like a good start. Thanks a lot !

**Comment by zaharidichev** [comment]
@patriknw Looking at the `InmemJournal` to get some ideas for the testkit journal. And meanwhile I am thinking. Shouldn't that be `volatile` https://github.com/zaharidichev/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/journal/inmem/InmemJournal.scala#L54 or I am missing something ?

**Comment by manonthegithub** [comment]
@zaharidichev this should not be volatile, because all journal methods are invoked inside `receive` method of the actor which guarantees synchronisation, as I understand.

**Comment by manonthegithub** [comment]
@zaharidichev as well as Future should guarantee synchronisation. As long as imems's journal method passes in Future all the changes are synchronised.

**Comment by zaharidichev** [comment]
@manonthegithub Again, I might be missing something. But if you have some shared state, references by  two or more actors (e.g. an in-memory journal) would that be safe ? I do not think so. Not sure I understand the point about futures ?

**Comment by manonthegithub** [comment]
@zaharidichev In case of shared state in my example, it is accessed not only from actor but from any other thread using testkit, so concurrent map should be used not only to synchronise memory but also for atomicity of modifying operations.

In case of `InmemJournal` it is assumed to be used only inside actor's receive method so `volatile` is not needed because actor is responsible for synchronisation.

About Future. I mean that all the methods of the journal return Future, so any changes to variables that are done before Future starts are visible to other threads after future returns no matter volatile or not.

**Comment by manonthegithub** [comment]
@zaharidichev also, there is only one actor accessing state in case of InmemJournal so it is thread safe.

**Comment by manonthegithub** [comment]
@zaharidichev one more point... map in InmemJournal is immutable, so it is 100% thread safe. But atomicity there is guaranteed by actor's receive method. On the other hand making variable volatile gives nothing to thread safety, because volatile variables are not atomic.

**Comment by zaharidichev** [comment]
@manonthegithub Yes, you are actually right about one thing and is the fact that atomicity is guaranteed by receive in this case. Sorry, I just missed the fact the AsyncWriteJournal is an actor itself and this very actor is the one invoking these methods that update the state. So yes, that is thread safe :) I take all of it back. I was living some different assumptions.

**Comment by tonicsoft** [comment]
I think there is a critical requirement here that hasn't been made explicit.

Any Persistence TestKit should not be tied to unit tests only. It should be possible to run a real actor system as part of a whole application (many actors) but use the Persistence TestKit (for black box style tests).

This is less useful for testing failure scenarios of individual actors but essential for verifying that a whole application behaves correctly on startup.

Furthermore, it should be possible to create tests that involve multiple actor systems as part of a cluster, which share the same Persistence TestKit, as recently I wanted to test migration of a persistent actor to a new node in a cluster.

For me, this is what shows some part of the journal implementation must be injectable on ActorSystem creation. @zaharidichev rather than robbing the user of some control I feel it gives the user more control.

**Comment by zaharidichev** [comment]
@tonicsoft 

>  I am just a bit ambivalent about the question of injection. It feels hi-jacking the actor system to make it use an alternative journal implementation robs the user of some controll. Any thoughts ?

Quating myself here, but I totally agree with you. I meant that not having dependency injection and instead hi-jacking the system and overwriting its journal robs the user out of controll. Injecting the actor system in contract gives ultimate control. However, we really do not have much of an option of injection, do we ?

**Comment by manonthegithub** [comment]
@tonicsoft @zaharidichev Some kind of journal backend (with all kind if facilities) can be written and then injected into journal implementation so that this backend could be shared. Backend probably can be implemented as akka extension which can be discovered in any part of application.

**Comment by patriknw** [comment]
You can perhaps use the ActorSystemSetup thing to do the sharing between several ActorSystems (in same jvm), but I’m not convinced that this an important aspect of the testkit. https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/setup/ActorSystemSetup.scala

**Comment by manonthegithub** [comment]
Hey @zaharidichev, are you making progress? 
I can continue to evolve my branch which was submitted in case you are having problems.

**Comment by patriknw** [comment]
If this is picked up again there is a good starting point at https://github.com/akka/akka/pull/25393

**Comment by manonthegithub** [comment]
I've made some more progress and took into account most of your comments. I also implemented serialization of the messages which can be turned off.
Sorry, I thought I will have more time for it.

**Comment by pawelkaczor** [comment]
:+1:
