### ISSUE TITLE
akka persistence: multiple plugins

### ISSUE THREAD

**Issue by TimPigden** [akka/akka#15587]
It would be useful to allow akka persistence to employ different journal  plugins at the same time. One use case is porting event-source data from one database to another as underlying architecture requirements change.
Another is simply different life-cycles of the event-sourced models, for example when dealing with non-server applications with a defined process cycle for internal data vs some data that is persisted long-term - for example to a backend like EventStore - where the events are separately accessed from other applications.

**Comment by Andrei-Pozolotin** [comment]
after a bit of prototyping with akka-persistence we discovered that different types of persistent actors need either different settings for the same plugin, or different plugins altogether.

there is a "promise" of this feature in Persistence.scala

can we have it in 2.4?

**Comment by Andrei-Pozolotin** [comment]
lets just do it now for 2.4

please suggest how do you see a) actor -> plugin mapper and b) multi config name space?
using persistenceId to resolve to plugin/config profile seems convoluted. 
how if we add to PersistentActor explicit configuration name:

/**
* Persistent actor configuration name. 
* Must be located in the following 'reference.conf' section:
* akka {
*    persistence {
*       configuration {
*          name { // User-provided custom configuration name.
*              journal { ... }
*              snapshot-store { ... }
*          }
*       }
*    }
* }
*/
def configuration: String = "" // Empty default for legacy config name space.

**Comment by patriknw** [comment]
@Andrei-Pozolotin I agree, this would be a great feature.

We can change the signature of the `journalFor(persistenceId: String): ActorRef` method.

I'm thinking that a journal should have an identifying String key, that can be defined by overriding a method in the `PersistentActor`. That key match a configuration section, e.g. `akka.persistence.journal.leveldb`.

We probably need a default value for this key, so that it works as it is today, i.e. using what is defined in config `akka.persistence.journal.plugin`.

Similar for snapshot-store.

Would you be interested in taking a stab at it?

**Comment by Andrei-Pozolotin** [comment]
ok. please move this out of the way #16633

**Comment by bantonsson** [comment]
Fixed by #16794
