### ISSUE TITLE
Make PersistentActor.persist iterate over a Traversable type instead of immutable.Seq 

### ISSUE THREAD

**Issue by Fristi** [akka/akka#15644]
Would it be possible to let `PersistentActor.persist` accept a traversable type instead of a immutable.Seq? I stumbled upon writing this today;

`persist(u.items.map(CharacterScanList.Added))(evs => state = evs.foldLeft(state)(_ apply _))`

Where `evs` is a `Seq[CharacterScanList.Added]`. The `u.items` property appears to be a list and seems not be converted as `collection.immutable.Seq[_]` so it is using the overload:

`def persist[A](event: A)(handler: A ⇒ Unit): Unit`

So folding seemed like the right solution. But actually it isn't the right way? It will persist a Seq[CharacterScanList.Added] now as event while it should persist a batch of CharacterScanList.Added events.

**Comment by rkuhn** [comment]
Thanks for pointing this out: we need to remove the overloaded method (i.e. introduce `persistAll`) and then I think we can permit `Seq[T]` even though that is mutable (because we only traverse it once within the method).

**Comment by sibex** [comment]
Yesterday I've spend almost an hour to figure out why the scala compiler demands an event handler of type `Seq[Event] => Unit`. It's because the default `scala.Seq` is `scala.collection.Seq` and not `scala.collection.immutable.Seq`. Actually a no-brainer. But please remove/rename the overloaded method.

There is another issue. The API documentation says:
 > Asynchronously persists `events` in specified order. This is equivalent to calling
    `persist[A](event: A)(handler: A => Unit)` multiple times with the same `handler`,
    except that `events` are persisted atomically with this method.

This is misleading. The `events` are **not** persisted atomically as a block in an ACID way. The current implementation is:
```scala
  final def persist[A](events: immutable.Seq[A])(handler: A ⇒ Unit): Unit =
    events.foreach(persist(_)(handler))
```
Other persistent actors can write to the log between the events. Or for some of the events `persist` may fail. If the new `persistAll` can somehow achieve the promised atomicity then it should take an _all or nothing_ atomic event handler of type `immutable.Seq[A] => Unit`.

**Comment by patriknw** [comment]
@sibex Thanks for feedback.

**Comment by ktoso** [comment]
Actions here:
- remove `persist(Seq)`
- add `persistBatch(Seq)`
- atomicity guarantees are to be defined as follows:
  - persist - each write is atomic
  - perstiBatch the batch is atomic
