### ISSUE TITLE
Add session renegotiation to SSL/TLS

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15833]
The SSL/TLS support in #15402 doesn't support session renegotiation.

**Comment by rkuhn** [comment]
Preliminary sketch of the types (based on web-based research, so comments welcome):
~~~scala
sealed trait SessionRead
case class SessionNegotiated(session: SSLSession, parameters: SSLParameters) extends SessionRead
case class SessionReadData(data: ByteString) extends SessionRead

sealed trait SessionWrite
case class SessionRenegotiate(parameters: SSLParameters, invalidate: Boolean) extends SessionWrite
case class SessionWriteData(data: ByteString) extends SessionWrite

def addSSL(f: Flow[ByteString, ByteString], parameters: SSLParameters): Flow[SessionWrite, SessionRead]
def addNoSSL(f: Flow[ByteString, ByteString]) = Flow[SessionWrite].collect{case SessionWriteData(d) => d}.via(f).map(SessionReadData)
~~~
The last two will eventually be represented as standalone pieces with four ports, so the method signatures only serve to document the intent.

On the HTTP side the HttpRequestParser will have to keep track of which bytes were received with which session and reject requests that are “split” between them. The HttpRequest will include a field that holds the session that was in effect when the request was received, and the entity’s stream will need to be terminated upon renegotiation. A renegotiation will then be effected by including this request in the HttpResponse; the response itself will only be sent once the new session has been established, so that follow-up requests are delivered with the new parameters in effect.
