### ISSUE TITLE
Add client-side response routing DSL

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#15909]
Make up a nice API corresponding to the routing DSL, but for the client side; it also does response routing in addition to request building.

**Comment by sirthias** [comment]
This is part of the bigger initiative to support a high-level HTTP client interface as tracked as #16856.

**Comment by guersam** [comment]
It would be helpful for #16591, describing the API from the client side in the integration tests.

**Comment by abesanderson** [comment]
Does this include support for consuming external http services(eg REST)?  I've been working with the javadsl and parity isn't quite up to the scaladsl as far as marshalling/unmarshalling goes.  It's been a pretty big headache finding anything in docs for examples of taking http responses and getting objects from them.  All the documentation related to the Jackson deserialization seems to be around consuming the entity in a request on the server side rather than anything with response on the client side.

**Comment by ktoso** [comment]
In general we're lacking a "simple client" which is what this ticket is about. 
Thanks for the feedback @abesanderson, we know it's not very good yet and are thinking hot to best fix it – one of the ways would be implement the simple client API, which this ticket is part of.

**Comment by abesanderson** [comment]
Thanks for the quick response!  I think a large part of it could be resolved with improvements to the javadsl unmarshallers which take care of extracting the entities from the http response object.  One key advantage of Jersey's rxjava based client right now is the JAX-RS dependency injection which handles most of the deserialization for you.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
