### ISSUE TITLE
Add automatic redirection handling

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#15990]
The high-level client-side API should support some form of configurable redirection handling.

Several things need to be taken into account:
 *  dealing with headers to be used for the redirected request. This has security implications.
   * user-agent [spray-user](https://groups.google.com/forum/#!topic/spray-user/1F1cSBeYPh8)
   * cookies
   * authorization
 * redirection not allowed for non-idempotent request (already implemented in spray) for some redirection status codes
 * which HostConnector to use for cross-domain redirections

Before starting on this, it would make sense to go through the mailing list / spray tickets to find further cases we might need to support.

A first solution could only support redirections to the same domain, where keeping certain headers may be safer (but: cookies with path constraints set).

Maybe also consider how browsers deal with redirections.

This is part of the bigger initiative to support a high-level HTTP client interface as tracked as #16856.

/cc @sirthias

**Comment by huntc** [comment]
I've just stumbled across the need for this and will have to of course hand craft it. I just thought that you'd like to know of at least one person who needs this functionality.

**Comment by francisdb** [comment]
Another case to handle would be redirect loops

**Comment by CptnKirk** [comment]
Also +1 for this feature.  Did tracking of this issue get lost?  Was 1.0-RC4, now I see it has no milestone. Yet I don't see that anyone has modified the milestone since sirthias on Jun 24.

**Comment by coreyauger** [comment]
Also +1 from me.

**Comment by ktoso** [comment]
Logging a +1 :point_up: [February 24, 2016 3:11 PM](https://gitter.im/akka/akka?at=56cdba24bfb1cf9a7ff2badb)

We'd welcome contributions of this feature, anyone interested in helping out? :-)

**Comment by RomanIakovlev** [comment]
I'd like to try to help with this, since I need it in my project. However, I'm totally new to akka source code, so I'd definitely need some initial guidance. What would be the best channel to ask questions related to this?

**Comment by ktoso** [comment]
Thank a lot for offering help on that :-)
Best discussed here actually as it's nice and async, or gitter (however this week the team is mostly offline, planning the next months of development, so we may be a bit slow to respond - sorry about that).

**Comment by RomanIakovlev** [comment]
Thanks, I'd be happy to help. Just not sure if I'm up to this task, but one never knows unless one tries. :)

Ok, here are the initial questions.

1. API overview. I imagine adding a couple of properties to the `akka.http.scaladsl.model.HttpRequest`, like `followRedirects: Boolean = false` and `maxRedirects: Int = 1`. Or maybe wrap these two in a single case class. What do you think?
2. Where the actual redirect handling code should live? So far my best guess is `akka.http.impl.engine.client.OutgoingConnectionBlueprint`, but I'm in doubts.

This is just to get my thoughts straight before I can begin even thinking of possible solutions.

**Comment by jamesmulcahy** [comment]
@RomanIakovlev You probably also need to consider adding an option to decide which headers are re-submitted when the re-direct is followed.  Spray used to drop the headers, which is apparently an appealing approach to some, but doesn't suit all scenarios.  See spray/spray#1045.

**Comment by RomanIakovlev** [comment]
I've started working on this issue, and I'm sort of stuck on some questions I can't resolve myself. 

My overall idea is to create a `GraphStage[BidiShape[HttpRequest, HttpRequest, HttpResponse, HttpResponse]]`, which will sit on top of the `OutgoingConnectionBlueprint`. This new stage will keep track of incoming request (In1) and forward them downstream (Out1). When response comes (In2), the stage checks if the response is redirect, and, if it is, sends the new redirected request (Out1). When the "real" response will come, it's forwarded to requester (Out2). I don't want to send the pull request so far, but, if you wish, you can have a look at the current implementation in branch `wip-15990-http-client-redirect-RomanIakovlev` in my forked Akka repo at https://github.com/RomanIakovlev/akka/

This implementation fails at one of the tests in `akka.http.impl.engine.client.HighLevelOutgoingConnectionSpec`, concretely on the "catch response stream truncation" one. It's not completely clear to me what's the expected behavior for that test, so maybe someone can clarify?

Besides that, I have 2 questions about this approach in general. 

First of all, do you think it makes sense? I mean, the `GraphStage[BidiShape]` part of it. Maybe there's a better way? 

Secondly, if the `BidiShape` is the way to go, is it supposed to support multiple requests in flight? If yes, then how received response can be mapped to a incoming request? I need this correspondence to be able to copy the headers to the redirected request from the original request (and maybe for something else that I don't know yet). If only single request in flight can be supported, then I'm not sure how the pipelining will be dealt with.

I hope my questions make sense. I'm on vacations now and will be able to dedicate more time to this issue for the next week, especially if I'll have some guidance from the Akka core team. :)

**Comment by RomanIakovlev** [comment]
Another thought has just occurred to me. The existing `OutgoungConnectionBlueprint` does support pipelining, obviously, but, as far as I can tell, it also guarantees the order of responses to be the same as the order of requests. Is it correct? If yes, then I can rely on this fact to get correspondence between requests and responses in my redirect supporting graph stage to support copying certain headers into redirect requests. Would that work?

**Comment by ktoso** [comment]
This had some progress in https://github.com/akka/akka/issues/20135 but we decided together that it wasn't quite there yet. Would be awesome to see it be picked up again (@Romanlakovelv again perhaps if he has time?)

**Comment by gaydenko** [comment]
Have you some workaround, please? It is a hard stopper.

**Comment by ktoso** [comment]
a) follow the redirect manually.
b) help us deliver this feature - contribute!
c) use a different http client.

**Comment by gaydenko** [comment]
Thanks. I know the a) is the best for akka, but resources are limited at the moment resulting in preferring the b).

**Comment by drewhk** [comment]
Take a look at this for implementing retries: https://github.com/akka/akka-stream-contrib/pull/26

**Comment by drewhk** [comment]
currently in contrib, but seems like useful for many things so we might want to migrate it to akka-streams and consider adding it to the HTTP client API somehow.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
