### ISSUE TITLE
Add marshallers for standard jdk xml interfaces

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#16210]
akka-http should provide marshallers for `org.w3c.dom.Node`/`javax.xml.SAXSource`

**Comment by 2beaucoup** [comment]
For element-streaming support we should introduce something like https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/xml/XmlFrameDecoder.java.

**Comment by ktoso** [comment]
Great that there's one out there.
That's exactly what I implemented for myself in a project years ago, would
be awesome to have it in Akka or akka-stream-contrib <3

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 2 August 2016 at 14:31:09, 2beaucoup (notifications@github.com) wrote:

For element-streaming support we should introduce something like
https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/xml/XmlFrameDecoder.java
.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/issues/16210#issuecomment-236889594>, or mute
the thread

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
