### ISSUE TITLE
Provide actor Restart message

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16252]
it is a bit surprising that while there is system ```Kill``` message, there is no ```Restart``` one.

is there a real reason for that? our current work around for monkey wrench testing is via aspectj

```
@Aspect
class CommandAspect {
  import CommandAspect._

  @Pointcut("execution(* akka.actor.ActorCell.receiveMessage(*)) && this(cell) && args(msg)")
  def receiveMessagePointcut(cell: ActorCell, msg: Any): Unit = {}

  @Around("receiveMessagePointcut(cell, msg)")
  def receiveMessageAround(point: ProceedingJoinPoint, cell: ActorCell, msg: Any): Unit = {
    msg match {
      case RESTART_ACTOR =>
        throw new RestartException(msg.toString)
      case _ =>
        point.proceed()
    }
  }

}
```

**Comment by rkuhn** [comment]
With akka-typed I’m moving away from all these special messages: there are the declared messages that an actor supports, and there are system signals. Signals cannot be sent from the outside—from other actors—because they are generated by the system to notify low-level events like child actor failure.

So, I’d say that if you want your actor to be restartable at will then you’ll have to foresee a message for that. And if an actor does not foresee such a message then it cannot be (externally) restarted.

**Comment by Andrei-Pozolotin** [comment]
I see your point, but we still see cases when "signal metaphor" would help. Since we run with kamon (aspectj) in production, we will continue to use aop for this use case. Feel free to close this issue.

**Comment by rkuhn** [comment]
Thanks for the discussion, I’ll keep it in mind while exploring the brave new world—maybe something comes of it much later ;-)

**Comment by Andrei-Pozolotin** [comment]
thank you
