### ISSUE TITLE
Add load tests for streams looking for performance regressions and memory leaks

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16290]

**Comment by benjamingeer** [comment]
We recently switched back from Akka HTTP to Spray because we found that Akka HTTP leaks memory. I haven't had time to make a minimal test case for you, but it involved hammering our REST API using [Apache Bench](http://httpd.apache.org/docs/2.4/programs/ab.html) for 20 minutes with 50 concurrent connections, and watching the application's total heap allocation in [VisualVM](http://visualvm.java.net/). With Akka HTTP, the average allocation increased steadily, up to the JVM's maximum heap size:

![screen_shot_2015-02-09_at_12 18 02](https://cloud.githubusercontent.com/assets/558389/6249280/73e534f8-b786-11e4-87f7-a4f5bec5a50b.png)

With Spray, the average allocation is roughly constant:

![screen_shot_2015-02-17_at_16 31 05](https://cloud.githubusercontent.com/assets/558389/6249314/9f695dde-b786-11e4-895c-08e4c04f9d96.png)

**Comment by jrudolph** [comment]
@benjamingeer thanks for reporting. I think this warrants an extra ticket. I recreated your report in https://github.com/akka/akka/issues/16900.

**Comment by drewhk** [comment]
Getting closer, we need to implement fusable stream-of-stream ops and the fusing method itself. Moving out from M1 though.
