### ISSUE TITLE
`HttpEntity.Strict` toString prints char int values instead of entity text

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#16395]
`HttpEntity.toString` is difficult to read in the Akka HTTP preview releases, e.g.

```
HttpResponse(400 Bad Request,List(Date: Tue, 25 Nov 2014 17:26:27 GMT, Server: akka-http/2.3.6),HttpEntity.Strict(application/json; charset=UTF-8,ByteString(123, 10, 32, 32, 34, 114, 101, 113, 117, 101,…
```

In Spray 1.3.1, the entity body was printed as a string: [HttpEntity.NonEmpty.toString](https://github.com/spray/spray/blob/1ce512cbd17380655fe1756b524c7f19dc9a3de3/spray-http/src/main/scala/spray/http/HttpEntity.scala#L81)

Please could we have something similar in Akka HTTP? It makes testing much harder if the error responses from your web server are printed as int char values instead of as an error message.

(Perhaps this needs to be overridden in `HttpEntity.Strict` based on the ContentType rather than in `ByteString` itself, in case the body is a binary type.)

**Comment by RichardBradley** [comment]
Is there any chance of seeing this in the HTTP 1.0 milestone?

I've just had another painful debugging session where my error message looks like
```
Cannot parse response from remote server: HttpEntity.Strict(application/json,ByteString(123, 10, 32, 32, 34, 101, 114, 114, 111, 114, 34, 58, 32, 34, ...
```

Converting this output to a readable string is surprisingly difficult if the ByteString is very long, as the scala compiler won't accept an `int[]` literal over a certain size: "Method code too large".

I'll see if I can make some time to submit a PR for this issue in the next few days.

**Comment by sirthias** [comment]
This ticket is currently not a high-prio ticket for us, so now, there probably won't be any work on it from our side in the immediate future.
However, it appears to be a pretty self-contained thing (at least if we restrict the fix to `HttpEntity.Strict` instead of `ByteString` for now), so I guess you'll have a good change of getting a contribution PR merged, if you like... :)

**Comment by ktoso** [comment]
Isn't this more about making `logRequest` and friends print something nicely, instead of the raw byte string?
We do not want to change the toString on it itself.

**Comment by ktoso** [comment]
Note, there was this very cool toString by @jrudolph that we might want to put on ByteString in any case.

**Comment by catalin-ursachi** [comment]
@ktoso - I do agree that, unlike in Spray ([HttpEntity.NonEmpty.toString](https://github.com/spray/spray/blob/1ce512cbd17380655fe1756b524c7f19dc9a3de3/spray-http/src/main/scala/spray/http/HttpEntity.scala#L81)), we shouldn't have toString decode the entity as text in all cases; if it's of a binary type, the text decoding is both useless and distracting.

However, I do think that, for entities that are explicitly identified as non-binary, and which have a defined HttpCharset, in pretty much all instances where toString is called it's more useful to have the actual text, rather than an array of integer values. While a 'renderAsText' method could contain that behaviour without overwriting toString, it'd be extemely cumbersome to have to explicitly call it at every point where we might want to inspect a text-formatted entity (e.g. the runtime debugger), compared to simply using the implicitly called 'toString'.

For instance, if we have an HttpRequest that may or may not contain a Strict entity, then if we've overridden 'toString', we can simply call:

```scala
request.toString
```

to get the best possible rendering of the request's entity. By contrast, if we've only added a 'renderAsText' method, we have to call:

```scala
request.entity match {
  case strict: Strict =>
    strict.renderAsText
  case nonStrict =>
    entity.toString
}
```

and with increasing degrees of complexity if we've got, say:

```scala
case class HttpError(request: HttpRequest, response: HttpResponse)
```

Additionally, 'renderAsText' may well be confusing if, in fact, we only render as text those Strict entities which have a non-binary ContentType.
