### ISSUE TITLE
Bind failure doesn't propagate to the stream properly

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16425]
`akka-http-core-experimental/testOnly akka.http.ClientServerSpec`

**Comment by drewhk** [comment]
Interesting. There is an explicit call to onError() in that code path, and the path seems to be executed.

**Comment by drewhk** [comment]
Ok, there seems to be a race in the test that is caused by the delayed materialization of the actual listen actor, so in my runs it is the *first* stream that fails and not the second, and the second is the one that succeeds. Seems to be solved by awaiting on the local address of the first stream first.

**Comment by drewhk** [comment]
but unbind has some issues which I don't understand. Also, we failed the unbind future when the original bind failed, I would say this is unexpected. We should only fail the localAddress future.

**Comment by drewhk** [comment]
btw, the test also expected an immediate onError, but first a subscription is handed out and then the onError. This is valid behavior even if it is not optimal.
