### ISSUE TITLE
Enable (late?) programmatic access to `max-content-length` limit

### ISSUE THREAD

**Issue by huntc** [akka/akka#16468]
`akka.server.parsing.max-content-length` is not required when dealing with streams unless strict entities are required. For example, having this setting apply does not make sense when loading large files via multipart file data. The size of the file to consume in this instance becomes an application concerns, perhaps associated with the amount of disk space available.

**Comment by sirthias** [comment]
Coming back to issue now (and aiming for a solution in the immediate future) I'd summarize the discussion
so far as follows:

1. We want to enable (late) programmatic definition of a length-limit for request entities,
   e.g. with something like ``request.withEntityLengthLimit(bytes)``.
2. By default the configured, rather aggressive (small) limit should be "attached" by the HTTP-layer.
3. The user should be able to increase or decrease the limit on their side.
4. The limit should apply to chunked requests just as well as unchunked ones.
5. A "limit-exceeded" error would be raised by error closing the request entity stream. It also means that
   the connection is burned for subsequent requests because we stop reading from the incoming side.
   After the response has been sent the connection must be (hard-)closed.

The requirements have these consequences:

1. We cannot immediately decide (in the HTTP layer) whether an incoming request has an exceedingly-large entity
   or not. We need to dispatch the request to the user in all cases because the user might apply a large enough
   limit after having received the request.
2. The best time for applying the configured or programmatically set limit appears to be the time the request
   entity stream is materialized. It can only be materialized once anyway and materialization happens on the
   user side, so the user has a chance to apply whatever limit before materialization.
3. If the entity is unchunked the decision whether the entity is small enough can be made right at
   materialization time (because we have the `Content-Length` header). For chunked requests we need to
   inject a counting stage which checks for length overrun as the entity is being consumed.

Implementation proposal:

The core problem to solve here is how to surface an adaptable limit to the user without introducing mutability
and without disrupting the established and otherwise quite clean entity model API.
And we need to uphold this property:

```scala
val requestA = HttpRequest(entity = HttpEntity.Default(20MB))
  .withEntityLengthLimit(10MB)
val requestB = requestA.withEntityLengthLimit(30MB)
requestB.entity.toStrict(...).get // ok
requestA.entity.toStrict(...).get // throws
```

I currently don't see a perfect solution here (maybe someone else does) but could imagine that we can introduce
one small constraint that is acceptable and allows for 98% of use cases to be fine:
If we allow `withEntityLengthLimit(bytes)` to return an `Option[HttpRequest]` rather than a plain `HttpRequest`,
i.e. if we allow `withEntityLengthLimit` to sometimes *not* be available, then we can do it by introducing a
special type of `Source` that also internally keeps an (unapplied) limit.
When setting a new length limit we would simply copy the special source and set a new limit.
The drawback is that the user would have to apply a custom limit *before* somehow transforming the ``Source``
inside an entity, because only the source created by the HTTP layer itself is the *special* source that
has the unapplied limit.
All other solutions I could think of were worse in terms of required (und unpleasant) changes to the
entity model or ugly hacks.

Thoughts?

**Comment by rkuhn** [comment]
Taking a step back (and disregarding the requirement of immutability for now) we have three things we can potentially work with:

* the HttpRequest object
* the Source object
* the Source’s materialized value

The last option would allow this to be solved without mutability, e.g. by materializing to a `Promise[Long]` (or isomorphic) which could then be completed within a `mapMaterializedValue` transformation—problematic is the question of how long the Source should wait before emitting elements without having been “reconfigured” because this step will not be required.

The Source itself could be used to store a mutable field that can be updated by a directive, but this only works if the HttpRequest type enforces that this kind of “special” Source is used, otherwise this could easily be broken by custom directives—breakage would be detected and could lead to exceptions, though.

The HttpRequest could store this value if we make the Source aware of the request; since the request contains the Entity which contains the Source this will require mutability—in order to get this right we would have to make it difficult to create custom HttpRequest objects without going through appropriate factories.

I’m leaning towards the second solution.

**Comment by sirthias** [comment]
Ok, so you are essentially thinking along the same lines as me. Keeping the solution confined to the Sources in the `HttpEntity` sub-types appears to have the least amount of detrimental effects on the current API.
Also, this feature is "small" in that only a minority of people will actually want or need to use it. So I'd strongly prefer a solution that doesn't have *any* cost (API-wise) to everyone else.

I'll give the "special source" approach a spin then.

**Comment by rkuhn** [comment]
Yes, sounds good, thanks!

**Comment by ktoso** [comment]
Missed commenting here yesterday somehow... (I blame the jetlag :airplane:).
Sounds very good (custom source), thanks for picking it up @sirthias!

**Comment by ktoso** [comment]
We have the low-level thing solved, and will add a high level directive very soon.
