### ISSUE TITLE
ServerBinding.startHandling* must not throw away errors

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16507]
E.g. by returning `ForeachSink`'s `Future[Unit]` result to be able to subscribe to errors.

**Comment by drewhk** [comment]
currently the localAddress Future reports this failure. I can easily add another future for this purpose.

**Comment by jrudolph** [comment]
This still happens in some form using the `Http.bindAndHandle` methods. The reason is that they are implemented as `bind().to(Sink.foreach(_.flow.join(handler).run())).run()`.

If something happens during the inner `run()`, i.e. materialization fails, errors will be swallowed because `foreach` only reports them to its own materialization value which is discarded by using `Flow.to`.

**Comment by jrudolph** [comment]
Discussed a possible solution with @sirthias: adapt the return value of `bindAndHandle` to include a Source of the user-flow generated materialized values. `bindAndHandle(A)Sync` could return an additional Future[Unit] which would be completed with an error when the materialization on one connection fails.

Right now an error during materialization of a connection flow will always also kill the binding. I guess we keep it that way?

**Comment by sirthias** [comment]
Actually I think the solution that `bindAndHandle` returns another source is not the best.
This would mean that the user would have to actively consume this source again in order to drive the process. And that would kind of defeat the purpose of `bindAndHandle`, which is to provide a concise and convenient overload for the most common case "just do it".

After thinking about this more I'd vote for keeping `bindAndHandle` and friends as simple as possible and simply log any errors that might be occuring. If the user want something else, like access to the materialized valued of their handler flows, they should be using `bind`.

**Comment by jrudolph** [comment]
Yep, right, I didn't think of the backpressure issue. Yes, let's log.
