### ISSUE TITLE
Add path directives to add/remove the trailing slash

### ISSUE THREAD

**Issue by guersam** [akka/akka#16543]
Copied from this ML thread: https://groups.google.com/forum/#!topic/akka-dev/ZpEHVVdu5W4

> akka-http has a strict path matching policy about trailing slash by distinguishing `pathEnd`, `pathSingleSlash` and `pathEndOrSingleSlash` directives. `pathEndOrSingleSlash` is not recommended, and users are encouraged to stick to a certain style. [1]
> 
> Currently, the client gets 404 NotFound if the URI doesn't match due to the trailing slash. It's fine when developing REST API, but when it's a web site, it might be confusing to some users who directly typed the URI. 
> 
>To fill this gap, does it make sense to add some built-in directives to keep the URI with/without the trailing slash by 301 redirect like this? It might also be a mental safety-net for some programmers who are familiar to some other web frameworks which have 'tolerant' behaviour.
>
> [1] http://googlewebmastercentral.blogspot.de/2010/04/to-slash-or-not-to-slash.html

```scala
withoutTrailingSlash { // redirect from '/users/' to '/users'
  pathPrefix("users") {
    pathEnd {
      // user list ...
    } ~
    pathPrefix(UUID) { userId =>
      pathEnd {
        // user profile ...
      } ~
      path("articles") {
        // articles of the user ...
      }
    }
  }
}
```

**Comment by rkuhn** [comment]
@smlin Whether or not something is “bad” is not an objective measure. Since we do already support the ability to ignore a trailing slash I think we can close that part of this thread. This ticket is about adding a convenience work-around for sloppy clients (a.k.a. humans), and there a redirect is technically superior to ignoring the trailing slash (as discussed in the Google webmaster link), also for debugging an API with command line tools (because the redirect will be obvious). Both mechanisms are opt-in, so no harm done.

@2beaucoup Thanks for your good inputs, but please keep the discussion style impersonal even when things heat up a little (“As pointed out in the linked documents” instead of “If you’d have read”). I’m sure nobody meant any harm, so this is just a friendly reminder.

**Comment by 2beaucoup** [comment]
@rkuhn I actually used both versions (the second referring to the first). But point taken. :)

**Comment by smlin** [comment]
@rkuhn Thank you for clarifying.
