### ISSUE TITLE
FastFuture.scala in release-2.3-dev is copyright Typestrict, Inc

### ISSUE THREAD

**Issue by danarmak** [akka/akka#16566]
[This file](https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/util/FastFuture.scala) says it's copyright Typestrict. This is either a find-and-replace artifact or an internal Typesafe / Typelevel joke.

Or it might be a conspiracy,  because for some reason using Github to search this repo for "typestrict" doesn't find this file...

**Comment by patriknw** [comment]
ping @jrudolph @sirthias

**Comment by sirthias** [comment]
Since I put this in I'm pretty sure it's an unintentional search-n-replace artifact.
I think I even remember applying a `safe` to `strict` replacement at one point, to globally change method names in the file. IDEA folds the copyright header by default, which probably contributed to this change going unnoticed.

Anyway, nice find! :)

**Comment by danarmak** [comment]
For some reason (why?) Github finds no code results for "typestrict", so other files might have the same error. I suggest searching a local checkout.
