### ISSUE TITLE
FlexiMerge doesn't support reacting to demand from downstream

### ISSUE THREAD

**Issue by sirthias** [akka/akka#16565]
The current `FlexiMerge` design appears to be flawed:

The `MergeLogicContext` sports a `isDemandAvailable` method, which I am supposed to use in order to determine whether `ctx.emit(element)` is currently allowed.
However, if this is not the case, i.e. if I am not allowed to push to downstream because no demand is currently available, what am I supposed to do with the element?
There doesn't appear to be a way to react to demand from downstream.

**Comment by rkuhn** [comment]
I agree with @sirthias that isDemandAvailable should be removed since we plan on making improvements later that would bereave it of the little usefulness it currently has.

On the first question I’m leaning towards just stating that FlexiMerge is about emitting zero or one element in response to some input—which is a limitation but still very useful.

**Comment by drewhk** [comment]
Before anyone freaks out, this does **not** mean that we won't add support for arbitrary input output port stages that do more complex logic. The question whether FlexiMerge needs to gain new powers, or it remains as it is now.
