### ISSUE TITLE
Support REST API doc generation

### ISSUE THREAD

**Issue by guersam** [akka/akka#16591]
Related ML thread: https://groups.google.com/forum/#!topic/akka-user/d18_smRGeoE

> Hi,
>
>Although this topic has been discussed several times in spray-user list [1], I'd like to refresh this issue because I think it's an important feature for wider adoption as well as the mostly asked ones like WebSocket.
>
>Spray/akka-http's routing DSL is the best among the existing framework/libraries IMO, however, it's cascaded and mixed routing structure makes automated documentation and code generation somewhat difficult. Although there's already good looking spray-swagger, it's annotation based approach seems too verbose sometimes.
>
>A random thoughts for alternatives are:
>1. Macro based introspection which extracts routing structure from the DSL
>2. Integration with the testkit (either way of doc <-> test code generation) instead of with routing code directly
>
>I know it isn't urgent now, just hoping to gather some wisdom to bring it to the next step for the long term goal. 
>
>
>Regards,
>Jisoo
>
>
>[1] https://groups.google.com/forum/#!searchin/spray-user/swagger
>[2] https://github.com/gettyimages/spray-swagger
>[3] http://www.scalatra.org/2.3/guides/swagger.html

**Comment by sirthias** [comment]
As already discussed several times on the spray ML automatically producing documentation for the current server-side routing DSL is close to impossible to do robustly.
The DSL is built upon nested functions which are fully opaque to the outside. One would have to use macros to inspect them at compile time. Also, because the DSL allows any kind of Scala construct on all levels any kind of route structure analysis tool will be very easy to trip up.

As a simply example, think about how you would want to automatically document this snippet:

```scala
path("order" / IntNumber) { orderId =>
  if (orderId < 10000) // legacy orders only support GET
    get {
      parameters('foo, 'bar) { (foo, bar) =>
        // ...
      }
    }
  else
    get {
      parameters('baz) { baz =>
        // ...
      }
    } ~
    post {
      // ...
    }
}
```

In its current form the routing DSL is simply too powerful to allow for robust automatic inspection.
We will have to evolve it into something less powerful, that additionally separates route structure construction from route structure exection (2 phases instead of one, as we have it know), in order to have a chance to to this properly.

**Comment by rkuhn** [comment]
Possible idea: instead of trying to analyze and interpret the route definition, why not observe its execution while running the test suite (that every app surely must have)? The added benefit is that only those parts are documented that are also exercised in the tests. Another component here would be to provide test fixtures for certain RESTful resource patterns to make this task easier.

**Comment by kodemaniak** [comment]
+1

Using the tests to produce documentation for a REST API sounds like a good idea. For Spring MVC there is 

https://github.com/spring-projects/spring-restdocs

I specifically like the integration with asciidoctor.

**Comment by drewhk** [comment]
interesting idea. If this is ever implemented then it would be nice to have an intermediate format emitted so that it can be used in various other ways.

**Comment by smlin** [comment]
One more idea: instead of generating documentation by API it possible would be better generate an interface of API from other format like swagger.

**Comment by hhimanshu** [comment]
Any progress or recommendation on this?

**Comment by ktoso** [comment]
The akka team does not have enough people/time to tackle this problem. 
External contributions are more than welcome!

**Comment by kodemaniak** [comment]
A couple of weeks ago I've done a proof-of-concept, that tried to provide something similar to Spring Restdocs (https://github.com/spring-projects/spring-restdocs) for akka-http. The project can be found here:

https://github.com/kodemaniak/akka-http-restdoc

(I hope the README is accurate and does not only work on my computer)

That POC is far from being complete. But currently I use a spray port of it to document our main microservice at work. My conclusion after a couple of weeks is that following such an approach (i.e. using asciidoctor for the bulk of documentation and extracting request/reply information from the tests) feels like the right way to go. It fits very well together. It is much easier to keep the docs in sync with the actual behaviour, at least the request/response headers and bodies are generated from tested code, and you save some work since you don't have to write down JSON bodies or HTTP requests by hand.

I thought I throw that POC into this dicsussion to get some more feedback. Our spray port is a bit more advanced already, but adding the missing bits and pieces also to the akka-http version would be rather simple.

**Comment by analytically** [comment]
@kodemaniak awesome approach, would love to see this developed further!

**Comment by rkuhn** [comment]
Thanks @kodemaniak for pushing this, looks like a good starting point!

**Comment by phani1kumar** [comment]
I have recently started to know about akka-http and scala and started off to build my first microservice in this technology. I humbly accept that I am not qualified to make points in this space, but would like to seek guidance on the following points:

1. We are pretty much used to follow javadoc standards while writing code in which we already provide the documentation of the methods, and parameters. Can we somehow plug this information into the swagger API? through macros / some scala magic! ==> If there are some specific documentation only to be known to the programmers / next maintainers, we may introduce exclusion syntax in the existing javadoc comments!

2. Scala as per my lame understanding has a very strong type support, hence the optional/ mandatory part of the types may be made available to swagger transparently again through macros / some scala magic

By following the above two points, we may avoid large portions of the annotations and the annotations we will be left with would be the routes! 

I know, I might be sounding stupid, but I just want to get your expert opinion on my lame thoughts.

**Comment by michallepicki** [comment]
My not-so-pretty [attempt](https://github.com/TouK/akka-http-swagger/blob/master/src/test/scala/pl/touk/swaggerAkkaHttp/test/Example.scala) at allowing to write separate endpoints that are automatically documented in swagger.

This is ugly and very likely has errors, e.g. I have a problem with merging parameter directives with (my own) [SwaggerPathMatcher](https://github.com/TouK/akka-http-swagger/blob/master/src/main/scala/pl/touk/swaggerAkkaHttp/swgr/SwaggerPathMatcher.scala). I can't compile

 `path("user" / IntMatcher("userNumber")) & parameter('x.as[Int])` 
when I'm using the original `parameter` Directive so parameters can't be auto-documented yet.

But the general idea is to give an interface for writing simple auto-documented API endpoints that generate akka-http directives and to allow extending and wrapping them with normal akka-http directives, what do you think?

**Comment by ktoso** [comment]
Note for interested parties, I currently believe to be more efficient and powerful: generating the structure from tests, similar to: http://docs.spring.io/spring-restdocs/docs/1.0.x/reference/html5/#getting-started-documentation-snippets-invoking-the-service

**Comment by FeiWongReed** [comment]
Guys-guys-guys. 

Automatic docs generators is the only one part of problem.

What about me - I'm strictly need API _schemas_. It's impossible to generate _schema_ during the test.

Akka-http is definitely needs directives tree introspection. And it's not so hard to implement this. I may try to start this project, but I need to be sure that it will be accepted to upstream.

**Comment by ktoso** [comment]
I suggest starting out as separate project and if it makes sense to be pulled into Akka HTTP we can do so later on.

**Comment by FeiWongReed** [comment]
Ok, I have to possible ways to implement this:

1. External library, which will duplicate all the features of scaladsl and be able to build tree with introspection data.
2. Break into directives and built introspection abilities in.

I prefer second option. I already have partial implementation of (1) and it requires a lot of work until completion.

**Comment by ktoso** [comment]
`trait IntrospectableDirectives` instead of the Akka `Directives` and you're good to go.
Keep method parity and it's a drop-in replacement for pure Akka HTTP then. I don't see why it has to be "break into Akka's directives" right away. It can be a library, exposing same methods. If it works out, everyone is happy, and if you'd like to contribute then we have a place to start from.

**Comment by FeiWongReed** [comment]
Ok, got it.

**Comment by pjfanning** [comment]
Hi,
I have forked the swagger-spray project (https://github.com/swagger-akka-http/swagger-akka-http) and I have published it to maven central. The code requires the swagger.io annotations and JAX-RS annotations but at least, gives support for creating Swagger API models based on request and response case class definitions. It isn't ideal to duplicate the routing informational in Swagger annotations but it may be useful as an interim solution.
The swagger definition allows for a lot of description about the API that can't be inferred from the Akka-Http Routing DSL so any solution that does generate swagger docs from Akka-Http routes would ideally allow informational items like license details and API descriptions to be provided.

**Comment by bfil** [comment]
@FeiWongReed have you made any progress around the `IntrospectableDirectives`? I'm trying to look into using a similar approach to generate basic API docs. I'm hitting huge road blocks though around some of the types, for example the `PathMatcher` obfuscates everything about the matched requests paths, and needs to be rebuilt in a compatible/introspect-able way. How far have you gone with this?

**Comment by FeiWongReed** [comment]
Unfortunately I still have not enough time to finish it. I have my own subset, working for my services, but its dirty and can't be used in arbitrary project.

**Comment by FeiWongReed** [comment]
> for example the PathMatcher obfuscates everything about the matched requests paths, and needs to be rebuilt in a compatible/introspect-able way. How far have you gone with this?

You may use implicit macros and construct not only pathmatchers but also additional introspection data. Anyway its hard to do that in general way. Proper solution is to make scaladsl introspectable.

**Comment by rklaehn** [comment]
@FeiWongReed is your incomplete impl somewhere on github? We have an urgent need to have something like this, but would be fine with a limited subset as well.

**Comment by FeiWongReed** [comment]
For now I may offer you only this idea (just an idea): https://github.com/akka/akka/issues/19334

**Comment by ktoso** [comment]
FYI, we core team won't be available to implement this feature, we're very much looking forward to PRs about it though!
There's plenty of ideas in this thread, please ping and discuss if you'd like to give it a shot :)

**Comment by cppexpert** [comment]
For those who is interested in having Swagger documentation for their akka services I can say that after trying a lot of semi-automatic ways I ended up using http://editor.swagger.io. Yes, you need to manually maintain `yaml` but it's cheaper and faster than dealing with bugs of Swagger reflection and other issues.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by digital-wonderland** [comment]
@ktoso would it please be possible to provide links to the transferred tickets when transferring them? I realise it is more work but otherwise everyone, who is subscribed, has to bother Google or Githubs search, to find the new one, as well as anyone how stumbles upon this ticket later.

**Comment by alias1** [comment]
If you load the page on GitHub, look above the 'transferred' post. The new
task is referenced.

**Comment by digital-wonderland** [comment]
Heh, sorry, I was missing the forrest cause of all the trees. Thanks a lot for the pointer!

**Comment by alias1** [comment]
No worries :)

**Comment by ktoso** [comment]
Yes, as @digital-wonderland mentioned - the link is there automagically once you go to github.
I'll amend the comment to explain that perhaps.
