### ISSUE TITLE
Ability to customise HTTP parse error handling

### ISSUE THREAD

**Issue by jroper** [akka/akka#16606]
Given that akka-http is very strict on its http header parsing, and there are a lot badly behaving clients and browsers out there, it would be quite common for clients to encounter bad request errors.  Many users of Play like to customise this error handling, including providing custom error pages, as well as logging errors to a monitoring system so that application errors can be quickly noticed.  Play currently provides callbacks for handling these errors.  In order to implement Play on top of Akka http, custom bad request error handling must be possible.

I'm not sure what support is currently provided, but one thing that Play currently supports custom error handling for that as far as I can see akka-http doesn't support is a malformed URI.

There are a few things that make this a little difficult - users typically want access to the request in order to report and render results.  But given akka-https strict parsing, this is difficult.  In Play, when the URI is malformed, we simply avoid parsing it altogether.  A degraded header model may be needed here, where everything is just a map of the raw strings.

**Comment by patriknw** [comment]
cc @sirthias @jrudolph

**Comment by sirthias** [comment]
Currently akka-http-core tries to parse all headers that we have a model for but still accepts the message, even if the header parsing fails (if the header is a non-crucial one). You can configure whether a warning is logged or not in these cases (https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/resources/reference.conf#L150).
What you are asking for is the ability to somehow apply custom error handling logic, which I think makes sense.
Could we maybe (optionally) add a special internal header (e.g. called `MessageParsingErrors`) which contains a list of all parse errors? Then the user has full control over how to react to errors without us having to change the API in any way.

As to malformed URIs: we already support this:
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/resources/reference.conf#L140
Does that suffice or do we need even more relaxed URI parsing modes?

**Comment by jroper** [comment]
I think the `uri-parsing-mode` config option looks like it will let us implement the issue we're trying to address right now, I'll try it out and let you know.

When a header parse fails currently, is there a way to get the original unparsed value?  If not, then the `MessageParsingErrors` internal header with the errors and unparsed values would be very useful.

**Comment by jroper** [comment]
So `uri-parsing-mode` doesn't give me exactly what I want, but at the same time, making Play's behaviour identical between the netty and akka-http backends around these edge cases is not necessarily a worthwhile activity.  The current exercise is to get the tests we run against the Netty backend passing against the akka http backend, which is why this has come up, but there is a question as to whether this particular difference in behaviour matters, and right now I don't have an answer to that.  I think it would depend on the amount of effort/disruption in required in akka-http to implement it.

The problem with setting a relaxed `uri-parsing-mode` is that rather than being able to handle the errors in Play, the errors are simply ignored altogether, and there's no way to get the original raw uri from the request because the uri is passed in its parsed format (as an `akka.http.model.Uri`), which effectively "corrects" the URI when Play sees it.

To exactly replicate Play's existing behaviour here, we'd need strict uri parsing, which when the parsing failed, rather than send a 400 response, would fallback to relaxed parsing (or possibly an even more relaxed mode that allowed anything including unicode and non printables), and pass the error through the internal header mechanism you mentioned.

**Comment by sirthias** [comment]
> When a header parse fails currently, is there a way to get the original unparsed value?

Yes. When parsing fails the header is kept as is as an instance of `RawHeader`, which is essentially a `(String, String)` pair.

> ... and there's no way to get the original raw uri from the request ...

Yes, there is! Check out this setting:
https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/resources/reference.conf#L31

> To exactly replicate Play's existing behaviour here, we'd need strict uri parsing, which when the parsing failed, rather than send a 400 response, would fallback to relaxed parsing (or possibly an even more relaxed mode that allowed anything including unicode and non printables), and pass the error through the internal header mechanism you mentioned.

I see. My guess is that we'll indeed need this support for a `MessageParsingErrors` header and another `uri-parsing-mode` called `strict-or-raw` (or the like), which attempts a strict parse but doesn't auto-reply with a 400 in case of errors, but adds an entry to the `MessageParsingErrors`.
The question then is what we put into the `uri` field of the request in these cases. The cleanest way might be to let the user configure a static URI to be used in these cases, e.g. `/uri-parsing-error`.

**Comment by richdougherty** [comment]
I'm going to delve into the Play API a little bit here because I think it affects the API that we need from Akka HTTP.

At the moment in Play we handle invalid requests using the following method.

```scala
def onClientError(request: RequestHeader, statusCode: Int, message: String = ""): Future[Result]
```

Notice we always pass a `RequestHeader` object. When I look at this method I wonder whether it is a good idea to actually supply a `RequestHeader` object when the request header can't be parsed. It's arguably insecure to give the `RequestHeader` to the user if `RequestHeader` doesn't follow its normal contract. For example, if the `RequestHeader` has a URI with invalid characters in it then the user might accidentally insert it into HTML and expose the user to a XSS vulnerability.

Maybe a better idea would be to make parse errors explicit in the error handling code. Here are two examples.

1. Change `onClientError` to take an `Either`, where `Left` indicates parse errors and `Right` indicates a header that parsed properly but was invalid in some other way.
```
def onClientError(request: Either[List[ParseError],RequestHeader], statusCode: Int, message: String = ""): Future[Result]
```
2. Leave `onClientError` how it is, but add a new, separate method for handling parse errors.
```
def onRequestParseError(errors: List[ParseError], statusCode: Int, message: String = ""): Future[Result]
```

I think either of these options would be OK. The API would be harder for users to misuse. These APIs makes it easy for us to express parse errors to user: just return a list of them. In particular, we don't need to shoehorn an invalid field into the `RequestHeader` object, which is problematic for security.

If we had an API like this then in Play then we'd also need similar support from Akka HTTP. (I haven't checked; maybe Akka HTTP already supports this style of API.)

**Comment by jrudolph** [comment]
@richdougherty, @sirthias was there a conclusion reached about how to proceed?

**Comment by sirthias** [comment]
My proposal for this ticket would be this:

There are many potential sources of parsing errors. The most important ones are probably issues with parsing the request target (URI) or header values. Other problems (unknown method, unknown protocol version, white-space issues, etc.) should be much rarer.
Play needs to be able to customize the error response for all of these.

This means that there needs to be a config setting which tells the HTTP layer to never produce an automatic error reply but rather dispatch an "error request" instance to the application, which can then respond in any way it pleases, with one exception: For security and consistency the connection should always be closed after the error response has been sent, i.e. the error response should always receive a mandatory `Connection: close` header, even if the application doesn't add it itself.

There needs to be a clear and simple way for an application to tell error requests apart from regular requests. I'd suggest that the addition of a `MessageParsingErrors` header is that criteria.
If there is a `MessageParsingErrors` header present in the request the request is not a regular one. Instead, the application has to look through the error list in this header's value in order to find out which properties of the request can actually be considered "ok". For example, if the list contains a "method parsing error" the request method is unknown. If the list contains an "URI parsing error" the request target is undefined. And so on.

There is a question of whether we want to add special "Undefined" methods, URIs, Protocol versions, etc. for this purpose or whether we simply let the error request have (potentially configurable) default values. IMHO custom error response production is an advanced feature and it'd be ok if the error request has default properties (rather than "Undefined"). This would make it a bit less convenient for application to inspect error requests but we'd avoid adding "strange" values to the part of the API that everyone sees and might get confused by.

**Comment by jroper** [comment]
@sirthias I agree with your proposed solution.

**Comment by 2beaucoup** [comment]
I'm not a fan of adding "internal" headers to messages.

What about making the error handling pluggable in the parser with a default handler that rejects.

Could this be done by overriding/replacing `HttpServerBluePrint.finishWithError()` with the possibility to match against `ErrorOutput`s?

**Comment by jroper** [comment]
I don't think there's any problem adding "internal" headers to messages.  If rather than thinking of an http request object being an exact replica of what's on the wire, you think of it as an input message for your application that originated at a client, and passed through many processors along the way, including proxies that may have added various headers (like forwarded headers etc) then the headers just become an arbitrary store of meta data associated with the request.  As the request passes through proxies, load balancers, various filters etc on its way to the business logic, the request message and its meta data may be transformed, with headers being modified, removed, and added.  With this mindset, it feels completely natural to introduce new meta data for the message.  With this mindset, we have a more thorough and complete view of the system, where the system doesn't start at the server socket, it starts at the client, extends through the network, all the way to your server process.

**Comment by 2beaucoup** [comment]
I don't agree with the "arbitrary store of meta data" argument beacause most of the cited headers added by middleware are either specified by RFC or de facto standards with defined semantics.

While you are able to add remove any headers you like to message objects flowing into or out of your app and don't think such practices scales with increased application complexity. With standard headers it's rather clear who (or which directive) is responsible for adding/consuming them.

It may be OK for an app to introduce new semantics for custom headers but I wouldn't expect a toolkit like akka-http to do so.

**Comment by sirthias** [comment]
@2beaucoup I agree with your reservations against using the headers for "everything and the kitchen sink". If there are good ways to design akka-http's API in a way that avoids the addition of internal headers then I'm all for it.
Sometimes however, especially when a somewhat rarely used feature requires the transport of metadata across several layers of the (akka-http) stack and the addition of respective parameters etc. appears too heavy-weight for the benefit they provide I'd consider internal headers a good escape hatch.
The nice thing is that the APIs are not affected at all, which means that ordinary users don't have to bear any weight of specialized features that are only relevant to a small minority.

We could debate whether parse error customization is such a feature, but seeing that nobody in the entire history of spray has ever really requested it I'd be inclined to say yes.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
