### ISSUE TITLE
akka-plugins: consolidate repositories under akka

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16618]
1) Problem:
currently akka community plugins are a wild forest http://akka.io/community/
our primary problem with that is consistent lagging behind akka releases
although in most cases upgrade would be a minor effort.
then of course one has to chase down the plugin author and beg for the release,
while akka team has nothing to do with release cycle.

2) Solution
we suggest that akka adopt a [jenkins](https://github.com/jenkinsci) approach:
* all plugins are under akka org
* akka team is plugin project owner
* original plugin authors are contributors to their akka plugin project
* akka team is doing the release in typesafe org name space
* akka team makes minimal effort to upgrade all plugins after akka releases

We think that would increase plugins visibility and increase
customers faith in them, now that typesafe is backing them up a little more.

**Comment by patriknw** [comment]
The Akka team is resource constraint and I think this would only slow down updates and releases of journal plugin projects.

The Akka team can't be responsible for maintenance of all journal plugin projects because that would require in depth product knowledge all the data stores. Maintenance is not only about bumping version numbers and fixing obvious compilation errors.

We have experience of the suggested approach from [akka-modules](https://github.com/akka/akka-modules) and it didn't work out.

**Comment by Andrei-Pozolotin** [comment]
> We have experience of the suggested approach from akka-modules
> <https://github.com/akka/akka-modules> and it didn't work out. 
I am curious as to why it works for jenkins and not for akka.

May need to relax further: have agreement to support 2 branches:
"typesafe" with typesafe release org and "author" with author release org.

The intent is to have more vetted repository owners from the project
beginning.

**Comment by Andrei-Pozolotin** [comment]
more on how it works for jenkins:
https://github.com/orgs/jenkinsci/teams/owners
https://github.com/orgs/jenkinsci/teams/everyone

1) 10 owners have commit rights to 1325 = 1148 external + 177 internal plugin projects
2) 373 plugin authors have commit rights to all 1148 external plugin projects
3) releases are still done by/in the individual author org name space

so you get an automatic benefit of treating every owner nad any module author as a vetted committer to all other external modules; jenkins also have screening process on what modules to accept under its umbrella, to ensure minimum module quality

how come akka team is any less capable of doing same or better? :-)

**Comment by rkuhn** [comment]
Andrei, you are raising a very good point. We have so far “carefully neglected” the modules due to the reasons Patrik gave, but we are now in a different situation as we were with akka-modules back in 2011: an ecosystem has begun to develop and is thriving around Akka and we need to consider how to tend to it. We’ll study the Jenkins approach in more depth and research how others are doing this and then I’m sure we will find something that helps both the core team and the module authors (and not least all the users out there).

If someone else has more inputs diversity is always welcome, especially while searching for solutions!

**Comment by Andrei-Pozolotin** [comment]
Roland, thank you for considering this. FWIW, I did personal experiment: I went through the list http://akka.io/community/ and I'd say I would be interested in and proficient enough to contribute to some 50% of those projects. In other words, that could be a potential win for 50% of module authors.

**Comment by rkuhn** [comment]
Hi @Andrei-Pozolotin,

sorry for the delay, these things take a bit of time to settle. We have discussed the pros and cons of the proposal and while we do see the need to better support external module authors we cannot take on the responsibility of adding the actual repositories to the Akka organization. Not only does it exceed our capacity to monitor everything that happens in these repositories (which we would have to do because improper conduct on “our premises” would fall into our domain), it would also send the wrong message to the community. Typesafe may be perceived as a well-funded sponsoring entity behind all of these projects—I’m not aware of similar arrangements for Jenkins—which could easily stifle external contributions instead of encouraging them; the truth is that Typesafe does not have the resources to do any such thing. We very much need external contributions, so we thought about how to foster those.

What we will do is to clean up the community page (already done) and present that a lot more prominently (to be done soon) as “step zero”. The first step we will take is to set up a project that aggregates CI information for all community projects (of course open for PRs to make modifications) and displays an up-to-date overview of what is available for which version of Akka etc. As a second step we are planning to add a community build as is done for Scala itself, based on dbuild in testing external modules against current Akka development versions. This would then notify authors whenever updates are needed to keep things working.

As to having commit rights: github makes it really easy to open a PR on any repository out there and I think it is a good thing to reserve the right to press the green button to the owner or those whom they trust. In case of an orphaned project anyone can fork it and update the community build description accordingly.

One thing that we have not yet figured out is whether or not a chat room (like [gitter](https://gitter.im/akka/akka)) is needed. We are hesitant to advertise that for the same reason as above: if someone conducts themselves poorly in there then this will reflect poorly on us unless we constantly stay on top of it—which is a huge time drain (and we sometimes actually do sleep ;-) ).

You raised valid concerns, and I hope that these plans will address them. If we missed some aspects please let us know!

Regards,

Roland

**Comment by MasseGuillaume** [comment]
/cc @Andrei-Pozolotin @patriknw @hepin1989 @rkuhn

I just added every projects from http://akka.io/community as tags in scaladex. Plugins or extension authors
still need to bump the akka version and republish. However any new release will be listed automatically.

## [akka-extension](https://index.scala-lang.org/search?q=keywords:akka-extension)
* [x] jodersky/flow
* [ ] gideondk/nucleus
  * custom resolver not supported: "gideondk-repo" at "https://raw.github.com/gideondk/gideondk-mvn-repo/master"
* [ ] gideondk/sentinel
  * ibid
* [x] vigdorchik/rxmon
* [x] levkhomich/akka-tracing
* [x] sclasen/akka-zk-cluster-seed
* [ ] patriknw/akka-data-replication
  * Deprecated. Use akka/akka-distributed-data-experimental
  * https://index.scala-lang.org/akka/akka/akka-distributed-data-experimental
* [x] hseeberger/akka-log4j
* [x] hseeberger/constructr
* [x] ilya-epifanov/akka-dns

## [akka-http-extension](https://index.scala-lang.org/search?q=keywords:akka-http-extension)
* [x] hseeberger/akka-http-json
* [x] hseeberger/akka-sse
* [ ] denigma/akka-http-extensions
  * something is wrong (POM present not indexed)
* [x] softwaremill/akka-http-session
* [x] lomigmegard/akka-http-cors

## [spray-extension](https://index.scala-lang.org/search?q=keywords:spray-extension)
* [x] sclasen/spray-aws
* [x] wandoulabs/spray-websocket
* [ ] wandoulabs/spray-socketio
  * moved to dcaoyuan/spray-socketio
  * resolver not supported: sonatype snapshot
* [x] galarragas/spray-funnel
* [x] jarlakxen/spray-extensions

## [akka-persistence-plugin](https://index.scala-lang.org/search?q=keywords:akka-persistence-plugin)
* [ ] chriscoffey/akka-persistence-android
  * not following scala artifacId convetion (added to nonstandard.json)
* [x] bseibel/akka-persistence-bdb
* [x] akka/akka-persistence-cassandra
* [x] krasserm/akka-persistence-kafka
* [ ] sclasen/akka-persistence-dynamodb
  * moved to akka/akka-persistence-dynamodb
* [x] akka/akka-persistence-dynamodb
* [x] ktoso/akka-persistence-hbase
* [ ] drexin/akka-persistence-mapdb
  * not supported: snapshot
* [x] ironfish/akka-persistence-mongo
* [x] scullxbones/akka-persistence-mongo
* [x] product-foundry/akka-persistence-couchbase
* [x] michaelpisula/akka-journal-inmemory
* [x] dnvriend/akka-persistence-inmemory
* [x] pnerg/akka-persistence-mock
* [ ] dnvriend/akka-persistence-jdbc
  * not found
* [x] okumin/akka-persistence-sql-async
* [x] jdgoldie/akka-persistence-shared-inmemory
* [x] eventstore/eventstore.akka.persistence
* [ ] carrot-garden/akka-persistence-chronicle
  * incomplete: https://github.com/carrot-garden/akka-persistence-chronicle/issues/1
* [x] hootsuite/akka-persistence-redis
* [x] acflorea/akka-persistence-titan

## [akka dependents](https://index.scala-lang.org/search?dependencies:akka/*)

**Comment by patriknw** [comment]
Thanks a lot @MasseGuillaume

**Comment by drewhk** [comment]
My only concern is that we will lose the categories as the search page is just an unstructured list. I personally love the awesome-stuff like pages with categories, so I would be sad to lose the structure. Maybe scaladex should support categories...

**Comment by ktoso** [comment]
WDYM @drewhk ? Did you see these queries: https://index.scala-lang.org/search?q=keywords:akka-persistence-plugin

You can search the category

**Comment by drewhk** [comment]
That is not the same as having a list with categories. I mean like any "awesome-xxx" list. See https://github.com/kud1ing/awesome-rust and then compare it to the page we link now with the badge.

**Comment by 2m** [comment]
We do not loose categories. Every category (with the exception, that persistence journal and snapshot plugins are now one instead of two categories) is mapped to a keyword in Scaladex.

What we do loose is the listing of all projects grouped by categories in one page. We will instead have a listing of categories with links to a corresponding list of projects under that category. I do not think this is a great loss, especially given the advantages that we get:

* already listed projects always have up to date information
* assigning a project to a category is a one time effort

However, @drewhk, I also do like the awesome-xxx pages that you mentioned. So as a new feature in Scaladex we could have a broken down by category list of all of the projects that depend on any akka module. This would not only be an equivalent migration of our current community page to Scaladex, but a vastly advantageous one because of the reasons listed above and the fact, that it might be used not only for akka, but for anything listed in Scaladex.

**Comment by MasseGuillaume** [comment]
If I understand correctly, @drewhk would want a nested structure

akka-extension
* jodersky/flow
* gideondk/nucleus
* ...

akka-http-extension
* hseeberger/akka-http-json
* hseeberger/akka-sse
* ...

Scaladex is only flat:

* jodersky/flow (akka-extension)
* hseeberger/akka-sse (akka-http-extension)
* gideondk/nucleus (akka-extension)
* hseeberger/akka-http-json (akka-http-extension)

It's a good idea IMO, we just need to find a way to paginate on each category

**Comment by 2m** [comment]
Yes. To illustrate the idea with a more general example, it would be great to break down the list [here](https://index.scala-lang.org/search?q=dependencies:akka/*) by keywords, even if some projects would end up multiple times under different keywords.

**Comment by drewhk** [comment]
> If I understand correctly, @drewhk would want a nested structure

Exactly. Not necessarily the default, but at least one option so we can link to that directly and not hurt discoverability.

**Comment by MasseGuillaume** [comment]
@drewhk @2m 
another way to go could be like: https://swiftpkgs.ng.bluemix.net/browse#?chart=moststarred&page=1

I could display all keywords aggregated by the search so you could filter the search

* akka-persistence-plugin (10)
* kafka (1)
* spark (2)
* ...

I could also only limit to certain keywords (akka-persistence-plugin, akka-http-extension, akka-extension)

filters | results
--- | --- 
akka-persistence-plugin | hseeberger/akka-http-json
akka-http-extension        | hseeberger/akka-sse
akka-extension               | denigma/akka-http-extensions
                                       | softwaremill/akka-http-session
                                       | lomigmegard/akka-http-cors

**Comment by 2m** [comment]
@MasseGuillaume aggregation by keywords looks good. But they take up too much space in the link you provided. What about showing tags with number of projects in the search results, like so:

![tags_aggr](https://cloud.githubusercontent.com/assets/422086/18233043/f5c012ce-72e5-11e6-97dd-bc56055042bb.png)

**Comment by 2m** [comment]
Created a ticket as a follow up on this discussion. https://github.com/scalacenter/scaladex/issues/272

**Comment by MasseGuillaume** [comment]
@2m Hey sorry I totally forgot to follow up. Thanks for the reminder ;-)
