### ISSUE TITLE
Flexibility of actor naming

### ISSUE THREAD

**Issue by ale64bit** [akka/akka#16613]
Is it possible to be more flexible in the actor naming? Giving an automatically generated name to an actor is good if you don't care about it. Giving a fixed name to an actor is good if such actor is "unique" in some sense. But for example, for giving names to some worker actors, it would be good to be able to name them after some pattern, as *"worker-actor-%"*, where % is the automatically generated ID. This enables the developer to have more pleasant and customizable logs, besides being more portable since the developer doesn't need to write its own naming schema, which could collide in another actor system if the project is used as third-party code.

**Comment by ktoso** [comment]
Hi Alejandro, thanks for the suggestion! 

However, I do think that actor naming is best left up to the application developer, reasoning being that if you have multiple workers perhaps their names should correspond to some workId etc. I like to think as actor names as part of your application, so for example - you want to know how many workers you've spawned - so you want to be in charge of that counter, instead of using selection to count them asynchronously each time.

About the point that actor names may conflict if you use a lib – I think this is rather unlikely as we*highly* encourage *deep* actor hierarchies. So let's say you're using some persistence plugin, those usually will start actors, true, but they should do so as child actors - so paths would look like `/user/hdfsPersistenceActor/worker-1` (or `/system/...`), or `/user/myLibraryThingy/worker-1` etc.

Let's hear what the other hakkers think but I'd vote against making this a built in feature.

**Comment by ale64bit** [comment]
Thanks for the answer, Komrad!

Well, I agree with you about naming being application-developer-specific, but for example (and following your example of counter for worker actors), if I don't want to care or pollute my code with counting workers and naming strategy for workers, it would be incredibly pleasant to have built-in feature to simplify debugging and logging. Moreover, this built-in feature would not be invasive, since it's up to the developer to use it or not, so it doesn't really affect backward compatibility and eases development.

About actor names usage in lib, I also agree with deep actor hierarchies, although in some cases when many people build different parts of a complex Akka system and then those parts need to collaborate, it would nevertheless be good to have the flexibility of naming "fearlessly". I would like to hear more in this point anyway.

**Comment by patriknw** [comment]
It is only a few lines of code to implement a naming strategy (counter) in the parent actor. That can also be packaged as a trait. I don't think there is a need to add extra feature in Akka itself.

**Comment by rkuhn** [comment]
small correction: one line.
~~~scala
val workerName = Iterator from 1 map (i => s"worker-$i")
~~~

**Comment by huntc** [comment]
A point to note re this issue and Akka Typed... you must now carry the id state across all actor behaviors. To resolve the issue is no longer just a couple of lines... :-)

**Comment by huntc** [comment]
Another technique is to use the number of child actors as an identifier e.g.:

```
val actorName = NamePrefix + context.children.size
```
