### ISSUE TITLE
investigate ways for faster reflection

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#16627]
https://github.com/EsotericSoftware/reflectasm is about 2x faster

**Comment by ktoso** [comment]
While pretty cool I'd be rather reluctant to include this in `akka-actor` itself - it would mean bringing in `asm` as an dependency.

**Comment by rkuhn** [comment]
Yes, external dependencies are problematic for akka-actor due to the widespread risk of version collisions (among others). We’ll dive into actor creation performance (which would be the main beneficiary) when speeding up streams, but then we might just generate byte-code ourselves in some simple and well-contained case.

**Comment by hepin1989** [comment]
thanks for thinking about this,this one is using asm and the ```kryo``` is depends on this and the ```FiledSerializer``` is using asm to generate byte-code for maximum speed.
