### ISSUE TITLE
Community version of akka-zeromq with JeroMQ?

### ISSUE THREAD

**Issue by rcsenkbeil** [akka/akka#16636]
What happened to this effort - https://github.com/akka/akka/pull/15246 - even moving it to a community project? The [Spark Kernel](https://github.com/ibm-et/spark-kernel) uses _akka-zeromq_ right now, which serves as a great abstraction on top; however, several users have an issue (https://github.com/ibm-et/spark-kernel/issues/1, https://github.com/ibm-et/spark-kernel/issues/23) with the dependency on _libzmq_ and would rather have JeroMQ.

Does an effort for the community project exist anywhere? Is everything being abandoned in favor of [scala-zeromq](https://github.com/mDialog/scala-zeromq)? I tried dropping in JeroMQ 0.3.4 into that project to see where it stood, but got quite a few (11) test failures.

I'm not sure where to look for the current status of the effort: https://github.com/akka/akka/issues/13856, https://github.com/akka/akka/issues/12924 All I know is that there was some interest (from the JeroMQ pull request) and that the project "might" be moved to a community-run project outside of the main akka repository.

With regard to the special exception in the license, it looks like JZMQ can be swapped for JeroMQ without needing to change the license of the main project: https://github.com/zeromq/jeromq/issues/234

**Comment by rkuhn** [comment]
To clarify the license part: the wording of the exception is too unclear to put serious (legal) weight onto it from the Typesafe side, we cannot ship a module that links to LGPL JARs due to ambiguities that arise from LGPL being written with C and object files in mind.

As to the community effort: I have opened a PR (#15864) to remove akka-zeromq from the master branch and as of yet there has been no reaction besides yours that indicates interest in keeping the module around in some fashion—which frankly surprises me a little. Maybe we should get a discussion going on akka-dev to figure out the way forward.

**Comment by rcsenkbeil** [comment]
Ah, I see. So, the current akka-zeromq implementation uses https://github.com/valotrading/zeromq-scala-binding (Apache v2 license), which is similar to JZMQ (but without the odd licensing). The transition isn't as simple as going directly from JZMQ to JeroMQ, which share a similar exception in their license.

**Comment by rcsenkbeil** [comment]
As there does not appear to be any interest in the community version, we have finally rolled our own (non-extension) version of [JeroMQ with Akka](https://github.com/ibm-et/spark-kernel/tree/master/communication/src/main/scala/com/ibm/spark/communication) to suit our needs. So, I'm going to close this.

**Comment by rkuhn** [comment]
Thanks for sharing!
