### ISSUE TITLE
Akka-stream groupBy operator consumes 5 seconds on a few elements

### ISSUE THREAD

**Issue by l15k4** [akka/akka#16798]
Hey,

I'm just trying to map elements by boolean and then groupBy that boolean and lastly map Source by that 2 boolean states. It is definitely cause by **groupBy**, but I can't figure out what exactly is causing it... the Dump is just profiling time passed before pull and push phases... I'm using 1.0-M3 akka-streams

```
  "group by consumes 30 seconds" - {
    val b = (2 to 6).map(_ % 2 == 0).iterator
    Source(List("a","b","c"))
      .map(e => b.next() -> e)
      .groupBy(tuple => tuple._1)
      .map { case (success, source) =>
        success -> source.map(_._2)
    }.transform(() => Dump("prefix"))
    .runForeach(_ => Unit)
    .onComplete(_ => system.shutdown())
  }
```
OUTPUT 

```
pull prefix
push prefix took 44ms
pull prefix
push prefix took 5020ms
pull prefix
```

**Comment by l15k4** [comment]
Is there any idiomatic way of troubleshooting these errors? Since I'm new to akka-streams, it took me 4 hours to find it, because I didn't really expect it to happen at a groupBy operator.

**Comment by drewhk** [comment]
Hi Jakub,

The stream did what you told it to do. GroupBy produced two substreams (you
logged them), but you didn't consume them (you forgot to run its child
streams!). Since all Akka Stream processing stages are bounded, groupBy can
only buffer a couple of elements before its substreams gets consumed
properly. Also, dropping a group (forgetting to consume one of the groups)
will deadlock, too.

In general, prefer static graphs instead of nesting/flattening elements
(anything that transform Source[...] to Source[Source[...]] or vice versa),
since the latter are very dangerous in a bounded setting. In your above
example, since the number of groups is only two you could have just used a
graph and routed the elements left or right then possibly merge them back.

One of the typical example of a completely unsafe usage would be:

   infiniteRandomIntegerSource.groupBy(_ %
2).map(_._2).flatten(FlattenStrategy.concat).runForeach(println)

The above line tries to take an infinite sequence of random integers, and
then tries to print *all* odd numbers and then *all* even numbers (well,
the order between the two groups is undefined, so it can be *all* even and
then *all* odd numbers). If you think a little bit about this problem then
you will realize that it is impossible, since you would need to store an
infinite number of even (or odd) numbers in memory while you print the
infinite number of odd (or even) numbers.

For a more complex example on groupBy and how to possibly avoid deadlocks
see this cookbook recipe:
http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M3/scala/stream-cookbook.html#Implementing_reduce-by-key

-Endre

**Comment by l15k4** [comment]
Thank you,

it was part of an integration test where I didn't care about those child streams. I just didn't know it is necessary to consume them anyways.

I originally wanted to have 2 output streams using `Unzip` but it is not possible to return 2 `UndefinedSource` from `PartialFlowGraph` so that the processing would have to happen withing that `PartialFlowGraph`, right?

**Comment by drewhk** [comment]
Hi Jakub,

On Tue, Feb 10, 2015 at 9:12 AM, Jakub Liska <notifications@github.com>
wrote:

> Thank you,
>
> it was part of an integration test where I didn't care about those child
> streams. I just didn't know it is necessary to consume them anyways.
>
Just think about it: groupBy needs to pull from its upstream source
elmements, but it is allowed to only store a limited number of them. Now if
*any* of the substreams is not consumed (and not explictly cancelled!) then
if the next 101 elements happen to belong to exactly the not consumed
group, but we are allowed to store only 100 elements then we are blocked,
since we cannot store all elements in that burst, we can only free up space
when that substream gets consumed. The solution is to say
runWith(Sink.cancel) on the ignored substreams. This is the most effective
way, since it does not need to explicitly consume and drop the group
elements, but by immediately cancelling it notifies the groupBy itself that
it can just ignore that group and drop its elements.



> I originally wanted to have 2 output streams using Unzip but it is not
> possible to return 2 UndefinedSource from PartialFlowGraph so that the
> processing would have to happen withing that PartialFlowGraph, right?
>
Yes, this is true, but this will be one of the big changes in M4 where we
give graphs some new powers, allowing them to be used more flexibly than
before.

Btw, here is a recipe that wraps a graph in a flow:
http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-M3/scala/stream-cookbook.html
It does not solve your problem probably, but might give some inspiration.

-Endre
