### ISSUE TITLE
Add "wire logging" feature

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16830]
@sirthias in spray/spray#709:

> Given the more flexible stream setup infrastructure in Akka one could argue that a "wire logging" feature could be implemented outside of Akka HTTP, as a plain and simple "log what is going through the stream" stage.
> However, similar to the wirelogging feature provided by the Apache HTTP client there is value in having a logging stage that has a concept of HTTP.
> For example it should be possible to restrict logging to only the message headers, i.e. suppress the message entity.

**Comment by crypticmind** [comment]
I think that with the advent of HTTP/2 this will cause some stirr. Since HTTP/2 is a binary protocol, what would a wire logging show? Maybe for HTTP/2 cases, "go ahead and use wireshark" could be an acceptable answer.

Nevertheless, HTTP/1 isn't going anywhere and we still need to see what's going on over the wire.

**Comment by jrudolph** [comment]
@crypticmind I agree. With HTTP/2 wire logging itself makes not so much sense any more. 

I guess what this ticket boils down to is providing insight into what's happening at the boundaries of each layer. For HTTP it may e.g. only be "network <-> parsing/rendering <-> content decoding <-> user" while for HTTP/2 it may be "network <-> framing <-> multiplexing <-> header (de)compression <-> content decoding <-> user" or similar.

The good thing is that with akka-streams the layers will be implemented as flows that are part of a bigger stream processing pipeline. That should make it easier to inject configurable logic at well-defined points.

**Comment by rkuhn** [comment]
Changed this into a Streams feature: it would be great to have some generic logging facilities, but for HTTP there are better and more specialized tools (like wireshark).

**Comment by jrudolph** [comment]
I agree that this should be a stream feature. Wireshark isn't particularly helpful if you need to debug an HTTPS connection. In that case, you'd rather want to have a logger that sits between TLS and HTTP, so you can see the plain bytes.

**Comment by briantopping** [comment]
I just got hit with this myself. I think the best solution might be to create a push-pull that could capture traffic and publish it in [pcap-ng](https://github.com/pcapng/pcapng) format to a named pipe. Some background on Wireshark and named pipes are available [here](https://wiki.wireshark.org/CaptureSetup/Pipes).

A lot of the tooling out there can connect to a named pipe and the facilities and format are unlikely to change over time.

**Comment by jrudolph** [comment]
@briantopping providing a BidiFlow that exports to pcap is a great suggestion. Why do you suggest named pipes? Is it to support live capturing?

**Comment by briantopping** [comment]
> Why do you suggest named pipes? Is it to support live capturing?

Yes, exactly.

**Comment by jrudolph** [comment]
One obstacle would be figuring out with which link-layer framing the file should be written. We would probably have to synthesize some kind of link layer framing (or [it seems](http://www.tcpdump.org/linktypes.html) you could also use IP). Do you have any examples of other libraries that have attempted something like this?

**Comment by briantopping** [comment]
I don't know of any examples of this, that's why Akka is so cool :)

http://www.jopdesign.com/ejip/ or similar would be a good way to generate the framing, but I haven't dug into it.

**Comment by drewhk** [comment]
Interesting idea

**Comment by briantopping** [comment]
In hindsight, the `pcap` direction may be misguided. Flows don't have a binding on any network and using `pcap` creates such a binding. That said, pcap compatibility tool avoids tool famine for those that don't use eclipse or are on a non-standard OS. It sucks being an IJ user sometimes because tools like this never make it over.

That said, it probably makes sense to somehow instrument the materializers so they can tap flows when they are built. Maybe that's what @jrudolph was considering in https://github.com/akka/akka/issues/16830#issuecomment-73888167. 

The problem with tapping SSL connections isn't going to go away, but #19511 may have an answer to that. This would allow a flow tap solution to not get muddled by crossed-requirements.

**Comment by jrudolph** [comment]
The basic feature requested in the beginning was merged into akka-http as https://github.com/akka/akka-http/pull/523. 

I think something like pcap idea would also be nice but would require significant effort. So I'm closing this here as fixed for now.

**Comment by drewhk** [comment]
But something like this can be useful for any ByteString streams I think.

**Comment by ktoso** [comment]
Yeah, the printing itself would be fun to bring back to akka/akka.
Shall I open a ticket?
