### ISSUE TITLE
akka-build: split out modules into separate repos

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16849]
after doing some work on
```
akka-cluster-metrics
akka-persistence-experimental
akka-samples/...
```
etc

and doing my share of build turn around wait time, when a local clean build/test of these modules takes 1-2 minutes, while remote jenkins build takes 1-2 hours, I have a question:

is it really necessary for  all these modules to be part of monolithic, overly-complicated, highly-coupled monster  that akka build has become? would it be possible to externalize build cross-concerns into some akka-build-plugin and move all the modules into their own repositories?

**Comment by Andrei-Pozolotin** [comment]
next repo/module request: #15884

**Comment by hepin1989** [comment]
then this will reduce build and merge test time?

**Comment by hepin1989** [comment]
I was wondering how about only run the merge build test on the target modules?like If a PR is for the ```akka-remote```,and then only run the test on ```akka-remote``` and the modules depends on it?

**Comment by patriknw** [comment]
Moving core modules to a separate repositories is not desired, e.g. we want to track a change with one single commit. That also doesn't reduce the build time, unless reducing what is tested.

I think it is a good idea to have some targeted build tasks that don't run all tests. These can be used by contributors locally before submitting a PR, since running all tests locally is not feasible.

Reducing the build time of PR validation would be great, but that would mean less testing before merging and risking regressions. Those can be found by a later build step with the tradeoff that some bad commits end up in master. I'm not sure what we value most.

**Comment by Andrei-Pozolotin** [comment]
you could look into using some kind of jenkins plugin which builds only part of dependency tree that is actually affected by a single commit in a multi-module single-repo project family

we made such plugin for mvn in the past (also makes partial sub-tree releases)
https://github.com/jenkinsci/maven-release-cascade-plugin

that would still require to make individual module builds independent
