### ISSUE TITLE
Add support for HTTP/2

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16862]
RFC draft: http://tools.ietf.org/html/draft-ietf-httpbis-http2-17

As a pre-requisite TLS ALPN support is needed (#16861).

See also the [previous attempt](https://github.com/jrudolph/spray/commits/feature/spdy2) to implement SPDY for spray.

/cc @sirthias

**Comment by 2beaucoup** [comment]
For Info: [known implementations](https://github.com/http2/http2-spec/wiki/Implementations).

**Comment by hepin1989** [comment]
+1
https://http2.akamai.com/demo

**Comment by romansky** [comment]
+1

**Comment by Biacode** [comment]
+1

**Comment by mubarak** [comment]
+1

**Comment by dcheckoway** [comment]
+1

**Comment by dbaba** [comment]
+1

**Comment by nmelkozerov** [comment]
+1

**Comment by LaoZhongGu** [comment]
+1

**Comment by whiplash** [comment]
+1

**Comment by yongjianwang** [comment]
+1

**Comment by andreareginato** [comment]
+1

**Comment by ekrich** [comment]
+1

**Comment by dtaniwaki** [comment]
+1

**Comment by RickyB98** [comment]
+1

**Comment by lowdewijk** [comment]
+1

**Comment by darionyaphet** [comment]
+1

**Comment by dungvn3000** [comment]
+1

**Comment by daniloqueiroz** [comment]
+1

**Comment by timcharper** [comment]
`+1` does not make this come faster. Pull requests and contributions do. Please stop commenting with `+1` and stop spamming those of us interested in real updates to this issue.

Also https://github.com/dear-github/dear-github

**Comment by lowdewijk** [comment]
Sorry man. Appreciate the effort.

**Comment by ktoso** [comment]
That wasn't nice or helpful @timcharper, please refrain from such comments. You can very easily stop receiving notifications on an issue if these bother you - by clicking the notifications button next to the issue here, so please do that instead if you are bothered by these comments.

@lowdewijk thanks for voicing your interest in this, we are taking note of interest in this issue and hope to work on it sometime soon. 

We are not officially backing the dear-github initiative, nor are we angry at people commenting "+1".
Of course PRs get things don't, and +1 don't however it is an indicator of what people care about, so it is a way to communicate with our audience, which is a valuable thing. Since github does not have better tools than such a comment, people are using that to voice their interest – I don't see anything wrong with that.

(this can be seen as an official akka team statement)

**Comment by drewhk** [comment]
@ktoso I think @timcharper has a point. All those people who wants to keep notifications for this ticket -- because they are interested in whether there is progress/discussion/debate here -- are now forced to either deal with the `+1` spam or disable the notification altogether. I don't think `+1`'s are worth to make a useful feature useless which is what happening now. There is no need to be harsh of course, but I completely understand the cause of annoyance.

**Comment by ktoso** [comment]
Sure, I also agree with it being very noisy etc (as mentioned in :point_up: [January 16, 2016 12:28 PM](https://gitter.im/akka/dev?at=569a29462bc35f6c1c1a6cd1)),
however we should not be harsh when someone does such comment – it's discouraging when you come to a project and get yelled at because you `+1`ed (since no better alternative built-in voting system currently exists).

I propose to leave the discussion at that and leave the ticket to float back to it's original purpose :)

**Comment by rkuhn** [comment]
@drewhk I see your point, but I agree with @ktoso on what we can do given the current feature set of github. I don’t think this is a significant problem for Akka because after the websocket ticket this is only the second ticket in the history of the project that gets these votes. If this becomes more frequent we may have to revisit this point.

If anybody wants to discuss this aspect further please open a dedicated issue for it.

**Comment by schmitch** [comment]
I wanted to ask something regarding this question since it's not clear. what spec will akka follow? Only h2 or h2c.
Currently I think h2c is important, too since playframework could be using akka-http as it's underlying server and when you develop a full stack application which actually pulls a lot of js files either via rjs, systemjs or any dynamic module loader you will actually need to wait 9-10 seconds to actually fulfill the request. However generating a tls certificate just for development seems a little bit complex.

**Comment by sahataba** [comment]
+1

**Comment by jrudolph** [comment]
@schmitch in any case, h2c shouldn't be particularly hard to implement once the implementation itself is in place. We already have some infrastructure for upgrade requests for WebSocket support which could be reused to plug-in HTTP/2 instead.

**Comment by jsw** [comment]
+1

**Comment by punitag** [comment]
+1

**Comment by timcharper** [comment]
I don't want to create another controversy, but want to politely point out that GitHub added reactions and you can give this a thumbs up now (instead of commenting with `+1`).

**Comment by ktoso** [comment]
// No promises yet, marking for internal planning session.

**Comment by shveik** [comment]
So is there any plan/roadmap/idea when http/2 would be available? Is this a priority?

**Comment by ktoso** [comment]
We'll do a Proof-of-Concept, but can't guarantee how much that will include.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
