### ISSUE TITLE
sender() is not valid in for comprehension

### ISSUE THREAD

**Issue by behrad** [akka/akka#16920]
in my Snapshot based persistent actor in my `updateState` method the following happens:

```scala
log.info( s"${sender()}" )  //correct actor path of the message sender
def u = for {
   x <-  store.fetch(...)
   resp <- {
      x match {
          case "something" =>
              log.info( s"${sender()}" ) // prints dead letter actor path !!!
      }
   }
}
```

**Comment by ktoso** [comment]
Hello there @behrad!
is `fetch()` returning a `Future`?
Since `sender()` is a mutable reference this is *not safe* - you must not refer to sender() from another thread / asynchronously. Before you get to execute the callback (resp) the sender reference may point point to someone completely different (or dead letters).

Instead, write something like this:

```scala
// freeze the sender value
val replyTo = sender()
log.info( s"${sender()}" )  //correct actor path of the message sender
myFuture map { f => replyTo ! f }
```

or

```scala
// use the pipeTo pattern:

store.fetch() pipeTo sender() // safe, sender is accessed on current thread.
```

* this info is mentioned at the end of http://doc.akka.io/docs/akka/snapshot/scala/actors.html#tell-fire-forget
* docs about pipeTo http://doc.akka.io/docs/akka/snapshot/scala/futures.html#use-with-actors
* Here's a nice blog on the subject: http://helenaedelson.com/?p=879

I just noticed this is not very highlighted in the docs... I'll update the docs to be more explicit about this. It's rather "known", but I understand it may be surprising if you're new to mixing Actors and Futures.

**Comment by behrad** [comment]
great @ktoso thank you
