### ISSUE TITLE
Think about materialization value handling in Http

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16933]
Currently it is not very consistent, although in most of the cases of API methods:

 - take a materialized value type of _
 - produce a materialized value type of Unit

There might be better ways to handle this.

**Comment by rkuhn** [comment]
One main point is that `entity.data` is declared as `Source[ByteString, Unit]` when in fact it should be `Source[ByteString, Any]` (to allow arbitrary materialized values—they are ignored anyway). This would work without any issue if this method were only ever mentioned in Scala source, but HttpEntityCloseDelimited.java kills it; the problem is that Unit is an AnyVal while Java cannot express the concept of Any.

**Comment by rkuhn** [comment]
same as #17039
