### ISSUE TITLE
PropsSource overrides Props dispatcher with the one in Materializer Settings

### ISSUE THREAD

**Issue by TrustNoOne** [akka/akka#16952]
Hi,
as pointed out in the code by @2m on the akka user list, PropsSource calls materializer.actorOf when creating the ActorProducer, overriding any custom dispatcher set in the props object. 

The only way to use a different dispatcher is ping-ponging the stream objects to an actor outside the actor flow.

this  is where PropsSource creates the actor:
https://github.com/akka/akka/blob/38d8f265dad3909f3d597f4c3c9da65a7bf576d2/akka-stream/src/main/scala/akka/stream/impl/Sources.scala#L166

This is where the materializer overrides the dispatcher:
https://github.com/akka/akka/blob/38d8f265dad3909f3d597f4c3c9da65a7bf576d2/akka-stream/src/main/scala/akka/stream/impl/ActorFlowMaterializerImpl.scala#L157

Thanks

**Comment by drewhk** [comment]
Since this is closed: https://github.com/akka/akka/issues/16902 it is possible to properly set attributes on sources. The real question is whether it makes sense to override the dispatcher on a Props from stream settings. The solution would be that if the Props has an explicit dispatcher then it should be taken, otherwise it should fall back to the attributes inherited from the stream it is embedded in.

**Comment by TrustNoOne** [comment]
I can tell you my use case: an ActorProducer that acts as a source but does blocking operations (e.g. reading from a database) thus needing a different dispatcher.

**Comment by drewhk** [comment]
Yes, that is a perfectly valid use-case.

**Comment by drewhk** [comment]
This needs to be tackled first: https://github.com/akka/akka/issues/16957
