### ISSUE TITLE
document how to create custom directives

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#16962]
see https://groups.google.com/d/msg/akka-user/7v0dxqjf5R0/aU4gMbcyKG0J

**Comment by ktoso** [comment]
I just stumbled upon this and realised it's not `http-next`; don't want to add to your heap of tasks beyond on what we agreed upon though :-)

I can write this up basing it upon http://spray.io/documentation/1.2.2/spray-routing/advanced-topics/custom-directives/ then. If there's some hints that would be good to have in mind when porting the docs let me know, thanks! @sirthias @jrudolph

**Comment by ktoso** [comment]
This would be very important to have in 1.1 so we have complete docs.
@johanandren that's a potential ticket that'd be awesome if you could pick - it's mostly picking the spray doc, and translating the code snippets such that they compile/work (most likely not much changes needed).

The answer for custom JavaDSL directives is "well, not really..." you can try custom RequestVals I guess, but not much since the DSL layer is completely static.
