### ISSUE TITLE
Upgrading AtLeastOnceDelivery to 2.4-snapshot

### ISSUE THREAD

**Issue by behrad** [akka/akka#17033]
I have a snapshot based atleastonce delivery trait as below:
```scala
abstract class SnapshotAtLeastOnceDelivery[M: ClassTag,C <: ConfirmDelivery : ClassTag] extends AtLeastOnceDelivery with ActorLogging {

  def receive: Receive = {
    case RecoveryCompleted => recoveryCompleted()

    case msg: M =>
      unconfirmedHg.record( numberOfUnconfirmed )
      updateState( DeliveryRequest(msg) )

    case confirm: C =>
      confirm.deliveryIds map confirmDelivery
      updateState( DeliveryConfirmed( confirm ) )

  }

  abstract def updateState(evt: Evt)

}
```

whose children are implementing the `updateState`; But when I upgraded from `2.3.9` to `2.4-snapshot` my previously working code is not being  compiled, complaining about new abstract `receiveCommand` method in AtLeastOnceDelivery as seen below:
http://doc.akka.io/api/akka/2.3.9/index.html#akka.persistence.AtLeastOnceDelivery
VS
http://doc.akka.io/api/akka/snapshot/index.html#akka.persistence.AtLeastOnceDelivery

I am not sure why should I see two `receive` and `receiveCommand` method hooks in there, and which should I implement how ?

**Comment by patriknw** [comment]
AtLeastOnceDelivery is intended to be used as:

    SnapshotAtLeastOnceDelivery extends PersistentActor with AtLeastOnceDelivery

i.e. you are supposed to implement the abstract methods `receiveRecover` and `receiveCommand`. `PersistentActor` implements `receive`.

We can look into if we can make this mandatory, by `AtLeastOnceDelivery extends PersistentActor` instead of `AtLeastOnceDelivery extends EventSourced`, but then I think there is a need for something more internally to support the Java API `UntypedPersistentActorWithAtLeastOnceDelivery`.
