### ISSUE TITLE
ActorPublisher with Stash totalDemand confusion 

### ISSUE THREAD

**Issue by SF-300** [akka/akka#17037]
I'm implementing custom ActorPublisher subclass which has Stash trait. The publisher must receive some initialization message before it can start to respond to ActorPublisherMessage.Request messages. The most natural solution was to stash() all incoming ActorPublisherMessage.Requests until initialization message arrival and then unstash and proceed normally. All seemed to be fine until I started to get IllegalStateException("Input buffer overrun"). It turned out that stashing ActorPublisherMessage.Request doesn't prevent totalDemand increase and hence totalDemand was effectively multiplied for each unstashed message:
```
case _:Request | _:Cancel => stash()
// later
unstashAll() // totalDemand == totalDemand*(number of unstashed Request messages)
```
 I believe that it's a very confusing behaviour and should be documented so newbies like me won't waste time.

**Comment by patriknw** [comment]
good point

**Comment by jypma** [comment]
I just got hit by the same thing. I would appreciate the documentation, but it'd be even better if there were something to prevent this.

Since `ActorPublisher` already overrides some `private[akka]` stuff, might it be an option to have (in main akka) a marker trait like `Transient`, which would cause `Actor with Stash` to not stash those messages? Or maybe `ActorPublisher` itself can find out of `Stash` is being mixed in?
