### ISSUE TITLE
HttpEntity.transformDataBytes is no longer immediate for Strict entities (including Empty)

### ISSUE THREAD

**Issue by RichardBradley** [akka/akka#17048]
In HTTP 1.0-M3, the “`HttpEntity.transformDataBytes`” override on `HttpEntity.Strict` used “`StreamUtils.runStrict`”.
This was removed in 1.0-M4 in favour of a simpler implementation.

The previous version had two distinct advantages: 
 * `Strict` entities would remain `Strict` under a simple transform
 * known-empty entities would remain known-empty under a simple transform

Now if you call “`transformDataBytes`” on an `Empty` entity, it is converted into a `Chunked` entity of unknown length.

We have several bits of app code that transform requests in general ways, which didn't used to distinguish between `Empty` and non-empty bodies, e.g.:

```
def wireLogRequest(
  request: HttpRequest
): HttpRequest = {
  request.copy(entity = request.entity.transformDataBytes(
    Flow[ByteString].transform(() =>
      WireLoggingInterceptStage(...))))
}
```

This code used to work fine for all of `Default`, `Strict` and Empty requests (it doesn’t work for Chunked – see #16319 ).

However, in 1.0-M4, this code now converts `Empty` requests into `Chunked` requests, which throws an exception on Get requests.

I have worked around this by doing:
```
def wireLogRequest(
  request: HttpRequest,
): HttpRequest = {
  val flow = Flow[ByteString].transform(() =>
    WireLoggingInterceptStage(...))

  request.copy(entity = request.entity match {
    case e@ HttpEntity.Empty =>
      // We must run this now, else it doesn't get run for Empty entities.
      e.dataBytes.via(flow).runWith(Sink.ignore())
      e
    case e: UniversalEntity =>
      e.transformDataBytes(e.contentLength, flow)
    case e =>
      e.transformDataBytes(flow)
  })
}
```

This is a bit of a faff for consumers of the Entity classes.
Can we put the “`StreamUtils.runStrict`” back in, or find some other way to make `transformDataBytes` behave consistently on possibly-empty requests?

Thanks,

Rich

**Comment by jrudolph** [comment]
There are probably several issues here.

One problem is that what you call a "simple transformation" isn't really modelled in akka-stream. That means to provide something like what you need we would either need to rely on hacks (the previous version which relied on implementation details) or we would need to introduce a new abstraction for "simple transformations" (we had this before). It turned out that even decompression (which was the main use case for `transformDataBytes`) wasn't a simple transformation and already needed the full power of a Stage.

To solve the problem we could either
 * introduce a proper akka-stream API for runStrict and resurrect the previous code
 * introduce another abstraction or special cased `transformDataBytes` for simple transformations, e.g. `mapDataBytes` that requires that the user-defined function `f: ByteString => ByteString` must always produce as many bytes as it got
 * if you just need to tap into the entity data for logging you may also put the logging infrastructure not in the main flow but add a broadcast element that just taps into the flow and pulls the data out without altering the main stream. An API could then be a method `broadcastDataBytesTo(sink: Sink[ByteString])` which wouldn't need to change entity type

Another problem seems to be that the failing assertion in HttpRequest may be too strict in that it requires that the `entity.isKnownEmpty` for GET requests when the actual condition is more like `!isKnownNonEmpty` and the actual check could be delayed to rendering time.

/cc @sirthias

**Comment by RichardBradley** [comment]
Thanks, I agree with your summary.

> if you just need to tap into the entity data for logging 

There is one other "simple transform" that we use which has been affected by this change.

In some cases we wrap the request stream with a transform that wraps all stream failure exceptions with a known exception subclass.

We need this because we have some API endpoints which relay requests to other web services (a bit like a HTTP reverse-proxy). They create a `HttpRequest` for their downstream services which re-uses the Entity from their upstream client's request. In that case, we were not able to distinguish between stream exceptions which were caused by our client and stream exceptions which were caused by the downstream server without doing something like:

```
def markRequestStreamErrors(
  request: HttpRequest
): HttpRequest = {
  request.copy(entity = request.entity.transformDataBytes(
    Flow[ByteString].transform(() =>
      StreamExceptionWrappingStage(
        e => new ClientStreamException(e)))))
}
```

This now suffers from the problems described above: non-empty Entities are no longer known to be non-empty, so can't be used in Get requests. The "`broadcastDataBytesTo`" workaround you suggest wouldn't fix that case.

> for simple transformations, e.g. ... the user-defined function must always produce as many bytes as it got

You're right -- by "simple" here I think I mean "length-preserving".

**Comment by RichardBradley** [comment]
In case it helps anyone else, and for context, we are currently using a workaround helper function which looks like:

```
  implicit class RequestEntityWithTransformDataBytesPreservingLength(entity: RequestEntity) {
    def transformDataBytesPreservingLength(
      flow: Flow[ByteString, ByteString, Unit])(
      implicit flowMaterializer: FlowMaterializer
    ): RequestEntity = {
      entity match {
        case e@ HttpEntity.Empty =>
          // We must run this now, else it doesn't get run for Empty entities.
          e.dataBytes.via(flow).runWith(Sink.ignore())
          e
        case e: UniversalEntity =>
          e.transformDataBytes(e.contentLength, flow)
        case e =>
          e.transformDataBytes(flow)
      }
    }
  }
```

There is a corresponding class for `ResponseEntity` (they can't be shared due to the types).

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
