### ISSUE TITLE
TypedActor methods returning Future trigger an ask timeout unnecessarily

### ISSUE THREAD

**Issue by drewhk** [akka/akka#17053]
The logic is messed up for Future returning function:
 - we ask the actor for the Future via ask (using a Method message)
 - we register locally an onComplete on that actor to pipe back the result to the original ask

This is however, wrong. It confuses the timeout for getting the Future from the actor with the timeout of that future. What I propose is that the proxy should
 - ask the actor for the Future via ask (using the same mechanism)
 - instead of registering an onComplete we should send the Future (well, remoting will break this so this actually needs some more smartness, but you get the idea)
 - flatten the future at the proxy call site

This in effect:
 - will only AskTimeout if the actual acquisition of the Future failed, but has nothing to do with how long the user returned Future needs to complete

**Comment by rkuhn** [comment]
This does not fix things: we will still need to install the same timeout for GC purposes, because we will need to set up some “receiving entity” on the asking side that will need to be remotely addressable. The current code is doing the right thing entirely as far as I can see.

TypedActor is a shrink-wrapped package that cannot be made equally powerful as normal actors, which is why we will eventually remove it.

**Comment by viktorklang** [comment]
#notabug #wontfix
