### ISSUE TITLE
optionally allow a payload with GET, HEAD, DELETE, CONNECT request methods

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17214]
This may be configurable—the specification says that such payload has no predefined semantics, but it is also not forbidden.

Careful: for TRACE it actually is forbidden, so just ignoring isEntityAccepted based on some configuration is not the right thing to do.

**Comment by rkuhn** [comment]
Thinking a bit more: the server should probably always accept it while on the client it needs to be enabled with a configuration setting (cf. Postel’s law).

**Comment by sirthias** [comment]
Things to remind user of who are trying to rely on GET request entities which are "undefined" by the spec:

1. Existing proxies implementation might refuse to proxy the request payload.

2. By default the responses to GET requests are cachable. (["unless otherwise indicated by the Cache-Control header field"](http://tools.ietf.org/html/rfc7231#section-4.3.1))
It is unlikely that existing cache implementations include the request entity into the cache key, which means that a server relying on GET request entities must make sure to always set cache control headers properly itself.

In general we should discourage users from creating APIs which rely on such "undefined" features. If they choose to ignore this advice they will be on their own and see all kinds of strange issues in the wild, that we will be probably be unable to provide help for.

**Comment by sirthias** [comment]
Also interesting is [section 4.3 of RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3), which was the state-of-the-art spec for almost all HTTP related products that are currently in the field. It says:

> A server SHOULD read and forward a message-body on any request; **if the request method does not include defined semantics for an entity-body, then the message-body SHOULD be ignored when handling the request.**

This [was relaxed with RFC 7231](http://tools.ietf.org/html/rfc7231#appendix-B):

> To be consistent with the method-neutral parsing algorithm of
> [RFC7230], the definition of GET has been relaxed so that requests
> can have a body, even though a body has no meaning for GET.
> (Section 4.3.1)

So apparently the change was done for simplifying parser implementations rather than enabling new API styles.

**Comment by 2beaucoup** [comment]
FTR: This came from https://groups.google.com/forum/#!topic/akka-user/9Ue5m9YC3l8

**Comment by sirthias** [comment]
Interesting pointer from @analytically:
Dropbox decided to switch one of their API calls from GET to POST to get around the "GETs don't have an entity" problem: https://blogs.dropbox.com/developers/2015/03/limitations-of-the-get-method-in-http/

Comparing the downsides of "switching to POST" vs. "GET w/ entity" I'd probably go the latter however.

**Comment by rkuhn** [comment]
So the conclusion seems to be that we enable the use of such “meaningless” payloads both on server and client based on a configuration option that informs about the dangers, right?

**Comment by sirthias** [comment]
Yes, I think that'd be the best approach.

**Comment by analytically** [comment]
What's the decision here? I'm in need of DELETE with json entity. Shall I produce a PR?

**Comment by rkuhn** [comment]
The decision is to allow this, guarded by a config option; a PR would indeed be most welcome, thanks!

**Comment by ktoso** [comment]
Thanks in advance @analytically! Let us know if you need any help to pull this through.
I marked the ticket as in progress do indicate you're working on it.

**Comment by analytically** [comment]
Having limited knowledge of the Akka HTTP codebase, it's not a trivial feat passing settings around. As @sirthias proposes in #16981, just setting `isEntityAccepted = true` for `DELETE` would solve my usecase, and would also not be harmful.
