### ISSUE TITLE
Akka HTTP Handle Execption thrown by a directive

### ISSUE THREAD

**Issue by mrkaspa** [akka/akka#17223]
How can I catch an exception produced inside a directive I’m trying to do this

```
(post & entity(as[DonorLoginRequest])) { donorLoginRequest => …
```

And throws an exception whe unmarshalling into the DonorLoginRequest, I tried to catch it inside 

```
implicit val exHandler = ExceptionHandler {
    case _ => complete(StatusCodes.BadRequest, "F***")
  }
```

But doesn’t work

**Comment by sirthias** [comment]
You'll have to wrap the respective branch of your route structure with the `handleExceptions` directive in order to tie in your custom `ExceptionHandler`.
Alternatively, if your custom handler is in scope at the top-level of your routing structure (where the route get's used, e.g. in a `Http().bindAndHandle(route, ...)` call it will be automatically picked up, without the need for an explicit `handleExceptions` directive.

We'd like to ask you to ask question like these on the akka (or spray) mailing list rather than here, because that way other users can benefit from the entailing discussion as well. (Plus, we reserve the ticket system here for managing our own work on the project rather than user support).
