### ISSUE TITLE
Better Documentation About Materializers

### ISSUE THREAD

**Issue by sirinath** [akka/akka#17221]
More elaborating documentation with examples on materialisers is desired as it is a new concept.

**Comment by rkuhn** [comment]
Do you mean “how to write my own Materializer?” All usage is rather trivial, and writing your own is not something that we want to encourage right now—first we need to have everything working and stable and possibly write a second one ourselves so that we can see the implications.

**Comment by sirinath** [comment]
Not necessarily write your own but internals on what is going on under the hood. Perhaps writing your own would cover the same ground. 

Having mentioned this it would be interesting to maybe have more control of materialisation relate API with a view to have a custom materialisation process.

**Comment by rkuhn** [comment]
Would you mind sketching some use-cases? The Materializer has just one method and that can be implemented in any way it sees fit, so it has full control.

**Comment by sirinath** [comment]
You are commenting from the standpoint of someone who is very familiar with the details as you have been hands on experience implementing it. In my case I only have a superficial view of what this is and what is happening under the hood. So some documentation answering:

 - What is materialisation?
 - Why use materialisation vs other alternative?
 - In using materialisation what happens behind the scene?
 - How does the materialization process work?
 - How to is materialisation implemented? How can you implement your own materialisation?
 - What are the current implementation detail and perhaps what are the future direction you will take to improve?

**Comment by drewhk** [comment]
What is missing from here: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/stream-flows-and-basics.html#Stream_Materialization

**Comment by sirinath** [comment]
The question comes can the graph blueprint be used to generate a non Akka graph by providing a different materializer. 

Also why do you have to make the distinction as materialized value. Any value flowing through the graph is materialised?. Why is toMat, viaMat, materializedValue, etc. needed? Is this distinction really necessary? Is it some internal implementation details which makes it needed? My impression is that these make accessible additional states in processing like failed states and in case of internal use intermediate values in folding. Can this be done without exposing materialisation and perhaps using more simpler naming and concepts which resonate when what is being done? (E,g, accessing error states, intermediate calculation, etc.) If this is the cause can the API made such that you can use domain knowledge to optimise the materialized resources. (With error states and intermediate value access abstracted into different concepts.)

**Comment by sirinath** [comment]
Another line of thought in materilisers comes from: https://github.com/Primetalk/SynapseGrid/. Here you can use different underlying representations. Also a more natural way to access intermediate values and maintain state changes. Here you just generate the representation (in your terminology materialise) but has different abstraction for the intermediate values.

**Comment by drewhk** [comment]
> The question comes can the graph blueprint be used to generate a non Akka graph by providing a different materializer.

These are the future plans. Currently there is only one materialiser provided, but the machinery is there.

> The question comes can the graph blueprint be used to generate a non Akka graph by providing a different materializer.

The materialized value is an *external* channel compared to the elements flowing through the stream which are *internal* channels. A fold for example calculates a final value of the stream, however this value will be consumed *outside* the stream, therefore it needs to be a side-channel to the external world. If you don't need to communicate with the running stream, then you don't need the materialized value.

> Why is toMat, viaMat, materializedValue, etc. needed? Is this distinction really necessary?

This is because of the type safe nature of streams. In order to safely combine materialized values of the different components you use to define a stream layout, you need to explicitly tell Akka and the Scala compiler how you want to construct the final materialized value.

> My impression is that these make accessible additional states in processing like failed states and in case of internal use intermediate values in folding.

The only way to communicate with a running stream from a non-stream context is through the materialized values (you can materialize to a Publisher/Subscriber if you want to, of course). Since the stream layout is just a blueprint, every materialization yields a different materialization result. This is similar to Akka actors:
 - Props is similar to RunnableFlow. Both are reusable, you can create arbitrary amount of running entities from them
 - ctx.actorOf is similar to .run(materializer). Both take a representation (Props or RunnableFlow), then start executing an entity that runs the encoded logic
 - Materialized value is similar to ActorRef. Both are used to communicate with the running entity, and in both cases you get unique, new values when you materialize (actorOf) a new instance every time.

>  If this is the cause can the API made such that you can use domain knowledge to optimise the materialized resources. (With error states and intermediate value access abstracted into different concepts.)

I don't understand what you mean here.

**Comment by sirinath** [comment]
> If this is the cause can the API made such that you can use domain knowledge to optimise the materialized resources. (With error states and intermediate value access abstracted into different concepts.)

If you make materialisation as setting up the process and abstract communication with a running process into another subset, you can perhaps write different implementation of the flow. E.g. a Stomp graph instead of Akka. In this case the communication with the process is a different SPI / API hence it will be less problematic to do thing like this in the future?

**Comment by drewhk** [comment]
> Here you can use different underlying representations.

Yes, it is very similar indeed.

> Also a more natural way to access intermediate values and maintain state changes. 

What do you mean? What is easier? Can you give a runing code example in synapse that you want to see in streams?

>  Here you just generate the representation (in your terminology materialise) but has different abstraction for the intermediate values.

I don't understand this sentence. What do you mean "different abstraction for the intermediate values"? What do you mean by "intermediate value"? Can you please elaborate?

In general, I have hard time to understand what you actually miss here. Can we make it more concrete by giving me an example of existing runnable code, that you want to achieve but can't do with Akka Streams? I try to understand what is the perceived difficulty, but the discussion is simply too high level for me to completely comprehend.

**Comment by sirinath** [comment]
Much of my confusion is more of a terminology issue from what I gathered. I have now more or less understood what I was looking for. You guys are using the term materialisation as an umbrella term for communicating with a running process and accessing error states also the main purpose of setting up the resources to set up the network. 

If possible if might be good to have a different terminology for communicating with a running process than calling it materialisation while materialisation is reserved for setting up the network only.

Thanks for the detailed clarifications.

**Comment by ennru** [comment]
With Materializers mostly removed from the user API in Akka 2.6, I don't see any need for it. Closing.
