### ISSUE TITLE
Possible bug: sending Status.Success message to an Source.actorRef can discard previous messages

### ISSUE THREAD

**Issue by kostya-sh** [akka/akka#17323]
I was experimenting with akka-streams 1.0-RC1 and was confused by the behavior of a sample program I wrote:

```
import akka.actor.ActorSystem
import akka.actor.Status
import akka.actor.actorRef2Scala
import akka.stream._
import akka.stream.OverflowStrategy
import akka.stream.scaladsl.Sink
import akka.stream.scaladsl.Source

object PossibleBug extends App {
  implicit val system = ActorSystem()
  implicit val mat = ActorFlowMaterializer()
  
  val a = Source.actorRef(10, OverflowStrategy.fail).to(Sink.foreach(println)).run()
  a ! "abc"
  a ! "def"
  Thread.sleep(100)           // (1)
  a ! Status.Success("ok")    // (2)
  
  Console.readLine()
  
  system.shutdown()
}
```

The program as it is prints two messages: "abc" and "def"
With Thread.sleep (line (1)) commented out it doesn't print anything
With Status.Success (line (2)) commented out it prints two messages: "abc" and "def"

it looks like there is a race between consuming regular messages and Status.Success message.

**Comment by ktoso** [comment]
Hi and thanks for reporting,
It does work as-designed currently I'd say... it completes the stream and stops the actor **as soon as** it gets a completion message (`Status.Success`).

Perhaps the answer here should be allowing to configure when termination takes place "after buffer is drained" or "right away". 

The problem with "when buffer is drained complete" is that *this may never happen*, if the downstream never requests any more elements. So I don't think the semantics you are asking for are a safe setting.

I'm leaning towards better documenting stopping behaviour (the semantics you want could be achieved using an explicit `.buffer(2, ...)` *after* the Source - since then the buffer will be drained as soon as possible.

**Comment by kostya-sh** [comment]
I now see the reason behind this but I still think that this behavior is confusing.

actorRef(...) takes bufferSize and overflowStrategy parameters (the same as buffer(...)). Chaining it to another buffer feels wrong to me.

Also adding buffer(..) call did not help. I.e. the following code doesn't print anything:
```
  val a = Source.actorRef(10, OverflowStrategy.fail)
    .buffer(10, OverflowStrategy.fail)
    .to(Sink.foreach(println)).run()

  a ! "abc"
  a ! "def"
  a ! Status.Success("ok")
```

**Comment by ktoso** [comment]
You're right that this code is still racy. Was half asleep 5AM-ish and pre-coffee when I was drafting the initial reply, sorry about that.

So summing up, we should amend the behaviour to be such that:
* `Status.Success()` should abide the buffering strategy and first signal the remaining elements, then complete and stop
* `Status.Failure` must be delivered out-of-band, as in: once the Actor receives the failure it OnErrors and stops itself.
- `PoisonPill` is the "stop now" message, as known with Actors

**Comment by patriknw** [comment]
Last proposal sounds good to me

**Comment by ktoso** [comment]
Submitted a PR as soon as I got internet connectivity => https://github.com/akka/akka/pull/17324
Thanks for reporting!
