### ISSUE TITLE
Graph Serialization to XML JSON YAML HOCON etc.

### ISSUE THREAD

**Issue by sirinath** [akka/akka#17360]
Creating the Graph though configuration can be better and useful in some cases.

**Comment by ktoso** [comment]
I had to think for a bit rather intensely to make the connection - you mean the `FlowGraph`?
I'm not sure why one would want to serialize it this way. 

It is serializable using any serializer you might pick - we would advertise for binary ones though, because you may want to ship a "blueprint" to another (remote) actor to materialize as part of actor messaging.

**Comment by sirinath** [comment]
Text is easier to manipulate. Easy to debug in remote systems. Easy to validate than full valid set of code.

**Comment by ktoso** [comment]
> Text is easier to manipulate.
You should not manipulate a flow graph's serialized format... Create / amend the graph, serialize it, send it over the wire, de-serialize it.

> Easy to debug in remote systems. Easy to validate than full valid set of code.
This assumes the serialized form of the FlowGraph was wrong somehow. In this case a) it should not have been allowed to be constructed by the builder in the first place b) when de-serialized and connected not-completely or improperly somehow the FlowGraph builder is able to provide much better hints about *what* is wrong with the connections (like "ports: [in1, important-port] are not connected!") and debugging such things in Scala also gives the help of the typesystem.

If you mean to print out a graph in order to "look at it's layout" I agree, this can be helpful, however I would use the DOT format for this, because you can load it into graph visualisation tools. 
We already have a ticket for this: https://github.com/akka/akka/issues/15153

**Comment by sirinath** [comment]
This can be just another format to store and create the graph / partial graph. E.g. NoFloJS uses JSON fomat to specify the flows. If you are using an visual editor to create parts of the graph and put it together then things are easier if it is done in another format. Using this format you can build and then materialise the graph.

**Comment by drewhk** [comment]
How do you plan to serialize functions? Like in .map(f), how do you plan to serialize f to text? How do you serialize custom stages to text? How do you serialize RS compliant 3rd party implementations included in the graph to text?

**Comment by sirinath** [comment]
The smallest atomic unit will be a persistent component. In many cases this will be a partial graph which is stored with an identifiable name. What will be modeled is the relationship and flows between the components.

So it is not necessary to model `.map(f)` as long as the containing artifact can be persisted and identified.

See the following to generate an idea about it:

 - http://noflojs.org/documentation/json/
 - http://noflojs.org/documentation/protocol/
 - http://noflojs.org/documentation/fbp/

Having the above option will help towards using a subset in a visual UI like http://noflojs.org/noflo-ui/
