### ISSUE TITLE
Fix PubSub behaviour when subscribing to a group

### ISSUE THREAD

**Issue by 2m** [akka/akka#17458]
Couple of issues reported:

1. When subscriber *is not* subscribed to a group topic and publisher publishes to the topic with `sendOneMessageToEachGroup = true`, subscriber does not receive message.
2. When subscriber *is* subscriberd to a group topic and published publishes to the topic with `sendOneMessageToEachGroup = false`, subscriber does not receive message as well.

**Comment by edufer** [comment]
Hi. Just as a normalized rule, an actor subscribing without a group should be equivalent to subscribing with a null group. Then the behavior is exactly the same as with any other group value. In other words, if for the same topic we have subscriptions with many group values, lets say, group1, group2 and null, the null value is a group by itself. So when I send a message with sendOneMessageToEachGroup=true we'll get a single message to an actor in group1, other to group2 and one for the 'group' with null value.
With this behavior we cover all cases.

**Comment by edufer** [comment]
Here you have a workaround in the meanwhile:

If you need to mix subscriptions with and without groups just create two topics, one for every single subscription and other to the ones with a group and also with a fake group id for the ones without a group. Then when you publish to them and you have OnePerGroup=false you publish to the first topic and if not you publish to the other.

**Comment by patriknw** [comment]
After pondering this my conclusion is that it is a matter of how we define and document it. I don't think we should change the implementation (that would also not be trivial) but clarify the documentation. I don't see a strong reason for mixing those two different ways of subscribing/publishing.

Documentation improvements in https://github.com/akka/akka/pull/20227

**Comment by edufer** [comment]
Hi.

The mix situation is just a workaround. The critical point are the one in
the beginning:


   1. When subscriber *is not* subscribed to a group topic and publisher
   publishes to the topic withsendOneMessageToEachGroup = true, subscriber
   does not receive message.
   2. When subscriber *is* subscriberd to a group topic and published
   publishes to the topic withsendOneMessageToEachGroup = false, subscriber
   does not receive message as well.


I suppose that those points are fixed, right?

Many thanks!

**Comment by patriknw** [comment]
Why would you as a developer need that? Either you decided to use groups, or you don't use groups (on both the sender and receiver side). Subscriber and Publisher must anyway agree on a topic to use, so they can also agree on groups or not groups.

**Comment by edufer** [comment]
Ok,Maybe my particular case is not so frequent. I'm implementing an OS
wrapper on top of Akka. In that situation sometimes the end user (the
programmer which use my framework) could assign his subscriber to a group,
and sometimes he doesn't. So If the programmer choose to not use groups I
have to user an Akka api and if the user decide to use groups I have to use
a completely different one. If Akka would implement the NO group like a
NULL group or similar I could use the very same api for all situations
without loose generality.

From a purist point of view Akka (in my opinion, of course)  is connecting
a subscription style to a API feature, which is not strictly necessary.
Because of that I made the suggestion of naming a non-group to a named
void-group so all actors without a group binding could take advantages of,
for example, sending a message to only one subscriber in the nulll group.

Anyway, I got your point. I'm afraid then that I have to implement the
generalization on my side, right?

Thanks again Patrik for your time.

**Comment by patriknw** [comment]
Thanks for clarifying. We might have designed it differently if we implemented this now, but the group feature was added afterwards and is treated rather differently than the non-group topics. Sounds like you can implement it on your side. Thanks for understanding.

**Comment by edufer** [comment]
Thank you.

Ok, we'll implement it on our side.

Regards.
