### ISSUE TITLE
A directive that allows to send request context to an actor and complete request there

### ISSUE THREAD

**Issue by 2m** [akka/akka#17492]
Currently
``` scala
get { ctx =>
  handler ! ctx
}
```

does not compile with:
```
[error]  found   : Unit
[error]  required: scala.concurrent.Future[akka.http.scaladsl.server.RouteResult]
[error]         handler ! ctx
```

//cc @sirthias @jrudolph

**Comment by sirthias** [comment]
We already have something similar, which might be architecturally better:

```scala
get {
  completeWith[Seq[Employee]] { completerFunction =>
    actorRef ! completerFunction
  }
}
```

In this example the `completerFunction` would have type `Seq[Employee] => Unit`, i.e. the backend would not have to depend on *akka-http* in order to be able to access the `RequestContext`.
Rather, everything would remain nicely decoupled and the implicit marshaller for `Seq[Employee]` would be tied in at the *routing layer* rather than in the backend.
```

**Comment by jrudolph** [comment]
The other way is using the ask pattern and completing with a future.

**Comment by hepin1989** [comment]
```
get { ctx =>
  val promise = Promise[RouteResult]()
  handler ! (ctx,promise)
 promise.future
}
```
I may use this,I think.

**Comment by 2m** [comment]
Thank you, everyone. `completeWith` really seems like a better variant than my asked functionality. Not only it decouples response completion from marshalling, it also keeps response completion typesafe.

However I noticed that `completeWith` [does not take marshaller implicitly](https://github.com/akka/akka/blob/b11a5d488fbc1a2212ba317949ddb9c6d58fd480/akka-http-scala/src/main/scala/akka/http/scaladsl/server/directives/MarshallingDirectives.scala#L44). I see that inside that directive marshaller is reassigned to an implicit val, so it seems to be so by design. But it renders usage of `completeWith` [a bit](https://github.com/2m/akka-stream-sandbox/blob/e6d3e71615ba358206bad055d2f190c86d7722b4/src/test/scala/ServerResponseFromActor.scala) verbose.

**Comment by 2m** [comment]
Closing this, as `instanceOf` can be used instead of summoning marshaller with `implicitly`.

**Comment by sirthias** [comment]
@2m Just to get back on your comment that `completeWith` doesn't take a marshaller implicitly:
This is intentional and a limitation of all directives in the routing DSL. Directives cannot have an implicit argument list because this would collide with the `apply` that is pimped onto them.
See also [this section of an old blog post of ours](http://spray.io/blog/2012-12-13-the-magnet-pattern/#removal-of-implicit-parameters) which explains the problem in detail.
