### ISSUE TITLE
Update codahale metrics dependencies

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17515]
low priority
metrics has a new GroupId for artifacts post 3.0.2
The latest version is 3.1.2
some of the related libraries might also need update

**Comment by lucianenache** [comment]
@patriknw I would be interested on working on this.
Is this relevant only to the master branch or it should target also 2.4.x ?

As far as I have noticed the current metrics version is 3.2.4 with a 4.0.0-alpha2 pushing towards a 4.0.0 should we upgrade to 3.2.4 first and afterwards investigate the impact for switching to 4.0.0 or wait directly for 4.0.0 and perform the upgrade to that directly ?

Since I am new to the project and getting my head around the structure, is the ```project/Dependencies.scala``` the only place for managing the dependencies ?

**Comment by patriknw** [comment]
That would be great, @lucianenache 

> target also 2.4.x

no, master is enough

> upgrade to 3.2.4 first and afterwards investigate the impact for switching to 4.0.0

sounds good to start with 2.3.4

> project/Dependencies.scala

yes, that is the place

**Comment by lucianenache** [comment]
Thanks, I will submit a PR later this afternoon then. 

Cheers 
Lucian
