### ISSUE TITLE
StackOverflowError awaiting future within akka

### ISSUE THREAD

**Issue by sthielo** [akka/akka#17530]
works with akka 2.3.10
fails with akka 2.3.11

our prototype's tests wait for some actors to be in place before actually running the tests (allowing smaller timeouts within the tests). it doesn't fail the first time but after some repetitive calls
The failing code called from within a actor's receive (! - we run tests in the same thread using sbt with fork=false, which seams to matter, as running the test from IDEA doesn't show the same errors):
```Await.result(system.actorSelection(system / myServiceActorName).resolveOne, serviceDuration)```
[info]   java.lang.StackOverflowError:
[info]   at java.lang.ThreadLocal$ThreadLocalMap.set(ThreadLocal.java:483)
[info]   at java.lang.ThreadLocal$ThreadLocalMap.access$100(ThreadLocal.java:298)
[info]   at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:184)
[info]   at java.lang.ThreadLocal.get(ThreadLocal.java:170)
[info]   at akka.dispatch.BatchingExecutor$AbstractBatch.resubmitUnbatched(BatchingExecutor.scala:60)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:104)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)

it might be related to #16327 introduced in 2.3.11

**Comment by drewhk** [comment]
Hi @sthielo, thank you for reporting. Can you prepare a minimized test-case that reproduces the problem?

**Comment by rkuhn** [comment]
I must second this: the only way I can think of to get into this situation would be to schedule a callback using the sameThreadExecutionContext within which an Await.result is performed (which is reasonably illegal to begin with), so I’d be very interested in seeing the code that does this.

**Comment by sthielo** [comment]
I tried to strip our playground as much as possible: 
   https://github.com/sthielo/ab11ij 
edit project/Dependencies.scala to switch between akka 2.3.10 and 2.3.11 followed by 'sbt clean test' to show the different behavior (2.3.11 with StackOverflowError).

**Comment by sthielo** [comment]
Some minor infos - I don't think to matter - effects shown on 
* OSX 10.10.3 with Oracle JDK 1.8.0_45 at work
* Win7 64bit with Oracle JDK 1.8.0_40 at home
* CentOS 64bit with Oracle JDK 1.8.0_40 on buildserver

Running the tests in IDEA doesn't show any failure. I guess this is because IDEA starts the test in own jvm.

**Comment by rkuhn** [comment]
Wow, that is some pretty … baroque … code, if I may say so. Synchronously looking up Actors using actorSelection + resolveOne + Await.result has really bad performance and will deadlock eventually, and stubbing out Actors in tests by subclassing LocalActorRefProvider is also not at all recommended—you are relying on internal interfaces and bend their rules at the same time. Looking at what the test actually does you can easily replace all of this with properly passing ActorRefs to the Actors that need them, and the use of TestActorRef can also be removed without consequences.

Having said that, the StackOverflowError is caused by a collaboration of CallingThreadDispatcher and Await.result, multiply nested. I cannot see how any other combination would achieve this effect, which is good since it means that this is not a bug that can happen in legitimate production code. We’ll fix it anyway, but please reconsider how you are using Akka, you are leaving much of the performance and reliability on the table with the current scheme.

**Comment by sthielo** [comment]
I agree with all of your statement ... it was some of the first code in our playground. :-( Our current prototype part should already improve in quality ... we are still learning. Some of us currently participating your course on coursera. All of this learning and expierencing should give us a good start for real code in the future.

**Comment by rkuhn** [comment]
Thanks for this back-ground. I hope my critique did not come across as harsh, it is meant fully constructive; if you have questions you are welcome to ask on akka-user or if you need deeper assistance we can also offer that commercially. In any case, a fix for the StackOverflowError is under way.

**Comment by guidomedina** [comment]
Sorry for the intrusion here, JDK 8u40 matters, I lately running with JDK 8u60 EA builds, I think we have to make developers aware of this Fork-Join bug:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8078490

Which was fixed at JDK 8u60 build 16, more info on JDK 8u60 EA changes: 
http://download.java.net/jdk8u60/changes/

**Comment by rkuhn** [comment]
@guidomedina Wasn’t that problem limited to the actual JDK ForkJoinPool (which we don’t use) and only when it is configured to have only a single thread?

**Comment by guidomedina** [comment]
I wasn't sure Akka/Scala use ForkJoinPool from Java, I thought it was worth mentioning it since these specific bugs get me chicken skin, I also mentioned it because one of the tests done for Akka on someone's else github JMH benchmark -can't recall what was being tested- mentioned it which was when I learned about it, that been the case then disregard my comment ;-) just trying to help.

**Comment by rkuhn** [comment]
I agree that such bugs are really scary, and thanks in any case for pointing it out! Based on the evidence I concluded that there is currently no need to panic ;-)

This would change, though, once we switch to using the JDK’s FJP implementation in the master branch. How would you propose to communicate this issue, where would you look? It should probably be asked and answered on StackOverflow, perhaps a link posted on letitcrash.com or even a news item on akka.io?

**Comment by guidomedina** [comment]
Probably in two places:

* A JDK compatibility page for Scala, for the things are are more global that would affect any Scala proogram.
A JDK compatibility page for Akka, for the things that can affect Akka without overlapping the Scala side.
* At Akka release notes, a pointer/link to the first two.

Once Akka and/or Scala are released on the news suggest to check for JDK compatibility issues for both?

Hope that helps,

Guido.
