### ISSUE TITLE
Document effects of enabling HTTP pipelining (possible head-of-line problem) in connection with streams

### ISSUE THREAD

**Issue by samueltardieu** [akka/akka#17595]
Long-running HTTP requests using `POST` will not cause other requests to the same host to be delayed in any case as they are not idempotent, and their slot cannot be used for pipelining before the request is over.

However, the user has no way to indicate that a `GET` request may cause a head-of-line problem because it is a long-running one. For example, it is possible to request future changes made to a CouchDB database using a `GET` request to the special "_changes" endpoint. In this case, additional requests may be queued onto the same slot if pipelining is enabled.

Today, a user can use a separate pool with pipelining disabled to achieve this (pending resolution of #17591), but it complicates things as the superpool cannot be used for example. A request-level flag would make things easier.

**Comment by jrudolph** [comment]
FWIW I would just add a note not to ever enable pipelining until you know what you are doing which includes knowing about the head-of-line blocking issue which is well-known and one reason pipelining isn't used in practice.

As you cannot rely on servers handling it properly and you cannot even find out which servers are supporting it pipelining is an absolute special case that you don't want to use normally and which is IMO only implemented because the specs mandates it. In practice, browsers don't use it and the head-of-line blocking problem has been solved for years with spdy and http 2.0. Spending time on an improving pipelining would be better spent on implementing http 2.0.

/cc @sirthias

**Comment by sirthias** [comment]
I agree with @jrudolph in that, after the fix of #17403, the only things we should change is to better document the effects of enabling HTTP pipelining and required entity consumption.

**Comment by rkuhn** [comment]
agreed, this is a doc issue for HTTP/1.1
