### ISSUE TITLE
epub publishing broken?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17603]
"@akkateam EPUB formats at akka.io/docs/ only contain 8 pages of links to web and does not work on offline ebook readers" via https://twitter.com/mohamnag/status/604003318885523456

**Comment by ktoso** [comment]
It is broken for 2.3.11 http://doc.akka.io/docs/akka/2.3.11/Akka.epub

**Comment by ktoso** [comment]
"@akkateam I tested also the older version and was the same: 2.2.5"

**Comment by rkuhn** [comment]
What exactly constitutes broken? (or conversely, how would I know that it’s working?) The files are ~2MB heavy …

**Comment by mohamnag** [comment]
so I reported the original issue, I tried to dig further and the problem was not what I suspected at the beginning. The content are not linked to web but they are linked with wrong protocol. however the issue remains as before, I cant use it on my ebook reader.

I'm not sure how you test the result but if you use "calibre" for opening the book, after clicking on the "Introduction" on java documentation index, a browser window is opened instead of simply going to that page.

**Comment by mohamnag** [comment]
so I could use the book by converting it to mobi format, however not such elegant ebook as I have seen. Looks more or less like a webpage opened on B&W.

I have seen cleaner ones generated from [gitbook](https://github.com/GitbookIO/gitbook)

**Comment by rkuhn** [comment]
As I don’t use ebooks I’d very much welcome PRs and/or more background on this issue. FWIW we are using sphinx to build the documentation and changing that would need very good justification (because it probably would be a large amount of work).
