### ISSUE TITLE
Class Flow of Java DSL uses scala Future as parameter for mapAsync and mapAsyncUnordered 

### ISSUE THREAD

**Issue by agolubev** [akka/akka#17622]
As far as I understand in Java API there should be now Scala classes. If so we need to wrap Future as it's  done for functions and pair.

**[note: valid ticket, but delayed until we can use CompletableFuture in Java APIs] -- ktoso**

**Comment by ktoso** [comment]
Future is a bit special - Java's `java.util.concurrent.Future` is not very good, as in - if forces clients to block in order to get a value out of it. The new `CompletableFuture` addresses that problem, however we can not require users to upgrade to JDK7+ on the `release-2.3...` branches, we can and did already on the master branch (Akka 2.4).

So yes this ticket makes sense, but only after we have merged Akka Streams into Akka 2.4.

**Comment by agolubev** [comment]
Ok, that makes sense.

**Comment by rkuhn** [comment]
this has been fixed
