### ISSUE TITLE
Include links to the source file of the code segment in the docs

### ISSUE THREAD

**Issue by 2m** [akka/akka#17650]

**Comment by 2m** [comment]
https://groups.google.com/forum/#!topic/scala-user/ZO_2__i63jA

**Comment by briantopping** [comment]
Interesting thread, I guess I was not alone in this. Thanks @2m for filing this, @jrudolph for linking them.

To me, the shining example of documentation is Sencha ExtJS. The pages are each treated as threaded discussion, providing both a direct feedback loop to documenters and allows the community to learn from each other. I've sometimes learned as much from the discussions that grow on a page as from the page itself.

I hesitated to suggest this for Akka in the past because I don't like proposing what I don't have the resources to contribute to, but now that the subject is broached...

**Comment by rkuhn** [comment]
Thanks for the input in any case :-)

**Comment by ktoso** [comment]
I think that'd be very useful indeed – esp. for Akka HTTP where sometimes seeing the entire class is helpful (to see implicits / included directives)

**Comment by Captain1653** [comment]
It's the old issue. Is it still needed? I can try to do it, if you help me. Can you show me one example "as is" and "should be" in docs? I'll find other examples and fix them.

Kind regards

**Comment by johanandren** [comment]
<img width="1145" alt="Screenshot 2021-06-28 at 21 48 21" src="https://user-images.githubusercontent.com/666915/123695208-9138b100-d85a-11eb-8122-83fa96eabc5b.png">

This is already present since quite a while.
