### ISSUE TITLE
doc: Headers in new doc should be references

### ISSUE THREAD

**Issue by briantopping** [akka/akka#17669]
It's helpful if the references generated by Sphinx would be relative references in HTML. 

Example from Github:
![akka_akka_and_inbox__27574_messages__3_unread_](https://cloud.githubusercontent.com/assets/158115/8019219/21bb7bba-0c6d-11e5-83d6-786b95f44731.png)

Even without the scriptalicious little link icon, being able to "Inspect Element" in the browser and grab the generated relative reference would be a great start for discussions about the documentation.

**Comment by rkuhn** [comment]
Hmm, what exactly do you mean? All headings have `id` tags and these are used in the ToC at the top right of each page.

**Comment by ktoso** [comment]
I understand what Brian means and agree - it's about when you click a header it should change the location in the browser, so that copying links is easier - currently you have to revert to looking at the ToC and inspect element.

I had this working on an asciidoctor PoC branch, should be able to port it back to the sphinx based docs.

**Comment by rkuhn** [comment]
Ah, thanks for the pointer, yes, that would be great.

**Comment by briantopping** [comment]
Yes, thanks Konrad. It's possible to "inspect element" in most browsers and cobble a link now, but far more useful to do it the way github markdown generates doc. Apologies for the lack of clarity!

**Comment by ktoso** [comment]
Totally agree Brian, let's see if I'll be able to find my hack and port it to our sphinx docs :)
