### ISSUE TITLE
Optional entity and empty body

### ISSUE THREAD

**Issue by 2m** [akka/akka#17716]
As [reported in the mailing list](https://groups.google.com/forum/#!searchin/akka-user/optional$20entity/akka-user/gvP184RVHZQ/2QOfmMOHCAkJ) akka-http is not able to handle a request with an empty body when route expects an optional entity.

Even an empty string is not a [valid json](https://www.ietf.org/rfc/rfc4627.txt) it should still be possible to handle such a request when expected entity is optional.

**Comment by jrudolph** [comment]
The issue on the mailing list was that

```scala
entity(as[Option[DeleteUserBody]])
```

returns a 400 response with this message:

```
The request content was malformed:
JSON terminates unexpectedly.
```

The underlying issue is what to expect for the above entity line. This is statically decided by the choice of the implicit unmarshaller.

In this case a JSON unmarshaller was chosen which depends on the body being well-formed JSON (which an empty entity isn't). A JSON unmarshaller for `T` is always available if a JsonFormat for `T` is available which is because we define a generic `JsonFormat` for `Option[T]` in spray-json. However, this works on a `JsValue` and not on the plain input string so it cannot be fixed on that level.

Instead, you could also lift a JSON unmarshaller for `DeleteUserBody` using `GenericUnmarshallers.targetOptionUnmarshaller` which would already do the right thing. So, the question here is how to disambiguate the two cases and make sure the right unmarshaller is chosen.

/cc @sirthias

**Comment by sirthias** [comment]
That is indeed a good question. Basically we'd want to deprioritize `DefaultJsonProtocol.optionFormat` over `GenericUnmarshallers.targetOptionUnmarshaller` in this case.
However, because of the old-school way that spray-json defines its infrastructure implicits the `DefaultJsonProtocol.optionFormat` is usually explicitly imported, which puts it into a higher implicit priority bracket than the `targetOptionUnmarshaller`.

So, unfortunately, there doesn't appear to be a clean and good solution.
The best solution would probably be to remove the `DefaultJsonProtocol.optionFormat` in spray-json altogether (as it is quite limited anyway) and replace it with something better where is really needed (which is defining JsonFormats for case class hierarchies). However, we can't do that from akka-http.

The way I see it is that we need to address this via documentation, where we ask people to either
`import spray.json.DefaultJsonProtocol.{optionFormat => _, _}` in these cases or shadow `optionFormat` if they mix in the `DefaultJsonProtocol` trait.

**Comment by jrudolph** [comment]
Would adding a local alias for the `targetOptionUnmarshaller` help? Maybe if you write

```scala
implicit val optionsAsEmptyUnmarshaller = Unmarshallers.targetOptionUnmarshaller[HttpRequest, DeleteUserBody]
```

this unmarshaller would have higher priority than any otherwise imported ones?

**Comment by sirthias** [comment]
I haven't checked but that may provoke an implicit ambiguity if I `import DefaultJsonProtocol._` instead of mixing it in as a trait.

**Comment by divijan** [comment]
I was going to raise an issue that seems a sub-issue of this one. I define my own JsonSupport in the same vein as SprayJsonSupport is defined. I would like Entity Expected error message instead of 

    The request content was malformed:
    ...

when no body is provided. This also holds for non-optional entity routes. Can this be made a default behavior on the lowest level Unmarshallers, like byteStringUnmarshaller? Judging from MarshallingDirectivesTest in akka-http-tests, the user is expected to handle empty entities by hand, which, to my mind, should be handled automatically

**Comment by sirthias** [comment]
@divijan If you write your JSON support yourself then you should simply reject with a `RequestEntityExpectedRejection` if no request entity is present.

**Comment by analytically** [comment]
:+1:

**Comment by ymeymann** [comment]
Any plans to fix this issue or at least a workaround?

**Comment by ymeymann** [comment]
I ended up doing 
```scala
def myMethod(e: Option[MyEntityType]) = ???
...
extractRequest { req =>
  if (req.entity.contentLengthOption.contains(0L)) {
    myMethod(None)
  } else {
    entity(as[MyEntityType]) { e =>
      myMethod(Some(e))
    }
  }
}
```
Is it a reasonable workaround?

**Comment by bandrzejczak** [comment]
@ymeymann You can enclose it into your own directive:
```scala
def optionalEntity[T](unmarshaller: FromRequestUnmarshaller[T]): Directive1[Option[T]] =
  extractRequest.flatMap { req =>
    if (req.entity.contentLengthOption.contains(0L)) {
      provide(Option.empty[T])
    } else {
      entity(unmarshaller).flatMap(e => provide(Some(e)))
    }
  }
```

**Comment by analytically** [comment]
This should be part of Akka HTTP.

**Comment by bandrzejczak** [comment]
Actually I've just checked and it doesn't work for empty body. What I've actually used and tested is:
```scala
def optionalEntity[T](unmarshaller: FromRequestUnmarshaller[T]): Directive1[Option[T]] =
  entity(as[String]).flatMap { stringEntity =>
    if(stringEntity == null || stringEntity.isEmpty) {
      provide(Option.empty[T])
    } else {
      entity(unmarshaller).flatMap(e => provide(Some(e)))
    }
  }
}
```
Seems hackish, but I haven't found better way to check whether the body is empty. `entity.isKnownEmpty()` doesn't work well for this case.

**Comment by genarorg** [comment]
Hello, if the ultimate goal is to make the body optional, you can just provide an alternate route if you get a rejection from the entity directive:

``` scala
entity(as[SomeModel]) { model => 
  complete(OK, "a request body was received") 
}
~  complete(OK, "no request body received")
```

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
