### ISSUE TITLE
RoundRobinRoutingLogic negative index after Long wrap around

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17738]
Guido Medina proposed improvements here: https://groups.google.com/d/msg/akka-user/bMfdK9ox4-I/gvRSAZtzEqEJ

**Comment by guidomedina** [comment]
Even though you created this issue for 2.4.0 I couldn't successfully import Akka current master into IntelliJ *-latest and updated IntelliJ with Java 8u60 EA b19-*, after several minutes on my laptop with 8GB of RAM it completely froze.

So I checked out release 2.3.dev and created my branch from it, hope that's not a problem, also I made sure I didn't reformat anything and only modified what was related plus one typo causing a red warning at IntelliJ [#comment] and removed a couple of unused imports.

**Comment by ktoso** [comment]
Hi @guidomedina, sadly the `release-2.3-dev` branch is "streams and http only", so it's not the target branch for this feature - it would be ok on `release-2.3`. Don't worry for now though, let's discuss the feature in the PR for now, and then switch the target branch (new PR)

**Comment by guidomedina** [comment]
That's fine, I'm very agile with git branches and stuff, see the streams of thoughts at the pull request because I'm hesitating a bit, I know the small *-and theoretical-* problem that it is fixing, but unless you find me a case where you can have more than 64 processors and you can process more than 100m msg/s and in fact take less than a year to exhaust long numbers, then that would be human reachable, otherwise it is safe to treat it as infinite mathematically speaking and now I feel like I have wasted a bit of everyone's time for a concern that isn't really a concern.

**Comment by ktoso** [comment]
Long overflow *does* happen sometimes... See funny case in youtube last year: http://www.economist.com/blogs/economist-explains/2014/12/economist-explains-6 :-)

Getting to review the PR finally now

**Comment by guidomedina** [comment]
292 years processing 1b msg/s, that would be a beast of a server, hidden in some bunker? :D

**Comment by ktoso** [comment]
Irrelevant to our case, but I love the story about how they got into the overflow scenario :-)

**Comment by guidomedina** [comment]
Yeah, this isn't a distributed counter, nor persisted, nor serialized.
