### ISSUE TITLE
explain Magnet Pattern in HTTP docs

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17749]
users will invariably confused by missing implicits and will need to have a goto place to find out more

**Comment by briantopping** [comment]
I've never fully understood magnets after a few years of using Spray. That probably something I shouldn't admit. Seems like I usually grok these subjects from a presentation, you guys put out great ones. Maybe this is fodder for one.

Which leads me to think: It might be very cool if the presentations you guys do were linked from the documentation at appropriate points (or even embedded to give that uber rich browsing experience...)

**Comment by jrudolph** [comment]
IMO the only good reason we still use some magnets is that they are the only possible way to write functions

```scala
def f[T](t: T)(implicit tc: TC[T]): X => Y
```

which you can use as

```scala
f(t).apply { x =>
  // ...
}
```

without having to use the explicit `apply`. Without explicitly writing `apply` the code block will be interpreted as the implicit value.

A magnet just collects the `t` and a type-class `TC[T]` into a single value, the magnet, so that `f` can look like this:

```scala
def f[T](fMagnet: FMagnet[T]): X => Y
```

and its usage like this:

```scala
f(t) { x =>
  // ...
}
```

The basic usability problem, however, isn't related to magnets but to the bad support of implicits in the scala compiler. This cannot be explained away but only been avoided by decreasing the use of implicits (which is something we tried to do with the move to akka-http by moving many implicits into the RequestContext).

**Comment by sirthias** [comment]
@briantopping I assume you've seen [our blog post from the end of 2012](http://spray.io/blog/2012-12-13-the-magnet-pattern/), which tries to exhaustively explain the pattern as well as its motivation.
Even though it's 2.5 years old it still applies to the current state of Scala in many ways.

**Comment by briantopping** [comment]
@sirthias: Hmm, good stuff. Even more so that I understand it this time :-) 

I posted somewhere that it might be good to have an "Akka concept map" for people to learn by.. In other words: "If you need to understand `Z`, `X` and `Y` are prerequisites that you can see from this map and if you don't understand `X` as a prerequisite to `Y`, you may not understand `Y` either. It helps people understand _when_ to learn something, which may have been my problem on first reading of this, 

Apparently, I just wasn't prepared with the prerequisites the first time I read it, but then checked off the document as "visited" and didn't study it when it came across again. Tools shouldn't be created just because one flawed process with one person, but I can't be the only one that's made this mistake.

It's not that hard to imagine the documentation become a very nice conceptual DAG. I think it blends well with the tweet thread @jamie-allen started regarding scaling the growth of Scala training in general as well. Implementing it is obviously a different story since it would require actual UX people to study the problem and sponsors to pay their rent while they do.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
