### ISSUE TITLE
Document Tupler and its effect on Unit and other TupleX extraction

### ISSUE THREAD

**Issue by jypma** [akka/akka#17754]
I'm trying out the scala DSL for `akka-http`'s routing part, and it seems that when trying to pull in a `Future[Unit]` into my route, I'm hitting a strange compile error.
```
  val futureOfUnit:Future[Unit] = Future.successful( () )

  val route =
    path("success") {
    onSuccess(futureOfUnit) { unit =>
      complete("Future was completed.")   // compile error
    }
  }
```
The indicated line fails with the following compile error:
```
type mismatch;  found   : akka.http.scaladsl.server.StandardRoute  required: scala.concurrent.Future[akka.http.scaladsl.server.RouteResult]
```
`StandardRoute` extends `Route`, which is a `RequestContext => Future[RouteResult]`. I'm guessing that possibly, somehow the compiler found a `RequestContext` to insert, invoking the function that `complete` returns, rather than returning the function itself.

My IDE also informs me about a _Call-by-name parameter creation_ on the `onSuccess` line. Maybe that's related?

Anyway, the extraction syntax works fine if invoked with anything except `Unit`, so maybe it's something to look into, or at least include a possible workaround in the docs. The only workaround I could come up with was to do `onSuccess(futureOfUnit.map(_ => true)) { unit =>`, turning it into a `Future[Boolean]`. That's hardly nice :)

The use case here is to complete a route after the future has completed, without relying on the result of that future (other than it completing successfully, without an exception).

**Comment by jypma** [comment]
By the way, this is on akka-http 1.0-RC3.

**Comment by jrudolph** [comment]
That's a feature of the general structure and syntax of directives to prevent that directives extract nested tuples.

I'll try to explain it on an example. 

If your future would be of type `Future[Int]`, `onSuccess(fut)` would be of type `Directive1[Int] = Directive[Tuple1[Int]]`. 

In your case, the same reasoning would make `onSuccess(fut)` return a `Directive1[Unit] = Directive[Tuple1[Unit]]`. However, the DSL interprets `Unit` as `Tuple0` and automatically converts the result to `Directive[Unit] = Directive0`.

A similar thing happens if your future returns a tuple, e.g. for `fut: Future[(String, Int)]`, the type of `onSuccess(fut)` wouldn't be `Directive1[(String, Int)] = Directive[Tuple1[Tuple2[String, Int]]]` but would automatically be converted to `Directive[Tuple2[String, Int]] = Directive2[String, Int]]`.

All of this automatic conversion is done for you convenience so that it is easy to extract values from directives 1) without having to pack and unpack tuples all of the time and 2) allowing to combine directives in various ways using the `&` operator and others.

So, if you change your code to

```scala
  val futureOfUnit:Future[Unit] = Future.successful( () )

  val route =
    path("success") {
    onSuccess(futureOfUnit) {
      complete("Future was completed.")
    }
  }
```

it should work.

(
Similarly for a Tuple2:

```scala
  val futureOfUnit:Future[(String, Int)] = Future.successful( ("a", 1) )

  val route =
    path("success") {
    onSuccess(futureOfUnit) { (str, i) => // no manual tuple extraction necessary
      complete("Future was completed.")   // compile error
    }
  }
```
)

/cc @sirthias

**Comment by jypma** [comment]
Duh, of course! That helps, thanks so much!

I guess that leaves this issue to be just about documentation then, or could I have read about this somewhere beforehand?

**Comment by jrudolph** [comment]
Yes, it should be documented properly.

**Comment by ktoso** [comment]
We'll want to put basically what @jrudolph explained there into the docs here

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http  (direct link to new issue visible on github just above this comment). Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
