### ISSUE TITLE
Use reactive streams demand signal to trigger 100-continue

### ISSUE THREAD

**Issue by jroper** [akka/akka#17782]
Http 100-continue is used to allow HTTP clients to not send request bodies if the server is going to refuse it anyway.

Akka HTTP supports this by checking whether the server attempts to consume the request body stream or not, ie, whether a sink is provided to the source.  While this sounds ok, a better mechanism, in my opinion, is to use reactive streams demand to signal it, as this will work better when integrating Akka HTTP with other, non Akka streams, reactive streams implementations.  The 100-continue response itself is a request for demand, so maps nicely to the concept of invoking `request` on a `Subscription`.

So essentially what I'm saying is rather then sending `100-continue` when `Source.runWith(Sink)` is invoked, it should be sent when the (akka streams equivalent of) `Subscription.request` method is invoked.

@jrudolph @sirthias any thoughts?

**Comment by jroper** [comment]
Just to put a concrete use case here, while in Akka HTTP, the developer has to explicitly connect the source to their sink, and this is what triggers the continue, in Play, the developer always returns a Sink, and it's based on the demand from that sink as to whether continue should be sent.  So, the situation with Play is that whether continue is sent or not is decided dynamically after the stream is materialised.  So the use case is for when whether to continue or not is decided dynamically by the stream, not before stream materialisation.

In order to implement Play on top of Akka HTTP as it currently stands, we need to materialise two streams, the first to consume the initial demand, and the second to actually plug the source in if there is demand to be consumed.  Obviously, this is less than ideal.

**Comment by rkuhn** [comment]
If you look at [the implementation](https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala#L143) you will see that this is exactly how it is implemented already: 100-continue is triggered by demand arriving at the Source within the entity. Therefore I do not fully understand what the problem is.

One problem with the approach you describe is that in Akka Streams the generation of demand is automatic within the Processors and Subscribers that our graphs materialize to—this is due to abstracting over the input buffer as an internal implementation detail. I still maintain that this is a good thing, users should not have to worry about this aspect. I fully appreciate that this is possibly the largest mismatch between (fully synchronous) Iteratees and (fully asynchronous) Streams, where there used to be strict coordination between producer and consumer there now is some slack to allow for the asynchronous processing to be efficient.

Coming back to your use-case, could you write down a very concrete piece of code that illustrates in which way the provision of the Sink could be made dynamic? I don’t see how that should work in a way that does not depend on running reactive streams in “synchronous mode”.

**Comment by jroper** [comment]
You're right, I just implemented an isolated test case and demand is triggering 100 continue, not materialisation.

**Comment by jroper** [comment]
Ok, I found the problem, the behaviour I was actually seeing was caused by #18013.
