### ISSUE TITLE
Document that DetachedStage resets holding state when absorbing termination (ScalaDoc)

### ISSUE THREAD

**Issue by Joe-Edwards** [akka/akka#17803]
If you put a `DetachedStage` into a downstream holding state, when it absorbs termination that state appears to be reset. For example:

```
class DetachedStageSpec extends Specification {
  "DetachedStage" should {
    "not reset demand when absorbing termination" in {
      implicit val system = ActorSystem()
      implicit val materializer = ActorFlowMaterializer()

      var onPullCalls = 0

      class Stage extends DetachedStage[String, Int] {

        override def onPush(elem: String, ctx: DetachedContext[Int]): UpstreamDirective = {
          ctx.holdUpstream()
        }

        override def onPull(ctx: DetachedContext[Int]): DownstreamDirective = {
          onPullCalls += 1
          ctx.holdDownstream()
        }

        override def onUpstreamFinish(ctx: DetachedContext[Int]): TerminationDirective = {
          ctx.absorbTermination()
        }
      }

      val (source, sink) = TestSource.probe().transform(() => new Stage).toMat(TestSink.probe())(Keep.both).run()

      sink.request(1)
      onPullCalls mustEqual 1
      source.sendComplete()
      sink.request(1)
      onPullCalls mustEqual 1 // This assertion currently fails (as onPull is called twice)
    }
  }
}
```
If I hold downstream, I don't expect another 'onPull' until pushing an element - otherwise I've got more demand than I should!

Naturally this also affects AsyncStage (which is where I noticed it)

**Comment by drewhk** [comment]
There is no bug here. Imagine what would happen if the framework would *not* call onPull for you:
 - you are in the state where you are holding downstream
 - now upstream finish happens, and you absorb the termination
 - at this point no onPull, or onPush can ever occur, ending up with a deadlock

The reason why there is an explicit absorbTermination() call in the first place, as opposed to just allowing directly to call the push methods from the termination handlers is exactly to be able to recover activation signals.

Depending on the stage type absorbTermination() might cause onPull to be called:
 - in the case of PushPullStage, onPull will be called by absorbTermination() if the activation token is upstream (we expected an onPush), and therefore the upstreamFinish event means that it will never come back as an onPush, so the token must be restored. If the next expected signal would be pull, then absorbTermination has no effect apart from stopping the completion process at the stage.
 - in the case of DetachedStage, onPull will be called by absortbTermination() if the downstream token is currently hold by the stage and upstream finishes, since there cannot be an onPush() method ever that would "set it free" by calling pushAndPull(). If the stage does not hold the downstream token, then absorbTermination has no effect apart from stopping the completion process at the stage.

**Comment by drewhk** [comment]
The AsyncStage scenario is less clear-cut though, since there *might* be an external signal that is able to kick off the hold downstream token. But for ordinary DetachedStage it is expected and correct.

**Comment by Joe-Edwards** [comment]
Ah, I didn't realise it was the absorbTermination calling onPull (as opposed to more demand). That does make more sense. Perhaps the documentation on absorbTermination should make it clearer that this may happen?

It's still a bit annoying in the AsyncStage case (which is what I'm really interested in) but I guess I can keep track of that special case myself.

**Comment by drewhk** [comment]
I have to look up AsyncStage, because in that case this can be a bug. And yes, adding some documentation might help.

**Comment by drewhk** [comment]
The case at least for PushPullStage is mentioned in the Note here: http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/stream-customize.html#Completion_handling

**Comment by Joe-Edwards** [comment]
OK, thanks. If you're interested, the base stage I'm making looks like [this].

It seems to be working as expected now.

**Comment by rkuhn** [comment]
Did I understand correctly that everything is as it should?

**Comment by Joe-Edwards** [comment]
IMO there's still some _surprising_ behaviour here: calling absorbTermination() while holding the downstream ball results in an additional onPull() call.

- In a DetachedStage this makes some sense, because otherwise you would be in a guaranteed deadlock.
- In an AsyncStage it is less clear, since you can also 'escape' the deadlock by receiving an async input.

However there is a reasonably compelling argument for consistency between the two, so I'm happy if it's left as-is :)

**Comment by drewhk** [comment]
First, this should be properly documented. This behavior is intended, and correct for DetachedStage, however, I am not sure if this is desirable for AsyncStage. It is easy to work around this in AsyncStage though, but something that we should think about at least.

**Comment by rkuhn** [comment]
AsyncStage is intentionally not yet documented, so we’ll get around to that when writing those docs. So, this ticket shall be dedicated to adding a note to the ScalaDoc for `Context.absorbTermination()`.

**Comment by patriknw** [comment]
@drewhk this issue is marked as invalid, but it is still open?

**Comment by drewhk** [comment]
No, this is not invalid, this behavior needs to be documented. There is no bug though.
