### ISSUE TITLE
Use CRDTs instead of PersistentActor to remember the state of the ShardCoordinator

### ISSUE THREAD

**Issue by smlin** [akka/akka#17846]
Currently the cluster-sharding module requires an akka-persistence journal for it to work (and database of course). With CRDTs it would be possible to remove this requirement.

**Comment by patriknw** [comment]
That is a very interesting thought, that I also have had.

The difficult part is if we can get enough consistency.
Let me illustrate with an example.

* 7 nodes: n1, n2, n3, n4, n5, n6, n7
* coordinator lives on n1
* shard s7 for entity e700 is allocated to n6 and the coordinator successfully writes this to a majority of nodes, which happens to be n1, n2, n3, n4
* e700 is started on n6
* network partition, (n1, n2, n3, n4) / (n5, n6, n7)
* downing decision to keep (n5, n6, n7), and shutdown (n1, n2, n3, n4)
* n5 becomes new coordinator in the cluster that now consists of (n5, n6, n7), it reads from majority, e.g. n5 and n6, which don't contain any information about s7 (because it was not replicated there before the split)
* s7 for entity e700 is allocated again, now to n7, and now e700 is running on both n6 and n7

This could also happen if (n1, n2, n3, n4) crashed, instead of network partition.

**Comment by smlin** [comment]
Such "unhappy" partitioning is possible only when allocation of s7 to n6 happens before the data about this event was replicated.
I also thought about inconsistency and came to a conclusion that it can be solved by instantiating a coordinator on each node, from which only one will be allowed to write to CRDT collection (change coordinator state). I think it should be the one on the oldest node. So e700 may be started on n6 only after data about this had been received by coordinator6 from coordinator1.

Earlier I was planning to make a small PR to demonstrate this concept, but I have time only after Monday.

**Comment by patriknw** [comment]
it is indeed interesting, and we should try to find a solution, even if it means a "relaxed" mode, which perhaps can't be used with persistent entities

**Comment by smlin** [comment]
I make PR to demonstrate this concept. https://github.com/akka/akka/pull/17871
1) After some thoughts I was decided to save the Coordinator as singleton, but to allow the changing of the distributed data only from a region inside which shard would be allocated. It is allowing do not worry about inconsistency between the distributed data, Coordinator and ShardRegions.
2) Currently I do not know how make the rebalancing and proxy. But I think it is solvable problem.
