### ISSUE TITLE
pr validation build dependencies doesn't work?

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17841]
For example, akka-distributed-data was included in this pr validation

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3041/consoleFull

which was triggered by pr https://github.com/akka/akka/pull/17839
changes in akka-docs, akka-persistence and akka-sample-persistence-java-lambda

**Comment by patriknw** [comment]
not urgent
cc @ktoso

**Comment by ktoso** [comment]
Thanks, will investigate

**Comment by ktoso** [comment]
I see, the diffing (which determines which directories changed) is too naive in this case..
It compares to `master`, so if there's other changes on master since this PR was created it will yield more directories as "touched", example:

- create PR A, based on `aaaaa` hash
- some PR B gets merged to `master`
- PR validation A runs, compares with `master` to see how it differs from the changes in here, this yields also the changes introduced as B as "diff", so will include them in the test run.

Now I'm thinking if this is a bad thing or not really hm...

**Comment by 2m** [comment]
Do you know what jenkins does with git before starting PR validation? If it does a merge commit then you could diff the current commit with HEAD^ to see the diff of what has changed.

**Comment by ktoso** [comment]
I wasn't sure it it always does a merge commit hm... that would be awesome, let's see

**Comment by 2m** [comment]
It would be wrong If it would not do a merge commit and validate the PR branch, as then validation would run on a code that may never see master.

**Comment by ktoso** [comment]
From what I noticed it does always perform a merge, let's go with your suggestion of `diff HEAD^` :-)

**Comment by 2m** [comment]
Nice. :) I think you will be able to get rid of some of the env var checking in the code in this case.

**Comment by patriknw** [comment]
+1, great suggestion @2m
