### ISSUE TITLE
[akka-cluster] Getting `sending HandOverToMe to [None]` on newer versions (2.3.9 and 2.3.11) while it's Ok in older version (2.3.6)

### ISSUE THREAD

**Issue by AmirKarimi** [akka/akka#17909]
I'm using akka cluser sharding. When akka version is `2.3.9` or `2.3.11` I get `sending HandOverToMe to [None]` messages and the cluster is getting ready too late (35 seconds) while there is no `sending HandOverToMe to [None]` in version `2.3.6` and also cluster gets ready faster (3 seconds). 

I've build a sample to demonstrate it here: https://github.com/AmirKarimi/akka-cluster-shardin-bug-2.3.9

**Comment by ktoso** [comment]
Thanks for reporting, we're a bit short on manpower over this month (holidays season), but will try to have a look at it as soon as we can.

**Comment by patriknw** [comment]
`HandOverToMe to [None]` is not an error. There might have been some other bug in 2.3.6 that caused it to get ready faster. I don't see any issues when running your sample.

**Comment by AmirKarimi** [comment]
@patriknw Please change the akka version to 2.3.11 and run the sample twice.

**Comment by AmirKarimi** [comment]
@patriknw I got your point! You mean it's OK to get ready late?

**Comment by patriknw** [comment]
I see. I think the bug we fixed after 2.3.6 was that we immediately triggered death watch on early connection failures instead of always using the heartbeat based failure detector. That is why it is so quick in 2.3.6 (but it is also not correct in all situations).

In this case the sharding coordinator thinks that the shard is located at old actor system instance with the 0 (random port) and therefore tries to route the messages there. It will do so until death watch is triggered by the failure detector.

You can see that it works better if you change to port 2553 instead of 0.

There is no guarantee in cluster sharding that messages will not be lost, so you have to use some kind of at-least-once mechanism if you can't allow for message loss.

I understand that this can be considered inconvenient as this startup scenario is rather common. I'm not sure we can find a way to improve this, but I will keep this issue open and think more about it.

**Comment by patriknw** [comment]
Related to #15646

**Comment by AmirKarimi** [comment]
@patriknw Thanks for explanation.

Another interesting situation is that, when you remove leveldb folders (with default persistence configuration) cluster gets ready fast again.

There are more information [here](https://groups.google.com/forum/#!searchin/akka-user/cluster$20ready/akka-user/axqoHHnqC1Q/uLaUTsjYlXYJ)

**Comment by patriknw** [comment]
yes, that is expected, because then it doesn't know about the old port 0 system

**Comment by patriknw** [comment]
This should have been improved by PR https://github.com/akka/akka/pull/18324.
@AmirKarimi please try with 2.4.0-RC2
