### ISSUE TITLE
requirement failed: Shard [...] not allocated

### ISSUE THREAD

**Issue by 2m** [akka/akka#17955]
ShardCoordinator failed to recover after a restart. Workaround was to delete persisted corrdinator events. This was on Akka 2.3.11.

```
ERROR (06/23) 17:14:20 [akka.actor.OneForOneStrategy]: requirement failed: Shard [85d8376d-8bbc-474b-81f6-80ee6741c8a3] not allocated: State(Map(1b3cae47-f105-4f6d-aa08-2a23febd88eb -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], d5f10f4d-7500-4c48-8015-46c552fc02b0 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 16b5ddb2-4a8b-49a8-bb24-2ec49d9e35a8 -> Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694], 11a75447-c2ee-4410-ab50-6ee5bfdd7052 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 21c8a040-dd5a-4a4a-9cbf-b5a8e84f4a95 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 6e7eb445-73c5-4494-b71f-e1d1839345d7 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 232501ce-91ce-4941-860d-96b827b2cccc -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], d2b5a973-d167-410a-b737-dc78aed6d3fe -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 703afc55-6499-4d54-abb5-f0bf02ef879d -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 9ea37a6f-eb03-4587-bec6-b741f699709a -> Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694], e6ad4a16-faba-4776-b576-9062b8b3c2f1 -> Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694], cbd292bd-4966-4dc6-8372-d9dcab3464f0 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 2518df75-3e1f-4ad3-acf8-51908e3ea759 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 85887706-cf47-4da7-ad1c-aefa2883dc6a -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 48540e7d-025c-49a8-8b79-b0cbd457d19c -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 11d9a0a0-cd64-4360-bf90-437546e1f61a -> Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694]),Map(Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623] -> Vector(11a75447-c2ee-4410-ab50-6ee5bfdd7052, 6e7eb445-73c5-4494-b71f-e1d1839345d7, d2b5a973-d167-410a-b737-dc78aed6d3fe, 703afc55-6499-4d54-abb5-f0bf02ef879d, cbd292bd-4966-4dc6-8372-d9dcab3464f0, 2518df75-3e1f-4ad3-acf8-51908e3ea759, 85887706-cf47-4da7-ad1c-aefa2883dc6a, 48540e7d-025c-49a8-8b79-b0cbd457d19c, 1b3cae47-f105-4f6d-aa08-2a23febd88eb, 232501ce-91ce-4941-860d-96b827b2cccc, d5f10f4d-7500-4c48-8015-46c552fc02b0, 21c8a040-dd5a-4a4a-9cbf-b5a8e84f4a95), Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694] -> Vector(16b5ddb2-4a8b-49a8-bb24-2ec49d9e35a8, 9ea37a6f-eb03-4587-bec6-b741f699709a, 11d9a0a0-cd64-4360-bf90-437546e1f61a, e6ad4a16-faba-4776-b576-9062b8b3c2f1)),Set())
java.lang.IllegalArgumentException: requirement failed: Shard [85d8376d-8bbc-474b-81f6-80ee6741c8a3] not allocated: State(Map(1b3cae47-f105-4f6d-aa08-2a23febd88eb -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], d5f10f4d-7500-4c48-8015-46c552fc02b0 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 16b5ddb2-4a8b-49a8-bb24-2ec49d9e35a8 -> Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694], 11a75447-c2ee-4410-ab50-6ee5bfdd7052 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 21c8a040-dd5a-4a4a-9cbf-b5a8e84f4a95 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 6e7eb445-73c5-4494-b71f-e1d1839345d7 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 232501ce-91ce-4941-860d-96b827b2cccc -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], d2b5a973-d167-410a-b737-dc78aed6d3fe -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 703afc55-6499-4d54-abb5-f0bf02ef879d -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 9ea37a6f-eb03-4587-bec6-b741f699709a -> Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694], e6ad4a16-faba-4776-b576-9062b8b3c2f1 -> Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694], cbd292bd-4966-4dc6-8372-d9dcab3464f0 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 2518df75-3e1f-4ad3-acf8-51908e3ea759 -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 85887706-cf47-4da7-ad1c-aefa2883dc6a -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 48540e7d-025c-49a8-8b79-b0cbd457d19c -> Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623], 11d9a0a0-cd64-4360-bf90-437546e1f61a -> Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694]),Map(Actor[akka://ServerSystem/user/sharding/Keymaster#1359473623] -> Vector(11a75447-c2ee-4410-ab50-6ee5bfdd7052, 6e7eb445-73c5-4494-b71f-e1d1839345d7, d2b5a973-d167-410a-b737-dc78aed6d3fe, 703afc55-6499-4d54-abb5-f0bf02ef879d, cbd292bd-4966-4dc6-8372-d9dcab3464f0, 2518df75-3e1f-4ad3-acf8-51908e3ea759, 85887706-cf47-4da7-ad1c-aefa2883dc6a, 48540e7d-025c-49a8-8b79-b0cbd457d19c, 1b3cae47-f105-4f6d-aa08-2a23febd88eb, 232501ce-91ce-4941-860d-96b827b2cccc, d5f10f4d-7500-4c48-8015-46c552fc02b0, 21c8a040-dd5a-4a4a-9cbf-b5a8e84f4a95), Actor[akka.tcp://ServerSystem@10.5.0.30:2553/user/sharding/Keymaster#-334570694] -> Vector(16b5ddb2-4a8b-49a8-bb24-2ec49d9e35a8, 9ea37a6f-eb03-4587-bec6-b741f699709a, 11d9a0a0-cd64-4360-bf90-437546e1f61a, e6ad4a16-faba-4776-b576-9062b8b3c2f1)),Set())
        at scala.Predef$.require(Predef.scala:233)
        at akka.contrib.pattern.ShardCoordinator$Internal$State.updated(ClusterSharding.scala:1124)
        at akka.contrib.pattern.ShardCoordinator$$anonfun$receiveRecover$1.applyOrElse(ClusterSharding.scala:1244)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at akka.persistence.Eventsourced$$anonfun$akka$persistence$Eventsourced$$recoveryBehavior$1.applyOrElse(Eventsourced.scala:168)
        at akka.persistence.Recovery$class.runReceive(Recovery.scala:48)
        at akka.contrib.pattern.ShardCoordinator.runReceive(ClusterSharding.scala:1195)
        at akka.persistence.Recovery$State$$anonfun$processPersistent$1.apply(Recovery.scala:33)
        at akka.persistence.Recovery$State$$anonfun$processPersistent$1.apply(Recovery.scala:33)
        at akka.persistence.Recovery$class.withCurrentPersistent(Recovery.scala:185)
        at akka.contrib.pattern.ShardCoordinator.withCurrentPersistent(ClusterSharding.scala:1195)
        at akka.persistence.Recovery$State$class.processPersistent(Recovery.scala:33)
        at akka.persistence.Recovery$$anon$1.processPersistent(Recovery.scala:104)
        at akka.persistence.Recovery$$anon$1.aroundReceive(Recovery.scala:110)
        at akka.persistence.Recovery$class.aroundReceive(Recovery.scala:265)
        at akka.contrib.pattern.ShardCoordinator.akka$persistence$Eventsourced$$super$aroundReceive(ClusterSharding.scala:1195)
        at akka.persistence.Eventsourced$$anon$1.aroundReceive(Eventsourced.scala:35)
        at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:369)
        at akka.contrib.pattern.ShardCoordinator.aroundReceive(ClusterSharding.scala:1195)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)


```

**Comment by elyrank** [comment]
We had the same issue. happened when we had a split brain in our cluster.
the only way to recover is deleting the shard coordinator data

**Comment by yousef-fadila** [comment]
We had the same issue when a network partitioning happened and then the two clusters write simultaneously to the same persistent document. 

Tracking down the issue shows that the two clusters are writing journals with the same sequence numbers. so if the journal that contains region registration was override from the other cluster data using existing sequence number, the sharedhomeAllocated processing will had requirement failed exception because of the missing journal that was supposed to be replayed before it 

as quick workaround, changing the implementation of the persistent plugin to support multiple journals using the same sequence and reply all of them solved the issue, this workaround passes the requirement failed exception but in case its a live singleton-actors relocation(not cluster shutdown) and the two clusters save the allocation of the same region, the recovered coordinator will use the later allocation data and therefore if there region were already active in another node it will keep up and will end with two live actors with the same ID (both will be accessible, one from nodes who have cached its old location and the one through node don't have the old location and get it from coordinator) - in our business logic this was not a big deal.

Suggested solution in case the network partitioning is considered as temporary state could be:
In case of missing requirement journal, save shared-region aside and continue the recovery without the requirement failed fatal exception, after finishing recovery, re-allocate the regions failed to be recovered and signal this change to other node (so they will update/clear the cached location of the shared regions and current active actors will move to the new location)

it seems in case on coordinator re-location we always need to signal other node to clear their cache(as in case of temporary network partitioning and two cluster write to the same documents, the coordinator persistent data could be corrupted but still pass the requirement check, e.g the two journal ( the allocation and registration) related to specific region were overridden and therefore no requirement failed exception will be fired. the recovered coordinator will not have allocation data on that region while its an active one and has active actors somewhere...( the same issue described above in the workaround we implement)

If we need to support lasting network partitioning scenario in case both clusters write the same documents, we need to add more data to the journals/snapshot metadata to identify this in live and to ignore other cluster journals. 
otherwise, it seems the only possible solution to support lasting network partitioning and two cluster living side by side is not to persist the coordinators data in the persistence level therefore in case they have been relocated all other nodes should clear their and active region should be relocated or the coordinator. 

Another solution to support lasting network partitioning but yet not to reallocate all regions in case of coordinator actors relocation is to recover the coordinator data from the active node cache it sees and not from the persistent level. the coordinator data is not relevant in case all nodes are shutdown so it won't be a problem to start with empty state in the next cluster launch...

**Comment by patriknw** [comment]
#17837 (released in 2.4-M3) should help if such things happen, but splitting the cluster into two clusters can easily happen with auto-down, and therefore auto-down should be avoided

**Comment by yousef-fadila** [comment]
how could the #17837 solve this issue if the recovery still expect allocation message before the shard assigning ?  in case we ignore messages related to shard that no allocation message of it replayed before (because of data corrupted ) then we also need to invalidate the cache each cluster node has about the place if the shard region..

otherwise nodes that don't have cache will receive another allocation from the coordinator and those who have cache will still forward to old actor location... we will end with 2 shared actors with the same name in different nodes!

**Comment by patriknw** [comment]
You are right that it will not solve all cases, especially not when there are two separate have been created and they are still running. That should be avoided by all means. #17837 tries to repair if an accident has happened. 

 I'll reopen this and we can investigate your suggestions more after 2.4.0.

**Comment by patriknw** [comment]
I can't see that we can do much about this. Using a cluster downing strategy is crucial. Auto-down does not handle network partitions (or long GC or system overload). To use cluster sharding and akka persistence in a cluster one must use something like [Split Brain Resolver](http://doc.akka.io/docs/akka/rp-16s01p03/scala/split-brain-resolver.html)
