### ISSUE TITLE
FSM mixes-in ActorLogging, maybe could use _log instead

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17994]
Since FSM is defined as `trait FSM[S, D] extends Actor with Listeners with ActorLogging {`
we use up the `log` identifier in FSM actors.

If someone does not want to use `ActorLogging` but something else, and the name `log` makes sense for them, they're forced to rename.

Removing the trait would break binary compat, so it's something for then, but it makes sense in general (we could use `_log` for example, and users who want actor logging can mix it in anyway).

**Comment by kelebra** [comment]
Hi, @ktoso. I would be more than glad to participate if it is possible and nobody is working on that as of now. 
One question in order to clarify: you want to remove binary compatibility by removing `ActorLogging` or make `_log` accessible (by making it `protected` or package visible) from `ActorLogging` trait?

I am new to akka internals, so sorry if question is sort of newbish :)

**Comment by ktoso** [comment]
Hi, thanks for offering to help out here :-)
This one is tricky because it will break binary compatibility which we don't want to do on the current master branch... (we have not forked off so far for enable breaking changes – Akka 2.5 will be bin-compat with Akka 2.4 (which is bin compat with Akka 2.3)).

The issue here is about removing the ActorLogging trait from it, and instead use a private `_log` field.
This will break existing clients which use FSM and the logging field, so we can only do so in Akka 3.x...

Sorry that it's a task best not picked up now.

**Comment by ktoso** [comment]
Only FYI for 2.6 though I guess we can't make it in there and it will have to wait till 3.0? @patriknw

**Comment by patriknw** [comment]
Seems like a rather unimportant request, so closing for now.
