### ISSUE TITLE
Don't use deprecated scala.concurrent.util.Unsafe -- to be removed in 2.12.0

### ISSUE THREAD

**Issue by adriaanm** [akka/akka#18007]
You could [inline it](https://github.com/scala/scala/pull/4629/files#diff-39840923e78c5b9ecc80ab7b8daf2e57) into Akka's `Unsafe` wrapper, I suppose. We have to make the core Scala library Java 9 friendly in 2.12, since we move slowly. The first step was taken in https://github.com/scala/scala/pull/4629, which removes our fork of forkjoin (leaving a compatibility stub in place for the equivalent classes in `java.util.concurrent._ `).

**Comment by ktoso** [comment]
Inlining seems like a perfectly good solution to allow you guys to remove the "scala Unsafe" - done that https://github.com/akka/akka/issues/18009

The next release of Akka which does not use `scala.concurrent.util.Unsafe` would be `2.4-M3` then, which is roughly a few weeks away (less than more) - timing sounds good enough?

Seems like that's enough, since `2.3.x` will not be released against Scala `2.12` anyway, so no need to change there.

**Comment by ktoso** [comment]
The bigger problem for us will be the actual `sun.misc.Unsafe`. 
There's ongoing discussions on a number of mailing lists, we'll see what the way forward will be soon (Also, useful link to analysis of Usafe removal impact: http://bit.ly/sunmiscunsafe )

**Comment by adriaanm** [comment]
Awesome! Thanks for the lightning fast response :)
