### ISSUE TITLE
Detecting unreachable members too slow

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#18014]
I have a little multi-jvm-spec which shuts down one member (node2). node1 detects that (AssociationError), then 5 seconds later it detects it again (Association with remote system … , has failed), then after another 6 seconds it detects it again and only then, i.e. after 11 seconds, the member is marked unraechable. Is that expected? Why does that take so long, so many hoops?

Find the test here: https://github.com/hseeberger/unreachable

**Comment by ktoso** [comment]
Thanks for reporting Heiko! We'll have a look at it as soon as we can, definitely something to check before 2.4

**Comment by patriknw** [comment]
@hseeberger That is a good observation. The reason is that you shutdown node-2 before they have exchanged any heartbeats. Then the `akka.cluster.failure-detector.expected-response-after` adds to the failure detection time. The default is 5 seconds, which is unreasonably long. In 2.4 we are decreasing the default value of that setting. See https://github.com/akka/akka/pull/18263

You can use `akka.cluster.failure-detector.expected-response-after = 1 s` in your test.

**Comment by hseeberger** [comment]
Thanks, @patriknw!

I have found the following settings to give me an optimum for fastest unreachable/removed detection:

```
akka.cluster.auto-down-unreachable-after                 = 100ms
akka.cluster.failure-detector.acceptable-heartbeat-pause = 250ms
akka.cluster.failure-detector.expected-response-after    = 100ms
akka.cluster.failure-detector.hearbeat-interval          = 250ms
akka.cluster.failure-detector.threshold                  = 2.0
```

**Comment by patriknw** [comment]
Sure, but then you will also have a lot of false positives (e.g. due to GC).

You can set `auto-down-unreachable-after = 0s`
You should also set `unreachable-nodes-reaper-interval = 250ms`

**Comment by hseeberger** [comment]
Thanks!

**Comment by hepin1989** [comment]
```
akka.cluster.failure-detector.acceptable-heartbeat-pause = 250ms
```
this value should be more large,otherwize you cluster will split.

**Comment by hseeberger** [comment]
I should have mentioned that these settings are for demo purposes, all nodes run on one machine, and I want to demo failover etc. as quickly as possible.

**Comment by patriknw** [comment]
@hseeberger yeah, if it wasn't you I would have strongly recommended against any such settings ;-)

and @hepin1989, I know you know this but I have to correct you anyway because it's a common misuse of the concepts in mailinglist questions and such: the cluster is not split by detecting unreachable, it is split by auto-down-unreachable-after ;-)

**Comment by hseeberger** [comment]
;-)
