### ISSUE TITLE
Exceptions thrown in `FlowOps`.`log` do not abide provided Supervision strategy.

### ISSUE THREAD

**Issue by timcharper** [akka/akka#18037]
```scala
implicit val ec = ExecutionContext.global
case object LeException extends Exception("le fail")
implicit val materializer = ActorMaterializer(ActorMaterializerSettings(actorSystem).withSupervisionStrategy(Supervision.resumingDecider : Supervision.Decider))
val result = scala.concurrent.Await.result({
  Source(Range(1,20)).log("hi", { n => throw LeException }).runWith(Sink.fold(0)(_ + _))
}, 1 second)
result should be (0)
```

I'd expect the stream to resume, but instead, the stream is falling. I can see why this behavior would make sense, since the log is not really manipulating the stream. I'm wondering if that should be highlighted in the docs, just to warn people. I can send a doc pull request if so.

**Comment by timcharper** [comment]
I'd be happy to contribute a fix, too, if this is deemed surprising behavior. I'm not sure what the correct behavior should be.

**Comment by 2m** [comment]
I think this falls in the category of stream components that do not abide to supervision configuration yet.   I think [a note here](https://github.com/akka/akka/blob/release-2.3-dev/akka-docs-dev/rst/scala/stream-error.rst#error-handling) (on java and scala side) can be expanded to include `log` as well. This ticket should still be kept open, until the underlying issue is fixed.

**Comment by ktoso** [comment]
Agree with your rationale here @timcharper. Another way instead of supervision here would be to treat the extract in a special way – if it fails we say "hey, EXTRACTION FAILED" or something like that. I don't think we should "instead let's log the element", since maybe the intent of `extract` was to not log a password etc, so we could accidentally log something that was never meant to be logged.

**Comment by ktoso** [comment]
Marking as bug and we'll fix it soon. Default strategy will be `resume`.
