### ISSUE TITLE
WebSocket low level API

### ISSUE THREAD

**Issue by jroper** [akka/akka#18126]
This issue is to discuss how the WebSocket low level API should be exposed to end users.

Currently, the ability to handle WebSockets at the frame level is not possible in Akka HTTP.  There is a low level API, `UpgradeToWebsocketLowLevel`, which is private to Akka HTTP, which can be used to do it.  A comment in this indicates this won't always be private - `INTERNAL API (for now)`.

As Play's current API stands, the high level API that Akka HTTP provides is satisfactory.  However we've been receiving an increasing number of feature requests in Play to expose a lower level API.  These include:

* Sending a close frame with a custom code and/or reason.
* Implementing extensions such as per message deflate, which requires setting the RSV1 bit of each data frame that is compressed to true.

So currently, I'm not sure what the motivations are behind not making the low level API public yet, but this issue can stand as a place to discuss those as well as the requirements Play has.

**Comment by jroper** [comment]
One problem with the current low level implementation - if the application wants to handle the close event from the client, and, for example, know the reason it was closed, then it will have to check the frame opcode itself, then parse the data out of the frame, there's no simple way for it to do this.  Perhaps close should be moved to the higher level API.  Similarly, a server might want to send ping frames, handling the returned pong frames would require manual decoding.

**Comment by jrudolph** [comment]
Wrt surfacing the close code. I created a new ticket to surface erroneous close code in the exceptions that will be dispatched as `onError` on the message stream. See https://github.com/akka/akka/issues/18129.

There's already a ticket for supporting Websocket compression: #17725

Wrt the low-level API: we chose not to increase the API surface more than necessary in this first version. I still tried to make sure that the low-level API is good enough to support arbitrary later extensions on the frame level.

A few things currently prevent third parties to create their own extensions: 
 * the low-level API is `private[http]`
 * in the `private[http]` low-level API is proper extension negotiation support in the WS handshake is currently missing: #18130
 * `impl.engine.ws.Websocket.handleMessages` implements the high-level API on top of frames. It doesn't have any predefined extension points currently so that third-party extensions would have to copy the complete method to inject custom handling somewhere in the flow (e.g. between masking and message collection). By reorganizing the code we could either allow inserting custom flows at predefined extension points or otherwise we could allow (`private[http]`) access to all the required parts so that only the final pipeline would have to be copied and adapted by the third party.

**Comment by jroper** [comment]
Another use case is having the server periodically send ping frames to detect dropped connections, we've had a few requests for this on Play.

**Comment by jroper** [comment]
Also, one problem I see with the high level API is that it's not very nice to use - the message will generally not be strict as soon as the size of the payload exceeds the MTU.  Many use cases just want to work with discreet messages, and so will need to insert an intermediate flow in there that buffers (up to a configured limit of course) each message.  This will have obvious performance impacts, since materialising the source will create an actor - creating an actor per websocket frame greater than 1.5kb is very likely going to be a big performance problem.

It's likely to impact streaming even more - instantiating actors mid stream say in a live video conference, which would be very sensitive to the latency caused by doing this, is not going to be good.

I think a better API would be to have the high level API only work with strict messages (buffering up to a limit and closing the socket with a "Too big" close code if the limit is ever exceeded), and provide a lower level API for working with streams if you need that.  We currently provide that high level API in Play, and my first implementation of the Play websocket support on Akka HTTP is using the low level API (by putting it in a package under `akka.http.play` to work around the `private[http]` limitation) to avoid materialising sources mid stream.

**Comment by jrudolph** [comment]
@jroper adding automatic ping support is tracked as #17968.

Regarding the API: We chose to provide a stream based high-level API for consistency with the rest of the HTTP APIs that work the same way.

Nevertheless, I agree that we should provide a simpler API that works only on strict message or even remove the wrapping completely and provide streams of String/ByteStrings. You can provide such an API on top of the current one but it is non-trivial to implement.

As you say this comes with a performance penalty but this is expected because akka-stream is not yet optimized for performance. I wonder if it wouldn't be premature optimization to give up the stream based Websocket API at this point and put more work into optimizing high-level code before any attempts have been made to make akka stream itself faster.

**Comment by jrudolph** [comment]
In https://github.com/akka/akka/blob/e82e95f3cfa8faa8afed06525683a742fadd8437/akka-http-core/src/main/scala/akka/http/impl/engine/ws/Websocket.scala I restructured the stack that provides the low-level to high-level implementation. @jroper hopefully, this would allow you to reuse more of the internals. Most notably, `FrameHandler` already outputs `MessageParts` which is kind of a middle-level API that doesn't use nested streams.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
