### ISSUE TITLE
Errors originating in FlexiRoute's RouteLogic implementations escape supervision and lead to stream failure

### ISSUE THREAD

**Issue by manuelbernhardt** [akka/akka#18140]
I attempted to test supervision by triggering an error inside of a FlexiRoute's `RouteLogic#initialState` implementation. I would have expected supervision to kick in and allow me to Resume for known exceptions. However the supervision strategy does not seem to be called in this case.

Now I know that in practice I should be very careful when building my own elements, but _error humanum est_ and it would be nice if supervision could guard, to some degree, against unforeseen cases in FlexiRoute (and possibly other junctions of the kind).

**Comment by drewhk** [comment]
This error cannot be handled by supervision since the call to initialState() is during materialization, i.e. before the stream has been assembled. In that phase there might not be even downstreams to send error events to. This is the analogue to a Props(=> Actor) where the factory method throws. There is no supervision involved (as in no possibility to restart), since the actor could not been created in the first place (i.e. restart is not possible).
