### ISSUE TITLE
Persistence: If misconfigured, fail loudly

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18153]
Recently a user was confused about a PersistentActor "hanging" (it was "hanging" as journal was misconfigured AFAICS), "It looks like my actor is asking itself and then hanging, but I don't know what to do.".

We should check that `PersistentActor` fails loudly if started without configured journal.
We already do so nicely for when no snapshot store is configured and it tries to store a snapshot.

// note: this may already be done in 2.4... I vaguely remember we were working on something along the lines.

**Comment by michaelom** [comment]
related: https://github.com/akka/akka/issues/16090

**Comment by ktoso** [comment]
Indeed, thanks :)

**Comment by patriknw** [comment]
@ktoso I don't know what is intended with this issue. Is it about an AsyncWriteJournal actor that throws something from constructor and is therefore stopped due to akka.actor.ActorInitializationException?

Then I guess subsequent PersistentActor interactions with the journal will never "return". The journal is not supposed to be stopped. Not sure if we really want to protect against that? The only way I can think of is to use watch from each PersistentActor (or `isTerminated`).

**Comment by ktoso** [comment]
I think the problem some users had on gitter was that they did not configure any journal, and "nothing happened" when they sent messages to the PA. I may have misunderstood the issue they described, but that's how I understood it – in this issue I wanted to check this scenario and make sure we blow up with "hey, no journal configured" (though I vaguely remember we might be doing this already...).

**Comment by ktoso** [comment]
So maybe it's just sanity checking that the above is what happens when no journal configured.

**Comment by patriknw** [comment]
alright, it logs this when the journal is used the first time
`ActorInitializationException
Caused by: java.lang.IllegalArgumentException: requirement failed: default journal plugin is not configured, see 'reference.conf'`

That is triggered by this code in Eventsourced.scala

      override protected[akka] def aroundPreStart(): Unit = {
        // Fail fast on missing plugins.
        val j = journal; val s = snapshotStore

Same exception happen when subsequent PersistentActors that are started, so I would say it is very loud.

Mission complete!

**Comment by ktoso** [comment]
Great, thanks for checking. :-)
