### ISSUE TITLE
[akka-http] Cancelling response entity stream with Sink.cancelled doesn't work

### ISSUE THREAD

**Issue by kodemaniak** [akka/akka#18203]
I am performing a series of HTTP requests and am only interested in the status code of the response. Cancelling the response entity data stream with Sink.cancelled doesnt seem to work, as the connections are exhausted after `max-connections` requests. Example:

```scala
  val future2 = Source(1 to 15)
    .map(i => RequestBuilding.Get("http://akka.io") -> i)
    .via(Http(system).superPool[Int]())
    .map(response => response._1.get.entity.dataBytes.runWith(Sink.cancelled))
    .runForeach(println)
```

Explicitly consuming the stream, however, does work:

```scala
  val future1 = Source(1 to 15)
    .map(i => RequestBuilding.Get("http://akka.io") -> i)
    .via(Http(system).superPool[Int]())
    .map(response => response._1.get.entity.toStrict(1.second).map(_ => response))
    .mapAsync(5)(identity)
    .runForeach(println)
```

**Comment by jypma** [comment]
I'm seeing something similar when prematurely finishing an HTTP response from a downstream `PushStage`, it seems to stop further processing on that connection.

Might this be related to https://github.com/akka/akka/issues/18189 ?

**Comment by jrudolph** [comment]
@kodemaniak what would you expect the behavior to be when the entity data stream is cancelled? Akka-http could either 
 - close / abort the connection
 - automatically consume and ignore the entity stream and then put the connection back into the pool

Consuming the stream means pulling it completely through the network which is something you may want to avoid.

That said, I agree that the connection slot should never be blocked.

Btw. if you are only interested in the status code, there's the HTTP's `HEAD` method which is meant to be the solution for exactly that case (as long as we are talking about the original requests being GET requests).

**Comment by kodemaniak** [comment]
@jrudolph The concrete use case I have is a batch importer that reads a bunch of files, parses them and updates data via REST. However, there might be data present for which there is no corresponding resource available. Since I don't want to check existence of the resource before every request (and quite a few of those are happening), I just try a PUT and remember if it was successful or not. So HEAD doesn't help me here. Now, in the success case the response body is empty (always), but in the error case the REST API returns some JSON with details. However, in my batch process I am not interested in that JSON. Therefore, I basically need a way to say give me the status and ignore the entity.

In the akka gitter one proposal was to use Sink.cancelled, but that does nothing as explained above and the connection slot stays occupied resulting in a blocked stream. So currently I am calling toStrict() and make a mapAsync afterwards. That consumes the entity, obviously.

In general, I would expect Sink.cancelled to at least free the connection. With respect to your question whether it should abort the connection or just silently consume the entity, I think that probably it would be nice when we could save sending the response over TCP at all, but I have no idea what that means in terms of HTTP (maybe an error on the server side?). Silently consuming the entity on the other hand would also be unexpected when I cancel something. So I would argue that it should close/abort the connection, without knowing the implications for things like keep-alive or pipelining.

**Comment by jypma** [comment]
How about making it customizable, and adding the decision to `ConnectionPoolSettings`, maybe even as some function of `HttpRequest -> EarlyFinishDecision`, the latter being `CLOSE_TCP` or `READ_AND_IGNORE_BODY`? Of course, the default could be either.

I think customization is in order, because the typical reason to re-use an HTTP TCP connection is to save the time required for a new SYN/ACK phase, and being able to do pipelining. I reckon that needs to be weighed, performance-wise, against reading a full response body you don't need. 

Wouldn't it, by default, make sense to drop the connection when having received a `Content-Length` header that indicates there's more than 1 TCP packet (e.g. >1500 bytes) coming, and just read and ignore the body otherwise?

**Comment by jrudolph** [comment]
@kodemaniak thanks for the explanation. I asked because I don't think it is currently defined in the akka-http API what the meaning is of cancelling an entity stream.

For me it would also make sense to give cancelling the entity stream a different meaning from slurping it to give the user the choice of what to do.

In any case, there's no way of cancelling an in-flight entity body on the HTTP level. So, it means that a persistent connection must be aborted. However, aborting and reconnecting may be far slower than ignoring a small and fast-received entity body.

I'm just seeing @jypma's comment which goes in the same direction.

**Comment by kodemaniak** [comment]
After thinking about it, I am more and more convinced that Sink.cancelled should close the stream, and that consuming and then ignoring the stream should probably be a concious decision by the developer using the provided means (e.g. toStrict()). The only thing I don't like is that cancelling the body for me does not imply that the whole connection is closed. I do understand that there is no other way in HTTP, but I think that could result in confusion. I guess that needs to be documented.

**Comment by jypma** [comment]
@kodemaniak In a typical stream, the different `Flow` steps are not aware of each other. For example, the http source might plug into an XML parsing flow, that plugs into some content scanner. The content scanner could finish when it has found a specific XML tag it's looking for. It would do that, regardless where the source comes from (http, file, or otherwise).

I do feel that using the received `Content-Length` header in the decision would give the highest performance, but I'm OK with just trashing the connection on an early upstream finish, if that's simpler to build.

**Comment by kodemaniak** [comment]
@jypma I think the "problem" here is that we are talking about a source that is actually divided into substreams (not technically, I don't know how it's done internally, but at least semantically). So when we have the entity stream available, it's actually not a stream of it's own, but it's linked to the connection. When you have an XML parser stage that takes the entity stream and parses XML tokens out of it, the stream of tokens is still connected to the HTTP connection. I think this leads to the problems we are discussing here. When you cancel your token stream because you are not interested in the rest of the XML document, you are not "talking about" the connection at all, because you don't know that it exists. So, you are right, it's not as simple as I wrote above.

On the other hand I am not a fan of too much intelligence in such a library. So, trying to figure out when the connection should be closed or not doesn't seem attractive to me. Maybe having the possibility to configure it from the outside as you proposed initially is a reasonable solution. At least it gives the developer the chance to decide how it should be handled.

**Comment by jrudolph** [comment]
It seems these things cannot be solved just technically. I.e. the type `Source[X]` is usually not enough to completely describe the behavior of the source (like additional semantics of cancellation or reusability). This means that you always need to document things like that at API boundaries.

For your XML example, it means that you have two boundaries:
  * one between akka-http and your request handler, where we have extra semantics for the data stream source in the entity of the request
  * one between your request handler and the XML processing stage, where extra semantics may be undesirable

If desired semantics don't match when you pass a source over an API boundary, the layer that passes a source around needs to adapt the source to the expected semantics. In the example, it means that your request handler needs to decide if cancellation from the XML processing should be propagated to the HTTP layer and insert appropriate adapter stages to fix the behavior (e.g. to convert downstream cancellation into ignoring the upstream data without cancelling it, etc.).

So, I somewhat agree with @kodemaniak that the semantics of akka-http's entity sources should be as simple as possible. What we could provide on top of that would be predefined adapter flows that cover things like what @jypma suggested like a simple adaptor that conditionally or not converts downstream cancellation to ignoring upstream.

WDYT?

**Comment by kodemaniak** [comment]
@jrudolph Sounds good to me.

**Comment by jypma** [comment]
+1 from me as well on just breaking the connection. We already have a "read the whole response" adapter around our actual flow anyways, to work around the current bug, so that would keep working.

However, "converting downstream cancellation into ignoring the upstream data without cancelling it" apparently can't be a simple stage, as https://github.com/akka/akka/issues/18189 says that's impossible by design. What would be the best way to represent that translation step? We currently do wrap the worker flow, by doing a broadcast / merge into the actual worker and a custom `PushStage` that only does `ctx.pull()`. That seems a bit elaborate though.

**Comment by jrudolph** [comment]
@jypma yes, #18189 is a bummer for now but I consider it a bug that you cannot write such a stage right now. It shouldn't prevent us to provide such a stage in the future in some way or another.

/cc @sirthias

**Comment by drewhk** [comment]
#18189 might be circumvented by providing an appropriate built-in stage, but exposing it to user-available mechanism is currently looking too risky. It might be possible to solve it in a nice way, but I am currently not sure how.

**Comment by RichardBradley** [comment]
>  I don't think it is currently defined in the akka-http API what the meaning is of cancelling an entity stream.

The docs seem clear on this:

http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/low-level-server-side-api.html#Closing_a_connection

> Closing a connection
> The HTTP connection will be closed when the handling Flow cancels its upstream subscription or the peer closes the connection. An often times more convenient alternative is to explicitly add a Connection: close header to an HttpResponse. This response will then be the last one on the connection and the server will actively close the connection when it has been sent out.

I see that #18010 has already been raised to fix this bug.

**Comment by RichardBradley** [comment]
I have uploaded a demo of this bug to https://gist.github.com/RichardBradley/7711589bdf353e07edab

Because the Akka server doesn't close the upload stream when the application cancels the HttpRequest Flow, there is no way for a Akka HTTP server to reject a very large upload.

You can work around this bug a bit by adding `Connection: close` to a HTTP 413 error HttpResponse in the server. If the client reads that response (as the Akka HTTP client does even if the upload is still progressing), then the Akka HTTP framework will finally close the upload, aborting the very large unwanted upload.

However, most HTTP clients (including Java's `HttpURLConnection`) will not read a response while they think they are still making a request. The above demo shows that a Java HTTP client will continue to upload data to an Akka HTTP server forever, even if the Akka HTTP app has closed the stream, e.g. using the "ByteLimiter" recipe from http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-cookbook.html#Limit_the_number_of_bytes_passing_through_a_stream_of_ByteStrings

**Comment by drewhk** [comment]
On Wed, Sep 9, 2015 at 8:20 PM, Richard Bradley <notifications@github.com>
wrote:

> I don't think it is currently defined in the akka-http API what the
> meaning is of cancelling an entity stream.
>
> The docs seem clear on this:
>
>
> http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/low-level-server-side-api.html#Closing_a_connection
>
> Closing a connection
> The HTTP connection will be closed when the handling Flow cancels its
> upstream subscription or the peer closes the connection.
>
> I think this is not correct in the docs, the Flow must onComplete its
downstream. Cancelling a TCP connection stream only means ignoring incoming
bytes, there is no TCP level event corresponding to stopping reads, you can
only stop writes or abort the whole thing. Unless HTTP has something to
specially handle this, but I am not sure.

-Endre

**Comment by drewhk** [comment]
On Thu, Sep 10, 2015 at 12:02 PM, Richard Bradley <notifications@github.com>
wrote:

> I have uploaded a demo of this bug to
> https://gist.github.com/RichardBradley/7711589bdf353e07edab
>
> Because the Akka server doesn't close the upload stream when the
> application cancels the HttpRequest Flow, there is no way for a Akka HTTP
> server to reject a very large upload.
>
There is no such thing in TCP that correspond to "close the read side", you
can only close the write side. The only two choices our TCP implementation
can have regarding of cancel() is to:
 - keep reading bytes from the wire, but drop them
 - backpressure forever

Unfortunately, if we choose option 2, then we won't get close events from
NIO since they are signalled at reads. Also, a blocking client might simply
deadlock if option 2 is taken (write-first-then-check-read will never get
to the read part since it will block forever).

The issue is here is that the write side of the TCP connection should be
closed because that will be treated as a TCP FIN or RST depending on the
actual state (probably a RST since client still uploads).

> You can work around this bug a bit by adding Connection: close to a HTTP
> 413 error HttpResponse in the server. If the client reads that response (as
> the Akka HTTP client does even if the upload is still progressing), then
> the Akka HTTP framework will finally close the upload, aborting the very
> large unwanted upload.
>
This should be the correct approach.

However, most HTTP clients (including Java's HttpURLConnection) will not
> read a response while they think they are still making a request. The above
> demo shows that a Java HTTP client will continue to upload data to an Akka
> HTTP server forever, even if the Akka HTTP app has closed the stream, e.g.
> using the "ByteLimiter" recipe from
> http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-cookbook.html#Limit_the_number_of_bytes_passing_through_a_stream_of_ByteStrings
>
Now this is interesting though, this should work. I will take a look at
this.

-Endre

**Comment by RichardBradley** [comment]
> there is no TCP level event corresponding to stopping reads, you can
only stop writes or abort the whole thing

Is that right? So there is no way for a HTTP server to both abort the upload and also return a response?

> > The above demo shows that a Java HTTP client will continue to upload data to an Akka
 HTTP server forever
> Now this is interesting though, this should work. I will take a look at

Sorry, I made a mistake when I first posted this. The Java client's upload is aborted by the server if the app uses "connection:close" on its response.

The above demo shows a Akka server trying to abort an over-large upload and return an error 413 response.

The Akka client can read the response, but the Java client cannot. Try "sbt run" on that demo to see this in action.

**Comment by jrudolph** [comment]
> The Akka client can read the response, but the Java client cannot. Try "sbt run" on that demo to see this in action.

This is somewhat well-known. Browsers usually also ignore (or better postpone showing) any response that was received before the request was fully sent.

**Comment by drewhk** [comment]
On Thu, Sep 10, 2015 at 12:38 PM, Richard Bradley <notifications@github.com>
wrote:

> there is no TCP level event corresponding to stopping reads, you can
> only stop writes or abort the whole thing
>
> Is that right? So there is no way for a HTTP server to both abort the
> upload and also return a response?
>
Well, there is only FIN and RST in TCP. The first indicates that the sender
side will stop writes, but the other side might still continue writing
(half-close). This is to ensure no message loss (i.e. just because I
finished with what I wanted to say, you might still want to talk to me)
happens (kind of). The RST is an abort event with no acknowledgement.

I think the only thing that can work in HTTP in this case is to send down a
response and then send an RST packet. This might not guarantee the delivery
of the response though.

I might be wrong of course, there might be a trick that HTTP
implementations use to handle this case, but TCP is not the most flexible
protocol out there :)


> The above demo shows that a Java HTTP client will continue to upload data
> to an Akka
> HTTP server forever
> Now this is interesting though, this should work. I will take a look at
>
> Sorry, I made a mistake when I first posted this. The Java client's upload
> is aborted by the server if the app uses "connection:close" on its response.
>
> The above demo shows a Akka server trying to abort an over-large upload
> and return an error 413 response.
>
> The Akka client can read the response, but the Java client cannot. Try
> "sbt run" on that demo to see this in action.
>
I guess when the connection is borked at the write (upload) side, then the
Java client just treats the connection "dead" and the read (download) side
will not deliver the final messages. I am not sure though, we can look into
it.

-Endre

**Comment by drewhk** [comment]
Btw, the https://github.com/akka/akka/issues/18189 issue is no longer an "issue" as the Octopus (new GraphStage support) has less restrictions than the ordinary Stages. I.e. you can do whatever you want and shoot yourself in the foot in various ways -- but it gives much more flexibility.

**Comment by drewhk** [comment]
And don't forget that this ticket is originally about the *client* and not the server. The server can use the `connection:close` response to terminate uploads, this is about clients terminating downloads via cancel(). It makes total sense to map the HttpResponse's source cancellation to abort, as in HTTP after the response there cannot be writes anyway (with no pipelining at least), i.e. there is no reason to keep the write side open.

**Comment by ktoso** [comment]
Note for us here: We need to document a matrix of what cancelling entity streams actually means (on server / client / ...) and then make some decision if things need changing or not.

For the server case (I know, not this ticket in theory...) I'd opt for aborting the TCP connection when the request entity source gets a cancel, otherwise we can't kill off "dumb clients".

// cc @sirthias @jrudolph

**Comment by drewhk** [comment]
My opinion on this ticket, server or client is to do the following:
 - by default, propagate entity body cancellation to the connection
 - if someone wants the current default behavior, just attach a Sink.ignore and drain the entity into the void himself.

This eliminates the need for any static flag and users can do the right thing independently for each entity if they would like to.

**Comment by ktoso** [comment]
Solved in https://github.com/akka/akka/issues/19528
