### ISSUE TITLE
ActorPath.fromString missing in 2.4 M2 and 2.4 M3

### ISSUE THREAD

**Issue by mikestov** [akka/akka#18242]
(Using Akka with Java 8)
I was upgrading from 2.4 M1 to 2.4 M3 and I noticed an error pop up in our code that ActorPath.fromString is gone. I looked at the API documentation and it appears to have been removed in M2. I read through the 2.3 to 2.4 migration guide and I didn't see anything mentioned about what to use an alternative. Is this intended? If it is, could you provide a suggestion on how to code around it? For now, going back to 2.4 M1. 

Thanks!

**Comment by ktoso** [comment]
Copying my reply from gitter:

seems like an omission in the overloads... would you mind opening a ticket for it?
one answer is "once we compile using Scala 2.12 that should work", another answer is we can add an overload in the RC this friday  please open a ticket and we'll decide

// cc @jvieten

**Comment by patriknw** [comment]
`ActorPath.fromString` was introduced in 2.4-M1 (doesn't exist in 2.3.x) as far as I recall. It was a mistake, it was not completely binary compatible. In 2.4-M2 and later it was replaced by `ActorPaths.fromString`.

No migration guide because we don't write migration guide between milestones, and it is a new feature compared to 2.3.x.
