### ISSUE TITLE
failed: ClusterShardingSpec ddata mode

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18287]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3480/consoleFull

    [JVM-6] - must recover coordinator state after coordinator crash *** FAILED ***
    [JVM-6]   akka://ClusterShardingSpec/user/counterRegion/3/3 did not equal akka.tcp://ClusterShardingSpec@a5.moxie:51499/user/counterRegion/3/3 (ClusterShardingSpec.scala:497)

**Comment by smlin** [comment]
@patriknw I reproduced it. When the nodes are joins the coordinator sometimes receive the info about the new regions faster then the replicator receives `MemberUp` message. So that info simple does not replicated. It could be partially fixed by making a rejection of registration for the regions from the nodes which are not `Up`.  A minimal chance of inconsistency anyway exists.

I did a fix. https://github.com/akka/akka/pull/18293
