### ISSUE TITLE
Implement TLS session renegotiation support for client certification authentication

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18351]
If someone knows a specification for this behavior please comment.

The scheme seems to be like this:
 * start TLS without requiring a client certificate
 * receive HTTP request
 * decide that an HTTP request is needed
 * send a TLS session renegotiation request to the client requiring a client certificate
 * wait for the client to provide the certificate
 * validate the certificate
 * send out the response

On the API level, we could introduce a special response header, that contains a client certificate validation function that when it is encountered in the renderer, first runs the TLS renegotiation, then calls the validation function with the new certificate, and only then sends out the response. In any case, it's tricky to get right because of the messages that need to be send around from the renderer to the parser and the other way round.

Part of #13749.

**Comment by bblfish** [comment]
The above scheme makes sense. It is also good to have a certificate validation function, as that would allow schemes like WebID-TLS to implement more flexible validation than CA based ones. 

Btw. I am not sure what the parser needs to do here. The parser just needs to parse the certificate. 
After that validation gets going. The basic validation is that one tests to see if the Certificate is signed by a known CA. If that fails one might want to search for the CAs public key ( eg: by looking at the Issuer Alternative Name ). If that fails one might want to just verify the ownership of the public key by doing what is described in [WebID TLS](http://webid.info/spec). All of those things combined would reduce the reliance on CAs. 

What may be useful at the API level is to return the Certificate wrapped in some Verification object, which says what types of verifications the Certificate has undergone, because that is what would tell one what one can extract from it, and also how reliable it is.

**Comment by jrudolph** [comment]
It seems this should be quite easy to implement by now if the validation can be configured at bind-time by providing the right SSLContext configuration to actually validate a certificate against a CA. In that case the only thing which needs to be done is issuing a `NegotiateNewSession` to request client authentication before sending the actual response. The SslTlsSupport will keep back the response until the new session (including the client authentication) was established and validated.

However, this only allows client authentication but not per-request authorization i.e. actually inspecting the client principal to figure out whether this generally accepted principal is also allowed to access a specific resource. To enable this we would need to access the new session between receiving the request and sending a response. Is this possible with the current SslTlsSupport implementation? I.e. will it send out a `SessionBytes(newSession, ByteString.empty)` after each successful handshake even if no other data is incoming at this point?

**Comment by jrudolph** [comment]
Indeed the above is an issue. It seems it can be easily fixed by enqueing `SessionBytes(newSession, ByteString.empty)` in `handshakeFinish`.

**Comment by ktoso** [comment]
After tracking the discussion in #19787 I'm left with the impression that it's a fun experiment however not much actual use of it...

What would you say if we closed this ticket and dropped the PR (like @jrudolph suggested a bit even), as we're not quite sure it pulls its own weight. Huge thanks for looking into it and the PR in any case @jrudolph though!

// cc @bblfish

**Comment by ktoso** [comment]
Closing due to not much action going on here. 
Thanks a lot for working on it @jrudolph – perhaps it'll come back one day.
