### ISSUE TITLE
Cluster Singleton "preference list" 

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18372]
This idea is rather unusual, however has been brought up recently.

This would be an extension to Cluster Singleton in which instead of "the oldest", the node on which singletons run would be defined in a "preference list" in configuration which would be used in the same way the current "sort nodes by age, and use the oldest node" is used currently.

This seems quite weird at first, however may make sense if the preference is dictated due to some external reasoning (load balancers) and the addresses are mostly static (i.e. "My team has these addresses, and the load balancer always prefers them in this order. We'd like to host the Singleton on these nodes, independently if they are the oldest in the cluster or not").

**Comment by patriknw** [comment]
It should be doable, I'm not sure that there is enough interest in this feature.

**Comment by michaelom** [comment]
Let me give you an example how we would use this feature in our project.

We run multiple cluster singleton in an akka cluster, each consuming events (via PersistentView) from an event store (populated by other services running in different clusters). We plan to use Akka Streams once 2.5 is released but for now its a PersistentView consuming events. Events are then written to a (denormalised) model in some datastore. Events must be consumed on exactly one node in the cluster otherwise the datastore gets corrupted. It easy to imagine what happens, if each node in the cluster consumes events and writes to the same datastore.

As of Akka 2.3.12 all singletons reside on the oldest node, consuming all events. That causes asymmetric load in the cluster. (Oldest node is doing all the work.) That's an issue! A mechanism to have cluster singletons distributed across all cluster members would be more than welcome. Release 2.4, I am looking at you! :-) 

I'd rather have a strategy I can implement and pass on to the SingletionPropsFactory then a "preference list". Or something similar to the `shard allocation strategy` in the ShardingExtension.

**Comment by patriknw** [comment]
@michaelom I don't see how your description is related to a static preference list. For what you describe I think that the new [Remember Entities](http://doc.akka.io/docs/akka/2.4.0-RC2/scala/cluster-sharding.html#Remembering_Entities) feature of Cluster Sharding should work. An entity actor in Cluster Sharding is like a Cluster Singleton (only one instance of that entity will run somewhere in the cluster) but the allocation is much more dynamic.
