### ISSUE TITLE
Do we really need header caching?

### ISSUE THREAD

**Issue by mcamou** [akka/akka#18397]
We've been trying to track down a very elusive bug in one of our systems, where we get a `400 Bad Request` error after a number of requests to the server. We finally tracked it down as far as the HTTP Header caching in Spray, for some reason the `nodeCount` variable in HttpHeaderParser is being set to a value > 32k, which, since it later is converted to a Short, results in overflow.

We have fixed the problem by disabling HTTP header caching (`spray.can.server.parsing.header-cache.default = 0`). We have tried to make a reproducible minimal project but have been unable to.

My question is, what effects can we expect from disabling header caching entirely? I don't really understand why it is even necessary, since the headers have to be parsed anyway in every request (since the values might have changed). Is this to save memory by reusing HttpHeader objects?

**Comment by ktoso** [comment]
// cc @sirthias @jrudolph

**Comment by sirthias** [comment]
The header caching logic in spray (and in akka-http) is especially important in high-throughput applications where minimizing the overhead of the HTTP layer is key.
Since most HTTP/1.1 connections are reused for several requests and many headers remain identical between requests (e.g. `User-Agent`, `Accept-*` or caching headers) the cache can significantly improve parsing performance and reduce GC pressure.
Of course, everything should still function correctly if you disable the cache.

What I didn't quite get from your description:
According to your experience, is there a bug in spray and/or akka-http that needs to be fixed?
Even if it is just a missing range verification of a config setting?

**Comment by mcamou** [comment]
Yes, it looks like there is a bug but I couldn't create a simple case that would reproduce it. As mentioned in the original report, what I observed is that somehow the `var nodeCount: Int` in `HttpHeaderParser` was being set to a large value (> 32k). This is then converted to a `Short` using `toShort` in the `insert` method (in spray-can 1.3.2 it's in lines 223 and 235) which results in a negative number. This is stored in the `branchData` array and later used as an array index, which results in an `ArrayIndexOutOfBoundsException`. As I said, we couldn't get to a point where we could create a small self-contained example.

**Comment by sirthias** [comment]
Ok, understood.
Is there any relation to Akka HTTP or is what you describe a pure spray issue?

**Comment by mcamou** [comment]
We haven't tried it with Akka HTTP, I don't know if the header caching code is the same on both projects or not.

**Comment by sirthias** [comment]
Ok, a quick code review did indeed show a way to trigger the `ArrayIndexOutOfBoundsException` you've been seeing. The code is identical in spray and akka-http, so this problem is also present in akka-http.
I'll propose a fix.
Thanks for reporting!

/cc @jrudolph
