### ISSUE TITLE
Proposal for ActorSubscriberMessage.OnSubscribe message

### ISSUE THREAD

**Issue by rauanmaemirov** [akka/akka#18443]
Currently `OnSubscribe(s: Subscription)` is a private class, which I'm told is done in order to hide underlying Subscription.

Because of that, there's no way to find out if there's a consumable subscription. If one would use `ZeroRequestStrategy`, he would need to call `request(n)` in advance, i.e. queue the pending demand. I'd like to suggest simple `ActorSubscriberMessage.OnSubscribe` message that doesn't expose subscription to the outside, but allows to know that there's an available one that can be consumed.

**Comment by patriknw** [comment]
It is supposed to be possible to call `request` before `OnSubscribe` arrives, e.g. in constructor or `preStart`. That demand will be requested when the subscription arrives: https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/actor/ActorSubscriber.scala#L192

Have you found that it does not work?

By the way, I think we have a bug related to this if it is is done from constructor and the actor is restarted, because the demand is overwritten by the state from the previous instance https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/actor/ActorSubscriber.scala#L220

**Comment by rauanmaemirov** [comment]
@patriknw Yeah, I know that:
> he would need to call request(n) in advance, i.e. queue the pending demand

It works fine. As I've been telling in gitter channel, this is the question of preference/convenience. I might want to control when to send my requests instead of operating 'self-imposed' blackbox.
