### ISSUE TITLE
parse "off" as MaxLong for akka.http.server.parsing.max-content-length

### ISSUE THREAD

**Issue by cubefriendly** [akka/akka#18489]
If I want to disable the max-content-length limit for my service, I need to give "MaxValue" as a param in the config.

But MaxValue can be seen as a magic number and makes the configuration less clear.

It would be good if "off" would be parsed to MaxLong and therefore make it explicit in the config

**Comment by ktoso** [comment]
Looking at the config option now, it does support the bytes syntax, i.e. `2G` or `200M`.
So instead of a MaxValue one can give it "10G" which or some other very large number which in turn can be dictated by your requirements. I'm pretty sure your service definitely should have some upper limit of file uploads it can take, I mean, even YouTube restricts those (at least it did a while ago :-)).

With file uploads one can also make the limit in code, maybe logic dependent ("authed user" => 10G, others => 1G): http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-cookbook.html#Limit_the_number_of_bytes_passing_through_a_stream_of_ByteStrings

Before we allow this "off" style setting, I'd like to re-visit this question again, given that the value can be given in a nice format and not just a very big long. I'd rather not allow disabling it, since then we have to, for consistency, do the same for max-chunk-size and other settings, which will encourage people to disable it altogether everywhere - which is a bad thing to do.

// cc @jrudolph @sirthias

**Comment by ktoso** [comment]
@drewhk provided a nice hint, that we should just enable this for these two settings:

```
max-content-length         = infinite
max-chunk-size             = 1m
```

Also, I'll use infinite instead of `off` as it better relays the meaning and is used in such places already.

**Comment by cubefriendly** [comment]
Having infinite instead of off is good for me. 
I understand your concern and I am 100% with you that it does not make sense to disable the limit by default. But it should be possible to do so.

**Comment by ktoso** [comment]
Cool, figured out the way to get this solved, here's the PR: https://github.com/akka/akka/pull/18491

**Comment by cubefriendly** [comment]
looks good!! thank you
