### ISSUE TITLE
Provide Supervisor(strategy, childProps) to ease Sharding entity supervision

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18487]
We should provide a `Supervisor(strategy, childProps)` that works similar to `BackoffSupervisor` however applies the strategy right away. It is useful when you need to configure supervision, yet "someone else is starting the actor for you, so you need to introduce this Supervisor parent", a common example being Cluster Sharding.

More details here: https://github.com/akka/akka/pull/18445#issuecomment-140698857

**Comment by patriknw** [comment]
at the same time we can also make `BackoffSupervisor` a bit more flexible by making it possible to install a strategy into that also, so that exceptions can result in stop-backoff-start instead of immediate restart

**Comment by patriknw** [comment]
See also https://github.com/henrymai/akka-transparent-exponential-backoff-supervisor that was shared via #18766

**Comment by masterzen** [comment]
:+1: for adding a possibility to add a supervision strategy to a cluster sharding entity.

Still, one of the issue with `BackoffSupervisor` (and other parent-masquerading-child patterns) with respect to Cluster Sharding is that it prevents using the Passivate mechanism.

Because the entity running as the child actor of the `BackoffSupervisor` will send its `Passivate` message, instead to the `Shard`, resulting in the entity receiving back the `Passivate`. The only solution is to infer the path to the `Shard` from its own entity path and use an `ActorSelection` or create a specific `BackoffSupervisor` that knows how to forward the `Passivate` message upstream.

**Comment by sdab75** [comment]
We tried testing the supervision functionality as described in the 2.4.0 documentation and in fact we ried running partiknw example and we don't see exception getting propagated to the supervisor actor. My project with few modifications checked-in at  this location (https://github.com/sdab75/akka-cluster-sharding-test/blob/master/src/main/java/akka/cluster/sharding/ClusterShardingTest.java). Since it was documented we thought this working. Can some one help us understand if this fix was merged in the 2.4.0 branch or not.
