### ISSUE TITLE
Fix or improve docs search

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18499]
Esp. due to the nature of Http docs (lots and lots of directives) it is hard for newcomers to find the exact thing they're looking for. 

Plan a) Fix the google search
Plan b) full text search with keywords extracted from docs (i.e. elastic search or sth) – this is kind of my pet project, have not gotten far yet though.

**Comment by jrudolph** [comment]
I know this is not directly applicable but for spray.io we have a workflow for generating the documentation that let's us access more metadata programmatically which we use to feed the search (and little known: the browser search bar suggestions when enabled...).

The workflow works basically like this:

 * let sphinx generate json output instead of html
 * parse this json output on server startup and build the document tree in memory
 * serve documents from json fields
 * use structure to build breadcrumbs, search, etc.

See https://github.com/spray/spray/tree/master/site/src/main/scala/spray/site

**Comment by jrudolph** [comment]
On spray.io it's not a full-text search but only a search for headings.

**Comment by ktoso** [comment]
That's very useful, thanks!
Our site is static so these things will be hard to pull off... we were working on a "docs server" for a while, but it's stuck currently (no manpower). Using something like the json indexing + external search service may be the easiest to get something up *soon*.

**Comment by ktoso** [comment]
Update: testing algolia (which is used on http://docs.scala-lang.org/style/ )

**Comment by ktoso** [comment]
Solved.
