### ISSUE TITLE
Setting akka.http.server.parsing.illegal-header-warnings = off doesn't work

### ISSUE THREAD

**Issue by analytically** [akka/akka#18533]
When using the following config:

```
akka {
  http {
    server.parsing.illegal-header-warnings = off
    client.parsing.illegal-header-warnings = off
  }
}
```

I still see

```[WARN] a.actor.ActorSystemImpl - Illegal response header: Illegal 'expires' header: Illegal weekday in date 1990-01-01T00:00:00: is 'Fri' but should be 'Mon'```

Using Akka HTTP 1.0.

**Comment by ktoso** [comment]
Thanks for reporting! I'll have a look right away :)

**Comment by ktoso** [comment]
Actually it seems to work properly, I've verified both with current latest version as well as the 1.0 version of Akka Http. Are you sure the settings are actually being picked up? Where do you put them, to application.conf (if so, are you using it? also known as: not supplying a custom conf that ignores this file?)?

(you can check it yourself using this [branch](https://github.com/ktoso/akka/tree/wip-illegal-headers-warning-bad-ktoso) by `sbt shell; project akka-http-tests-experimental; test:run`)

**Comment by analytically** [comment]
Try this:

```
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.client.RequestBuilding._
import akka.http.scaladsl.model.headers.{BasicHttpCredentials, Authorization}
import akka.http.scaladsl.model._
import akka.http.scaladsl.server.directives.UserCredentials
import akka.http.scaladsl.unmarshalling.Unmarshal
import akka.http.scaladsl.util.FastFuture
import akka.stream.ActorMaterializer
import com.typesafe.config.{ Config, ConfigFactory }

object TestClient extends App {
  val testConf: Config = ConfigFactory.parseString("""
                                                     akka {
                                                       http {
                                                         server.parsing.illegal-header-warnings = off
                                                         client.parsing.illegal-header-warnings = off
                                                       }
                                                     }
    akka.log-dead-letters = off""")
  implicit val system = ActorSystem("ServerTest", testConf)
  import system.dispatcher
  implicit val materializer = ActorMaterializer()

  Http().singleRequest(Get(Uri("http://localhost:8000"))).flatMap { response =>
    response.status match {
      case StatusCodes.OK => FastFuture.successful(StatusCodes.OK)
      case _ => Unmarshal(response.entity).to[String].flatMap { entity =>
        val error = s"Request to failed with ${response.status}. Entity: '$entity'"
        FastFuture.failed(new IllegalRequestException(ErrorInfo(error, ""), StatusCodes.BadRequest))
      }
    }
  }
}
```

and wrongheader.py:

```
from BaseHTTPServer import HTTPServer, BaseHTTPRequestHandler

class RequestHandler(BaseHTTPRequestHandler):
    def _writeheaders(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.send_header('Expires', 'Fri, 01 Jan 1990 00:00:00 GMT')
        self.end_headers()

    def do_HEAD(self):
        self._writeheaders()

    def do_GET(self):
        self._writeheaders()
        self.wfile.write("""check the expires header""")
        
serveraddr = ('', 8000)
srvr = HTTPServer(serveraddr, RequestHandler)
srvr.serve_forever()
```

Run with `python wrongheader.py`. I still get 
```
[WARN] [09/24/2015 14:56:50.166] [ServerTest-akka.actor.default-dispatcher-9] [akka.actor.ActorSystemImpl(ServerTest)] Illegal response header: Illegal 'expires' header: Illegal weekday in date 1990-01-01T00:00:00: is 'Fri' but should be 'Mon'
```

**Comment by ktoso** [comment]
Thanks for the reproducer, I've tracked it down to config resolution problems (these refer to one another pretty intensely and am trying to figure it out currently).

The workaround is to set `akka.http.host-connection-pool.client.parsing.illegal-header-warnings = off` directly, and not just `akka.http.client.parsing.illegal-header-warnings = off` though this seems like a bug to me, so looking into it and will fix.

**Comment by ktoso** [comment]
@jrudolph @sirthias I've been digging into this, and wanted to confirm if the intended use of the following fields is as I've initially imagined, or not really and we can drop supporting what I've imagined (because we don't, and supporting it would require quite some coding):

```
# Modify to tweak parsing settings on the client-side only.
akka.http.client.parsing = ${akka.http.parsing}

# Modify to tweak client settings for host connection pools only.
akka.http.host-connection-pool.client = ${akka.http.client}
# thus:
# akka.http.host-connection-pool.client.parsing == akka.http.client.parsing
# yet: during initial resolution time ONLY!
```

I had imagined, that by setting (in my `application.conf`, or String) the value of `akka.http.client.parsing.illegal-header-warnings = off` would effectively "sprinkle all the way down to `akka.http.host-connection-pool.client.parsing.illegal-header-warnings` and turn it off as well. This ticket is also kind of proof that users expect this to happen.

**What actually happens is:**
- all `reference.conf` values are resolved "together", in one sweep (!)
- which means that the default value "on" has been now verbatim copied to the `akka.http.client.parsing.illegal-header-warnings`, field
- now it's time for `application.conf` resolution, and yeah if I set `akka.http.client.parsing.illegal-header-warnings` then there it is changed, 
- however that change is *not* sprinkled all the way down to the `akka.http.host-connection-pool.client.parsing.illegal-header-warnings` which was using `${}` syntax to refer to the `client` setting
- thus the setting is not reflected in `host-connection-pool`
- thus it is not used by the client-side at all, because `ConnectionPoolSettings` simply gets what it has there.

Questions:
- Is the current behaviour what we want to keep? If so, I'll document more explicitly that there's `host-connection-pool` in addition to `client` and `server` config sections.
- It's tempting to say that this is not really the behaviour we want, and the "sprinkle change in client, into host-connection-pool" should actually work. This though... does not seem achievable without hacking around how typesafe-config handles resolution. It could be done in code I guess, via weird diffing etc.

On one hand, current semantics surprised me myself so I'd want the 2) option, but implementing it is actually pretty complex and also, when "just looking at config" it's less obvious what's happening, since some logic must be then in the code. Do you think we should pursue this (I'm very much on the fence about either way)?

**Comment by rkuhn** [comment]
Thanks for the analysis, @ktoso. The test case you propose is the wrong approach since it would mean breaking all Typesafe Config users: the current behavior is deliberate and specified as well as necessary for sane operation (referring to the fact that `reference.conf` must be fully resolved before building a multitude of other configs on top of it—there is only one shared instance per class loader).

The sane thing to do is to remove the magic-looking and misguiding `${}` syntax from our `reference.conf` files.

**Comment by ktoso** [comment]
Yeah, good idea, it won't look as-if it should magically propagate and is consistent with typesafe-config then.

I'll do that and improve docs around when which setting is used then.

**Comment by jrudolph** [comment]
Ah yes, thanks for investigating, @ktoso. It should have clicked when I saw that `parsing` was in there. We had similar issues in the past where people tried to configure client and parser side at the same time by setting `spray.parsing`. Now, this one is even less obvious with the additional level of indirection.

**Comment by ktoso** [comment]
Huh, this too surprisingly much time to figure out :-)
I think this PR: https://github.com/akka/akka/pull/18562 will make it much less confusing, both for us and users.

// please review @rkuhn @jrudolph
