### ISSUE TITLE
Document what to do instead, if using the (anti pattern) respondWithMediaType from Spray

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18625]
Hi @sirthias @jrudolph,
I realised we don't have `respondWithMediaType` ported to Akka HTTP and am expecting that this is because we want people to rely on using the content type negotiation that HTTP does instead of baking their own using this directive...?

I'd like to confirm my thinking about it so I can sleep peacefully at night :wink: 

Refs:
- http://spray.io/documentation/1.2.2/spray-routing/respond-with-directives/respondWithMediaType/
- https://github.com/akka/akka/issues/18425

**Comment by jrudolph** [comment]
Yes, it is an anti-pattern we didn't manage to get rid of.

Unfortunately, (as we found out too late) it was part of one of the introductory  examples, which needed it to serve scala-xml literals properly as `text/html`. IIRC we changed that behavior with the current xml node marshaller, so there are little reasons to use `responseWithMediaType` instead of using the marshaller infrastructure proper.

**Comment by sirthias** [comment]
Yes, +1 to "`respondWithMediaType` is definitely an anti-pattern"!

**Comment by ktoso** [comment]
Thanks for confirming guys! 
Sounds like this is best solved by adding a small note in the migration guide https://github.com/akka/akka/issues/17972.

**Comment by ktoso** [comment]
Added a note in migration-from-spray.rst

**Comment by ktoso** [comment]
Reopening, it was mentioned in http://akiradeveloper.hatenadiary.com/entry/2015/11/02/222054 as lack of this directive caused him to abandon akka-http (and another thing). We should re-visit the directive and explicitly explain what to do instead if we really don't want it.

// cc @rkuhn @jrudolph @sirthias

**Comment by sirthias** [comment]
I seriously doubt that the lack of a single directive can be the single cause why anyone would not use akka-http. Especially since you can easily write this directive yourself, if you so wish, with only a few lines of code.

`respondWithMediaType` is an anti-pattern because it essentially circumvents the content negotiation logic that the marshalling infrastructure was carefully designed to enable.

**Comment by jrudolph** [comment]
It seems the bigger problem of the blog poster was to get the entity types to work with the S3 API uploads. I guess it could be a confusion about when to use CloseDelimited vs Default but Google Translate didn't preserve enough semantics for me to understand what the real problem was.

**Comment by ktoso** [comment]
We tried to reach out to him (in Japanese, thanks @eed3si9n!) for more details. 
I guess what we should do here though is to look how he used it (how it was being used), and explain how to do it properly in the docs. Keeping the ticket open until we have that.

**Comment by eed3si9n** [comment]
@jrudolph is right about the main complaint being CloseDelimited. Should I open a new issue for this?
The motivation for using CloseDelimited with Content-Length > 0 was that some clients are not able to handle the Chunked response.

**Comment by rkuhn** [comment]
Hmm, so I take it that those less capable clients are relevant and we should support them? If so, then we’ll need to make it possible and document it. Otherwise we just need to document it.

**Comment by jrudolph** [comment]
As I understood it the problem was in *writing a client* for S3 uploads. Using chunked uploads with S3 seems to be possible but is quite complex (due to having to use an extra framing protocol layer in addition to the HTTP chunking to provide signatures). `CloseDelimited`, however, can not be used for requests (= uploads) because (half-)closing the connection to signal end of stream is not allowed for requests. This leaves a `Default` entity as the only streaming way to upload data. However, for a `Default` entity the content length must be known in advance.

I guess one of those things was the problem.

However, none of these problems are problems of akka-http but these are all limits inherent in HTTP. We tried to model everything that is available in HTTP by the HttpEntity ADT which is very explicit in what it needs and provides. AFAIK we support all the modes that are possible with HTTP. We already have [some documentation about the entity types](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M2/scala/http/common/http-model.html). To be able to improve the documentation we would need to know more clearly what exactly the problem was.

**Comment by jrudolph** [comment]
BTW, I just guessed what the problem was from the keywords. It would be nice if you could confirm that this is at least partly correct, @eed3si9n :)

**Comment by eed3si9n** [comment]
Yes. The implied "client software" that doesn't handle chunked response seems to be Amazon S3. Maybe he meant to say "peer."  In any case, I think he's trying to call [Complete Multipart Upload](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html), which seems to require `Content-Length`. To handle large files, he wants to return `Stream[T]` from it.
Most likely this is the code - https://github.com/akiradeveloper/akka-s3/blob/9d1288acf5db5d6725b96b6ff3b78233a7d7cf91/src/main/scala/akka/s3/api/CompleteMultipartUpload.scala

**Comment by jrudolph** [comment]
So, this is a restriction from S3 not from akka-http, right? If S3 requires a Content-Length you need to compute it somehow and use an HttpEntity.Default regardless from where the actual data comes.

**Comment by eed3si9n** [comment]
> So, this is a restriction from S3 not from akka-http, right? 

It's a combination of both since Spray was able to handle it by returning Content-Length > 0 with CloseDelimited, and now he's looking into other web frameworks.

**Comment by jrudolph** [comment]
No, there was no CloseDelimited in spray. If you want to supply a Content-Length, HttpEntity.Default is the right choice.

**Comment by betandr** [comment]
FWIW we use `respondWithMediaType` currently with Spray but I'm really happy to stop using it...

**Comment by omervk** [comment]
Hi all,

I've gone over the conversation in this thread and the linked threads and would like to pose a question. I have an API that creates an object, but only knows how to answer when the client `Accept`s `application/json`. A user of my API sent a request using `text/plain` and received `406 Not Acceptable` with the error `Resource representation is only available with these types: application/json`, but the object was still created. This is an unexpected side-effect.

Based on [the answers to this question on StackOverflow](http://stackoverflow.com/questions/32187858/akka-http-accept-and-content-type-handling), I created the following to wrap around my route:

```scala
extract(_.request.getHeader(classOf[Accept])) { accept =>
    if (!accept.isPresent || accept.get().acceptsAll() || accept.get().mediaRanges.exists(_.matches(MediaTypes.`application/json`))) {
        // My routes here...
    } else {
        reject(UnacceptedResponseContentTypeRejection(Set(ContentNegotiator.Alternative(MediaTypes.`application/json`))))
    }
}
```

This works, but I have two questions:

1. Does it make sense to have this? I would have assumed there was a built-in mechanism for this.
2. Issue #18425 linked in OP notes that we should use `Marshaller.oneOf` but I'm not sure how one would go about doing this.

**Comment by ktoso** [comment]
Hi @omervk, yeah that's the current behaviour indeed (see also https://github.com/akka/akka/issues/16974 ) and it's something we'd like to improve (make the marshallers more lazy).

Please track that other ticket too to get status updates on it (or help out if you can!)

**Comment by omervk** [comment]
Thanks! :+1:

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)

**Comment by ctataryn** [comment]
@ktoso I'm starting in on converting my Spray 1.3.1 app to Akka-Http. I do use this `respondWithMediaType` method when I'm serving up a file.  Can you point me in the right direction on what this code will look like in Akka-Http?

```scala
    dep.subtitleService.getSubtitlesByDistributionId(distributionId).right
      .map(_.toSRTStrings).right.map(_.mkString) match {
      case Left(e: DistributionNotFoundError) => complete { e:ToResponseMarshallable }
      case Right(srtString: String) => {
        if (asFile) {
          respondWithMediaType(MediaTypes.`text/plain`) {
            respondWithHeader(HttpHeaders.`Content-Disposition`.apply("attachment", Map("filename" -> (distributionId.toString() + ".srt")))) {
              complete {
                HttpResponse(entity = HttpData(srtString))
              }
            }
          }
        } else {
          complete { srtString }
        }
      }
    }
```

**Comment by jrudolph** [comment]
If you don't want to use a marshaller, you can use something like that:

```scala
complete(HttpResponse(entity = HttpEntity(MediaTypes.`text/plain`, srtString))
```

**Comment by ctataryn** [comment]
@jrudolph thanks.  May I ask, why is `respondWithMediaType` considered an anti-pattern yet `respondWithHeader` [1] is deemed ok?  Was it that the generic `respondWithHeader` should be the only access given to headers rather than having the specialized directives like `respondWithMediaType`?

[1] - http://doc.akka.io/docs/akka-http/10.0.5/scala/http/routing-dsl/directives/respond-with-directives/respondWithHeader.html#respondwithheader

**Comment by ktoso** [comment]
Content Type / Media Type is treated specially since the marshalling infrastructure inspects it to see if the provided unmarshaller/marshaller matches what you want to emit/parse.

None of the other headers impact marshalling in that sense, so changing headers in that way is fine.

Content Types should be always aligned with that _actually_ is being marshalled. Thus, the value should come from the marshaller, and not marshaller says "it's json!" but you say "oh actually it's text!". So it's to avoid such things basically.

**Comment by ctataryn** [comment]
@ktoso thanks. Now in the case where one is  completing on a `String` (as I am) how else could the marshaller be chosen other than by 'MediaType'? 

By creating a specialized container type for the `String` to trigger the use of the correct Marshaller? Or by explicitly forcing the Marshaller that is used,  like what is being done in the "Using Marshallers" section [1]

[1] - http://doc.akka.io/docs/akka-http/current/scala/http/common/marshalling.html

**Comment by ktoso** [comment]
> By creating a specialized container type for the String to trigger the use of the correct Marshaller? 

Yeah, this sounds the cleanest IMHO. Since it expresses intent nicely.
You can easily build one marshalled on top of another one, I blogged about this on http://kto.so

**Comment by ctataryn** [comment]
Thanks @ktoso!

**Comment by ctataryn** [comment]
@ktoso P.S. In the question/blog post I noticed it's implementing an _Unmarshaller_ for an Http*Response*. Isn't Unmarshalling something you'd typically want for an Http*Request* :thinking: ?

**Comment by ktoso** [comment]
Depends who you are :-) A client unmarshals responses.

**Comment by ctataryn** [comment]
@ktoso touché
