### ISSUE TITLE
Google's Quic protocol

### ISSUE THREAD

**Issue by bblfish** [akka/akka#18637]
Opening a new issue to track Google's Quic protocol which can be summarised as UDP + TLS + SPDY/HTTP2 in one.

Docs:
   https://www.chromium.org/quic 

Video: 
* [Feb 2014: Google Developers presentation](https://www.youtube.com/watch?v=hQZ-0mXFmk8), covers relation to SPDY
* [June 2015: Brian Rogan & Ian Swett, Google](https://www.youtube.com/watch?v=cSNT88_gedw), an update
* [IETF 93, Prague 2005 Quic Bof](http://recordings.conf.meetecho.com/Playout/watch.jsp?recording=IETF93_QUIC&chapter=BAR_BOF): Microsoft engineer in second part implemented protocol from spec in 3000 lines of c++ code
* [ 12 Sept 2014: "How Secure and Quick is QUIC? Provable Security and Performance Analyses"](https://www.youtube.com/watch?v=vXgbPZ-1-us) at the 36th IEEE Symposium on Security and Privacy

Is mentioned in summary report of IETF 93 Prague 2015
 https://centr.org/system/files/share/centr-report-ietf93-20150803_0.pdf

**Comment by bblfish** [comment]
Something to tie together with HTTP/2.0 support #16862

**Comment by ktoso** [comment]
Hi @bblfish :-)
We're aware of QUIC and it's a nice protocol. Currently we don't have the resources to work on it though, it's more likely we'd first pick HTTP2.

Sounds good to track interest from the public in implementing QUIC in this issue though, so thanks for opening.

**Comment by jrudolph** [comment]
FWIW I had a quick stab at it 2.5 years ago, the protocol has probably evolved a lot since that time but in case someone is interested in my ancient stumbling around I uploaded it to GH:

https://github.com/jrudolph/spray-quic

I got the code to actually deliver a single response to the browser which seemed like quite a achievement at that time. I left out the hard things, obviously, like proper encryption (not supported at that time), FEC (I couldn't get my head around that), congestion control algorithms (QUIC required reimplementing TCP congestion avoidance algorithms which I didn't bother with), etc.

**Comment by drewhk** [comment]
FEC in this case is a very simple erasure coding using parity bits, if I recall correctly. It works if packet loss is not bursty, although I am not sure how realistic that assumption is.

**Comment by viktorklang** [comment]
@drewhk You mean like cellular networks? ;-)

**Comment by drewhk** [comment]
Those as well :)

**Comment by dmitraver** [comment]
Actually I would like to contribute to this issue. It might be challenging though.

**Comment by hepin1989** [comment]
someone is want that from Netty 5 too.

**Comment by spaced** [comment]
Upcoming HTTP/3 is based on previous RFC draft "Hypertext Transfer Protocol (HTTP) over QUIC.
Can we reopen this issue and remove the `obsolete` flag?
https://tools.ietf.org/html/draft-ietf-quic-http-16

**Comment by patriknw** [comment]
We don’t have any immediate plans to implement HTTP/3. Higher up in the priority list would be HTTP/2 client side.
