### ISSUE TITLE
Potential null dereference

### ISSUE THREAD

**Issue by edainwestoc** [akka/akka#18644]
routee is not checked for Null prior to dereferencing on line 123:

Router.scala, lines 119-124:
119 private def send(routee: Routee, msg: Any, sender: ActorRef): Unit = {
120   if (routee == NoRoutee && sender.isInstanceOf[InternalActorRef])
121     sender.asInstanceOf[InternalActorRef].provider.deadLetters.tell(unwrap(msg), sender)
122   else
123     routee.send(unwrap(msg), sender)
124 }

**Comment by patriknw** [comment]
@edainwestoc what is the problem with that? `NullPointerException` is a valid exception in that case (and it would be an implementation bug of the `RoutingLogic` implementation to return `null`).

**Comment by edainwestoc** [comment]
Patrik,Yes, it is a valid unhandled exception. Where is the exception handled? Or is the caller responsible to handle the exception?
Ed

 

Date: Wed, 7 Oct 2015 08:59:01 -0700

**Comment by ktoso** [comment]
Well the caller – if you try to send to `null` then you're doing things wrong and you'll get an exception as-soon-as-possible, which is what the current impl does.

**Comment by edainwestoc** [comment]
What happens if there is a hardware or runtime problem where the null is not the callers issue?
Ed

 Date: Wed, 7 Oct 2015 09:15:56 -0700

**Comment by edainwestoc** [comment]
Thanks for ignoring this. 

If you would ... please look up CWE-395. This is scala code but the CWE above is directly related to using a NullPointerException to handle the situation.

Sent from Ed Aguinaga's iPhone
Life is analog, digital is just samples thereof

**Comment by rkuhn** [comment]
@edainwestoc Akka does not catch NullPointerException, so CWE-395 is unrelated. Hardware errors leading to null references are not a sensible constraint to program under, the program will and should just crash with an unhandled exception when the hardware does not behave as it should—also, a null check followed by a dereference might as well blow up under a matching hardware error scenario. Given these I fail to see your point, could you elaborate?

As a general comment, you seem to apply code inspection tools that flag “problematic” idioms without regards to the context: in Scala `null` is generally not used as in Java, it is neither expected nor emitted. We sometimes use it as an internal implementation detail for optimization—if you find a `null` leaking out then that would indeed be interesting. My point is that we don’t and won’t add null checks because emitting a NullPointerException is exactly the right thing that shall happen, and it is used in a fatal sense (i.e. not expected to be caught).
