### ISSUE TITLE
Source.lazyEmpty has slightly confusing name

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#18676]
Because nothing is `lazy` about it. Instead, it is "fremdkontrolliert" as we Germans say.

So, how about: `Source.alienControlledCompletion`

**Comment by ktoso** [comment]
cc-ing @rkuhn and @viktorklang who are working on "the surface api" currently ;)

**Comment by viktorklang** [comment]
Didn't I open a ticket about this already? Hmmm.

I'd go for something more akin to `Source.externalTrigger()`

**Comment by viktorklang** [comment]
Btw, would it be better with a Source.promise[T]

and then you can simulate `lazyEmpty` with: `Source.promise[Unit].filter(_ => false)`?

**Comment by ktoso** [comment]
Promise sounds interesting - what would the materialized type be? `Promise[T]` seems most obvious, though then it can also `p.future` on the promise you got materialized out of the stream which may be weird... A different name we had for it at some point was `trigger` AFAIR, because it's triggered externally.

**Comment by viktorklang** [comment]
`Promise[Option[T]]` as materialized type.

I tried Promise[T] but cancellation became weird.

I'm leaning towards: Source.maybe[T]

**Comment by viktorklang** [comment]
@ktoso I took a stab at it on my cleanup-wip-kitchen-sink branch: https://github.com/akka/akka/commit/d4abd3e7ac17962393e2687c8171a6c576e8c808

**Comment by rkuhn** [comment]
This has been done in #18700.
