### ISSUE TITLE
Clarify the criteria used by akka persistence to employ batch insertion

### ISSUE THREAD

**Issue by matheuslima** [akka/akka#18703]
http://doc.akka.io/docs/akka/2.4.0/scala/persistence.html#Batch_writes
The doc says:
"The batch size dynamically grows from 1 under low and moderate loads to a configurable maximum size (default is 200)"
But what is the actual criteria used to change the batch size? Size of mailbox? I think it could be more detailed explained.

**Comment by ktoso** [comment]
Thanks for rising the confusion, we'll look into it.

**Comment by patriknw** [comment]
until its written properly: it sends the write request to the journal if it doesn't have any outstanding write request, otherwise it keeps the write request buffered until it reaches the max buffer size (200) or the pending write is done and then it flushes the buffer as one batch

This only applies to persistAsync.

**Comment by matheuslima** [comment]
Thanks @patriknw :+1:

**Comment by patriknw** [comment]
I think this has been fixed by simplifying the batch logic. There is only one outstanding batch.
http://doc.akka.io/docs/akka/2.4.2/scala/persistence.html#Batch_writes
