### ISSUE TITLE
akka-http client, HttpsContext.create produces StackOverflow exception

### ISSUE THREAD

**Issue by georgeyanev** [akka/akka#18781]
I'm using akka with java only. Akka version: 2.3.14(Scala 2.11), akka-http-core-experimental_2.11 version: 1.0, java version: 1.8.0_25, OS: Ubuntu 14.04. 
My goal is to make a successful https client request with no server cert validation, nor server hostname verification.
First I tried with the default ssl configuration (without creating custom HttpsContext). Request failed with UnexpectedDisconnect exception. Then I tried creating a custom HttpsContext but this time the call to HttpsContext.create produced stack overflow exception.
Any suggestions how to avoid/bypass this?

**Comment by viktorklang** [comment]
Fixed here: https://github.com/akka/akka/pull/18784

**Comment by ktoso** [comment]
Thanks for reporting @georgeyanev!

**Comment by georgeyanev** [comment]
You are welcome.
So is it possible to make https requests with no server certificate and host-name verification?
When this 1.1 version will be available in maven central?

**Comment by ktoso** [comment]
> So is it possible to make https requests with no server certificate and host-name verification?

Disclaimer: I'd recommend against that for obvious reasons.

If you're talking about dev-time etc then it's OK to avoid cert checks I guess.
Yes, it's possible - you need to configure the HttpsContext to work like that - here's an example: https://github.com/akka/akka/blob/a3c22e2bffd50b66515f47247ecd7111c9b19e91/akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala#L36

We have tickets already about improving documentation for configuring the HttpsContext (see here https://github.com/akka/akka/issues/18334 ), so that'll be documented better soon.

We're planning for 1.1 in a week or few.

**Comment by viktorklang** [comment]
In the mean time the workaround is to create the scaladsl.HttpsContext as
it extends the javadsl one. see this patch for instruction how to create it
from java.

-- 
Cheers,
√

**Comment by georgeyanev** [comment]
These examples involve installing a CA cert in the local key store.
I want to disable any certificate checks and host-name validations without installing any certs in my place. Is this possible?

**Comment by georgeyanev** [comment]
It worked! Thanks for supporting!

**Comment by georgeyanev** [comment]
Hi, Konrad. Do you have any idea yet what is causing this and possibly some workaround ?
