### ISSUE TITLE
Method ignores exceptional return value CWE-252

### ISSUE THREAD

**Issue by edainwestoc** [akka/akka#18795]
The return value from a call to queueFile.delete is ignored and any exception is ignored by catching all non-fatal exceptions (if I get this correctly):

Journal.scala, Lines 102-109:
102  def erase() {
103    try {
104      close()
105      queueFile.delete
106    } catch {
107      case NonFatal(_) =>
108    }
109  }

**Comment by rkuhn** [comment]
Yes, that is the intention. Why is this a problem?

**Comment by edainwestoc** [comment]
Why did the delete fail? And if delete continues to fail, perhaps due to file system problems, runtime issues or whatever, how would you determine where this occurred?
I am sorry but ignoring exceptions is stupid. It invites problems and, in this case, problems that cannot be traced. Akka claims it helps build Resilient code. How can that claim be made when you ignore problems within you code?
Whether the problems ends up the cause of your code, or not, the code should be intelligent enough to at lest report that something went wrong. Or Akka should stop claiming that it helps build resilient code.
Sorry  but you asked.
Ed

 

Date: Wed, 16 Dec 2015 02:26:07 -0800

**Comment by rkuhn** [comment]
First off, the code that you are pointing at has long since been deprecated and removed. Second, the reason for removal was that durable mailboxes are a broken concept exactly due to resiliency concerns—their initial introduction was due to the broken state of the industry at the time which we are slowly correcting.

But even so, if you look at the reasons why this call may fail then you see that either the file was already deleted (which is fine) or we lost access to the filesystem—in which case we are in much bigger trouble and have logged that already.

**Comment by edainwestoc** [comment]
Thank you for pointing out this code has already been deprecated...
And sorry for my scratchy response...bad day.
Ed

 Date: Wed, 16 Dec 2015 08:22:12 -0800
