### ISSUE TITLE
Akka-HTTP: basicAuthentication directive promotes insecure passwords

### ISSUE THREAD

**Issue by jasonmartens** [akka/akka#18858]
When using the basicAuthentication SecurityDirective, you are required to pass in the clear-text user password to verify(). This implies that the clear-text password is stored somewhere, which is generally frowned upon. A more secure practice is to only save the one-way hash of the password in the database, the re-hash the clear-text provided by the user and compare the hashed output. 

This could be implemented in the verify method as an optional additional argument, which performs hashing of the clear-text password in the HttpCredentials, and compares it to the save hashed password. Something like this:
```def verify(hashedSecret: String, hasher: String => String): Boolean```

**Comment by jrudolph** [comment]
Thanks, @jasonmartens. That's a good point. The intention of the original design was to prevent developers from implementing a custom comparison function that leaks information about the stored secret. But you are absolutely right that we shouldn't encourage or even enforce (like we do now) unsafe secret storage. I like your proposal which allows to pass a user-defined function to transform the incoming data and the secret itself as separate parameters. As long as you don't use any information from the stored secret in the `hasher` function, it should be as safe as the existing one.

**Comment by Mullefa** [comment]
Say I have two services `user` and `user-pictures` which stores user passwords and profile pictures respectively. When a user sends a request with basic authentication to `user-pictures` to change their picture, I would like access to the `BasicHttpCredentials` so I can make a request to the `user` service to authenticate them. 

```scala
trait UserClient {
  def authenticateUser(username: String, password: String): Future[Boolean]
}

val userClient: UserClient = ???

def myUserPassAuthenticator(credentials: Option[HttpCredentials]): Future[Option[String]] =
  credentials match {
    case Some(BasicHttpCredentials(username, password)) =>
      userClient.authenticateUser(username, password).map {
        if (_) Some(username) else None
      }
    case _ => Future.successful(None)
  }
```
Does this seem unreasonable / an anti-pattern? 

Otherwise, if I wanted another service to authenticate the request, it seems I would have to do a `GET` request for the password hash (assuming that something like `def verify(hashedSecret: String, hasher: String => String): Boolean` is supported).

In general, I'd prefer access to the actual credentials rather than this limiting `Credentials` class, and if I don't mitigate for timing attacks - it's my own fault!

**Comment by quelgar** [comment]
This is a good change, but there are cases where there is no alternative but to extract the password. In my case, accounts will be managed by an LDAP server, and it isn't possible to access the password hash. The only way to check credentials is to try logging in to the LDAP server.

So, I'm going to have to implement my own basic auth directive to do this. It would be good if the built-in one also supported this as an option.

**Comment by ktoso** [comment]
> So, I'm going to have to implement my own basic auth directive to do this. It would be good if the built-in one also supported this as an option.

I think that's fine, Akka does not aim to provide directives for each and every case, instead it's relatively simple enough to build your own. I would be super happy if you could blog about your experience developing a directive, so people can learn from that!

**Comment by quelgar** [comment]
Yes, it turned out to be quite easy to make a directive for my specific case, the building blocks are public. I'll put it here in case anyone else stumbles across this:

```scala
def myBasicAuth[A](realm: String)(verify: headers.BasicHttpCredentials => Future[Option[A]]) = {
    authenticateOrRejectWithChallenge[headers.BasicHttpCredentials, A] {
      _ map {
        creds => verify(creds) map (_ map directives.AuthenticationResult.success)
      } getOrElse Future.successful(None) map
        (_ getOrElse directives.AuthenticationResult.failWithChallenge(challengeFor(realm)))
    }
  }
```

I don't bother asking the verify function what to do if the credentials are missing, which the standard directive does, presumably to support guest access.

**Comment by karol-brejna-i** [comment]
@quelgar Do you have the solution described in more details somewhere?
