### ISSUE TITLE
Possible inconsistency between journaled events and query side api when events are deleted

### ISSUE THREAD

**Issue by matheuslima** [akka/akka#18886]
Today the query side api only can read journaled events, but not read snapshots.
Consider the follow case to a persistent Actor: 
E1 -> E2 -> S -> E3 -> E4
E1 .. E4 are events and S is a snapshot
After successful save the snapshot S, the user delete the events E1 and E2 ( the final state yet can be rebuild).
The problem is the query side now only knows E3 and E4 and cannot properly build a read model to this persistent actor.

**Comment by rkuhn** [comment]
Unless someone has a brilliant idea I think we should just document that deleting events without ensuring proper representation of the final state (i.e. compacting events into fewer events instead of just deleting) is a good way to corrupt the log. For those use-cases that really are event-sourcing it should also not usually be a problem to retain all events—this issue normally only surfaces when Akka Persistence is abused as a message queue.

**Comment by patriknw** [comment]
I have no brilliant idea, so I agree with the comment.

Some query plugins create materialized views of the events that are decoupled from the original events, so deleting the events don't influence the queries. The tagged query in the leveldb plugin is an example of that.
