### ISSUE TITLE
warnOldDocs not working for RP docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18950]
See: http://doc.akka.io/docs/akka/rp-15v09p01/

**Comment by ktoso** [comment]
I think it's still broken, should be fixed.

**Comment by richard-imaoka** [comment]
What I observed was:

* http://doc.akka.io/docs/akka/rp-15v09p01/ did not load warnOldDocs.js (it should be next to ga.js, as in [layout.html](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-docs/_sphinx/themes/akka/layout.html#L16))
![image](https://cloud.githubusercontent.com/assets/7414320/18411719/332d56ae-77b8-11e6-87c0-bceabcf5596a.png)

* http://doc.akka.io/docs/akka/rp-16s01p04/ works fine

* http://doc.akka.io/docs/akka/1.1/ works fine to but I don't know why ... since [warnOldDocs.js](https://github.com/akka/akka/commits/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-docs/_sphinx/themes/akka/static/warnOldDocs.js) was added in 2015, much later than Akka 1.1

![image](https://cloud.githubusercontent.com/assets/7414320/18411671/10f126b6-77b7-11e6-932c-2518e1f8b4e6.png)

![image](https://cloud.githubusercontent.com/assets/7414320/18411681/46888cd8-77b7-11e6-9bee-5ab123f62325.png)

**Comment by ktoso** [comment]
RP considered obsolete by now?
If we wanted to it would make sense to check the redirects work though removing all mentions of the rp versions would be better quite honestly
