### ISSUE TITLE
akka.stream.scaladsl.Merge/Broadcast should require inputPorts > 0 

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#19028]
currently you could pass it a negitive number

**Comment by drewhk** [comment]
probably other stages need similar checks

**Comment by viktorklang** [comment]
Shouldn't merge and broadcast have at least 2?

**Comment by hepin1989** [comment]
I think when it have 1,then become a Flow[T].

**Comment by viktorklang** [comment]
@hepin1989 a Merge of input 1 or broadcast of output 1 == identity flow == no op == doesn't really make sense. @drewhk Is that optimized away?

**Comment by drewhk** [comment]
No, it is not, because the return type is `FlowShape` for flows and `UniformFanInShape` or `UniformFanOutShape` for merge/bcast. Of course FlowShape might be able to extend the 1 port version of these to make it work. Then the Broadcast and Merge factory methods can return an identity. It won't be optimized away later though.

**Comment by viktorklang** [comment]
@drewhk I'd rather have it error for < 2 outputports for BroadCast and < 2 inputports for Merge&friends.

**Comment by drewhk** [comment]
Yes, the user can do the optimization himself by using proper if-then in the builder block.

**Comment by viktorklang** [comment]
@drewhk :+1:
