### ISSUE TITLE
Investigate and remove buffer(1) in HttpBlueprint

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19091]
Making it an explicit ticket so I don't forget to follow up on it soon:

```
        // FIXME #16583 / #18170
        // `buffer` is needed because of current behavior of collect which will queue completion
        // behind an ignored (= not collected) element if there is no demand.
        // `buffer` will ensure demand and therefore make sure that completion is reported eagerly.
        .buffer(1, OverflowStrategy.backpressure)
```

**Comment by ktoso** [comment]
I believe we indeed can drop it not, but investigating to be sure.

**Comment by jrudolph** [comment]
I'd be interested as well if that can now be fixed (but I doubt it, actually).

**Comment by viktorklang** [comment]
@ktoso @jrudolph Is there a test which fails if it is removed and the problem isn't fixed?

**Comment by ktoso** [comment]
Lemme try while reviewing things actually.

**Comment by viktorklang** [comment]
:+1:

**Comment by ktoso** [comment]
Well, no tests failed so we're not sure if a) no test covers this behaviour or b) it actually works.
@jrudolph do you happen to remember how to get a case that would cause this buffer to show the need for itself?

**Comment by jrudolph** [comment]
I'll look it up.

**Comment by jrudolph** [comment]
It failed in this line: https://github.com/akka/akka/blob/release-2.3-dev/akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala#L637 before commit https://github.com/akka/akka/commit/3ffb53c85049fb9663973156c99517c5caf72554.

The buffer is not neccessary any more because there is now another element (the `One2OneBidiFlow`) between the problematic component and the user. It starts to fail again if you comment out both the `buffer` and the `userHandlerGuard(settings.pipeliningLimit) atop` line. So, we can now remove the extra buffer but maybe keep a comment that some buffering element is needed to pull completion through eagerly.

**Comment by drewhk** [comment]
I think fusing will uncover the underlying issue (if it still exists), since it will remove buffers. Then you can print the events with Debug mode on.

**Comment by ktoso** [comment]
Thanks a lot for looking it up @jrudolph !
We'll remove it and see if anything fails

**Comment by ktoso** [comment]
Great, thanks.
