### ISSUE TITLE
Unexpected DeathPactException in remoting

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19133]
We should investigate this.

INFO (11/23) 13:34:07 [stdout]: [ERROR] [11/23/2015 13:34:07.416] [RelaySystem-akka.remote.default-remote-dispatcher-6] [Remoting] Monitored actor [Actor[akka://RelaySystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FServerSystem%4010.3.1.102%3A2553-0/endpointWriter#-1184433023]] terminated (akka.actor.DeathPactException)

This was on 2.3.14

**Comment by patriknw** [comment]
I think I see how this can happen. ReliableDeliverySupervisor doesn't handle `Terminated` in its `idle` state, because then it is supposed to not have any writer child actor. However, it can enter the `idle` state with a non-terminated writer if it receives an `Ungate` message in `gated` state.

`Ungated` is sent from the `EndpointManager` at two places.

I think we need to keep track of when writer is terminated and only act on the `Ungate` message when the writer has been terminated.

Does that sound right, @drewhk ?

**Comment by drewhk** [comment]
Hm, but how can be there a writer if the connection is gated?

**Comment by patriknw** [comment]
I guess it is in progress of being terminated. Stopping is async, you know.
