### ISSUE TITLE
Improve Update and Gossip process

### ISSUE THREAD

**Issue by netcomm** [akka/akka#19131]
we want use LWWMap as our data structure, and split into 100 top level LWWMap entries

Update process:
but even this when one item add to LWWMap entry instance(for example lww1) use Update, it is send all lww1 full data to other replicas(if use WriteMajority), maybe we can just send the new item just like Delta-Mutation(i have read the paper,feel it like a semifinished product,it is still more detail not expanded)?

Gossip process:
maybe like LWWMap this type, in one gossip round-trip send one big full status is more heavy,can we segment into smaller parts,for example a LWWMap entry instance have 100000 items, we can segment into 10 parts.
These above are just ideas, please correct them.thanks! @patriknw

**Comment by patriknw** [comment]
I think support for delta-CRDTs would be a great improvement for Akka Distrubuted Data. That is not a trivial task and I don't have the bandwidth to start something like that now.

What you can currently do:
1) Use only top level key-values instead of LWWMap, take advantage of the delta transfer that already exists for the top level keys.
2) Partition your key space and use many top level LWWMap entries so that each LMWMap only holds a few real data entries.

**Comment by patriknw** [comment]
we might revisit delta-CRDTs or similar when we have collected real world demand for it
