### ISSUE TITLE
rework request parser to directly emit entities

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19240]
The current split/prefixAndTail/concat dance is not only costly, it also is inherently broken due to the ease with which substreams are dropped (ignored, because presumably empty), thereby deadlocking the whole stream. For a discussion see [this comment](https://github.com/akka/akka/pull/19212#discussion_r48040654).

This will also mean that MultipartUnmarshallers will be vastly simplified and optimized.

**Comment by 2beaucoup** [comment]
:+1:

**Comment by sirthias** [comment]
Yes, that is certainly the way to go, now that we have the cool new `GraphStage`, which was not available at the time the current HTTP stream structure was built.
Looking forward to the new perf numbers once this change is in!

**Comment by drewhk** [comment]
Is this ticket really fully closed?

**Comment by rkuhn** [comment]
I don’t think so.

**Comment by ktoso** [comment]
No it isn't, closing it must have been an accident, sorry

**Comment by jrudolph** [comment]
The problem that triggered this issue is now solved in another way which is cleaner IMO. Now we have two stages that split the work:

 * the parser is (mostly) responsible for interpreting the bytes
 * the preparation stage does the remaining work to present the data to the user

In any case, we don't created useless empty streams or streams for strict entities any more.

This split has the added benefit that it would allow a later, alternative entity-less and stream-of-streams-less API (more akin to spray's messaging API) that would deliver streamed messages as a sequence of dependent messages. As long as materialization is so slow this may be the only way to achieve reasonable performance also for streamed requests.

**Comment by ataraxer** [comment]
The client side has been taken care of in #19528.

**Comment by drewhk** [comment]
Hmm, is this solved now? The solution turned out to be somewhat different than what the original description states, but now both server and client are covered with an alternate solution. Is there something missing?

**Comment by rkuhn** [comment]
Yes, I think this is solved now.

**Comment by drewhk** [comment]
great! (moved to 2.4.2)
