### ISSUE TITLE
Sec-WebSocket-Protocol header is private[http]

### ISSUE THREAD

**Issue by analytically** [akka/akka#19258]
Overriding the default RejectionHandler is tricky for UnsupportedWebsocketSubprotocolRejection because Sec-WebSocket-Protocol is private.

**Comment by ktoso** [comment]
// cc @sirthias @jrudolph 

Technically apps are not supposed to create these headers that's why it's private I guess, but your use case makes sense hm.
We may need to do something special other than making it not private?

**Comment by ktoso** [comment]
I wonder If we have an opinion on this one, do you remember @sirthias @jrudolph?

**Comment by ktoso** [comment]
I guess I'd open up, if someone wants to do bad things they still can just create one via reflection

**Comment by sirthias** [comment]
Sorry for the late reaction (was on vacation last week).
I also don't see a problem with publicizing the header. But I think it was @jrudolph who added the header model initially and applied the `private[http]` modifier.

**Comment by jrudolph** [comment]
IIRC it was the conservative choice. We usually wouldn't want users to put their own WebSocket headers into requests or responses. On the other hand it is really nice to have all the headers available for unforeseen use cases. If we open them up, they should be marked somehow to be not used in normal requests or responses (unless you know what you are doing, i.e. probably reimplementing some part of akka http). If we want users to be able to actually override those headers with their own this would need to be supported in the implementation so that we don't output several potentially conflicting headers of the same kind.

**Comment by ktoso** [comment]
> supported in the implementation so that we don't output several potentially conflicting headers of the same kind.

Hm, that's a good consideration I have not thought about, thanks!

I'm on the fence of the need of working on this issue immediately, leaving in backlog in case it comes up again

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
