### ISSUE TITLE
Clarify TLS configuration in HTTP

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19294]
i.e. it should be clear what the relation between HttpsContext and sslConfig should be. HttpsContext allowed configuration of TLS settings for every single one of the `Http` APIs. It seems that now the global SSL config may override some settings.

IMO, in HTTP, there should only be one mechanism to configure TLS and this configuration shouldn't be touched by some global settings.

See also https://gitter.im/akka/akka?at=567c0e150199d70069df9867, #19264, and #19275.

**Comment by ktoso** [comment]
Thanks for raising this ticket, we need to have a plan here. I'll lay out our needs and current situation:

The reason ssl-config came into being (i.e. was ripped out from Play WS to be reusable between Akka and Play) was because we needed ssl host-verification and while we were at it, we ripped out the entire ssl-config module (wanted to do this for months already). That project is primarily geared towards making the client side safe: i.e. disables known weak algorithms etc. @wsargent did a great job there and we anticipate the same needs for the Akka HTTP client in any case (configuring SSL properly is hard => people don't do it or do it wrong => then blame the framework :wink:).

ssl-config is currently *not* applied to the server side, as the way things are users when hosting HTTPS provide the context manually, so we're not configuring it. With the client side they don't provide the context *usually* so we provide a default one -  which is configured using ssl-config.

Technically I guess we would want to disable weak algorithms etc "by default" on the server side as well, but we're not currently doing that (nor is ssl-config really complete to handle a server AFAIU).

So that's the situation – given that it seems to me at least that we want to secure the client side using ssl-config, should we strive to provide a "default https context" for the server as well – or at least help with configuring it somehow? If the answer is not, how do we explain that the client side has a nice default, but nothing else does?

**Comment by wsargent** [comment]
> Technically I guess we would want to disable weak algorithms etc "by default" on the server side as well, but we're not currently doing that (nor is ssl-config really complete to handle a server AFAIU). 

Yep.  There's a couple of settings that you would want on a server, such as `jdk.tls.rejectClientInitiatedRenegotiation`, that ssl-config does not cover.  See https://blog.ivanristic.com/2014/03/ssl-tls-improvements-in-java-8.html for more details.

**Comment by ktoso** [comment]
Still needs work on better and complete docs

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
