### ISSUE TITLE
Should warnOldDocs.js detect if redirect target exists?

### ISSUE THREAD

**Issue by utgarda** [akka/akka#19354]
http://doc.akka.io/docs/akka/2.3.9/scala/zeromq.html tells the reader to look at docs for 2.4.1, and provides the link: http://doc.akka.io/docs/akka/2.4.1/scala/zeromq.html , but the page doesn't exist. Same thing for Java.

**Comment by ktoso** [comment]
zeromq has been deprecated and removed since (it was though a full deprecation and warning cycle). 
The notice to "see latest" is automatically applied to all old versions of docs, we don't (yet) figure out if the target page exists or not.

If you have the time such contribution would be pretty interesting! It's the https://github.com/akka/akka/blob/master/akka-docs/_sphinx/themes/akka/static/warnOldDocs.js script.

**Comment by patriknw** [comment]
@rkuhn  this is something you have done, right?

**Comment by rkuhn** [comment]
Yes, this is in #19970.
