### ISSUE TITLE
HTTP: Consider running the routing infra on dedicated dispatcher?

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19376]
Just an idea.
To avoid people starving the routing layer as seen here: http://stackoverflow.com/questions/34641861/akka-http-blocking-in-a-future-blocks-the-server/34645097#34645097

**Comment by jrudolph** [comment]
Wow, that's quite an answer... :)

I wonder why a dedicated dispatcher for routing would help, though? In the case in question you could identify three zones you could want to isolate: routing, the single blocking Future, and everything else. In fact, the only thing that needs isolation is the single blocking Future. As long as something else is running in the same dispatcher as this blocking Future, something will be starved, right?

I think a better solution would prevent any `Future.apply` bodies in the default dispatcher. This may seem somewhat fundamental but in almost all cases starvation problems stem from `Future.apply` usages. At some point there was a discussion about this on the Scala mailing list and it seems the [documentation](http://docs.scala-lang.org/overviews/core/futures.html) was "improved" afterwards to make a distinction between a blocking and "non-blocking long lasting computation" which is not useful at all for the problem at hand.

IMO `Future.apply` could always be seen as a code smell because it lacks any mechanisms that would allow the inner code block to suspend execution and let something else kick in. Compare this to other Future combinators which are implemented using a Promise which can give up control to the dispatcher at some point.

A sensible solution would be to make the dispatcher argument in `Future.apply` explicit, or maybe remove `apply` completely and replace it by a better named thing which allows specifying a maximum number of parallel threads spawned to run a code block at this code location (or whatever scopes you could come up).

**Comment by ktoso** [comment]
@bantonsson I don't know when you guys will come around to instrumenting `Future` but it would be fun if you could issue warnings if a Future runs on Akka's default dispatcher.

**Comment by ktoso** [comment]
> Wow, that's quite an answer... :)

I had a day off and was procrastinating doing slides... :wink: 

Yeah isolating the routing layer addresses a tiny case in the sea of abusing blocking Futures to kill default dispatcher hm. Keeping the idea around for the time being. I wonder if tuning a dispatcher for routing could have (positive?) perf impact as well

**Comment by ktoso** [comment]
Closing as not actionable for now

**Comment by ktoso** [comment]
Would be semi-solved by having the "blocking is happening, aaaa!" warning actor in the system like we discussed with @drewhk
