### ISSUE TITLE
Timeouts when using StreamConverters.asInputStream

### ISSUE THREAD

**Issue by kostya-sh** [akka/akka#19392]
The following sample program eventually fails because of timeout:

    while (true) {
      val source = FileIO.fromFile(new File("file.txt"), 100)
      val inputStream = source.runWith(StreamConverters.asInputStream(5.second))
      val buf = new Array[Byte](200)
      while (inputStream.read(buf) > 0) {}
      inputStream.close()
      println("ok")
    }

file.txt size is 20kb

Timeout exception:

    Exception in thread "main" java.io.IOException: Timeout on waiting for new data
	at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply$mcI$sp(InputStreamSinkStage.scala:139)
	at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:124)
	at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:124)
	at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:104)
	at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:124)
	at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:115)
	at ....

Environment: Java 7, scala 2.11.7, akka 2.3.12, akka-streams 2.0.1

**Comment by viktorklang** [comment]
My suspicion: the returned InputStream's close()-method is not synchronous.

**Comment by kostya-sh** [comment]
@viktorklang, timeout happens in the read method (before close has been called) because `InputStreamAdapter.sharedBuffer` is empty and `InputStreamSinkStage` doesn't put anything there for more than 5 seconds. I suspect that communication protocol between InputStreamAdapter and InputStreamSinkStage is not broken.

**Comment by kostya-sh** [comment]
Possible reason: `sharedBuffer.poll()` is called by `grabDataChunk` that is called recursively from `getData`. While this happens `ReadElementAcknowledgement` is never sent to `InputStreamSinkStage`

**Comment by kodemaniak** [comment]
I think I am hitting the same problem, with the following snippet and Streams 2.0.2:

````scala
val source = Source.single(ByteString("test"))
val is = source.runWith(StreamConverters.asInputStream())
val source2 = StreamConverters.fromInputStream(() => is)
val result = Await.result(source2.runFold(ByteString.empty)((bs, c) => bs ++ c), 10.seconds)
result.utf8String should equal ("test")
````
This results in:

```
   java.io.IOException: Timeout on waiting for new data
[info]   at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply$mcI$sp(InputStreamSinkStage.scala:139)
[info]   at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:124)
[info]   at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:124)
[info]   at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:104)
[info]   at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:124)
[info]   at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:115)
[info]   at akka.stream.impl.io.InputStreamPublisher.readAndEmit(InputStreamPublisher.scala:55)
[info]   at akka.stream.impl.io.InputStreamPublisher.readAndSignal(InputStreamPublisher.scala:49)
[info]   at akka.stream.impl.io.InputStreamPublisher$$anonfun$receive$1.applyOrElse(InputStreamPublisher.scala:43)
[info]   at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
````

**Comment by kodemaniak** [comment]
OK, I didn't know my commit will show up here. Anyway, I fixed my issue above with that commit, but the  sample of @kostya-sh still produces a timeout after a lot of iterations. So, either that is another problem or my fix ist not complete.

**Comment by kostya-sh** [comment]
@kodemaniak, can you try to add `sendToStage(ReadElementAcknowledgement)` before `getData(arr, begin + size, length - size, gotBytes + size)` in `getData`:

    if (size == length)
        gotBytes + size
    else {
        sendToStage(ReadElementAcknowledgement)
        getData(arr, begin + size, length - size, gotBytes + size)
    }

**Comment by kodemaniak** [comment]
I've done some debugging. What happens is that the sharedBuffer (the LinkedBlockingDequeue) fills up before the timeout happens. The last Ack that is received by the Stage before the timeout, is handled when the buffer is already full, and subsequently the in-port is not pulled. After that no Ack makes it through to the stage anymore, but the buffer is drained empty by the adapter, and finally the timeout occurs since no new elements are pulled. I've put sendToStage(...) all over the place, but I guess there must be some race condition that I don't understand yet.

My assumption is that the stage and the adapter both run on the same thread, the poll blocks that thread, and therefore the asyncCallback is never called and no new elements are pulled. But to be honest, my knowledge of akka internals is not complete enough to fully understand what's going on here.

**Comment by kodemaniak** [comment]
And just after I hit the comment button, I realized that it was not quite right was I was writing. The problem was not the Ack, because the sendPuuIfAllowed does not check whether the buffer has capacity. So the problem is actually, that an Ackk pulls also if the buffer is full, which sometimes results in pushing into the buffer when it is full, which in turn results in an exception. That one is swallowed as it seems. If we change sendPullIfAllowed to

````scala
      private def sendPullIfAllowed(): Unit =
        if (dataQueue.remainingCapacity() > 1 && !hasBeenPulled(in)) {
          pullRequestIsSent = true
          pull(in)
        }
````

Your snippet above works flawlessly as far as I can tell.
