### ISSUE TITLE
[akka-http] scalac bug when using members of MediaTypes in a map

### ISSUE THREAD

**Issue by rklaehn** [akka/akka#19418]
The members of `akka.http.scaladsl.model.MediaTypes` have different types. Some are of type `MediaType.WithOpenCharset` while others are of type `MediaType.WithFixedCharset`. Using them in isolation works fine, but when scalac is asked to calculate the LUB of both types, it blows up in the most peculiar way. This can be worked around by declaring the type explicitly.

```
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import akka.http.scaladsl.model.{MediaType, MediaTypes}
import akka.http.scaladsl.model.{MediaType, MediaTypes}

scala> val a = MediaTypes.`application/xml`
a: akka.http.scaladsl.model.MediaType.WithOpenCharset = application/xml

scala> val b = MediaTypes.`application/json`
b: akka.http.scaladsl.model.MediaType.WithFixedCharset = application/json

scala> val boom = Seq(a, b)
error: missing or invalid dependency detected while loading class file 'MediaType.class'.
Could not access type WithFixedCharset in trait akka.http.javadsl.model.MediaType,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'MediaType.class' was compiled against an incompatible version of akka.http.javadsl.model.MediaType.

scala> val works = Seq[MediaType](a, b)
works: Seq[akka.http.scaladsl.model.MediaType] = List(application/xml, application/json)
```

Here is a repo with a tiny reproducer https://github.com/rklaehn/invaliddependency

**Comment by ktoso** [comment]
Thanks for digging this up! Related scalac issue: https://issues.scala-lang.org/browse/SI-9621
Delaying decision if we need a workaround until we get an estimate there

**Comment by ktoso** [comment]
Root of the issue is sadly a long-standing one, we should do a workaround I suggest.
Workaround seems to be: avoiding nested interface and making it a top level one. Yes, sadly not as nice, but at least it'll compile - see details in https://issues.scala-lang.org/browse/SI-9621 root cause: https://issues.scala-lang.org/browse/SI-1409

// FYI @sirthias @jrudolph

**Comment by jrudolph** [comment]
Yes, that's a bummer. Hopefully there aren't much more surprises wrt Java support. Fortunately, moving the types to top-level is a nice enough solution.

**Comment by ktoso** [comment]
I moved the interfaces to scala and can confirm it fixes the problem, we don't need to move them out to top-level! 

I first moved them out, but then noticed we'd have a naming conflict with Multipart so that's not fun. Sub-package for `mediatype.*` also looked crap, so attempted to move them to Scala and we're good :+1:

**Comment by jrudolph** [comment]
Even better :+1:

**Comment by ktoso** [comment]
Applying the same fix to ContentType now

**Comment by rklaehn** [comment]
That's a relief. So SI-9621 (duplicate of SI-1409) only happens in the
context of java interop? I guess the ticket should be updated.

**Comment by ktoso** [comment]
Yes, I'll ping there with this info

**Comment by ktoso** [comment]
Actually, I'll ping there with 2.0.2 released so they have a reproducer of "see, here it works"
