### ISSUE TITLE
add statefulMapConcat operator

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19423]
This will avoid the implementation of many a GraphStage (see [here](https://github.com/akka/akka/pull/19408#issuecomment-171236560) for previous discussion):
~~~scala
FlowOps {
  ...
  def statefulMapConcat[T](f: () => Out => Iterable[T]): Repr[T]
}
~~~

**Comment by drewhk** [comment]
Or implement unfold in terms of a Flow instead of a Source. termination of the unfold round maps to a pull, and the current source unfold maps to Source.single(seed).unfold().

Same can be done with fold, by introducing a terminal signal that expresses that a new batch to be folded is started.

(Sidenote, these were the two basic operations that I came up in the early days of streams design)

**Comment by viktorklang** [comment]
@drewhk I agree. I'd much rather see a generalized unfold.

**Comment by drewhk** [comment]
Btw, when I say "fold" of course I mean a new name since the current fold maps to something already taken and well understood ("foldBatching" or something like that can be the name of the new one).

**Comment by viktorklang** [comment]
@drewhk Why is that needed when you can add a mapConcat(identity) after?

**Comment by drewhk** [comment]
Fold emits only one result once the upstream finished. What I propose can emit before the upstream is finished. Useful for batch/aggregate multiple upstream elements into less downstream elements.

**Comment by viktorklang** [comment]
@drewhk
Wouldn't unfold (+ mapConcat for the Iterable-case) do just fine?

**Comment by drewhk** [comment]
No, that is the opposite, one-to-many.

**Comment by viktorklang** [comment]
@drewhk
If we generalize unfold to a Flow then it is definitely encodable:
unfold(Seq.empty[T])( (state, out) => if (someCondition(out)) Some((out :: state, Nil)) else … ).mapConcat(identity)

**Comment by rkuhn** [comment]
Guys, what you are discussing is different from what this issue is about, let’s please stay on topic. I’m looking for a combinator that can express “stateful map” as well as “hysteresis” and the above is the simplest that I could come up with. Modeling that as a generalized unfold will require multiple operators and even more function literals to be provided; it is of course possible but that is beside the point.

In fact, my proposal can be the efficient basis for a generalized unfold if you want to write one. The reverse is not true.

**Comment by agolubev** [comment]
@rkuhn, I started this and it turned out that mapConcat can just use implementation of statefulMapConcat. Still it's not clear from API where the state is. 

Potentially mapConcat can be implemented in stateful manner in case of using free variable. 

I could not find example of statful operators, perhaps need to implement first one and then rework if some other solution will seem better. Let me know if it make sense to proceed with ```f: () => Out => Iterable[T]``` API

**Comment by drewhk** [comment]
I am also not sure how this should exactly work. @rkuhn it would be helpful if you would sketch a couple of test-cases that demonstrate what should happen here.

**Comment by agolubev** [comment]
@rkuhn, should this ticket be closed?

**Comment by rkuhn** [comment]
Yes, indeed, sorry for the oversight.
