### ISSUE TITLE
add Flow.toActorRef

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19474]
``` scala
def toActorRef[T, U](ref: ActorRef, initialMessage: ActorRef => Any, lastMessage: Try[Done] => Any, bufferSize: Int, strategy: OverflowStrategy): Flow[T, U, NotUsed]
```

The use-case is handling websockets in the chatroom poster use-case: incoming messages should be sent to the given ref, outgoing messages can be sent back by the actor after having received the initial message that contains the stage’s ActorRef.

**Comment by drewhk** [comment]
I am a bit worried about this in this simple form: it completely bypasses backpressure. On the output side there should be some form of dropping or better, failing (clients that cannot keep up are kicked out), on the output side there should be some form of acknowledgement. My fear is that instead of the correct solution, people will just end up with the same actor overload problems as always.

**Comment by rkuhn** [comment]
I have pondered this more thoroughly and have come to two conclusions:

* this function is still useful, even though it must be used with care especially when exposed to potentially malicious users—but we do provide the mechanisms to implement protection
* the websocket use-case should instead be implemented using a proper stream-based eventbus interface that we should build

**Comment by hepin1989** [comment]
why not a props？

**Comment by rkuhn** [comment]
Props is not useful because the actors we want to use here are pre-existing: a chatroom, a persistent entity, etc.

**Comment by hepin1989** [comment]
Play is using props,even using props，I think we could set another ActorRef enclosing in it.

**Comment by ktoso** [comment]
I believe this is solved by Flow.ask that we have introduced.
