### ISSUE TITLE
add stream-based event bus (A.K.A. Hub)

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19478]
The input side should be a fair merge of configurable maximum width, where new sources are submitted e.g. via a Source.queue. The output side should be a dynamic broadcast stage of configurable maximum width that has two inputs—one for elements and one for Sinks—and no outputs. A buffer of configurable depth with `OverflowStrategy.fail` is prepended to each Sink. The bus itself may incorporate a rate limiter to protect against coordinated burst attacks from multiple sources—otherwise these could overload and disconnect all Sinks.

**Comment by drewhk** [comment]
alternative API:
```scala
val hub = Hub[T](parameters)
hub.source.to(Sink.println) // attach a receiver
Source.whatever.runWith(hub.sink) // attach a publisher

hub.close() // Termination must be explicit
```

Every materialization of the Source/Sink of the hub counts as an additional registration. This has the benefit of being lazy (only materialized streams claim resources) and being fusable (since you can reuse the adapters).

I think it would be nice if there would be a possibility to do additional logic inside the hub, so one possibility is to pass it as a Flow:

```scala
val hub = Hub[A, B](parameters, logic: Flow[A, Command[B]])
```

Another possibility is to delegate this to an actor, although the Flow version actually can allow for this via other means.

**Comment by drewhk** [comment]
Btw, in the flow version the rate limiting can be simply done by adding it to the `logic` flow.

**Comment by rkuhn** [comment]
Yes, exactly. And your API proposals make a lot of sense, thanks!

**Comment by drewhk** [comment]
Well, to be fair, @patriknw created similar interface to the PubSub in *elsewhere* (and I have independently created something like this in a sideproject)

**Comment by patriknw** [comment]
:-)

**Comment by rkuhn** [comment]
This might want to get done soonish, possibly with help/input from @jroper.

**Comment by cppexpert** [comment]
Hey guys, I needed something like this recently and implemented it via hack. Perhaps it'll be useful for the  discussion. http://stackoverflow.com/q/38233742/226895

**Comment by ktoso** [comment]
I believe we have it nowadays - it's both the MergeHub and BroadcastHub combined :)
