### ISSUE TITLE
akka-http - Http().singleRequest to https urls, freeze after 4 requests if response is not "used up"

### ISSUE THREAD

**Issue by jarlfr** [akka/akka#19538]
I noticed Http().singleRequest stopped working when using akka-http client to access https urls, and not reading the full response. No more response completed after 4 calls ending up in second case clause.

If I added Entity.toStrict (se below) to process the entity the problem was solved. 

Maybe this is according to spec? It is an nasty bug to get in your code, like below: 
- in the not OK case I ignored the repsonse and it hangs the Http() after a few NotFound responses. 

It seems http is not affected, only https. I'm using "akka-http-experimental_2.11" - "2.0.2"
```scala
    import akka.actor.ActorSystem
    import akka.http.scaladsl.Http
    import akka.http.scaladsl.model.{HttpRequest, HttpResponse, StatusCodes}
    import akka.stream.ActorMaterializer
    import akka.util.ByteString

    import scala.concurrent.Future
    import scala.language.{implicitConversions, postfixOps}


    implicit val system = ActorSystem("actors")

    def call(url: String): Future[String] = {
      implicit val ec = system.dispatcher
      implicit val materializer = ActorMaterializer()(system)

      val response = Http().singleRequest(HttpRequest(uri = url))
      val result = response map {
        _ match {
          case HttpResponse(StatusCodes.OK, headers, entity, _) =>
            val bytes = entity.dataBytes.runFold(ByteString())(_ ++ _)
            "OK"
          case HttpResponse(code, _, entity, _) =>
            //entity.toStrict(100, materializer)   N.B. Not having this, will freeze after 4 calls!
            s"Response code: $code"
          case unknown =>
            s"unkown response: $unknown"
        }
      }
      result.onComplete( println(_) )
      result
    }
```

**Comment by johanandren** [comment]
Hi, 
This is according to spec, albeit not so well documented and we would like to find a way around it. There are more details in the docs in master which will be in the next release. You can read it here:
https://github.com/akka/akka/blob/master/akka-docs/rst/scala/http/client-side/request-level.rst#example

The solution is to run the entity stream with `Sink.ignore` which will ignore the entire body, rather than collecting it into memory which `toStrict` does.

These are two related tickets:
#18716
#18540

**Comment by ktoso** [comment]
There are already tickets to work on this, closing as duplicate.
