### ISSUE TITLE
Akka http does not use Java's default TLS settings by default.

### ISSUE THREAD

**Issue by FrankvanMeeuwen** [akka/akka#19588]
I noticed that by migrating from akka-stream-and-http version 2.0-M2 to 2.0.2, the Java's default TLS settings are not being used anymore by default, for client https connections. It is however noted in the documentation.

A workaround is to explicitely add akka.ssl-config {default: true} in order to use Java's default TLS settings.

**Comment by ktoso** [comment]
This is a feature, not a bug though and has proven successful over a few years of Play WS's success (which provided exactly those settings instead of the default one). 1) It's not the default one by definition, read up on ssl-config 2) it is configurable.

You can also of course set your own custom HttpsContext (in Akka 2.4.2 HttpsConnectionContext) using a set method on the Http extension, so if you want to configure "just use the default" you can do so from code as well. The reason we don't "just use the default" is that the defaults are not as good against a certain number of known problems, see ssl-config documentation for more details.

Having that said – in what case exactly did the current defaults cause you trouble?

**Comment by ktoso** [comment]
Or I misread your comment and it's about "It is however noted in the documentation." by *it* being that the default one is used? Thanks if so, we'll need to fix the docs then :)

**Comment by FrankvanMeeuwen** [comment]
I read in the docs that the java default tls settings are used, which was also the case in 2.0-M2. When migrating i found out this has changed and the default java tls settings are not used anymore. (Which the application relied on)
So indeed, perhaps only the docs have to be updated. ;)

**Comment by ktoso** [comment]
Right, thanks! I misunderstood your initial comment at first :)
Yes, docs must be updated to explain and point to ssl-config more explicitly.

Note: We don't need to document configuring ssl-config, that we should point to it's own docs.

**Comment by ktoso** [comment]
I believe we point to ssl-config in most places now
