### ISSUE TITLE
Secure equals can leak the length information in timing attacks

### ISSUE THREAD

**Issue by orium** [akka/akka#19609]
The current implementation in `EnhancedByteArray#secure_==` leaks information about the lengths, since it compares them first and fails immediatly if they are different.

**Comment by johanandren** [comment]
As noted in the sources here: https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/util/EnhancedByteArray.scala#L19

**Comment by ktoso** [comment]
cc @sirthias

**Comment by jrudolph** [comment]
I think it's a compromise. Otherwise, you would probably need to introduce a maximum password length and add padding to the target secret statically (i.e. not in the checking call path). You can do so even now. 

Do you have another idea how to compare two strings without leaking the length of the target, otherwise?

**Comment by ktoso** [comment]
Please reopen if concrete proposal found
