### ISSUE TITLE
Request for Camel version upgrade to 2.16. 

### ISSUE THREAD

**Issue by jgoggins** [akka/akka#19615]
Project dependency is set to be "2.13.4". 

Camel 2.16 added a new component to support Spring Boot.

**Comment by rkuhn** [comment]
Is that version binary compatible with the one we are currently depending on?

**Comment by ianclegg** [comment]
A version bump to Camel 2.16 (or even 2.17) would helps us out too. The camel team are not averse to making breaking api changes in minor releases - though the refactoring is usually very minor.

**Comment by ktoso** [comment]
Would you be willing to help us out here and propose a pull request with
that change? We won't be able to spend much time on this, but a PR would be
wonderful so we could review and merge it :)

**Comment by ianclegg** [comment]
Sure, it would help us out too... on the off chance I had just started testing Akka 2.4.7 against the latest supported camel builds: 2.15.6, 2.16.3 and 2.17.1.

Building Akka against camel 2.15.6 looks good all the tests passed, the more recent releases 2.16.3 and 2.17.1 build, but we have a failed test. I have no idea what the Akka Camel test coverage is like right now, so I need to look into that too. I'll see what I can turn up in the next few days.

**Comment by ianclegg** [comment]
The failing test was due to a change in the default redeliveryDelay in Camel introduced in 2.16.0. Camel now waits 1 second before attempting to redeliver a message after a failure; since the test has a timeout of 1 second it now fails having not received the redelivered message from camel in time.

```
[info] - must Error passing consumer supports redelivery through route modification *** FAILED *** (1 second, 24 milliseconds)
[info]   java.lang.AssertionError: Failed to get response to message [hello], send to endpoint [direct:failing-once-consumer], within [1 second]
[info]   at akka.camel.TestSupport$CamelTestWrapper.sendTo(TestSupport.scala:42)
[info]   at akka.camel.ConsumerIntegrationTest$$anonfun$1$$anonfun$apply$mcV$sp$10$$anonfun$apply$mcV$sp$11.apply$mcV$sp(ConsumerIntegrationTest.scala:140)
```

Its a trivial change to set the affected tests redeliveryDelay to 0.
`rd.onException(classOf[TestException]).redeliveryDelay(0L).maximumRedeliveries(1).end`

I still need to do some more integration testing though, but Camel 2.17.1 is looking good

**Comment by stanfordbangaba** [comment]
Really need this update like yesterday
