### ISSUE TITLE
LightArrayRevolverScheduler throws exceptions on delays > ~8 months

### ISSUE THREAD

**Issue by technocoreai** [akka/akka#19661]
Akka's default `LightArrayRevolverScheduler` implementation has a delay duration limit that results in `IllegalArgumentException`s when it's asked to schedule something after ~8 months (`Int.MaxValue / 100` seconds with the default configuration). The delay is completely undocumented and implementation dependent, with the default value being somewhat large. This basically means that it'll come out unexpectedly once something inside the app is configured with longer-than-usual timeouts, at which point completely reasonable and simple code starts throwing exceptions. Every single piece of code that touches the scheduler has to include workarounds. A call that should've been a simple one-liner expands into idiotic duration caps (and the cap value is configuration dependent with no way to figure out the cap in runtime), double-checks after the timeout elapses with rescheduling, etc. Even `akka-contrib` library maintainers [have to deal with this](https://github.com/typesafehub/akka-contrib-extra/issues/21), and you'd think that they would remember to use Akka correctly.

If the `LightArrayRevolverScheduler` implementation is completely unable to deal with large delays internally, it should be refactored or at least wrapped into an implementation that caps the delays internally and reschedules task as necessary, instead of making all user code deal with this.

**Comment by rkuhn** [comment]
Thanks for this reminder, even if the text is a bit rude. When we introduce the scheduler we always say that it is meant for short timeouts—any other scheduling purposes are better served by a persistent task management service. Using the latter as the default scheduler will result in a very unhappy user experience because the ActorSystem’s scheduler must serve a very high volume of short-lived tasks and is highly optimized for this purpose. You are right that unfortunately we do not document this design choice sufficiently well.

**Comment by technocoreai** [comment]
Sorry for the rudeness, but I was a bit annoyed at having to handle this yet another time. :(

However, I still think that this should be something handled by Akka core, and the user code shouldn't have to decide whether the (most likely user-configured) timeout is greater than some implementation-dependent arbitrary value or not. It should be easy to implement as well — spawn a dedicated per-system Actor that would handle timeouts greater than whatever you consider acceptable, schedule a tick message at a dedicated interval and pass whatever is inefficient/impossible for LARS to handle to this actor.

If this is impossible for some reason, at least provide a huge warning around the scheduler code that the users should expect breakage at arbitrary timeout durations and consider shipping the task scheduler you speak of in the core package.

**Comment by drewhk** [comment]
At least we should expose a `getHighestSupportedDuration` method so at least user code has a chance to programmatically test against it.

**Comment by rkuhn** [comment]
@technocoreai A persistent task scheduler is a completely orthogonal concern to all current Akka modules. Including one in akka-actor is not only undesirable but impossible (since akka-persistence would be needed, which depends on akka-actor). These abstractions need to be built up in the right order.

A non-persistent best-effort Actor-based approach as you describe might be good enough for some use-cases, it would be interesting to see whether it works as easily as you say—it would be simple enough to propose an addition to akka-contrib for this purpose. But beware of resource leaks as users most likely do not know what they are doing when they schedule a timeout of unknown or unchecked length. “It just works” is never true without restrictions ;-)

@drewhk That is a very good point.

**Comment by technocoreai** [comment]
The current scheduler implementation already supports timeouts of 8 months, so it leaks in exactly the same way as the proposed generic scheduler. The latter just wouldn't break at arbitrary timeout values.

Persistence is completely irrelevant as well, since the default Akka scheduler isn't persistent.

**Comment by rkuhn** [comment]
I bring up persistence because it does not make sense to schedule something that long into the future if you don’t actually care about its execution—and the likelihood that the system will not be restarted within eight months is usually very small.

What I mean to say is that any use-case that runs into this limit is by definition not well-considered. We might also just introduce an arbitrary cut-off at 1 day to make this very clear. If the user does not care how long something takes then the timeout should not be scheduled at all instead of scheduling one with a very large duration.

**Comment by jnmoyne** [comment]
Just a +1 to what technocoreai said, I ran into this and it took me by surprise and besides being annoying that I have to write a workaround it's a bit unfortunate that the max value is not documented/exposed other than in the description of the exception and from what I'm reading here seems implementation dependent. 

Just like him, not asking for or expecting persistence, I take care of that myself and when my application is restarted I re-schedule things as needed, but I can't control or limit the start or end time/date that the user of the application selects...

**Comment by drewhk** [comment]
Still, Akka Scheduler is not meant for such tasks. Its main, and utmost purpose is to be able to handle huge amounts of timeouts and small interval timers that are usually cancelled (i.e. high cancel traffic). It is highly, highly optimized for such tasks. We have no intention to grow it into a general purpose scheduling mechanism. There are libraries out there that handle those cases. In fact, there is no timer implementation that fits all purposes, for example multimedia/game applications (where accuracy matters a lot) use quite different timers, and long running jubs use again, different solutions.

**Comment by jnmoyne** [comment]
I can certainly appreciate that a single implementation could never fit all use cases. I think the confusion here could be cleared by a little bit of clarification in the documentation. In my case I 'solved' my problem by adjusting scheduler.tick-duration to be much larger (1s) than the default of 10ms and yet sufficient resolution for my needs of scheduling things in the future up to a year in advance. 

I think part of the confusion comes from the fact you pass a scala.concurrent.duration.FiniteDuration argument (which in itself can represent a duration up to roughly 292 years), and the documentation doesn't say there's a much lower limit to the duration that you can schedule, and that the limit in question can be adjusted by playing with tick-duration.

So I would say you could solve this issue by improving the docs to explain the above.

**Comment by ktoso** [comment]
> I can certainly appreciate that a single implementation could never fit all use cases. 

Glad we agree on that.


> I think the confusion here could be cleared by a little bit of clarification in the documentation. 

Yes, we can document that (by-design) limitation.

> In my case I 'solved' my problem by adjusting scheduler.tick-duration to be much larger (1s) than the default of 10ms and yet sufficient resolution for my needs of scheduling things in the future up to a year in advance.

This is a very bad idea, please don't do this. You've just impacted all possible internal timeouts and timers of Akka and can cause weird things in the system by putting it to such really high value.

Please use the right tool for the right job or you'll end up hurting the system and yourself in the process. For your job at hand that means this scheduler: https://github.com/enragedginger/akka-quartz-scheduler

Yes, let's document the upper bound of what the timer supports - I'll do that.
Still, don't hack around this by making the tick one second - pretty please ;)

**Comment by jnmoyne** [comment]
Again, if there are limitations to what the value for tick-duration should be, then they should be documented. The only two references to tick-duration I can find in the doc are:

The following sentence:
> The accuracy of the default Scheduler can be modified by the akka.scheduler.tick-duration configuration property.

And the configuration documentation showing the default as being 10ms (also explains again that tick duration influences the resolution of the timers)

And nothing else... So how is someone supposed to know what values are 'good' or 'bad' to use?

I do know about Quartz, but since I'm already using Akka for actors (since it's now the actor library to use in Scala), and since Akka has a scheduler that the doc says you can use to schedule things in the future (the quote below is the first line in the scheduler documentation page).

> Sometimes the need for making things happen in the future arises, and where do you go look then? Look no further than ActorSystem! 

Can you then blame me (or other Akka noobs) for thinking that I could actually use it for scheduling things rather than add yet another dependency to my project??

In my case, I have more than one ActorSystem (maybe you're going to tell me that's a bad idea too :)), one for my processing (where I have left tick-duration alone), and one that I only use only for scheduling those timers (for which I only need second resolution, and which may have things scheduled up to a year in the future), each ActorSystem has it's own configuration . Is there a problem with having an ActorSystem with a tick-duration of 1s that is only used for scheduling things in the future with a resolution of at most 1s? (so far it's working absolutely fine for me).

**Comment by ktoso** [comment]
Let's keep this calm please.

I did a PR improving documentation explaining the limitation you were hit by, please review it if you have constructive feedback.

I do not blame anyone for anything, I do however say that using the Akka scheduler for long-term scheduling is a bad idea, as simple as that. 

If you indeed want to schedule 8 months ahead, you need:
a) need additional infrastructure to restore these things in case of crashes
b) likely are thinking about dates, and not "seconds" anymore in any case
c) a different scheduler impl would really serve better that purpose - quartz can definitely work for one-off events, it is not only for recurring events

I improved the docs however the scheduler impl will not be amended to serve these purposes as augmented by what it is designed for. The assumptions were not documented well, and I hope my PR (see link) improves that aspect of it.

**Comment by jnmoyne** [comment]
I apologize if my posts sounded like I was not calm about this or somehow angry at you or the software, I can assure you that's not the case and I totally understand were you are coming from because I am in the same position as you, except one layer above: my expectation was that the users of my software would only want to schedule things a few days (maybe a few weeks) in the future and as it turns out some want to schedule things up to a year in advance (I think we can also both agree about "those damn users" :))

If there's any emotion, I think it's the same as the original post on this issue: the surprise of running into this undocumented limitation unexpectedly (in production) which would require modifying the code. And I'm sure you can understand everyone is maybe a little bit annoyed when you are being told something wasn't meant to be used like you use it but the doc doesn't say how  you should use it in the first place :).  

Thank you for improving the doc about this, and I will look at the PR and comment on it if needed.

One question remains however: the tick-duration is a parameter that you can adjust in the configuration, so my assumption is that it is OK to adjust this value in some use cases. Since you are saying some particular values (like 1s) are not good to use, could the documentation give some information on what range of values would be acceptable, and on the things that changing this value will affect (right now all it says is that it affects the schedule's resolution)? In my (particular) case, if I adjust this value from the default 10ms just to 20ms (though I really only need second resolution) that's enough to be able to schedule something 1 year from now (since the limit is now 16 months rather than 8). Is it really 'hacking' if all you do is adjust one of the parameters exposed in the configuration? (only trying to avoid my particular problem by adjusting a line in a config file rather than having to re-write code using a new library that is a bit overkill for what I need to do).

**Comment by jnmoyne** [comment]
Just wanted to add I totally understand the salient point here which is that the scheduler is not designed for proper long term scheduling, and that I think you guys are doing a great job of answering and reacting to the questions and comments of any random noob like me! :)
