### ISSUE TITLE
[2.4.1][PersistentFSM] getting StateTimeout for state without timeout after restart

### ISSUE THREAD

**Issue by LoneEngineer** [akka/akka#19688]
Hi,

The behavior, I observed, looks like bug, but I'm not sure at which side (akka or mine). Behavior of StateTimeout for persistent FSM is not exposed in the documentation very clearly (or may be I missed something).

So the case is following: a persistentFSM actor has a short-lived state (with small timeout) and long-lived state (long or infinite timeout). After restart the actor receives StateTimeout in long-lived state (which is unexpected) if before restart actor visited short-lived state.

I tried to get minimal app (scalatest actually) which shows this behavior. It uses inmem db, but I tried with LevelDB as well - nothing changes.

https://github.com/LoneEngineer/akka-persistent-fsm-test

**Comment by patriknw** [comment]
This might be related to https://github.com/akka/akka/issues/18207

Any thoughts, @leonidb ?

**Comment by leonidb** [comment]
@LoneEngineer I've tried to run the tests, they pass if I run them both in one execution. 

If I run them one by one, I get a timeout in the second test, because the tests are configured to run with in memory persistence journal - so the actor is in the ```StateOne``` after recovery, so the timeout is triggered.

How do you execute the tests?

**Comment by LoneEngineer** [comment]
@leonidb Hi, of course I ran them both in one execution (I tried both in sbt console (output below) and under IDEA 15.0.1).

$ sbt test
[info] Loading global plugins from /home/sergei/.sbt/0.13/plugins
[info] Updating {file:/home/sergei/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to akka-test (in build file:/home/sergei/Work/github/akka-persistent-fsm-test/)
[info] Updating {file:/home/sergei/Work/github/akka-persistent-fsm-test/}akka-persistent-fsm-test...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 1 Scala source to /home/sergei/Work/github/akka-persistent-fsm-test/target/scala-2.11/classes...
[info] Compiling 1 Scala source to /home/sergei/Work/github/akka-persistent-fsm-test/target/scala-2.11/test-classes...
[info] TestApp:
Creating actor before reload
[WARN] [04/05/2016 09:20:49.978] [TestApp-akka.actor.default-dispatcher-5] [akka.persistence.Persistence(akka://TestApp)] No default snapshot store configured! To configure a default snapshot-store plugin set the `akka.persistence.snapshot-store.plugin` key. For details see 'reference.conf'
applying EvTwo in DataOne
applying EvOne in DataTwo
applying EvTwo in DataOne
[info] - before reload
Creating actor after reload
applying EvTwo in DataOne
applying EvOne in DataTwo
applying EvTwo in DataOne
[INFO] [04/05/2016 09:20:50.989] [TestApp-akka.actor.default-dispatcher-5] [akka://TestApp/user/$a] Message [akka.persistence.fsm.PersistentFSM$TimeoutMarker] from Actor[akka://TestApp/user/$a#-1737437848] to Actor[akka://TestApp/user/$a#-1737437848] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
got timeout in 2
[INFO] [04/05/2016 09:20:52.032] [TestApp-akka.actor.default-dispatcher-5] [akka://TestApp/user/$b] Message [java.lang.Integer] from Actor[akka://TestApp/system/testActor-1#-872101845] to Actor[akka://TestApp/user/$b#-356474413] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] - after reload *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsg while waiting for 0
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:336)
[info]   at TestApp.expectMsg(TestApp.scala:9)
[info]   at TestApp$$anonfun$2.apply$mcV$sp(TestApp.scala:39)
[info]   at TestApp$$anonfun$2.apply(TestApp.scala:30)
[info]   at TestApp$$anonfun$2.apply(TestApp.scala:30)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] Run completed in 4 seconds, 176 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	TestApp
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 11 s, completed Apr 5, 2016 9:20:53 AM

**Comment by leonidb** [comment]
@LoneEngineer I've reproduced it, thanks.
@patriknw it's not related to #18207, its a different bug.
The problem is caused by calling ```initialize()``` in constructor. It sets the state timeout according to 
```scala
when(StateOne, 1 second) {
```
Then recovery is executed ```TheActor``` state is changed to ```StateTwo``` and ```initialize()``` is called on recovery, in order to activate the timeout. The problem is that the timeout activated by calling ```initialize()``` from the constructor is not cancelled.

I think ```initialize()``` should be made package private in ```PersistentFSMBase``` :
```scala
private[akka] final def initialize()
```
Allowing to call  it in the end of the constructor is incorrect, since it's initialization should be finished after recovery. It will add another small difference between ```akka.actor.FSM``` and ```akka.persistence.fsm.PersistentFSM```.

@patriknw what do you think?

**Comment by LoneEngineer** [comment]
@leonidb, nice to hear that. I'm glad to help, do not hesitate to ask.

PS: We are using PersistentFSM (in pred-prod) so we're interesting to make it better. So currently we switched to named timers to workaround that issue.

**Comment by leonidb** [comment]
@LoneEngineer glad to here you're using PersistentFSM! Would be interesting to get you feedback.
Can you try removing the call to ```initialize()``` from the constructor, to check if it fixes the issue?

**Comment by LoneEngineer** [comment]
@leonidb I will check as soon as I can. Got sick. Sorry.

**Comment by LoneEngineer** [comment]
@leonidb, sorry for delay. Get back to business, and checked suggested fix, but it does not work in another case - I extended and pushed my test to github with failing case (if initialize() is skipped)

**Comment by leonidb** [comment]
@LoneEngineer I've looked at your updated example. If I understand correctly, you mean that the first case passes now, but the second fails, right?
In the second case the FSM shouldn't recover with timeout because:
1. FSM is recovered in state ```StateTwo``` and there is no state timeout in this state
2. ```stay forMax(5 seconds)```  is activated (and persisted) when the actor receives event ```2``` in state ```StateTwo```. However the last received event before the FSM is stopped is ```2```, and it's in state ```StateOne``` when the event is received, so no timeout should be activated on recovery

**Comment by LoneEngineer** [comment]
@leonidb, Oh-ho, my bad, you're right. Fixed 2nd test-case and it works too without calling initialize().
