### ISSUE TITLE
EventSourced must make sure that no two writes overlap, and after restart must wait for write confirmation

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19694]
Journals have a really hard time dealing with multiple outstanding WriteMessage requests from the same actor: since the interface is Future-based it is very easy to just fire them off, which means that they may actually be executed in the wrong order. This leaves holes in the log in case of intervening outages and in general messes up log consistency.

Put another way: it is really hard to get this right in the journal. I doubt that any of them does it right.

There is partial protection against this in EventSourced in the form of the writeInProgress flag, but this flag is not used consistently, and it cannot sensibly be used in preRestart.

Another problem is posed by a WriteMessage right before a restart, which may still be in flight when the postRestart recovery arrives at the journal. In this case the recovering actor may see an incomplete history and subsequently reuse sequence numbers, with catastrophic consequences.

/cc @patriknw

**Comment by sclasen** [comment]
+1

**Comment by patriknw** [comment]
Valid points. Sounds good to improve this. 

In practice I think it works now because when using `persist` there is only one write in-flight and for `persistAll` there will only be a second batch in-flight when the batch buffer is full. This combined with that you read your own writes. That said, I have no objections of making it better.

**Comment by patriknw** [comment]
s/persistAll/persistAll/
