### ISSUE TITLE
What if I need to trim BOM before Unmarshal?

### ISSUE THREAD

**Issue by lucianenache** [akka/akka#19714]
Consider that some programming languages prepend the BOM ([byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark)) at the beginning of a JSON object.

This is good when the client doesn't know the content encoding (eg utf-8, utf16 etc.) but at the same time
it breaks the spray Json unmarshaller where one must strip the BOM bytes manually before unmarshalling.

Currently this is achieved with the following:
```
   val content = for {
      response <- Http().singleRequest(HttpRequest(uri = "someServiceCall"))
      filteredEntity <- response.entity.toStrict(1.second).map(strict => response.withEntity(ContentTypes.`application/json`,strict.data.drop(3)))
      unmarshalledObject <- Unmarshal(filteredEntity).to[MyResponseEntity]
    } yield unmarshalledObject
```

What I was wondering is what it would be necessary to achieve something like this and handle the BOM removal directly in the unmarshaller:
`
Unmarshal(response.entity).to[TrimBOM[MyResponseEntity]]
`

**Comment by drewhk** [comment]
Added to 2.4.x since I am not sure if this can make it into 2.4.2. If someone disagrees, just put it into the milestone you prefer.

**Comment by viktorklang** [comment]
Worth noting: https://stackoverflow.com/questions/4990095/json-specification-and-usage-of-bom-charset-encoding

**Comment by ktoso** [comment]
Summing up our findings here:

The SO answer @viktorklang links to is a bit weird. Just by reading it one may come to the conclusion supporting BOM in our parser would be a good thing. The question/answer reference the RFC however in section 6 (to which they refer) there is zero mention of BOM or similar concepts.

The [RFC4627](https://www.ietf.org/rfc/rfc4627.txt) however states that:

```
3.  Encoding

   JSON text SHALL be encoded in Unicode.  The default encoding is
   UTF-8.

   Since the first two characters of a JSON text will always be ASCII
   characters [RFC0020], it is possible to determine whether an octet
   stream is UTF-8, UTF-16 (BE or LE), or UTF-32 (BE or LE) by looking
   at the pattern of nulls in the first four octets.

           00 00 00 xx  UTF-32BE
           00 xx 00 xx  UTF-16BE
           xx 00 00 00  UTF-32LE
           xx 00 xx 00  UTF-16LE
           xx xx xx xx  UTF-8
```

So since BOM is not an ASCII char as I understand it it would violate this section of the spec. The RFC technically also claims "parsers may accept non-JSON", so we could add a rule for it... but do we really want to. I'd say to leave BOM outside of spray-json and if users have it allow them to trim it.

Another reference: And another jQuery ticket ( https://bugs.jquery.com/ticket/7088 ) which was closed as `won't fix` about BOM breaking their own JSON parser.

// cc @jrudolph @sirthias

**Comment by lucianenache** [comment]
The way I see it, supporting BOM could be a good thing for low level systems that deal with JSON transported as octet streams. 
 
On the other hand, for what akka-http tries to solve, I firmly believe that is more valuable to have a way to easy remove the BOM when the client consuming the JSON service already knows from the headers that the service provides text/json with a given encoding because  for example the `Content-type: application/json; charset=utf-8` is present.

Therefore an out-of-the-box way of dealing with this kind of annoyances would be a good way to prove that akka-http is a high level library that provides the right abstractions to deal with things like the byte order mark.

On top, in the java world there were already issues with the BOM and libraries like apache commons provide a BOMInputStream that removes it from the stream if detected.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
