### ISSUE TITLE
Replace all PushStages usages with GraphStages

### ISSUE THREAD

**Issue by agolubev** [akka/akka#19834]
- [x] Collect in progress by @agolubev
- [x] Drop
- [x] DropWhile in progress by @agolubev
- [x] Filter in progress by @miciek
- [x] LimitWeighted WIP by @agolubev
- [x] Log  in progress by @miciek
- [x] Map  in progress by @miciek
- [x] StartTimed in progress by @vans239,@naferx
- [x] StopTimed in progress by @vans239, @naferx
- [x] TakeWhile in progress by @vans239
- [x] TimedInterval in progress by @vans239, @naferx
- [x] UTF8Encoder WIP by @agolubev
- [x] PrepareForUserHandler WIP by @agolubev
- [x] CheckContentLengthTransformer in progress by @vans239 PR #19913
- [x] Take in progress by @trautonen 
- [x] captureTermination by @leachbj

**Comment by agolubev** [comment]
will take this next if there are no objections.

**Comment by hepin1989** [comment]
I think should make the new GraphStage based PushStage support the supervision strategy:)

**Comment by drewhk** [comment]
I am not sure this is an urgent matter.

**Comment by agolubev** [comment]
@drewhk, I'm not aware about current priorities, but will be more than happy to fix something valuable. So let me know what I should take next.

**Comment by ktoso** [comment]
Marking as triaged, it's something we'd like to do but it's not on the top of the prioriy list.

**Comment by vans239** [comment]
Hi, i'm trying to migrate takeWhile and checkContentLengthTransformer to GraphStage.
I can't find any predefined behavior for SupervisionStrategy. Is there any equivalent of decider for graphStage or it should be solved like in Batch with custom handling?

**Comment by agolubev** [comment]
@vans239 you need to add your own logic to handle SupervisionStrategy like in Batch.

**Comment by miciek** [comment]
@agolubev Can I help with this one?

**Comment by agolubev** [comment]
@miciek go ahead. Just check description about what's already in progress.

**Comment by hepin1989** [comment]
@agolubev you should help track the `WIP` one too:).and how about you add a new abstract GraphStage based Stage,with `SupervisionStrategy` support and then we could easily extends to it?
as @vans239 just said.

**Comment by vans239** [comment]
I'd like to migrate StartTimed, StopTimed, TimedInterval

**Comment by ktoso** [comment]
Thanks, marked it as in progress.

**Comment by miciek** [comment]
I can do `Filter`, `Log` and `Map`.

**Comment by vans239** [comment]
@ktoso, I have small question. It looks like simple solution of migrating StartTimed, StopTimed couldn't be materialized few times, because it depends on timedContext.
I have solutions:
- just ignore it
- make StartTimed as stageWithMaterializedValue, but i don't know what to do with stopTimed

`class StartTimed[T]() extends GraphStageWithMaterializedValue[FlowShape[T, T], TimedFlowContext]` 
- make object Timed private[akka]

**Comment by ktoso** [comment]
Thanks in advance @miciek!

@vans239 sounds to me like both could simply be GraphStageWithMaterializedValue.

`Timed` can not be made internal, it's public API.

**Comment by vans239** [comment]
@ktoso What's right way to pass argument to graph stage during materialization? Is it attributes?

**Comment by ktoso** [comment]
In what specific case? Either directly via parameters; via attributes works but try to avoid that

**Comment by vans239** [comment]
StartTimed produces in moment of materialization timedContext (for graph reusability)
`class StartTimed[T]() extends GraphStageWithMaterializedValue[FlowShape[T, T], TimedFlowContext]`
And then timedContext should be passed to StopTimed. It couldn't be parameter.

**Comment by agolubev** [comment]
@trautonen @miciek @vans239 let me know if you have questions I can help with or any changes I can finish

**Comment by agolubev** [comment]
@vans239 > StartTimed produces in moment of materialization timedContext (for graph reusability)
class StartTimed[T]() extends GraphStageWithMaterializedValue[FlowShape[T, T], TimedFlowContext]
And then timedContext should be passed to StopTimed. It couldn't be parameter.

Actually it can be function that produces factory function that creates context. You can refer to FlowOps   ```def statefulMapConcat[T](f: () ⇒ Out ⇒ immutable.Iterable[T])```. However this will create additional objects for function and for link closure. And  as context has only  two atomic longs as state, I don't think this will be worth it to introduce this complexity.

**Comment by miciek** [comment]
I think we need to talk about dealing with `InterpreterSupervisionSpec` after migrating `Map` to GraphStage. It's not easy to reuse `OneBoundedSetup` when using `withAttributes` to set `supervisionStrategy` (or I just can't figure it out).

In case of `Filter` I moved the only test from `InterpreterSupervisionSpec` to a much nicer `FlowFilterSpec`. See #20269 for details.

@agolubev What do you think? Can I take the same approach with `Map` or do you have a better idea?

**Comment by danxmoran** [comment]
Dropping in to agree with @miciek about the trickiness of `InterpreterSupervisionSpec`, as I'm trying to migrate the spec's internal classes `RestartTestStage` and `OneToManyTestStage` to GraphStages (#20288), and I can't figure out how to make `OneBoundedSetup` work post-migration either.

**Comment by danxmoran** [comment]
@miciek I have an idea of what we could do with `OneBoundedSetup`, if we don't move away from it.  Currently the class builds an [array of empty attributes](https://github.com/akka/akka/blob/65a9e0a0f9372d2e2ecb945c8a9dae129a438f77/akka-stream-tests/src/test/scala/akka/stream/impl/fusing/GraphInterpreterSpecKit.scala#L336) and uses it to build a `GraphAssembly`.  Instead of this, maybe we could have `OneBoundedSetup` take a `Supervision.Decider` as a constructor argument, and then fill the initial attributes array as:
```Scala
val attributes = Array.fill[Attributes](ops.length)(supervisionStrategy(deciderPassedAsArg))
```
WDYT?  I started exploring the idea but found that I was changing code in a *lot* of places unrelated to the `RestartTestStage` and `OneToManyTestStage` I'm supposed to be working on.  Since you're already modifying `Map` (which seems to be everywhere in the tests), it might be more natural for you to try it out on your branch.

Alternatively, if you've pushed your changes onto a WIP branch I could build off of it, and then we can figure out what to do with the commit history once everything is working.

**Comment by patriknw** [comment]
PreStartAndPostStopIdentity, PreStartFailer, PostStopFailer, PushFinishStage fixed in #20348

**Comment by ktoso** [comment]
Timed* stages fixed in https://github.com/akka/akka/issues/20330 and now deprecated.
Feel free to move them to  https://github.com/akka/akka-stream-contrib/issues/2 if anyone wants to :)

**Comment by vans239** [comment]
Please. Mark CheckContentLengthTransformer as fixed. This is PR https://github.com/akka/akka/pull/19913

**Comment by ktoso** [comment]
Thanks for the reminder !

**Comment by agolubev** [comment]
@miciek if you have not started Log and Map I can do them. Let me know.

**Comment by miciek** [comment]
@agolubev Thanks. I have already started and haven't got time to finish. I will see what part of the work you can take over.

**Comment by ktoso** [comment]
Hey there @miciek, would you be able to share your WIP or hand over to @agolubev if you're not actively working on this one? Seems we're almost done with all the stages mentioned in this ticket :-)

**Comment by miciek** [comment]
@ktoso I will try to finish it this week and if it's not possible I will let @agolubev do it :)

**Comment by ktoso** [comment]
Sounds like a plan, thanks guys!

**Comment by miciek** [comment]
`Log` is in review. 

To finish `Map`, I will need #20336 to be merged first, because I am rewriting `OneBoundedSetup`. See [my comment](https://github.com/akka/akka/issues/19834#issuecomment-207950433) and @danxmoran's [one](https://github.com/akka/akka/issues/19834#issuecomment-211182408) for more details.

**Comment by miciek** [comment]
@drewhk I see that `map` is already a `GraphStage` but there's still a `FIXME` in the comments:

`// FIXME: Not final because InterpreterSupervisionSpec. Some better option is needed here`

Can you elaborate and tell me what's not final?

**Comment by johanandren** [comment]
The map graph stage class is not `final` because it is subclassed by `InterpreterSupervisionSpec.ResumingMap`

**Comment by miciek** [comment]
@johanandren @danxmoran Something like this: #21374 ? 😀

**Comment by patriknw** [comment]
Was that the last thing, or what is left?

**Comment by miciek** [comment]
@patriknw I think this was the last thing.

**Comment by ktoso** [comment]
Seems this is complete, thank you everyone for helping!
