### ISSUE TITLE
Document "what Akka HTTP is and what it is not"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19898]
Also known as "it's not as high level as Play and should not be".

Noticed some confusion around it around on the chat recently (about adding very high level features, like managing database connection pools).

**Comment by richard-imaoka** [comment]
Maybe porting  ["What is Spray"](http://spray.io/introduction/what-is-spray/) -> **Philosophy** part to  ["Akka HTTP introduction"](http://doc.akka.io/docs/akka/2.4.2/scala/http/introduction.html)  would be the first step? 

> on the chat recently

By "the chat", did you mean mean [Gitter](https://gitter.im/akka/dev) ? I couldn't find such questions but I will look through again if it was Gitter. Otherwise, was it .[Stack Overflow [Akka]](https://stackoverflow.com/questions/tagged/akka) or [Akka User List](https://groups.google.com/forum/#!forum/akka-user)?

**Comment by ktoso** [comment]
> Maybe porting "What is Spray" -> Philosophy part to "Akka HTTP introduction" would be the first step?


That's a great starting point, yeah

**Comment by ktoso** [comment]
> By "the chat", did you mean mean Gitter ? I couldn't find such questions but I will look through again if it was Gitter. Otherwise, was it .Stack Overflow [Akka] or Akka User List?

Yes, I mean the gitter chat. In general there were quite a few questions on "framework stuff" that we simply won't ever do in Akka (i.e. managing database stuff), thus this issue.

**Comment by richard-imaoka** [comment]
Could I assume this is ok for close, or do we still want to improve the doc further?
Thanks

**Comment by ktoso** [comment]
Agreed, let's close.
