### ISSUE TITLE
merge akka Paths with Uris.

### ISSUE THREAD

**Issue by bblfish** [akka/akka#19909]
There seems to be an overlap in functionality between akka's uri names, and the akka http Uri class.
Both actually do the same thing. Would it not be useful to simplify to one of them? (to http.Uri perhaps)

**Comment by ktoso** [comment]
Hm... "yes and no" :-)

ActorPaths are somewhat leaner and one does not usually modify/inspect them as one does with `Uri` IMO (with the .scheme/.port modifiers and default ports for known protocols etc – this is not really used for ActorPaths and Address).

**Comment by bblfish** [comment]
Both Uris and ActorPaths are immutable, both support relative urls, there are full and partial urls. Perhaps ActorPaths should be a subclass, but at least the interface should be the same.

My use case: I am writing an http server where every URL is mapped to an actor. If these were the same objects there would be no need to convert between those two apis, and it would reduce the things to learn.

**Comment by bblfish** [comment]
Ah minor error. `Uri.Path` does not yet support one important relative Uri functionality. See [Add `Uri::toRelative(base: Uri): Uri` method](https://github.com/akka/akka/issues/15495). But that would be easy to add.

**Comment by johanandren** [comment]
I think it is a typical example of over-abstraction because something seem alike, while they are not really. Providing a common base would introduce tight coupling where we do not want it. 

Uri:s are described by a RFC (2396?) while actor paths are something entirely specific to Akka, making them the same would impose restrictions on actor paths that we do not want.

Duplication is not always bad and abstraction is not always good.
