### ISSUE TITLE
Restartable Flow, Source and Sink

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19950]
Instead of the current scheme which uses attributes to configure internal supervision of a subset of operators, we should implement operators that wrap graphs, re-materializing them upon failure. One possibility could be to use SubFlow syntax:

``` scala
Flow[T]
  .supervisedSection(strategy)
  .doStuff(...)
  .mergeSubstreams
```

Another, possibly more intuitive way is to add

``` scala
def viaSupervised[T](graph: Graph[FlowShape[Out, T]], strategy: Strategy): Repr[T]
```

The strategy should regulate when and how often to restart, including back-pressure (which in contrast to Actor supervision becomes possible because of back-pressure).

**Comment by rkuhn** [comment]
supersedes #15710

**Comment by patriknw** [comment]
one scenario for `flatMapConcat`: https://github.com/akka/akka/issues/20173

**Comment by AlixBa** [comment]
is there any new on this?
I really would love to be able to catch this exception :p

```scala
import akka.actor._
import akka.stream._
import akka.stream.scaladsl.{ Broadcast, Flow, GraphDSL, Sink, Source, ZipWith }

val source = Source(List(1, 2, 3, 4, 5))
  .map(i => { println("before:" + i); i })
  .map[Int](_ => throw new Exception("IntException"))
  .map(i => { println("after:" + i); i })

val sink = Sink.foreach(println)

implicit val as = ActorSystem.create("as")
implicit val am = ActorMaterializer.create(as)

source.runWith(sink)
// Outputs before:1 as expected

val otherSource = Source(List(6, 7, 8, 9, 10))
  .log("1", _.toString)
  .flatMapConcat { i => source }
  .withAttributes(ActorAttributes.supervisionStrategy {
        case e: Exception if e.getMessage == "IntException" ⇒ Supervision.Resume
  })
// Outputs before:1 not as expected
// Expected: before:1, before:1, before:1, before:1, before:1

otherSource.runWith(sink)
```

**Comment by ktoso** [comment]
Really, if there was news they'd be noticed in the ticket 😉 
Have you read the docs on the subject? http://doc.akka.io/docs/akka/2.4.16/scala/stream/stream-error.html#Supervision_Strategies

We're focused on other areas that are more important right now.
If you have specific questions or needs please write them up, just poking tickets like this is not really helpful :)

**Comment by ktoso** [comment]
We also have operators like `recover`, `mapError` and the supervision as I just linked. 
Let us know what specifically you're looking for / missing.

**Comment by valdo404** [comment]
Mmmh, I'm sorry. I was just interested in the current state of that ticket. Let me know how I can help.

**Comment by ktoso** [comment]
I explained a few ways to obtain effects similar to this ticket, what are you missing from those?
I'm not sure supervision as explained in this ticket is how we want it in the end actually.

**Comment by valdo404** [comment]
Basically we are using a ReactiveKafka source which makes deserialisation errors and we would like to detect the error using a supervision strategy which stops the RunnableGraph, but it looks like it does not help. We have been crawling stack overflow for some time and we feel like it is the only place where we can have some information.

**Comment by ktoso** [comment]
I don't quite understand that part, could you explain in detail what's not working (with sample code perhaps?):

> deserialisation errors and we would like to detect the error using a supervision strategy which stops the RunnableGraph,

if a stream gets an error it will stop, what is not functioning as expected for you?

Sounds like this would be best handled as [akka-user discussion](https://groups.google.com/forum/#!forum/akka-user), where you'd explain in detail what you're trying to achieve, what you have, and what is not happening as you expected – then we'd be able to help :-) So far too little information to help out though.

Thanks in advance, cheers

**Comment by atemerev** [comment]
Here are the missing parts:

1) Streams lifecycle. I have e.g. a several hundreds Websocket client streams from akka-http, and I need to monitor them and do something if any of them is disconnected. I can use recoverWith for that (I can make a never-ending source stream with that, auto-reconnecting on errors), or I can use (poorly documented) watchTermination, which allows me to run some code out-of-band on flow termination (only after materialization). Both approaches are poorly compatible with graph DSL. 

2) Backoff supervision / restarts. There is no backoff support for restarting combinators mentioned above.

3) There is no supervision hierarchy, or it is currently undocumented.

3) For any non-trivial task with I/O streams, I need cleanup handler, together with Broadcast/Merge combinators for dynamic attachment/detachment. What is easily achieved with actors (supervision hierarchy, all-for-one / one-for-one restart strategies, backoff, logging) cannot be trivially translated in the terms of streams. Which means that I only can use streams for static, predefined flow graphs, and for dynamic parts I have to go back to actors (which are untyped and ad-hoc connected).

Streams are more powerful than that, and can be used for dynamic flows as well. If this ticket is not going to be implemented, could you at least describe best practices for supervision and logging, for us mere mortals?

**Comment by jroper** [comment]
Hi @atemerev,

We do a lot of the kind of supervision you're looking at in Lagom. Because we're a framework, we've just implemented our own solutions which do involve a lot of boiler plate, but that's ok for us because as a framework it's our job to worry about that stuff so we haven't thought about abstracting it to make it useful beyond our specific use cases. But now I've come across a use case in an end user application where I want to do the same thing, and so that brings me to the discussion on this ticket. So I'll explain what we do in Lagom, but I think what I explain here may also be useful to @ktoso and others as it will firm up some concrete use cases with existing implementations that a solution to this will solve.

One example use case for us is processing CQRS read side streams.  We want to try to ensure these streams are constantly running, so we need to restart in the case of error or termination, and we need backoff when consecutive failures occur.

Going into more detail about our requirements, but also generalising a bit, the first thing we always want to do with these types of streams is perform an asynchronous task. Often this is loading an offset from the database that our stream persists as it processes things so that the stream can be resumed from where it left off, but it would not be limited to that, in a WebSocket example the asynchronous task may be making the initial HTTP request to get the WebSocket flow.  Then, when the stream fails with an error or terminates normally (an error usually means a communication error or a crash on the other side, while normal termination could be the other side being gracefully stopped for upgrade) we want to restart it, but we want to use an exponential backoff, both so that we don't end up in a busy reconnect loop ourselves if the asynchronous task or stream is immediately failing, but also so that we don't exacerbate the reasons why the stream is failing to start.

This is by the way why a recursive recoverWith isn't suitable for our use case, if the other end goes down, we could end up in a tight loop attempting to restart it, consuming excessive resources while doing so.

So, the current solution we have is to use an actor to run the stream.  First the actor performs the asynchronous task(s), piping the result back to itself, and then once we're ready to start the stream, we start it. The stream is not a closed graph, in all our use cases it's a Source, and side effects are done by Flow.mapAsync.  So all that's left to do to run the stream is pass it into a Sink.ignore.  We then use the materialized value of Sink.ignore - which is a future of the streams termination (either akka.Done or a failure), and we pipe it back into our actor.  The whole way along, if our actor ever receives a Status.Failure or Done, it crashes or stops itself.  Here's an example of one of these actors:

https://github.com/lagom/lagom/blob/master/persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideActor.scala

You can see the state transitions as we run the asynchronous tasks (there are two), and you can see the handling of the failures simply being thrown by the actor.  The EnsureActive messages are not relevant here, they are in relation to distributing sharded work across an actor.  So then kicking this all off, we have this:

https://github.com/lagom/lagom/blob/master/persistence/scaladsl/src/main/scala/com/lightbend/lagom/internal/scaladsl/persistence/ReadSideImpl.scala

This wraps the actor in a back off supervisor, which gives us our backoff supervision that we need.  An important thing here is it's not just failures of the stream itself that will result in backoff, but also failures of the asynchronous task that produces the stream (perhaps this is not relevant if you make that asynchronous task part of the stream, eg, create a source from a future of the stream and then flatMapConcat it).  Most of the code above is actually related to the cluster distribution, which is not relevant here, but you can see the backoff supervisor at least.

So, I would say that what we are doing there is the best practice (it was @patriknw's implementation originally), but I also hope that we can find some useful and flexible abstractions here to be able to allow end users to get this with just a few lines of code.

**Comment by jroper** [comment]
Although we don't have a use case for it, I can imagine there may be some scenarios where you want to supervise closed graphs, this would particularly be true if you had a stream coming into your app, and another stream going out, and you wanted to ensure that they are always connected and running.  So a solution should allow supervision of closed graphs, but I don't have any experience of that use case.

**Comment by jroper** [comment]
Hi @atemerev and others,

So I had a look at RecoverWith, and realised it's probably easy for me to implement my own graph stage to do this.  I came up with this:

https://gist.github.com/jroper/f28ecf79f4a4be70e3f499a672d8d6b5

As you can see I've written some basic tests for it (nowhere near comprehensive), it basically works.

I think we can probably use this in Lagom, in our case we'd combine Source.lazily and Source.fromFutureGraph to ensure we can do the asynchronous setup at the start of each source, for example:

```scala
Source.lazily { () =>
  Source.fromFutureGraph {
    for {
      offset <- loadOffset()
    } yield {
      createReadSideProcessorSource(offset)
    }
  }
}.restartWithBackoff(minBackoff, maxBackoff, randomFactor)
```

Any comments as to whether this would meet anyone elses use cases?

@ktoso, @patriknw  etc, does this look like something worth adding to Akka streams?

**Comment by ktoso** [comment]
Thanks James, this looks really good actually - looked at both impl and how to compose things deeply for a while now.

Indeed wrapping is what we wanted to go for, and this way we could even pull off backoff hm.

I'd definitely consider this for inclusion, things to keep in mind would be:
- What about Flow? We have this attempt around btw https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/Retry.scala Flows could benefit from the same as you propose I think; Sinks are less interesting though hm
- I think I'd add the API separately, like we did with CoupledTermination and once it proves to be the exact right thing we'd move it into a method on Source, so for now as `RestartSource.withBackoff(source, ...)` or similar
- It needs to have a way to stop it when we actually do want to stop it, could be a materialized value with `stop()` for example
- Decupling the strategy into a RestartStrategy that has callbacks we can leave out for now perhaps, since we'd only do the backoff one, esp if we do it as separate object
  - we could later investigate how to fit it in with a common RestartStrategy param if we move it to the Source object

Otherwise I think this is very promising and if you could whip up a PR that would be awesome.
Next weeks we're focused on maintenance so review turnaround and helping out on those should be quick. WDYT?

// cc @rkuhn

**Comment by jroper** [comment]
I think sinks are interesting. You have a flow of user interactions, which, in addition to responding to the interactions, you want them logged to a datastore for future analysis. So you broadcast to a sink for that datastore. You don't mind dropping the occasional element when failures do happen, but you do what to ensure that failures don't cause the whole graph to terminate, and that logging continues once a connection to the store can be reestablished, with backoff. In general though sinks aren't as interesting as sources because just restarting a sink doesn't allow you to replay missed messages, if you need delivery guarantees then if the sink fails you usually need the source to restart too. It's only those use cases where message loss is ok and restarting the whole graph is not desirable.

**Comment by jroper** [comment]
Stop is done on the Source by cancelling from downstream, the user can insert their own KillSwitch after the wrapped Source if they need to control it from outside the stream.

I really don't have enough experience with actor supervision to understand the use cases we want to cover with different restart strategies. To me, I just always want to restart, and stop explicitly.

**Comment by jroper** [comment]
And I'll attempt a PR next week (and sorry for the split comments, on my phone, long comments are unwieldy).

**Comment by jroper** [comment]
PR: https://github.com/akka/akka/pull/23367

**Comment by wsargent** [comment]
I can see this helping on https://github.com/playframework/play-scala-websocket-example
