### ISSUE TITLE
Websocket client (or server) disconnect after 6 seconds

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19957]
This sample based on a question on the mailing list: https://gist.github.com/johanandren/858bc3d0cfeaf66ee116

Expected behavior is that the client would keep consuming one tick per second from the server until it is killed but in reality it gets 5 events and then the connection is closed.

On the server side this is logged: 
```
[akka://test/system/IO-TCP/selectors/$a/1] Closing connection due to IO error java.io.IOException: Broken pipe
```

**Comment by johanandren** [comment]
Findings so far: 

The close is on a high level caused by the client `Source` completing, (since the BidiFlows in the ws stack will complete?). If it is kept non-completed by for example a `Source.fromFuture` that never completes things works as expected.

Not sure if this should be fixed or documented, and if fix, very unsure how that would be achieved.

**Comment by rkuhn** [comment]
Further notes:

* the websocket protocol cannot express half-closed connections, just like TLS
* therefore the propagation of cancellation from the Source at either the client or server side needs to be decided deliberately (because propagating it tears down the connection while not doing so risks having the connection hanging until an idle timeout kicks in)
* the typical use-case would probably be that the client sends messages to the server until it is “done”, in which scenario the client should either propagate the completion as a close frame (if no further data are expected back from the server) or it should “know” when the last response from the server has been received and delay propagation of completion until this point (by adding a feedback merge from client’s receive end to client’s send end)

**Comment by jrudolph** [comment]
> the websocket protocol cannot express half-closed connections, just like TLS

I don't think this is strictly correct. A WS close frame only documents that no further frames will be sent. In http://tools.ietf.org/html/rfc6455#section-5.5.1 the spec explicitly mentions the possibility of continuing to send data after having received a close frame:

```
   [...] An
   endpoint MAY delay sending a Close frame until its current message is
   sent (for instance, if the majority of a fragmented message is
   already sent, an endpoint MAY send the remaining fragments before
   sending a Close frame).  However, there is no guarantee that the
   endpoint that has already sent a Close frame will continue to process
   data.
````

Whether that is a good idea is another question. The akka-http implementation currently leaves it to the user handler.

**Comment by jrudolph** [comment]
(See also #19359 regarding the same issue(

**Comment by Mironor** [comment]
As Akka team said in the mailing list, as a temporary fix use `Source.maybe`:

`val outgoing = Source.single(TextMessage("out")).concatMat(Source.maybe)(Keep.right)`

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
