### ISSUE TITLE
Remove exposed case classes in HTTP model

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#19956]
In particular HttpRequest / HttpResponse. If we leave them as is then BC will tie our hands very tightly.

**Comment by ktoso** [comment]
Work in progress here: https://github.com/akka/akka/pull/19959

However, while I agree on the elasticity BC wise we gain, I'm still iffy about changing all classes to this approach... I guess it is true that if we messed up even one header slightly right now we'd be unable to fix it in a binary compatible fashion hm.

I did not see any mature tooling around for "bin compat case-class like things" except the attempt Eugene did for sbt, but that died as well hm.

**Comment by ktoso** [comment]
cc @sirthias @jrudolph

**Comment by jrudolph** [comment]
The question is how much elasticity you need for the HTTP model. I don't think a lot of things had to be changed in the last years (this is different than the settings classes which are naturally more dynamic). It's more a problem of scale that there are so many model classes that a single one may have to be changed at some point. On the other hand, the amount of model classes also means that replacing the existing classes with non-case-classes is a major effort that also introduces a worse maintenance burden because all the previously case-class-provided stuff needs to be kept in sync manually. Then there's also a big "passive cost" in that case classes are so much more easier to read and understand than the manually written alternative. So, I'd vote for keeping case classes for the model understanding that any changes to the parameters would need to be postponed to the next major release.

The last time this topic came up I created https://issues.scala-lang.org/browse/SI-9627. Are there BC-hazard other than the ones I listed? (Not that I would know of a good solution for the ones I already listed there.)

**Comment by ktoso** [comment]
Thanks for chiming in! 
Seems we're in agreement – yesterday I spent the day checking for potential problems and if / where something could potentially change, I did not find enough to warrant making the sweeping change.

Technically `HttpRequest`/`HttpResponse` I thought may have potential for change so I made them so in the linked PR (though arguably perhaps overdoing it). Technically the thing that could cause some changes is HTTP2, which does not affect any headers, and request/response technically also not, but perhaps we want to smuggle information like priority etc into those (again, technically not part of the argument list, so I think we could get away with case class)... I made sure we use the name based extraction in those, so no Option will be allocated when matching on them even though they're not case classes. 

So the only question now is if we think HttpResponse/HttpRequest are worth it being changed in shown in: https://github.com/akka/akka/issues/19959
It's hard to anticipate if they will, but if anywhere I thought that those are most publicly prominent and worth the effort (changing all headers would be overkill)
