### ISSUE TITLE
DOC: 'Use-case and Deployment Scenarios' points to the wrong next chapter

### ISSUE THREAD

**Issue by maseev** [akka/akka#20150]
According to ['Contents'](http://doc.akka.io/docs/akka/2.4.2/java.html), the ['Use-case and Deployment Scenarios'](http://doc.akka.io/docs/akka/2.4.2/intro/deployment-scenarios.html) section is followed by ['Examples of use-cases for Akka'](http://doc.akka.io/docs/akka/2.4.2/intro/use-cases.html). But if you open 'Use-case and Deployment Scenarios' section you'll see that is followed by the 'Streams' chapter which is not correct. The same situation is true for the Scala version of the documentation.

**Comment by mineo** [comment]
It also points to the wrong previous chapter which makes reading the documentation very confusing. I think this is caused by it being used in https://github.com/akka/akka/blob/master/akka-docs/rst/scala/index-utilities.rst in addition to https://raw.githubusercontent.com/akka/akka/master/akka-docs/rst/intro/index-scala.rst.

**Comment by maseev** [comment]
It looks like this problem has already been fixed in the new version of the documentation.
