### ISSUE TITLE
Try genjavadoc "hide private members"

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20185]
https://github.com/typesafehub/genjavadoc/pull/47

**Comment by patriknw** [comment]
and https://github.com/typesafehub/genjavadoc/pull/70

**Comment by Captain1653** [comment]
The issue is really old. Is it still needed? I can try to do it, if you will help me. I have found [some commit in spark](https://github.com/apache/spark/commit/7226e1906796e1755dcb5c66fe8359f91e443afd#diff-6f545c33f2fcc975200bf208c900a600a593ce6b170180f81e2f93b3efb6cb3eR153) . Is it the right direction?

Kind regards

**Comment by johanandren** [comment]
I don't think this was ever done, see this method which is private[akka] for example: https://doc.akka.io/japi/akka/current/akka/AkkaVersion.html#require(java.lang.String,java.lang.String,java.lang.String). Could be worth trying out if you are up to it. Not worth investing a lot of time into though.

**Comment by Captain1653** [comment]
It looks good. Only one public method. I use one setting `"-P:genjavadoc:strictVisibility=true"`

<img width="1440" alt="Снимок экрана 2021-07-01 в 21 17 23" src="https://user-images.githubusercontent.com/4740207/124171947-e3274400-dab1-11eb-8dbe-a8e3ad50a3f1.png">
