### ISSUE TITLE
FAILED: TimeoutDirectivesSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20278]
```
[info] - allow mapping the response *** FAILED *** (1 second, 808 milliseconds)
[info]   503 Service Unavailable did not equal 420 Enhance Your Calm (TimeoutDirectivesSpec.scala:56)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[info]   at akka.http.scaladsl.server.directives.TimeoutDirectivesSpec$$anonfun$2$$anonfun$apply$mcV$sp$3.apply(TimeoutDirectivesSpec.scala:56)
[info]   at akka.http.scaladsl.server.directives.TimeoutDirectivesSpec$$anonfun$2$$anonfun$apply$mcV$sp$3.apply(TimeoutDirectivesSpec.scala:54)
[info]   at akka.http.scaladsl.server.IntegrationRoutingSpec$Checking.$tilde$bang$greater(IntegrationRoutingSpec.scala:44)
[info]   at akka.http.scaladsl.server.directives.TimeoutDirectivesSpec$$anonfun$2.apply$mcV$sp(TimeoutDirectivesSpec.scala:54)
[info]   at akka.http.scaladsl.server.directives.TimeoutDirectivesSpec$$anonfun$2.apply(TimeoutDirectivesSpec.scala:33)
[info]   at akka.http.scaladsl.server.directives.TimeoutDirectivesSpec$$anonfun$2.apply(TimeoutDirectivesSpec.scala:33)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by lolski** [comment]
I would like to help but seems to pass OK when running the test on master (https://github.com/akka/akka/commit/86f54e871940a2e507f3d0ab7252837cafa05e82)

Does the error only happen on Jenkins?

**Comment by ktoso** [comment]
It could be, perhaps the timeouts are too thight?

**Comment by lolski** [comment]
The error (`503 Service Unavailable did not equal 420 Enhance Your Calm`.) sounds more like a bug, as otherwise it would be a future timeout exception though

**Comment by gosubpl** [comment]
There is a race between `withRequestTimeout` and `withRequestTimeoutResponse`:
https://github.com/akka/akka/blob/4acc1cca6a27be0ff80f801de3640f91343dce94/akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/TimeoutDirectivesSpec.scala#L40-L41

This is well documented:
https://github.com/akka/akka/blob/4acc1cca6a27be0ff80f801de3640f91343dce94/akka-http/src/main/scala/akka/http/scaladsl/server/directives/TimeoutDirectives.scala#L76-L77
and I believe this is by design, not a bug. Increasing timeout in L40 would probably help.
