### ISSUE TITLE
Consider introducing HttpApp for Java/Scala to lessen boilerplate

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20299]
We could provide (for java we once did), an `HttpApp` trait that'd work like App that's setting up akka etc and require overriding `def routes: Route`, it would simplify the "hello world" examples for the server side.

Idea comes back after https://twitter.com/li_haoyi/status/719914887309176832

The other points from the discussion are tracked already:
- need better docs (we're working on that on multiple fronts)
- [ ] client in need of high level api (we are painfully aware): https://github.com/akka/akka/issues/16856

**Comment by 2beaucoup** [comment]
The high level APIs mentioned in #16856 seems to be done.

I can imagine that additional shortcuts like `HTTP().get("http://akka.io/")` could become handy. But that would be another alternative way of doing things. Oh my...

**Comment by ktoso** [comment]
Let's take the discussion on client api to the client ticket :)
Here opinions on HttpApp / SecureHttpApp / HttpsApp (naming bikeshed needed to)?

**Comment by johanandren** [comment]
While I definitely agree on that we could improve the getting started experience with the docs (which are more styled like a technical manual than the tutorial style of the python-requests docs referenced)
I don't agree that there should be a way to have all dependencies magically setup for you. 

I think that would be falling for something like a hello world fallacy, not actually useful because so few will be writing an application using akka-http that just makes one or two http calls (BTW in that case bash with curl or wget would be less boilerplate than Python).

I also think that we have chosen explicit self contained samples over minimal, so that users can just copy and paste and run. Maybe we could create some kind of toggle for "full" vs "minimal without boilerplate" for the code samples in akka docs?

**Comment by johanandren** [comment]
Ticket moved to http://github.com/akka/akka-http
 Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
