### ISSUE TITLE
Fix association lookup race by using computeIfAbsent on the ConcurrentHashMap

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20311]

**Comment by drewhk** [comment]
Turns out this is not an issue at all. The only way a race can happen if `send()` is called concurrently, which is impossible from a "same-sender" context for which ordering is defined.

**Comment by drewhk** [comment]
There is another race that exposes Associations through the hash-map which has not been properly initialized, so this ticket is valid but for a slightly different reason.

**Comment by patriknw** [comment]
This is fixed in https://github.com/akka/akka/pull/20657

**Comment by guidomedina** [comment]
I know this is a closed issue and I'm not sure if what I'm going to say is even related.

I have done my share with in-memory caches and recently with Java 8, when calling `computeIfAbsent` it is better to do a pre-scanning for the key 1st because `computeIfAbsent` will preemptively lock the key, I learned that talking with a great mind of caches:
https://github.com/ben-manes/caffeine/wiki/Benchmarks

And I use my mini-version of `computeIfAbsent` with predefined function (also will avoid creating lambdas all over), see `ComputingMap` at https://gist.github.com/guidomedina/b28e0ad0d13a4e5d5f8a4f1beabcb155

**Comment by drewhk** [comment]
The ticket is closed because we no longer need `computeIfAbsent` at all, so this is no longer relevant to us, but thank you for sharing!
