### ISSUE TITLE
Mailbox parameters per actor-instance

### ISSUE THREAD

**Issue by dforsl** [akka/akka#20340]
Would be a nice enhancement for situations where constraints, eg. mailbox capacity, are given independently during runtime and therefore is unable to affect the configuration of an existing actorsystem.

**Comment by patriknw** [comment]
We have early decided that deployment properties should be defined in config, because it can be difficult to serialize such properties.

You can define what mailbox configuration to use in runtime, using `withMailbox` of the `Props` and in that way you can get what you want as long as you have a finite set of mailbox configurations.

Closing as we will not implement this.

**Comment by dforsl** [comment]
Thanks for your reply!

My main interest for this was because we have a situation were eg. the mailbox capacity varies during runtime with different data flows that consists of a set of actors. These data flows that are started and stopped independently within the same JVM, and can have different requirements such as mailbox capacity for backpressure. 

It would have been nice to let all data flows run in a single actor system, but it seems then that we'll have to continue to create one for each as they are started, as the parameters of all data flows parameters aren't known when the actorsystem would have to be created.

Thanks again!
