### ISSUE TITLE
Gaps in stream TCK tests

### ISSUE THREAD

**Issue by agolubev** [akka/akka#20387]
reviewed tck tests and found that some combinators are not covered:
- idleTimeout
- keepAlive
- mergeSorted
- prepend
- alsoTo

Is it relevant?

I looked through only FlowOps. Should Source combinators will be added as well?

**Comment by patriknw** [comment]
Good question. When is it worth adding tck test? If it's "just" an ordinary graph stage I think it's not needed.

**Comment by ktoso** [comment]
For an ordinary GraphStage adding a TCK test won't add much, as it mostly validates "does the graph stage do its thing". I don't think the above (idle timeout etc esp., since they don't really fit what the TCK is testing) need to be covered using it.

Vote to close, however good to keep in mind every time we add a stage.

**Comment by drewhk** [comment]
I vote on closing, too. The reason why the old stages have dedicated TCK tests is because they used something custom that made it necessary to add those tests. Now everything is GraphStage based and it seems to be solid enough.
