### ISSUE TITLE
more MiscMessageSerializer

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20507]
add serialization for the following to MiscMessageSerializer
- `None`
- `Some`
- `Done`
- `NotUsed`

e.g. `None` is sometimes used as messageId in `Identify` messages

**Comment by patriknw** [comment]
cc @fsat

**Comment by patriknw** [comment]
Note that things that don't carry any data can be serialized using only the (short) string manifest, such as `DeletedData` in https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala

**Comment by huntc** [comment]
https://github.com/akka/akka/pull/20801 takes care of `Option`.

**Comment by huntc** [comment]
I've now discovered that Akka Singleton fails when Java serialisation is disabled. It appears that both `java.lang.String` and `akka.dispatch.sysmsg.Watch` are use as a payload to the `Identify` message. To work-around this, I have declared the serialisers as follows:

```
    serialization-bindings {
      "java.io.Serializable"                     = none
      "java.lang.String"                         = "akka-java"
      "akka.dispatch.sysmsg.Watch"               = "akka-java"
    }
```

**Comment by huntc** [comment]
Going forward, perhaps it'd be useful to constrain the types supported by `Identify`. Then, instead of conveying a type manifest, we could use protobuf's `oneof` construct. The way it is now, it feels quite "loose". WDYT?

**Comment by patriknw** [comment]
True that serializer for Watch is missing, but it's not sent via Identify.

Thanks for identifying more.

**Comment by jroper** [comment]
These serializers not being provided has a nasty consequence, as a library author, if you use `akka.Done` but don't provide a serializer for it, you will never see the warning about not using the Java serializers due to [the warning being explicitly turned off for it](https://github.com/akka/akka/blob/05c7975dc0849ae8c8a8b9e4a2034de072096c4c/akka-actor/src/main/scala/akka/serialization/Serialization.scala#L405), and so you think you've defined serializers for all the types you're using, but then one of your users goes and disables the Java serializer and `akka.Done` can't be serialized.

I'm not sure why those types are excluded from the warnings - don't we want to avoid using Java serialization everywhere due to security and performance concerns?  If we haven't provided a serializer for an Akka type, and someone wants to use it, then presumably it's still just as valid (and important) to warn them regardless of whether it's an Akka type or not?

**Comment by ktoso** [comment]
Was introduced around 2015 hm https://github.com/akka/akka/commit/146bb89e23f163838127d122d79657d6c0eb97a4#commitcomment-23093705

I think it may have been "because we have a lot of messages we know are not send over the wire". Weak explanation but seems that was the main driver unless @johanandren remembers a better reason.

I agree it can lead to tricky situations as you described. I'd like to check with Patrik if we can enable the warning globally during the 2.5 lifecycle since we have most misc-serializers hm...

I've put this into our next sprint to look at, and implement missing serializers as well, the lack of serialiser for Done is quite a surprise for me too hm, so we'll check for others too.

**Comment by johanandren** [comment]
I'm afraid I don't remember clearly either.

**Comment by patriknw** [comment]
It has been many iterations. Not sure if this specific was introduced by a customer request related to the serialize msg on send (testing facility). I think we are in a better position in 2.5 to enable the warning again.

Also surprised about Done.

**Comment by alexvaluyskiy** [comment]
@patriknw `reference.conf` contains a serializer-binding for `SmallestMailboxPool` in `MiscMessageSerializer`. But this class does not have a serializer for this type.

And there is no serializer for `ConsistentHashingPool`

**Comment by johanandren** [comment]
@alexvaluyskiy `SmallestMailboxPool` is a mistake from my work on serialisers, it should not be there.

**Comment by alexvaluyskiy** [comment]
Why? Is it possible to remotely deploy it? I never used this router, just curious

**Comment by johanandren** [comment]
It peeks into mailboxes, so it cannot have remote routees (one could perhaps imagine remotely deploying a router that only has local routees on the remote node, but I never heard of that).

**Comment by alexvaluyskiy** [comment]
Ok. What about `ConsistentHashingPool` router?

**Comment by johanandren** [comment]
I think that is just missing, and could be added.

**Comment by jroper** [comment]
`akka.Done` is being addressed in https://github.com/akka/akka/pull/23855.

**Comment by patriknw** [comment]
Strang that this ticket is never closed. Don’t we support all things listed here originally?

**Comment by johanandren** [comment]
All but `NotUsed`, which is tracked in #24599 so let's close this
