### ISSUE TITLE
Issue in HTTP routing - order of OR PathMatchers 

### ISSUE THREAD

**Issue by wlk** [akka/akka#20521]
I stumbled on a problem with defining Or Patch matchers:

This is sample path:
```
    path("" | "abc") {
      get {
        complete {
          OK
        }
      }
    }
```

Turns out this path doesn't match requests to `/abc` URL, only to `/`.

When I reverse order of matchers:
```
    path("abc" | "") {
      get {
        complete {
          OK
        }
      }
    }
```

Both `/abc` and `/` are matched correctly.

This is the repo where I reproduced the problem: https://github.com/wlk/akka-routing-bug/blob/master/src/main/scala/Main.scala

**Comment by johanandren** [comment]
Is it just about empty path? "abc" | "cde" and the other way around works?

**Comment by wlk** [comment]
I have updated example: https://github.com/wlk/akka-routing-bug/blob/master/src/main/scala/Main.scala

Problem exists only when first path matcher is `""`

**Comment by ktoso** [comment]
Would be awesome if you could give it a shot, we're focused on some other areas right now. 
Let me know if you need guidance :)

**Comment by rbudzko** [comment]
``""`` is special, because it  is a neutral element of concatenation operation. Implementations of ``Path`` matches (``Empty``, ``Slash`` and ``Segment``) empty string (empty word) as a valid prefix of any other string (word). Additionally, explicit optimization has been implemented in ``PathMatcher`` in form of ``if (prefix.isEmpty) provide(extractions)`` where provide returns matcher which always matches without consuming anything from path. 

Above produces strange behaviour (described by @wlk) of path where ``""`` is always a last matcher that try to match (it will "break" ``bar`` in ``path("foo" | "" | "bar")`` as well). Although, it makes a lot of sense, because ``path`` docs clearly states that whole path must be consumed/matched. In given scenario ``"foo"`` won't match and ``|`` will try with ``""``  which will match, but path (without evaluating ``""bar""``) is going to fail any way, because reaming path (``""`` consumed nothing - neutral element of concatenation) is not consumed. When we explode given expression it is ``pathPrefix(("foo" | "" | "bar") ~ PathEnd)`` in the end.

Once could argue about behaviour being not obvious. Maybe addition of explicit tests for this case and notes in documentation will help.
