### ISSUE TITLE
Expose mapWithInput in JavaDSL

### ISSUE THREAD

**Issue by kubukoz** [akka/akka#20689]
```scala
// TODO not exposed for Java yet
//  def mapWithInput[C](f: java.util.function.BiFunction[A, B, C]): Unmarshaller[A, C] =
//    asScala.mapWithInput { case (a, b) ⇒ f.apply(a, b) }
//
//  def flatMapWithInput[C](f: java.util.function.BiFunction[A, B, CompletionStage[C]]): Unmarshaller[A, C] =
//    asScala.flatMapWithInput { case (a, b) ⇒ f.apply(a, b).toScala }
```

in https://github.com/akka/akka/blob/acb71ac4e53d536fcba0ffe0fb0a48c09a63b108/akka-http/src/main/scala/akka/http/javadsl/server/Unmarshaller.scala#L139

**Comment by ktoso** [comment]
Wll issue title rather about "expose mapWithInput in JavaDSL" :)

**Comment by kubukoz** [comment]
I wasn't sure about the title :P

**Comment by gosubpl** [comment]
I think actually the title should be: _Unmarshalling doc overhaul for Java_. The reason is that at the moment `akka-docs/rst/java/http/common/unmarshalling.rst` sports the following comment: `TODO rewrite sample for Java` referencing `UnmarshalSpec.scala`. As usual, creating and improving the Java (and Scala!) test/spec should guide us towards suitable Java API shape.

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
