### ISSUE TITLE
Remembering entities is tied to Akka Persistence

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#20858]
Just found out the hard way that `remember-entities = true` is tied to using Akka Persistence, even in the face of `state-store-mode = ddata`. Is this by design or an issue? If by design, please mention that in the docs.

**Comment by patriknw** [comment]
It's documented that remember-entities is using persistence: http://doc.akka.io/docs/akka/2.4.7/scala/cluster-sharding.html#Distributed_Data_Mode

The reason is that there can be many many entities to remember and that can be difficult to implement with ddata given the limitations on how much data ddata can handle.

Also note the other caveat when using remember-entities with ddata mode:

> Using it together with Remember Entities shards will be recreated after rebalancing, however will not be recreated after a clean cluster start as the Sharding Coordinator state is empty after a clean cluster start when using ddata mode.

**Comment by hseeberger** [comment]
Sorry, I was scanning the docs too quickly. Thanks, @patriknw!

**Comment by patriknw** [comment]
np
