### ISSUE TITLE
Provide similar WithServer functionality Play! has

### ISSUE THREAD

**Issue by mhriemers** [akka/akka#20868]
It would be useful if the `akka-http-testkit` had the same [`WithServer`](https://github.com/playframework/playframework/blob/master/framework/src/play-test/src/main/java/play/test/WithServer.java) trait that Play! Framework currently has. I think this should make integration testing a whole lot easier because it doesn't require any nasty SBT tricks to have both the integrations tests and the project itself running at the same time.

**Comment by ktoso** [comment]
If you'd like to contribute this I think we could take it in actually.
We're using code like `      val (_, hostname, port) = TestUtils.temporaryServerHostnameAndPort()` to get an available port in HTTP tests, the trait should be doing the same.

There's a tricky question about supporting ScalaTest (yes we should) and also Specs2, not sure how dependencies would work out then – WDYT?

**Comment by ipsq** [comment]
I think it has to be similar in functionality as the Play! class but with a constructor parameter for a `Flow[HttpRequest, HttpResponse, Any]`. 

As for the dependencies, I can only comment for ScalaTest. I haven't used Specs2 at all. I think that the full `akka-http-core` should be a test-dependency because it includes the client-side HTTP functionality (maybe this would be an argument for separating client-side and server-side as a `akka-http-client` and `akka-http-server` project that both depend on a common `akka-http-core`).

I saw that the `TestUtils` object is defined multiple times in the whole `akka` GitHub repo. Maybe this should also be part of some sort of shared (test) project?

I'm just brainstorming here. I will start writing the wireframe of such an implementation in the next coming days.

**Comment by Captain1653** [comment]
The issue is really old. `akka-http` exists in the different repository, the link to `WebServer` trait is broken. I can't find any trait `WebServer` in Play Framework (abstract class - yes). Is it still needed here?

**Comment by patriknw** [comment]
Obsolete
