### ISSUE TITLE
When seed node restart, can seed node join to the cluster?

### ISSUE THREAD

**Issue by dysonbird** [akka/akka#20871]
The seed node conf like:

``
    	seed-nodes = [
      		"akka.tcp://ClusterTest@172.16.0.7:2550",
      		"akka.tcp://ClusterTest@172.16.1.79:2552"
      		]
``

node two conf like:

``
    	seed-nodes = [
      		"akka.tcp://ClusterTest@172.16.0.7:2550"
      		]

Start seed node first,and then start node two. The cluster work well.

When I shutdown the seed node application with some reason.Later I restart the seed node, but it can't join the cluster.

I can see the seed node restart, if the other nodes of the cluster don't restart, nodes may not in the same cluster of seed node.
 
Forgive my poor english.

**Comment by patriknw** [comment]
If you restart `172.16.0.7:2550` that is configured with
` seed-nodes = [ "akka.tcp://ClusterTest@172.16.0.7:2550", "akka.tcp://ClusterTest@172.16.1.79:2552" ]`
it will try to join to `172.16.1.79:2552`.

Is that what you are trying? Otherwise, please clarify.
I'm pretty sure that this is not a bug in Akka so your question would be better to ask in https://groups.google.com/forum/#!forum/akka-user
