### ISSUE TITLE
[akka-http, 2.4.8] HttpRequest builder: Add withQuery, withFragment, etc

### ISSUE THREAD

**Issue by alias1** [akka/akka#20935]
Using the `HttpRequest` builder I can do the following:

```
HttpRequest().withUri("/foo")
```

But if I then wanted to change the query, or fragment, I can't chain `.withQuery()` or `.withFragment()`

This can be worked around by building the `Uri` object as such:

```
val uri = Uri().withPath(Path("/foo")).withQuery(query).withFragment("foo")
HttpRequest().withUri(uri)
```

But this breaks the flow when chaining.

**Comment by ktoso** [comment]
One should remember that the HTTP *model* is *not* a nice fluent DSL (just happens to be nice enough, since Scala is so nice), so I don't think this is something that we should address here. Instead we should address this by implementing the high-level client features, which would be part of this super-ticket: https://github.com/akka/akka/issues/16856

We currently have the `RequestBuilding` trait which helps in those things, so if anywhere that would be a place to extend this API, and not on the raw HTTP Model itself.

Hope I explained the reasoning here, I'd propose to close this, as we don't want to extend the Model itself, but add builder things around it.

**Comment by alias1** [comment]
That seems reasonable :)
Feel free to close.
Get Outlook for iOS




On Mon, Jul 11, 2016 at 8:17 PM +1000, "Konrad Malawski" <notifications@github.com> wrote:












One should remember that the HTTP model is not a nice fluent DSL (just happens to be nice enough, since Scala is so nice), so I don't think this is something that we should address here. Instead we should address this by implementing the high-level client features, which would be part of this super-ticket: #16856



We currently have the RequestBuilding trait which helps in those things, so if anywhere that would be a place to extend this API, and not on the raw HTTP Model itself.



Hope I explained the reasoning here, I'd propose to close this, as we don't want to extend the Model itself, but add builder things around it.

**Comment by ktoso** [comment]
Thanks, done – and I've added a link to the high-level client ticket to RequestBuilding, so we work on it eventually. 

Thanks for raising issues, keep em coming :)

**Comment by alias1** [comment]
To make me life easier in the meantime, I put together some fluent enhancements. Seems most of the things I want already exist on the Uri class, so it was just a matter of exposing them on request. In case it's useful to anyone else:

```
implicit class EnhancedHttpRequest(val r: HttpRequest) extends AnyVal {

  def withPath(path: String): HttpRequest = {
    withPath(Path(path))
  }

  def withPath(path: Path): HttpRequest = {
    r.copy(uri = r.uri.withPath(path))
  }

  def withQuery(query: Query): HttpRequest = {
    r.copy(uri = r.uri.withQuery(query))
  }

  def withRawQueryString(rawQuery: String): HttpRequest = {
    r.copy(uri = r.uri.withRawQueryString(rawQuery))
  }

  def withoutQuery: HttpRequest = {
    r.copy(uri = r.uri.copy(rawQueryString = None))
  }

  def withFragment(fragment: String): HttpRequest = {
    r.copy(uri = r.uri.withFragment(fragment))
  }

  def withoutFragment: HttpRequest = {
    r.copy(uri = r.uri.copy(fragment = None))
  }
}
```
