### ISSUE TITLE
WebSocket client sample ignores half closed

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20938]
In #20440 we added docs to describe the behavior of websockets when one direction closes (there is also an open ticket about the actual behavior #19957) but there still is a sample which does not mention this and that users may likely see as the first example of websocket client logic:
http://doc.akka.io/docs/akka/2.4.7/scala/http/client-side/websocket-support.html#websocketclientflow

This then makes them spend a week understanding why the socket is closed, we should mention/update the sample. (See for example: https://groups.google.com/d/topic/akka-user/18SExqFsZ5s/discussion )

**Comment by eswenson1** [comment]
The specific example code referenced uses a publicly available echo service that supports web sockets. As such, it only responds to messages sent from the client. Since the example sends only one message, even if we changed the code to use Source.maybe, we would not be providing a "good" example of a client that remains connected to the server and receives any messages sent by that server. To properly illustrate this, we'd need a server example that, say, sends multiple messages over the web socket to the client. If we had such an example, then a good client example (perhaps to take the place of the one referenced here, or perhaps a second example) would connect to that service and display each message as it is received.  

However, complicating this is the fact that if an akka-http web socket server does not receive a message from the client in over 1 minute over the connection, then it will close the connection. A good client example would have to include a periodic heartbeat message to the server to keep the connection open.  

Do we believe it is sufficient to just update the referenced example to use Source.maybe even though, it doesn't really make any difference in the case where we're using echo.websocket.org and a single client-to-server message?

**Comment by johanandren** [comment]
I think a "note"  box with a link to the section which details half-closed would be enough.

**Comment by ktoso** [comment]
Moved to https://github.com/akka/akka-http/issues/1324
