### ISSUE TITLE
Align package structure in HTTP javadsl

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20945]
Some classes in JavaDSL live inside `akka.http.javadsl.server` while they should live outside in `akka.http.javadsl.marshalling / unmarshalling / common`.

All classes exist as far as I see, they just should be moved in the semantically right package before we go stable.

**Comment by Hawstein** [comment]
@ktoso If this issue open to community? will work on it if you don't mind.

**Comment by ktoso** [comment]
Sure, all issues are! :-)
That would be great, thanks a lot @Hawstein!

In general we want to be as 1:1 to ScalaDSL as possible with the packages.
Currently there's some things in javadsl in server that should be in akka.http.javadsl.common (or unmarshalling or mashalling).

Thanks in advance, feel free to ask if you're not sure about something

**Comment by Hawstein** [comment]
OK, will leave my questions in this thread if I am stuck :)

**Comment by Hawstein** [comment]
@ktoso do you think those java files in the `java` package should be aligned too? There are only 4 java file in the akka.http.javadsl.server:

* Coder.java
* ExceptionHandlerBuilder.java
* RegexConverters.java
* StringUnmarshallers.java

maybe better to align the structure for them, otherwise we will have both `akka.http.javadsl.server.StringUnmarshallers` and `akka.http.javadsl.unmarshalling.StringUnmarshaller` packages since the `StringUnmarshallers.java` sits in the former package and StringUnmarshallers.scala in the latter one.
