### ISSUE TITLE
Corresponding coding directives fail to process gzip- and deflate-compressed HTTP/1.0 requests

### ISSUE THREAD

**Issue by levkhomich** [akka/akka#20969]
The problem is that `decodeRequest` and `decodeRequestWith` directives map original request entity to `HttpEntity.Chunked` which, in turn, fails `HttpRequest.copy`'s requirement

```scala
require(
    protocol == HttpProtocols.`HTTP/1.1` || !entity.isInstanceOf[HttpEntity.Chunked],
    "HTTP/1.0 responses must not have a chunked entity")
```

and produces following stack trace:

```
java.lang.IllegalArgumentException: requirement failed: HTTP/1.0 requests must not have a chunked entity
	at scala.Predef$.require(Predef.scala:224)
	at akka.http.scaladsl.model.HttpRequest.<init>(HttpMessage.scala:207)
	at akka.http.scaladsl.model.HttpRequest.copy(HttpMessage.scala:271)
	at akka.http.scaladsl.coding.DataMapper$$anonfun$1.apply(DataMapper.scala:32)
	at akka.http.scaladsl.coding.DataMapper$$anonfun$1.apply(DataMapper.scala:28)
	at akka.http.scaladsl.coding.DataMapper$$anon$3.transformDataBytes(DataMapper.scala:41)
	at akka.http.scaladsl.coding.Decoder$class.decodeData(Decoder.scala:25)
	at akka.http.scaladsl.coding.StreamDecoder$$anon$1.decodeData(Decoder.scala:44)
	at akka.http.scaladsl.coding.Decoder$class.decode(Decoder.scala:22)
	at akka.http.scaladsl.coding.StreamDecoder$$anon$1.decode(Decoder.scala:44)
	at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$applyDecoder$1$1$$anonfun$apply$2.apply(CodingDirectives.scala:86)
	at akka.http.scaladsl.server.directives.CodingDirectives$$anonfun$applyDecoder$1$1$$anonfun$apply$2.apply(CodingDirectives.scala:85)
```

Steps to reproduce. Test case:
```scala
  val echoRequestContent: Route = { ctx ⇒ ctx.complete(ctx.request.entity.dataBytes.utf8String) }
  lazy val helloGzipped = compress("Hello", Gzip)
  def compress(input: String, encoder: Encoder): ByteString = {
    val compressor = encoder.newCompressor
    compressor.compressAndFlush(ByteString(input)) ++ compressor.finish()
  }

  "decode HTTP/1.0 request with 'gzip' encoding" in {
    HttpRequest(POST, Uri("/"), entity = HttpEntity(helloGzipped), protocol = `HTTP/1.0`) ~> `Content-Encoding`(gzip) ~> {
      decodeRequestWith(Gzip) { echoRequestContent }
    } ~> check { responseAs[String] shouldEqual "Hello" }
  }
```

**Comment by johanandren** [comment]
I cannot see that line 32 of `DataMapper` in the exception actually contains such a copy, which version of Akka is it you are using, is the error still there with 2.4.8?

**Comment by levkhomich** [comment]
`DataMapper.mapRequest` -- `HttpRequest.withEntity` -- `HttpRequest.copy` calls are still there:
https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/scaladsl/coding/DataMapper.scala#L27

**Comment by levkhomich** [comment]
Btw, test case I provided fails on master branch.

**Comment by johanandren** [comment]
Hmm. So as far as I understand it the problem boils down to `{Default|Strict}.transformDataBytes` changing it to chunked. This is passed into the `Decoder`/`DataMapper` infra on L87 in `CodingDirectives`. 

I find this a bit weird since chunked means something pretty specific in terms of http entities, and transforming the data stream is not the same thing as making it chunked. @ktoso you have any input on this?

**Comment by jrudolph** [comment]
I randomly stumbled over this... The reason why `transformDataBytes` usually returns chunked entities is because chunked is the best choice for a streamed entity for which the size is not known beforehand. 

Other choices are:
 * `HttpEntity.CloseDelimited` which only works for responses (but also for HTTP/1.0)
 * buffering the whole entity and create an `HttpEntity.Strict` (works also for HTTP/1.0 requests)
 * run the processing twice, once to measure the length, and once for streaming the actual data and then create an `HttpEntity.Default` with the size calculated in the first run. This only works if the actual transformation can be deterministically repeated.

We could default to `CloseDelimited` for HTTP/1.0 responses and improve the error message if someone tries to use `transformDataBytes` on HTTP/1.0 requests?

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
