### ISSUE TITLE
Akka cluster JMX command line tool appears to be unmaintained

### ISSUE THREAD

**Issue by carlpulley** [akka/akka#21172]
Not too sure what you want to do about this, but during Akka cluster testing, I was using the Akka cluster command line JMX tool. As such, I was observing my tests failing about 50% of the time due to the JMX command line tool failing to process JMX packets returned from the Akka cluster.

On investigating this issue further, I've noticed that https://github.com/akka/akka/blob/master/akka-kernel/src/main/dist/bin/jmxsh-R5.jar is not only old (IIRC, it was last updated in 2010) but is now part of an unmaintained Google code repository. Looking at the class files contained within this jar library, it looks like the code was built for JDK 1.6 and uses JMX API 1.2? Where as I'm expecting the Akka cluster node to be using JMX API 1.4?

No idea if this API version difference accounts for my failing test scenarios, but clearly basing a cluster tool on an unmaintained and (probably?) defunct library doesn't sound like a winning strategy going forward. Perhaps this is something that needs to be handled at some point in the future? At the very least, I'd suggest that Akka documentation is updated to highlight this?

**Comment by drewhk** [comment]
Thank you for raising this. I personally think that we need something more flexible eventually than the current approach, but anyway, if something does not work then it needs to be fixed.

**Comment by patriknw** [comment]
I have always wanted a HTTP based cluster management interface (in addition to JMX). The command line tool would then be curl (or similar). Now when we have akka-http that would be easy to add without introducing external dependencies. That would be an excellent task for community to pick up.

**Comment by drewhk** [comment]
Yeah, I was thinking in a built-in http Route for example, that someone can slap into his web API if he needs it (properly securing it of course!).

**Comment by hveiga** [comment]
I would not mind taking a look to this and see if I can create a PR for it. Is there any place where I could see the list of operations the tool was supporting?

**Comment by patriknw** [comment]
Thanks, @hveiga 
Here is the command line script: https://github.com/akka/akka/blob/master/akka-kernel/src/main/dist/bin/akka-cluster
Here is the MBean: https://github.com/akka/akka/blob/master/akka-cluster/src/main/scala/akka/cluster/ClusterJmx.scala

**Comment by hveiga** [comment]
I have been reviewing this and and I came up with this possible endpoints and Methods:

(join
 - HTTP Method: PUT
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/join/{node-url}
(leave
 - HTTP Method: PUT
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/leave/{node-url}
(down
 - HTTP Method: PUT
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/down/{node-url}
(member-status
 - HTTP Method: GET
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/member-status/{node-url}
(cluster-status
 - HTTP Method: GET
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/member-status/{node-url}
(members
 - HTTP Method: GET
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/member-status/{node-url}
(leader
 - HTTP Method: GET
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/member-status/{node-url}
(is-singleton
 - HTTP Method: GET
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/member-status/{node-url}
(is-available
 - HTTP Method: GET
 - HTTP Endpoint: http://(hostname:port)/akka-cluster/member-status/{node-url}

I am unsure if {node-url} can be part of the URL since it's of the form: akka.tcp://actor-system-name@hostname:port'. Also, I am not sure if the first three should be PUT or POST. Suggestions and feedback are appreciated 👍

**Comment by drewhk** [comment]
Hmm, shouldn't the pattern be http://(hostname:port)/akka-cluster/{node-url}/member-status instead, i.e. the node url first, then the command/request?

**Comment by drewhk** [comment]
And probably http://(hostname:port)/akka-cluster/ listing all known members

**Comment by patriknw** [comment]
I did something around this a year ago or so and then I came up with the following:

GET /members - full status of all members, including reachability and such, see json below
GET /members/$address - full status for one specific member
POST /members - join, the address of the node to join is in the posted form data
DELETE /members/$address - leave
PUT /members/$address - down, the actual down operation is in the posted form data (other operations could be added in future)

The member status json looked something like this:
```json
  {
      "selfNode": "${cluster.selfAddress}",
      "members": [
          {
              "node": "akka.tcp://ClusterSystem@host1:2552",
              "nodeUid": "1234",
              "status": "Up",
              "roles": []
          },
          {
              "node": "akka.tcp://ClusterSystem@host2:2552",
              "nodeUid": "5678",
              "status": "Up",
              "roles": []
          }
      ],
      "unreachable": [
          {
              "node": "akka.tcp://ClusterSystem@host2:2552",
              "observedBy": [
                  "akka.tcp://ClusterSystem@host1:2552"
              ]
          }
      ]
  }
```

`nodeUid` is `cluster.selfUniqueAddress.uid`

**Comment by hveiga** [comment]
@patriknw I like your approach of using DELETE, PUT and POST instead of having different endpoints. I will put some code together as an initial version and then we can modify from there. Thanks for the feedback!

**Comment by hveiga** [comment]
@patriknw should this be part of cluster-tools or a different module? I am asking because if I do it inside cluster-tools, cluster-tools will need to bring the akka-http dependency and I am not sure if that is ideal. Please suggest.

**Comment by patriknw** [comment]
@hveiga Sorry for delay. That is an interesting question. Originally I was thinking that we could include this in cluster-tools, or perhaps even in cluster, but now we have moved akka-http to a separate repository https://github.com/akka/akka-http, see [motivation](https://github.com/akka/akka-meta/issues/27).

That means that placing it anywhere in akka/akka would introduce cycles in the dependencies, which are not nice.

Placing it in akka-http is not desired, since akka-http should not have dependency to cluster.

Then the only remaining option is to place it in a third repository, and the only decent place I can think of now is to create a sub-project in https://github.com/akka/akka-stream-contrib

We will restructure that repository later, with a separate Alpakka repository and such, but for now I think that can be a good initial place for this utility.

WDYT?

**Comment by hveiga** [comment]
@patriknw No worries, I have also been on vacation. I see the cycle dependencies issue, I will see how easy is for me to add it to akka-stream-contrib. I have done good progress with the code. I want to push the initial version in the coming weeks to get some feedback.

**Comment by patriknw** [comment]
sounds good, looking forward to review it

**Comment by ktoso** [comment]
Replaced with https://github.com/akka/akka/pull/21981 :)
