### ISSUE TITLE
Stable PersistentFSM

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21190]
We should decide when / if to call it stable.
It's the "odd one out", in the otherwise stable module.

**Comment by ktoso** [comment]
cc @leonidb

**Comment by leonidb** [comment]
@ktoso thanks for mentioning me, I've meant to ask for quite some time if there are any additional development tasks left to be done.

**Comment by ktoso** [comment]
AFAIR you're in prod with it and happy with what it has currently right?
We'll go over it tomorrow during our team meeting then and see if/what's missing.

**Comment by leonidb** [comment]
Well, we used to have the original implementation in production and it was stable and useful. Since then, however, the project was canceled and we haven't used the implementation that ended up included in 2.4. 
But judging by the opened issues and occasional questions in akka user group, it has users. Maybe it's worth to ask the community via akka-user group or some other channel?

**Comment by patriknw** [comment]
After discussion we have concluded that it will be made stable in 2.5 (one full cycle as usual), unless there is a customer demand to do it earlier.

**Comment by leonidb** [comment]
Great, if it needs more work, I'd love to help, as usual
