### ISSUE TITLE
Failures handled in recoverWithRetries bubble up to the supervision strategies

### ISSUE THREAD

**Issue by iravid** [akka/akka#21192]
In a somewhat related manner to #21191, the following example demonstrates that errors that are handled in `recoverWithRetries` recovery function still bubble up to the stream's supervision strategy.

```scala
val graphDecider: Supervision.Decider = { e =>
  println(s"Caught ${ e } in graphDecider; stopping")
  Supervision.Stop
}

val matDecider: Supervision.Decider = { e =>
  println(s"Caught ${ e } in matDecider; stopping")
  Supervision.Stop
}

implicit val mat =
      ActorMaterializer(ActorMaterializerSettings(system).withSupervisionStrategy(matDecider))
val n = new AtomicLong(3)

val stream = Source
  .single("hello")
  .map(_ => throw new Exception("first"))
  .recoverWithRetries(-1, {
    case e =>
      val current = n.decrementAndGet()

      if (current == 0) Source.single("hello")
      else Source.single("hello").map(_ => throw new Exception(s"ex ${ current }"))
  })
  .to(Sink.foreach(println))
  .withAttributes(ActorAttributes.supervisionStrategy(graphDecider))

stream.run()
```

This example outputs:
```
[info] Caught java.lang.Exception: first in graphDecider; stopping
[info] Caught java.lang.Exception: ex 2 in matDecider; stopping
[info] Caught java.lang.Exception: ex 1 in matDecider; stopping
[info] hello
```
... which demonstrates another inconsistency: the errors from the `recoverWithRetries` stage skip the graph's supervision strategy and go straight to the materializer's strategy.

**Comment by drewhk** [comment]
I need to look into these in detail, but there might be a misunderstanding here. The currently supported supervision scheme is *very* very limiting. It only applies to a *single* stage (if you add the attribute to a longer chain it will be just individually applied to the stages), so there is no such thing as escalating to a parent decider. Even worse, only a few stages support supervision, the rest simply ignores it.

**Comment by drewhk** [comment]
didn't meant to close though, misclicked

**Comment by iravid** [comment]
Thanks for answer Endre - I've since read the implementation and reached the same conclusion myself, so I'd say that the fact that the errors reach the decider is not a bug but a behavior according to the design.

It might be wise to add a note to the docs mentioning that each stage in a graph applies the stream deciders independently of other stages. I'd be happy to send a PR if you think  that's a correct description of the behavior.

Regarding the fact that the error skips the stream decider and reaches the materializer's decider, seems like the same thing in the other issue I reported as `recoverWithRetries` uses subsources.

Is there a recommended strategy of doing something similar to hierarchical supervision with Akka Streams?

I'd

**Comment by drewhk** [comment]
> It might be wise to add a note to the docs mentioning that each stage in a graph applies the stream deciders independently of other stages. I'd be happy to send a PR if you think that's a correct description of the behavior.

A PR would be very helpful, thanks!

> Is there a recommended strategy of doing something similar to hierarchical supervision with Akka Streams?

Unfortunately this is tricky to implement. I would say, from the outside it is likely not possible at all, as it would need support from the internals. We do have plans for implementing "proper" supervision though, that would be able to restart graph modules just like you would expect.

**Comment by atemerev** [comment]
@drewhk Is "proper" supervision for akka-streams still in plans? Without it, it is really hard to write any dynamic restartable flows with it (like Websocket servers and clients)

**Comment by ktoso** [comment]
Firstly: I don't think that's entirely true. Existing supervision indeed only works when stages "support it". One has to notice that it's not as simple as it may seem from a high level perspective, since there's buffers involved between stages so what would "restart a section", or what _should_ it _really_ mean etc.

However, there's many ways to add restarting or other behaviours. 

Including, but not limited to:
- Retry - https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/Retry.scala 
- recoverWith http://doc.akka.io/docs/akka/2.5.1/scala/stream/stages-overview.html#recoverWith 
- recoverWithRetries http://doc.akka.io/docs/akka/2.5.1/scala/stream/stages-overview.html#recoverWithRetries
- mapError http://doc.akka.io/docs/akka/2.5.1/scala/stream/stages-overview.html#mapError
- and more stages, such as watchTermination, monitor etc.
- the existing supervision when it's enough
- or hosting within Actors and reacting to a termination with how you want.

Do bear in mind that Akka was, is and remains a toolkit. The tools are there, with killswitches, a spec how failure is propagated (reactive streams, which will be in JDK9)

Would we want to improve the current supervision scheme? 
Yes, we'd like to. Are we right now going to work on it? No, we're focused on other areas right now that are more pressing.


**What would be helpful now:** What I think would be the best next step here, is to actually *come up with patterns* - be it as blogs, or writeups in issues or PRs that pre-package behaviour such as the `Retry` stage did, and once we have the real use cases we can think about it again, because a *generic* "supervision" is very hard (note the generic part in that phrase, specialized ones are simple), and *very* likely not what you'd actually want (it would do unexpected surprising things, we experimented with some restarting schemes).

I do agree though that all those patterns should be then collected and put to: http://doc.akka.io/docs/akka/2.5.1/scala/stream/stream-error.html We're right now working on a new docs and website page, so once that's done we'll focus on such content.

Hope this answers the question about status, next steps, and how you can help :-)
