### ISSUE TITLE
Feature request: Let BackoffSupervisor reply to messages when its child is stopped

### ISSUE THREAD

**Issue by chris-martin** [akka/akka#21213]
When a `BackoffSupervisor`'s child is stopped, its messages get forwarded to `deadLetters`. It would be useful if the supervisor could optionally perform some simple action instead, such as replying to the sender.

Example code sketch:

``` scala
case object TheSystemIsDown

val ref = context.actorOf(BackoffSupervisor.props(Backoff.onFailure(
  childProps = databaseProps,
  childName = "database",
  minBackoff = 1.seconds,
  maxBackoff = 5.seconds,
  randomFactor = 0.2,
  replyWhileStopped = Some(TheSystemIsDown)
  // ^ replyWhileStopped is the new parameter being proposed here.
  // It's an Option, so it can default to None, resulting in the
  // same behavior we currently have.
)))

val future = ref.ask(query).map {
  case r: QueryResult => ??? /* Hooray */
  case TheSystemIsDown => ??? /* The database is down :( */
}
```

In this example, our `BackoffSupervisor` wraps a database, and we use the `ask` pattern to make queries. While the database actor is crashed, the supervisor replies to all messages with `TheSystemIsDown` so that the client can know immediately that the database is down instead of having to wait on the `Future` returned by `ask` to time out.

It looks like a pretty small change, and I'd be happy to make a PR if anyone thinks this is a good idea.

**Comment by patriknw** [comment]
Sounds like a good suggestion. Contribution is welcome.

**Comment by richard-imaoka** [comment]
Hi @chris-martin sorry to jump in. I found this is interesting - so could you let me know if you are still working on a PR, or do you mind if I make a PR in case you are busy with something else?

**Comment by chris-martin** [comment]
@richard-imaoka If I recall correctly, I got had this implemented but just got blocked by #21375 when I tried to test it.

https://github.com/chris-martin/akka/commit/47fae245dc2f0f96a8328c157d3a7f8709ab6e8f

Fine by me if you want to take it over.

**Comment by richard-imaoka** [comment]
Thanks @chris-martin 
Let me see what I get from running the tests which you got failure in 21375.

**Comment by richard-imaoka** [comment]
Hi @chris-martin, I saw #21375 was resolved.

I added a [new commit](https://github.com/richard-imaoka/akka/commit/4c255971b2f0fac1db91c21051ebf84d4fb33097) on top of yours. ([combined diff](https://github.com/richard-imaoka/akka/compare/d1d4985950d96e0e914803dbd875087a36bed8cb...richard-imaoka:4c255971b2f0fac1db91c21051ebf84d4fb33097)), but since you already did most of the work, would you like to submit a PR?

One question though:
Instead of users specifying what's sent back in the `receiveWhileStopped` parameter (i.e. do users always want to specify it?), 
we probably want to make `receiveWhileStopped` as `Boolean` and provide the standard case class in `BackoffSupervisor` companion object, which is sent back to sender? (users don't need to think about what to send back)

**Comment by richard-imaoka** [comment]
@chris-martin sorry to ping you again but would you be able to have a look at [my commit](https://github.com/richard-imaoka/akka/commit/4c255971b2f0fac1db91c21051ebf84d4fb33097) and if it looks good, can you raise a PR?

**Comment by chris-martin** [comment]
Hey sorry, I'll try to look at this soon.

**Comment by richard-imaoka** [comment]
If you are busy, would you mind if I raise a pull request? I will retain your original commit (not sure if that makes you as the author after squash merge though ...)

**Comment by chris-martin** [comment]
Of course, go for it, and don't even worry about retaining the authorship if it's any trouble.

**Comment by Chuwiey** [comment]
please mark as "in progress" due to PR #22051

**Comment by ktoso** [comment]
Thanks!
