### ISSUE TITLE
Rethink compression table ownership

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21210]
Esp. considering if there will be multiple lanes for sending/receiving messages.

**Comment by patriknw** [comment]
I have a rough sketch of what I think it should look like.

Outbound:
* it should be possible to make the `OutboundCompressions` immutable and thereby completely safe to use from multiple `Encoder` instances
* the `OutboundCompressions` should not be shared via the `AssociationState`, instead it should be sent to the `Encoder` stages with async callback when a new advertisement is received, no need to reference current `OutboundCompressions` in other place than in the `Encoder` stages themselves
* when outbound stream is started or restarted it can start out without compression, until next advertisement is received

Inbound:
* continue to use only one `Decoder` stage, which works in same way as today, apart from that deserialization of the payload is not done here
* the `Decoder` already owns the `InboundCompressions`, but to keep state when restarted it is created by `ArteryTransport` and passed in constructor, as today
* deserialization of payload in separate stage, so that it can be done after fan-out, parsed header values from the `Decoder` can be passed in the mutable `EnvelopeBuffer`

**Comment by ktoso** [comment]
Yes I think that's a good refactoring. Key feature is to keep the tables immutable once received thus they don't care about concurrent access. I like the owned-by-Encoder as well 👍 

Inbound side is non-controversial, LGTM as well.
