### ISSUE TITLE
improve latency when inbound-lanes > 1

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21365]
See performance test results in https://github.com/akka/akka/pull/21328#issuecomment-244606206

Suspect is that BroadcastHub degenerates to wakeups and actor messaging instead of going through the publish buffer. We need a proper "routeHub" there.

**Comment by jrudolph** [comment]
A first analysis of what's going on:

The `MaxThroughputSpec` wasn't really testing the right thing because send batches were too long, so that there was no parallelism on the receiver side because all the incoming messages of one batch (with a single target ActorRef) went to the same lane. Changing the sender to send messages of a batch to different target actors shows that parallel lanes can have a positive impact on throughput. In general, whether parallel lanes will give better throughput will always depend on how much work deserialization is compared to other work done in the pipeline and the cost of doing the asynchronous dispatch (see below).

As @patriknw measured in https://github.com/akka/akka/pull/21328#issuecomment-244606206, enabling parallel lanes comes with a huge penalty on latency as observed in the `LatencySpec`. Mean RTT goes up from < 100µs to > 1ms *per message*. 

I tried to understand why this happens, by gathering additional metrics:
 * transfer time, by adding a nanoTime timestamp into the envelope, measuring the time from envelope serialization to envelope deserialization
 * async boundary time, by measuring the time from envelope deserialization to the start of message deserialization

I ran all tests by removing the optimized stream setup for `inboundLanes == 1` in `runInboundOrdinaryMessagesStream`, so that I would still use only one lane but including the broadcast hub.

Here's a plot with histograms for
 * total RTT
 * transfer time (called network here)
 * async boundary time

at idle-cpu-level 7.

![histogram-rtt-vs-async-vs-network](https://cloud.githubusercontent.com/assets/9868/21255466/5a963a12-c36c-11e6-9083-5f9e6267ed36.png)

(In case you wonder, 2 * (transfer + network) should add up to roughly RTT but I don't think that works for a percentile plot, when looking at the means, it is the case.)

What you see is that all the latency is actually spent in the async boundary.

Seeing that `AeronSource.subscriberLoop` being prominent in the profile I played around with idle-cpu-level setting and found out that it makes quite a difference. Here the same plot with idle-cpu-level=1:

![histogram-rtt-vs-async-vs-network-icl-1](https://cloud.githubusercontent.com/assets/9868/21255599/2d9e16c8-c36d-11e6-9394-ca061332ea6d.png)

Now, the async boundary is fast but network latency rises so that the final RTT isn't much better as before.

I then took a series of measurements with different idle-cpu-level settings:

![histogram-rtt-multi-icl](https://cloud.githubusercontent.com/assets/9868/21255775/43e0943c-c36e-11e6-9efa-f9306aa1e1d6.png)

which would point to `idle-cpu-level = 2` being a very good compromise between network and async boundary latency. (For comparison, the diagram also contains the no-async variant which uses the optimized stream setup for `inboundLanes = 1`.)

So far, the experimental results. My theory why idle-cpu-level has such a dramatic influence on the performance of the async boundary is this:

Setting a high `idle-cpu-level` means that the AeronSource spins directly in the GraphStage. That means that it starves out any other work that is currently waiting to be done on the actor of this GraphInterpreter. (All the three queues of an ActorGraphInterpreter will not make any progress during this time) Spinning in the GraphStage seems much worse than spinning on a dedicated thread: on a dedicated thread, spinning will 1) eat idle cpu time on one core and 2) steal some CPU time from other runnable threads but only until it is preempted by the CPU to ensure fairness. Spinning in the GraphStage, however, means that all the work that can only be done by this actor must wait until the spin has completed.

So, I will continue to experiment with changing the spinning in GraphStage (independently of the TaskRunner spinning) to see where that gets us.

**Comment by jrudolph** [comment]
I had a quick try disabling spinning in AeronSource completely and that seems to improve latencies without having a significant impact on the optimized `inboundLanes = 1` case. Will check the impact on the MaxThroughputSpec next week.

**Comment by patriknw** [comment]
Excellent analysis, @jrudolph . Very interesting.
The amount of spinning in the AeronSource is not based on any scientific tests and I'm not surprised that it's spinning too much (for higher cpu-level).

You are still using `AeronSource` - `BroadcastHub` - `Deserializer`, right?
Then `AeronSource` and `Deserializer` should run on different actors so I don't fully understand "all the work that can only be done by this actor must wait until the spin has completed". What other work would that be? The downstream `Deserializer` lane should be able to progress. Perhaps it's cpu starvation and not actor starvation?

To add another factor is how the message rate influence the latency. Low message rate is the torture scenario because then we go into park mode in the task runner. However, for that case the async boundary should not matter much because the parking would be the dominating cost (just my 2c theory).

**Comment by jrudolph** [comment]
> What other work would that be?

I haven't found out yet. I didn't change the stream setup so it's only `AeronSource` and the `Decoder` which are running on that actor. Thread starvation seems unlikely from looking at stack traces. CPU starvation seems also unlikely because the latency spec doesn't exercise the CPU much.

My current guess would be that the other work is some streams signal that is either stuck in the actor mailbox or in one of the internal event queues. I don't have a concrete guess how that would happen but I will check.

> To add another factor is how the message rate influence the latency.

Good point, I will have to run the tests with the low message rates as well.

**Comment by jrudolph** [comment]
A few more results: The time on the async boundary seems to be lost while elements are sitting in the queue of the broadcast hub, i.e. if I take timings in BroadcastHub's `publish` and `poll` methods and check the timing difference from when an element is put into the queue vs. taken from the queue, it will show the bad latency as observed above in the "async" diagram, i.e. with 50% likelihood crossing the queue will take > 1ms. Removing spinning in AeronSource, mostly prevents that a queue builds up in the first place. Making the queue smaller (by changing `InboundBroadcastHubBufferSize`) also helps.

I also changed the code to use pinned dispatchers for both sides of the inbound artery transport (before and after the broadcast hub) which doesn't change anything significantly.

So, it seems the reading (from the broadcast buffer) thread is somehow influenced by the writing spinning thread but I cannot seem to figure out why that is the case. This would point to CPU starvation as @patriknw also suspected but I cannot reasonably explain why that would be the case with CPU resources left and the thread mostly being idle.

**Comment by jrudolph** [comment]
https://github.com/akka/akka/compare/master...jrudolph:jr/lanes-clean-setup?expand=1 contains a few timing additions I used for figuring out what's going on.

Instructions for reproducing:
 * run the aeron media driver
 * in akka-remote-tests: `multi-jvm:testOnly akka.remote.artery.LatencySpec`
 * play around with `spinning` value in `AeronSource`, e.g. setting it to 0 vs. the current setting
