### ISSUE TITLE
avoid logging from MergeHub when shutting down

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21397]
```
[ERROR] [09/08/2016 07:42:48.741] [AbstractRemoteSendConsistencySpec-akka.remote.default-remote-dispatcher-8] [akka://AbstractRemoteSendConsistencySpec/system/StreamSupervisor-0/remote-7-0-unknown-operation] Error in stage [akka.stream.scaladsl.MergeHub$$anon$2@36c2a247]: Upstream producer failed with exception, removing from MergeHub now
akka.stream.scaladsl.MergeHub$ProducerFailed: Upstream producer failed with exception, removing from MergeHub now
       	at akka.stream.scaladsl.MergeHub$$anon$2$$anon$4.onUpstreamFailure(Hub.scala:260)
```

I don't think we log error in other stages when the stream is completed with failure.

**Comment by patriknw** [comment]
@drewhk wdyt?

**Comment by drewhk** [comment]
Yes, it should. The general rule is that stages should propagate the error downward towards sinks, and sinks should report the error somehow. If they materialize to a Future or something that can report the error they should put it there, otherwise they should log it. Swallowing errors in a Sink is not a good idea as it will make things impossible to debug. There are of course always exceptions but this is the general rule.

The MergeHub acts as a Sink regarding to errors as it does not shut down the hub itself, only removes the failing input. There is nowhere to propagate the error, hence it logs. If this is undesirable, there are combinators to change this, for example adding a `recover` just in front of the MergeHub.

**Comment by patriknw** [comment]
ok, then I make this an Artery ticket instead

**Comment by patriknw** [comment]
In the shutdown process we abort the streams via the shared kill switch. I changed from `shutdown` to `abort` in https://github.com/akka/akka/pull/21390, because the stages treat successful completion gracefully, i.e. not stopping immediately if there is outstanding tasks.

We could change back to `shutdown` instead of `abort` and rewrite the stages to never do the graceful thing (we currently don't need that). However, we need to suppress this logging anyway because we log failures in other ways, when the AeronSink's `Future[Done]` is completed. We always tear down the upstream and downstream hub parts together. So, let's add `recover` in front of the MergeHub.
