### ISSUE TITLE
Revisit ActorRef banning in Artery ActorRef resolution

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21422]
The problem is remote deployment (again) where there are races between remote actor creation and messages. Since looking up these refs is very costly when they are not in fact there, we try to avoid unnecessary work by "banning" them (declaring unresolvable for once and all). This might cause issues though with system messages so we should investigate the possible effects (try them out, preferably). One option could be to not have banning for system messages, but this might have unforseen side-effects. Anyway, investigation is needed.

See discussion at: https://github.com/akka/akka/pull/21414

**Comment by patriknw** [comment]
I will write down my understand of how it works today,  and hopefully we can from that see if there are any flaws.

**Comment by patriknw** [comment]
@drewhk Here is my view of how it works and what might need improvements.



DaemonMsgCreate is not a system message. We send it over the control stream because remote deployment process depends on message ordering for DaemonMsgCreate and Watch messages.

Immediately after sending DaemonMsgCreate we watch the remote ref, i.e. it must be created before Watch arrives. Watch is only sent over control stream, since it's a system message.

The Decoder retries (with delay) the resolve of remote deployed refs if they can't be resolved immediately. The retries are only performed for the first message, thereafter the retry is banned. Next message will however still try to resolve once. It's only the retry mechanism that is banned for that ref to avoid head-of-the-line blocking in the Decoder in case someone sends to a terminated remote deployed ref.

RemoteSystemDaemon is not a real actor, i.e. no async boundary. Meaning that ! DaemonMsgCreate will immediately create the remote deployed actor.

*Problem*: There is an assumption in the Decoder that there are no asynchronous boundaries between its onPush and the RemoteSystemDaemon recipient, i.e. it will not process the Watch message before the actor is created by the RemoteSystemDaemon. When using multiple inbound lanes we have an async boundary here, the hub.

*Solution*: The retry mechanism will mitigate the problem, but it can still happen. Not sure what we can do? The result would be that the resolve of the recipient for the Watch message would fail and trigger DeathWatchNotification. We could drop the Watch message in that case and it will be resent, but for how long?

We also send DaemonMsgCreate over the ordinary message stream (all lanes) so that the first ordinary message that is sent to the ref does not arrive before the actor is created.

*Problem*: When using multiple inbound lanes the DaemonMsgCreate and the first ordinary message may take different lanes and therefore arrive in wrong order.

*Solution*: Duplicate the DaemonMsgCreate message in the inbound stream so that it is sent over all inbound lanes. That would work with current BroadcastHub + filter but would be complicated with future RouteHub.

We perform deduplication of DaemonMsgCreate in the RemoteSystemDaemon, since we send copies of it over several streams.

**Comment by drewhk** [comment]
> Next message will however still try to resolve once. It's only the retry mechanism that is banned for that ref to avoid head-of-the-line blocking in the Decoder in case someone sends to a terminated remote deployed ref.

Ok, that is good then, since that means system messages are good, since even if they are dropped at the receiver, they will be redelivered by the other side.

> We could drop the Watch message in that case and it will be resent, but for how long?

Hm, can't we have a cache for currently "in-deployment" actors that we can consult wether to drop the Watch (to force a retry for later) or send a DeathWatchNotification

> Duplicate the DaemonMsgCreate message in the inbound stream so that it is sent over all inbound lanes. That would work with current BroadcastHub + filter but would be complicated with future RouteHub.

I am thinking more and more that an out-of-bound cache (concurrentHashMap?) to track pending deployments could be better here. If we set the cache earlier than the fan-out this can work?

**Comment by patriknw** [comment]
I agree, we need something like that. In my opinion this can wait after the first release, let's revisit this afterwards.

**Comment by drewhk** [comment]
Agreed, I see the problem better now, thanks for the clarification.
