### ISSUE TITLE
Attribute.getFirst returns the last and not the first matching attibute

### ISSUE THREAD

**Issue by Silv3rcircl3** [akka/akka#21658]
Both implementations of [`Attibutes.get`](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/Attributes.scala#L93) and [`Attibutes.getFirst`](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/Attributes.scala#L100) are identical and therefore `getFirst` doesn't return the first attribute.

I found this while I ported [this](https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala#L127) SinkSpec, so this needs to be changed too.

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by BayStallion** [comment]
Can I take this one?

**Comment by ktoso** [comment]
Thanks would be wonderful :-) Thanks in advance!

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 13 October 2016 at 01:09:28, Vsevolod Belousov (notifications@github.com)
wrote:

Can I take this one?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/issues/21658#issuecomment-253365743>, or mute
the thread

**Comment by johanandren** [comment]
@BayStallion any progress on this, you still want to do it?

**Comment by BayStallion** [comment]
@johanandren Yes, still do. Have had too much on my plate recently, sorry for the delay.

**Comment by johanandren** [comment]
Thanks, no worries, good to know that we shouldn't take it over.

**Comment by BayStallion** [comment]
@Silv3rcircl3 Could you share your ideas why you think this implementation is wrong? I have played a little bit with [this test](https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala#L127)  and added more named attributes in line 129. As far as I can see, Attributes.getFirst retrieves the first attribute of the given type, Attributes.get retrieves the last attribute of the given type. I don't see anything wrong here.

**Comment by Silv3rcircl3** [comment]
@BayStallion as I said, the imellemantations for Get and GetFirst are identical, so it's impossible that they return different values ;) 
Also if you look at Sink.head it creates a graph and then calls "withAttributes" with the default attributes for head which already contain a Named attribute, so the spec should fail because the value of the first attribute isn't "name" but "head". 

https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/scaladsl/Sink.scala#L128

But I could be totally wrong, I'm working on the .Net port and therefore have only basic scala knowledge.

**Comment by BayStallion** [comment]
@Silv3rcircl3 I think I got it. The methods you were probably referring to as identically implemented are [this](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/Attributes.scala#L93) and [this](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/Attributes.scala#L100), but they are not being used in any of the existing tests (I should probably add new test cases to cover them). The methods which are used in tests have the same names, although not exactly the same signature ([get](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/Attributes.scala#L106 and [getFirst](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/Attributes.scala#L114)), and they are implemented differently, that's why I didn't notice any inappropriate behaviour while playing with the existing tests.
