### ISSUE TITLE
cluster-sharding doesn't delete snapshots and messages

### ISSUE THREAD

**Issue by 412b** [akka/akka#21725]
neither coordinator nor shard (if `remember-entities`=on) clean up after themselves, when a snapshot is done, poluting the persistence backend. in our persistence actors we ended up with cleaning up snapshots and messages after successful snaphot is done. if that solution fits, I can submit a PR with corresponding changes to `Shard` and `ShardCoordinator`.

**Comment by patriknw** [comment]
@412b Such contribution would be welcome. We don't need to keep the full event history for those. I would prefer to not delete them immediately. That is useful for debugging.

Additionally, with for example the Cassandra plugin it would not be safe to delete the events immediately because snapshots are stored with weaker consistency level so latest snapshot might not be visible immediately.

**Comment by mbknor** [comment]
This is also a problem for us. What is the status on a fix for this issue?

**Comment by patriknw** [comment]
There is a pull request in progress https://github.com/akka/akka/issues/21777
I think the remaining part is some better test coverage. It's a difficult thing to test though.

**Comment by 412b** [comment]
@mbknor @patriknw yep, low-level testing is missing there and I didn't have much time recently.
