### ISSUE TITLE
Revisit available random-number-generators of old akka-remote

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#21740]
Currently, it supports a few custom ones (from https://github.com/akka/akka/blob/ad3ef5982c81b522ddbc2a1bc2d09a01eb54ab5c/akka-remote/src/main/resources/reference.conf#L627):

```
        # There are three options, in increasing order of security:
        # "" or SecureRandom => (default)
        # "SHA1PRNG" => Can be slow because of blocking issues on Linux
        # "AES128CounterSecureRNG" => fastest startup and based on AES encryption
        # algorithm
        # "AES256CounterSecureRNG"
        #
        # The following are deprecated in Akka 2.4. They use one of 3 possible
        # seed sources, depending on availability: /dev/random, random.org and
        # SecureRandom (provided by Java)
        # "AES128CounterInetRNG"
        # "AES256CounterInetRNG" (Install JCE Unlimited Strength Jurisdiction
        # Policy Files first)
        # Setting a value here may require you to supply the appropriate cipher
        # suite (see enabled-algorithms section above)
        random-number-generator = ""
```

It might make sense to revisit the choices made there and maybe get completely rid of the custom ones. Also see @wsargent's [blog post](https://tersesystems.com/2015/12/17/the-right-way-to-use-securerandom/). We could also look into what ssl-config suggests (if it does).

**Comment by jrudolph** [comment]
The goal should be to reduce alternatives to the best ones for a platform and then maybe allow arbitrary random providers to be plugged in by classname if users want to use them for whatever reasons.

**Comment by gosubpl** [comment]
Please also see discussion in: https://github.com/akka/akka/pull/21716 and https://github.com/akka/akka/pull/21730

**Comment by gosubpl** [comment]
I have closed https://github.com/akka/akka/pull/21716 after unfortunately clumsily rebasing it on top of new master. However, the discussion there is IMHO still valid. As per request by @wsargent I have included more security providers/algorithms.
Below are performance results of currently used implementations, run on (x)ubuntu Linux, kernel 4.4.0-45, jdk8 u112 x64. u112 should (at least partially) account for performance problems described in [this issue](https://bugs.openjdk.java.net/browse/JDK-8098581)
```
jmh:run -wi 15 -i 15 -f 1 .*RandomReplacementBenchmark.*

[info] Benchmark                                     Mode  Cnt     Score     Error  Units
[info] RandomReplacementBenchmark.runCtr               ss   15   188.395 ±   6.817  ms/op
[info] RandomReplacementBenchmark.runNew               ss   15   179.377 ±  22.380  ms/op
[info] RandomReplacementBenchmark.runOld               ss   15   148.000 ±  21.102  ms/op
[info] RandomReplacementBenchmark.runSecRnd            ss   15  1564.641 ± 160.528  ms/op
[info] RandomReplacementBenchmark.runSecRndNonBlock    ss   15  1485.373 ± 101.823  ms/op
[info] RandomReplacementBenchmark.runSecRndSha1        ss   15   294.833 ±  29.386  ms/op
[info] RandomReplacementBenchmark.runSecRndSha1Sun     ss   15   316.233 ±  45.848  ms/op
```
`runOld` is the original AES-CTR algorithm from uncommons.math
`runNew` is its reimplementation in Scala (slower probably due to boxing/unboxing)
`runCtr` is the implementation based on actual AES-CTR algorithm from Cipher (`AES/CTR/NoPadding`) as per @drewhk suggestion
`runSecRnd` is the default SecureRandom implementation that is `NativePRNG` as I haven't used the `-D <something> /dev/urandom` option, initial seed is taken from true randomness source (`/dev/random`).
`runSecRndNonBlock` is the `NativePRNGNonBlocking` which should be equivalent to `NativePRNG` with the `/dev/urandom` set to randomness source
`runSecRndSha1` is the `SHA1PRNG`
`runSecRndSha1Sun` is `SHA1PRNG` with `SUN` option

If you take a look at the [SP800-90Ar1](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf) the market for CSPRNGs (or DRBGs, as they call them) is quite limited. The options are: HASH_DRBG / HMAC_DRBG - based on SHA-1 or SHA-256 and CTR_DRBG - based on AES or other block encryption standard. Or some combination of both. The limited choices are also reflected by the [JVM docs](https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SecureRandom).

HASH/HMAC DRBGs have their load of [issues](https://www.hgi.rub.de/media/nds/veroeffentlichungen/2013/03/25/paper_2.pdf) and are quite complex to implement. In JDK we have from that category of algorithms the `SHA1PRNG`. Where `SUN` is the canonical implementation and the `non-SUN` is platform dependent.

The CTR DRBGs are based on block Ciphers. This category contains e.g. the AES-CTR from uncommons.math (`AES[128|256]CounterSecureRNG`). Such algorithms are very fast also because some hardware offers AES accelarators.

More complex algorithms like Fortuna or Yarrow combine block Ciphers with SHA-1/SHA-256.

All require proper re-seeding for proper functioning.

FreeBSD and OS X are supposed to be using either Yarrow or Fortuna as their implementation of `/dev/random` / `/dev/urandom` pair. **I would be very grateful if someone could run the benchmark on actual FreeBSD or OS X machine** to see what would be the performance of `NativePRNG` there, as the bespoke CSPRNG used by Linux `urandom` seems to be widely known to be [slow](http://serverfault.com/questions/6440/is-there-an-alternative-to-dev-urandom). Therefore the custom AES-CTR algorithm offers a viable alternative for situations where high performance is desired, especially on Linux.

Hence, from my point of view, the allowed range of CSPRNGs in `NettySSLSupport.createSecureRandom`, which is `NativePRNG`, `SHA1PRNG` and `xCounterSecureRNG` seems to be right, perhaps module the replacement of `AES128CounterSecureRNG` / `AES256CounterSecureRNG` pair with AES-CTR based implementation using `AES/CTR/NoPadding` with re-seeding and droping the `Inet` ones (see https://github.com/akka/akka/issues/12636 ).

What is definitely worth considering is allowing "pluggable" CSPRNGs, which would allow something like https://github.com/grunka/Fortuna to be integrated by the library user. But I am not sure if this is worth additional complexity.

**Comment by drewhk** [comment]
I think we should support the AES-CTR from Cipher. While it might not be the fastest, it has the least error, by far. I don't want to introduce timing channels and hence I trust this most. I think reseeding it from time to time from urandom is enough to introduce enthropy. We just have to be aware that reseeding should not happen more frequently than in the minutes range, I don't want to introduce a timing channel through reseeding.

**Comment by wsargent** [comment]
Fair enough -- reseeding from urandom every 2^48 requests as per SP800-90 should be fine.

**Comment by gosubpl** [comment]
Yes. I will get around to submitting PR this weekend. Will do AES-CTR with 2^48 bytes re-seeding and then we can hopefully continue the discussion from there.

**Comment by drewhk** [comment]
Please benchmark it with shorter reseed cycles. We can pick the reseed cycle that does not introduce performance bottleneck anymore. I expect that can be much shorter than 2^48 bytes.

**Comment by gosubpl** [comment]
I am back on track to squeeze this in time for 2.5. However, more frequent re-seeds seem to be a problem, probably due to entropy exhaustion - the benchark gets stuck for longer periods while re-seeding. I am looking into this -I run on Linux with OpenJDK.

**Comment by gosubpl** [comment]
BTW, @ktoso can we please remove already deprecated `Inet` generators:
```
@deprecated("Use AES128CounterSecureRNG instead", "2.4")
@deprecated("Use AES256CounterSecureRNG instead", "2.4")
```
for the 2.5 release? It would let us seamlessly replace the other two with the AES-CTR PRNG and get rid of the `math.uncommons`. Otherwise, even after replacing the PRNGs, we'll be stuck with uncommons.
Shall I add this to the deprecation/removal ticket?

**Comment by ktoso** [comment]
Great, let's remove them :)

**Comment by ktoso** [comment]
You can create the ticket if you want 👍

**Comment by gosubpl** [comment]
@drewhk @wsargent re-seeding AES-CTR (`AESCounterBuiltinCTRRNG`).
Re-seeding is done in a "soft-scheduled" way on a separate thread. Every million requests (see below) re-seed request is generated. When new seed is available, the PRNG is re-seeded. However, when a hard threshold of 2^47 is exceeded, the generator blocks to wait for new entropy (which should never happen in real life).
If we reseed every million then for a 10 million test we get on average 3-5 re-seeds (so effectively a reseed takes around 2-3 million generations of a random number). This frequent re-seeding seems to impact a bit the entropy pool - so the algorithm might get stuck a bit at start-up when it is blocking waiting for the entropy, but otherwise the impact is minimal. We could choose to re-seed every 100 million or a billion - 2^47 is 140 thousand billion anyway, e.g. - WDYT?

```
after introducing reseeding:

[info] Benchmark                             Mode  Cnt     Score     Error  Units
[info] RandomReplacementBenchmark.runCtr       ss    5   230.315 ±  45.922  ms/op
[info] RandomReplacementBenchmark.runNew       ss    5   197.405 ± 150.660  ms/op
[info] RandomReplacementBenchmark.runOld       ss    5   140.662 ±  20.027  ms/op
[info] RandomReplacementBenchmark.runSecRnd    ss    5  1947.085 ± 301.460  ms/op

[info] Benchmark                             Mode  Cnt     Score     Error  Units
[info] RandomReplacementBenchmark.runCtr       ss    5   565.327 ± 468.836  ms/op (startup delay)
[info] RandomReplacementBenchmark.runNew       ss    5   163.493 ±  27.324  ms/op
[info] RandomReplacementBenchmark.runOld       ss    5   163.244 ± 218.053  ms/op
[info] RandomReplacementBenchmark.runSecRnd    ss    5  2079.254 ± 554.498  ms/op

[info] Benchmark                             Mode  Cnt     Score     Error  Units
[info] RandomReplacementBenchmark.runCtr       ss    5   238.378 ±  47.717  ms/op
[info] RandomReplacementBenchmark.runNew       ss    5   196.592 ±  88.059  ms/op
[info] RandomReplacementBenchmark.runOld       ss    5   156.586 ±  48.162  ms/op
[info] RandomReplacementBenchmark.runSecRnd    ss    5  2184.300 ± 745.457  ms/op
```

**Comment by wsargent** [comment]
@gosubpl LGTM
