### ISSUE TITLE
Change ORMap to have a generic type for key

### ISSUE THREAD

**Issue by jgordijn** [akka/akka#22035]
I would like to have the possibility to use anything as a key for the ORMap. Is there any reason why it is fixed at String? 

This should probably make it into 2.5 before removing experimental, as this would probably break the interface.

**Comment by guidomedina** [comment]
This will be great for `Integer` or `Long` keys for example.

**Comment by patriknw** [comment]
Ok, that should be doable.

**Comment by jgordijn** [comment]
I'll try to create a PR this week.

**Comment by patriknw** [comment]
Thanks, we should specialize some types for serialization efficiency, see for example how it's done for `GSet`.

**Comment by guidomedina** [comment]
@patriknw is there a way to provide your map/set creator factory, say I want to use a different `Set` or `Map` implementation like http://fastutil.di.unimi.it/

Would such functionality be affected by the specialization you are talking about?
The reason to use frameworks like `FastUtil` is because they provide a nice primitive specialization:
- `<int, Object>`
- `<int, int>`
- `<long, Object>`
- `<long, long>`
- ...
- etc

They are not only easier to serialize but also offer a low memory footprint in all aspects, this by itself I think deserves an issue but since you mentioned the serialization specialization thought it was worth mentioning here.

**Comment by inakov** [comment]
Hi guys, is anyone working on this task? I would really like to create a PR for this one! I may have some question about the serialization, but on first sight it looks like I'll be able to do it.

**Comment by jgordijn** [comment]
@inakov  Yep, I'm working on it. I'll create a PR this week.

**Comment by inakov** [comment]
OK cool :+1:

**Comment by patriknw** [comment]
@inakov There are a few other ddata tickets that shouldn't be too hard if you would like to try.
https://github.com/akka/akka/issues/20140
https://github.com/akka/akka/issues/21618
https://github.com/akka/akka/issues/21648

**Comment by jgordijn** [comment]
I've created a PR for this: https://github.com/akka/akka/pull/22060

**Comment by patriknw** [comment]
Thanks @jgordijn 
I'll review after the holidays.

**Comment by jgordijn** [comment]
@patriknw That's fine. Enjoy the holidays!
