### ISSUE TITLE
It would be nice to know if the replicator is restoring from durable storage

### ISSUE THREAD

**Issue by jgordijn** [akka/akka#22150]
If there is a durable store I would like to know that the replicator is currently restoring the data. In that case I can give a service not available instead of returning a 404 if something is not found yet.

**Comment by jgordijn** [comment]
What do you think:
- an event on the eventstream?
- a subscription?
- stashing incoming messages until loaded?

**Comment by patriknw** [comment]
I think they should be stashed. Not only for this reason, but it's actually needed for correctness for some update cases, e.g.
* Update of GCounter key A
* when modify is run the entry A is not loaded yet, new value is kept in Replicator
* when entry A is loaded it is merged with the updated entry, and such merge is not correct if the same node identifer is used (this will not be a problem if the ActorSystem is restarted, but it can be if only the Replicator is restarted for some reason)

Somewhat obscure scenario, I know, but I also think stashing will be easiest to use.
We can probably not use the `Stash`, though, since its (the mailbox) performance is not great.

**Comment by patriknw** [comment]
BTW, for testing purposes it's already possible to use `GetReplicaCount`, which will reply with `ReplicaCount(0)` until data is loaded.

**Comment by patriknw** [comment]
@jgordijn I'll work on this today, unless you have already started?

**Comment by jgordijn** [comment]
That's great! I'll look into the PR ASAP.
