### ISSUE TITLE
Strange behavior with akka http and nginx

### ISSUE THREAD

**Issue by George3d6** [akka/akka#22178]
I have a basic https nginx config (certificates from certbot) and I run my application on port 3666. Whenever I try to connect to the domain however I get this type of errors in my nginx logs:

2017/01/22 00:06:04 [error] 30764#30764: *35 connect() failed (111: Connection refused) while connecting to upstream, client: mylocalmachineip, server:mydomain.com, request: "GET / HTTP/1.1", upstream: "http://myServerIp:3666/", host: "mydomain.com"

I realized that this seems to be due to the fact that I am pointing nginx towards ip:port rather than localhost:port. However, this is a rather strange thing. It might have been due to a misunderstanding of how reverse proxying works, but I just happened to have always used the machine ip rather than the localhost.

Why would akka http react differently when called via http on ip:port vs localhost:port ?

**Comment by johanandren** [comment]
Hi @George3d6, this seems more like a question than a ticket, please use the [gitter channel](https://gitter.im/akka/akka) or the [mailing list](https://groups.google.com/forum/#!forum/akka-user) for questions and only use the issue system only for bugs and feature requests (additionally Akka HTTP has its own issue tracker over at https://github.com/akka/akka-http 

Based on this I'll close the ticket, please reopen anew in the akka-http if you use the recommended channels and end up confirming that it is a bug rather than a misconception or a misconfiguration. Thanks!
