### ISSUE TITLE
stashing for Akka Typed

### ISSUE THREAD

**Issue by simerplaha** [akka/akka#22275]
Or is `SynchronousSelf` the solution for stashing in Akka Typed ?

@rkuhn

**Comment by rkuhn** [comment]
I’m not sure stashing is a good idea at all. Instead of a hidden queue it is better to have an observable explicit queue so that you can react to the fill level for flow control purposes.

With a process DSL like in #22087 you will not need it because you just don’t read from the mailbox while not ready—but this should be seen in the context of a higher level of abstraction and also of limiting mailbox size by default.

**Comment by patriknw** [comment]
I agree with @rkuhn. `Stash` is much about restoring the `sender`, which doesn't exist in Typed. Let's not close it but rename it to "document..."

**Comment by dbolotin** [comment]
@patriknw thanks for clarification in #23161! Basically using internal explicit buffer it is exactly what I am doing right now. I am collecting messages that I can't handle before initialisation and then send all the buffered messages to `self`, before switching to new behaviour:
```scala
for (m <- messagesBuffer)
    ctx.self ! m
```
Is it the right pattern?

Basically I came up with the following wrapper behaviour:
```scala
private final case class BufferingBehaviour[T]
(bufferLimit: Int, behavior: Behavior[T])
  extends ExtensibleBehavior[T] {

  private val messagesBuffer = mutable.Buffer.empty[T]

  private def nextBehaviour(ctx: g.ActorContext[T], next: Behavior[T]): Behavior[T] = {
    val nextCanonical = Behavior.canonicalize(next, this, ctx)
    if (nextCanonical != this)
      if (!Behavior.isAlive(nextCanonical))
        nextCanonical
      else {
        val sctx = ctx.asScala
        for (m <- messagesBuffer)
          sctx.self ! m
        // Returning new behaviour, it will receive all buffered messages
        nextCanonical
      }
    else
      // Behaviour not changed, will be canonicalized by upper behaviour or behaviour executor
      Actor.same
  }

  override def receiveSignal(ctx: g.ActorContext[T], signal: Signal): Behavior[T] = {
    nextBehaviour(ctx, Behavior.interpretSignal(behavior, ctx, signal))
  }

  override def receiveMessage(ctx: g.ActorContext[T], msg: T): Behavior[T] = {
    val next = Behavior.interpretMessage(behavior, ctx, msg)
    if (Behavior.isUnhandled(next)) {
      messagesBuffer += msg
      if (messagesBuffer.size >= bufferLimit)
        // Stopping this actor with error, can be handled by supervisor
        throw new BehaviourBufferOverflowException
      // Returning unhandled behaviour
      next
    } else
      nextBehaviour(ctx, next)
  }
}
```

Basically it buffer all `unhandled` messages until not-`same` behaviour is returned by the wrapped behaviour. Can you please verify that this approach is correct?

I also noticed that there is no way to check whether returned behaviour is the `Actor.same` (there is no such helper function as `Actor.isSame(...)`). So I used `Behavior.canonicalize` to detect behaviour change to flush the buffer.

@rkuhn also mentioned "DSL like in #22087", but I can't see which code from this PR allows for the described selection of messages from the mailbox.

**Comment by rkuhn** [comment]
With a process DSL (see also https://github.com/rkuhn/akka-typed-session) there is no need to select from the mailbox since you just have many mailboxes and select from which you want to read next.

Concerning your BufferingBehavior: sending to self implies that the buffered messages will arrive after messages that were already in the mailbox when the behavior change was triggered, i.e. the wrapped behavior will see a distorted message ordering. Fixing this either means processing all stashed messages on the spot (which impacts scheduling fairness) or placing the buffer into another actor that hides a wrapped actor—and not a wrapped behavior. In the second case, the hidden actor needs to signal the wrapper when to release the buffer.

If this is only used as an initialization latch then the fairness issue might not be that important. But beware of uses that start stashing again after unstashing—this might result in quadratic increase in message dispatch counts.

**Comment by simerplaha** [comment]
Here is a Stash behaviour that was good my use case https://github.com/simerplaha/akka-typed-stasher. It appends messages to a Stash actor with a limit which get pulled by the target actor or push to the Actor based on the [StashType](https://github.com/simerplaha/akka-typed-stasher/blob/master/src/main/scala/stash/StashType.scala). Problem here is that for each actor that requires Stash, there are a total of 2 actors and 2 mailboxes per actor (Twice the number messages being dispatched) not very efficient :(

Having a custom queue internal to the Actor would also mean there 2 mailbox queues, 1 in the [ActorCell](https://github.com/akka/akka/blob/master/akka-typed/src/main/scala/akka/typed/internal/ActorCell.scala#L180) and 1 internal to the Actor itself.

I could be wrong here but could we configure how messages get pulled from the [queue in ActorCell](https://github.com/akka/akka/blob/master/akka-typed/src/main/scala/akka/typed/internal/ActorCell.scala#L180) directly. For example the following rough API. Or something better ? 

```scala
  val myMailboxOrder = new Ordering[Iterable[MyMessage]] {
    def compare(queue1: Iterable[MyMessage], queue2: Iterable[MyMessage]): Int = ???
  }

  Actor.immutable[MyMessage] {
    (ctx, message) =>
      message match {
        case StartStashing =>
          Actor.stash

        case ProcessNextMessage =>
          Actor.unstash

        //pull messages out of the mailbox lazily based on some condition
        case ProcessNextMessageLazily =>            
           ctx.mailbox.pop(condition = ???)
      }
  }.withMailbox(limit = 10, ordering = myMailboxOrder)
```

**Comment by patriknw** [comment]
I agree that it's good to use an internal buffer but we would need an api for processing those messages through the normal `Behavior.interpretMessage`.

**Comment by ktoso** [comment]
Initial merged, needs docs and prehaps revisiting if it needs a nicer API

**Comment by ktoso** [comment]
Some ideas on API: https://github.com/ktoso/akka/commit/08ce07783c1d975bda656fb2dda9eca2dc6fae88
