### ISSUE TITLE
Duplicate running instances when using cluster sharding with remember entities enabled

### ISSUE THREAD

**Issue by notxcain** [akka/akka#22289]
Recently I've noticed duplicate events for one of my persistent entities. 
I have only one node running. So here is the scenario that I have in mind:
1. Remember entities is enabled
2. There is alive entity `foo` in shard `A`
3. Shutdown app
4. Change sharding function (that what I did)
5. Start app
6. `foo` is recovered in shard `A`
7. Send message to `foo` and new sharding function routes it to shard `B`.
8. We have two instances of `foo`

Docs say `The sharding algorithm must be the same on all nodes in a running cluster. It can be changed after stopping all nodes in the cluster.` and I think this may be not true when using remember entities.

Please correct me if I'm wrong.

**Comment by patriknw** [comment]
I can confirm that this is a bug. When the identifiers have been loaded from storage the `Shard` just creates the actors as children even though it might not be responsible for the entities any longer. It would have to start them via some activation message taking the same path as an ordinary message, i.e. via the coordinator to decide where it should live. That adds the complication that such an activation message must be application specific so that the shard extractor understands it. Not trivial, but it must be fixed.
