### ISSUE TITLE
still some Java serialization for remote deployment

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22332]
akka.remote.RemoteScope, akka.actorScope ?

**Comment by johanandren** [comment]
The can of worms I just opened up in this ticket: `Deploy` contains `com.typesafe.Config`, which is also serialized with class name instead of manifest separately in `DaemonMsgCreateSerializer` so if I add a new proto serializer for it, that one starts to fail. Additionally there is a `RouterConfig` field, so all concrete subtypes of that (I make it ~20). :/

**Comment by patriknw** [comment]
Yeah. I see no other option than biting the bullet.

There are many `RouterConfig` but I think they are very similar and not very difficult. One thing that can't be serialized is the `supervisorStrategy`, but I can't see that it will be used on the other side. It's used by the `RoutedActorCell` on the parent side. We can use default `Pool.defaultSupervisorStrategy`.

If we use the full class name as the manifest string for the RouterConfig we can probably keep the class name based serialization for RouterConfig in DaemonMsgCreateSerializer.

For `Config` I think we should make it simple and format it as String and parse it on other side. Special case empty config (optional field in protobuf).
