### ISSUE TITLE
Persistence and Routing

### ISSUE THREAD

**Issue by enzeart** [akka/akka#22620]
I've been looking into using persistence with an actor that I plan to put behind a router in my project. Will journaled events be replayed at the router level during restart?

**Comment by ktoso** [comment]
Please ask general "how to use akka" questions on gitter ( https://gitter.im/akka/akka ) or the akka-user mailing list ( https://groups.google.com/group/akka-user/ ) since the issue tracker is dedicated to tracking specific issues, bugs or features - thanks in advance!

Whoever is the persistent actor will have events replayed. A router is not a persistent actor, your "domain" actor could be though.

**Comment by enzeart** [comment]
@ktoso Your response brings me to a potential issue then. I'll discuss it externally and reopen this if I find that my expected issue is valid.

**Comment by ktoso** [comment]
Please explain your actual use case on one of these forums and we'll get to it :)
The model works, since if a router routes to the same id, you'd replay that id's events so everything can recover properly. Routers are stateless in that sense.
