### ISSUE TITLE
Add log of cause exception when uncaught error kill the JVM

### ISSUE THREAD

**Issue by cpoissonnier** [akka/akka#22630]
It would be great to log the cause exception when an uncaught error kills the JVM.
 
I spent a lot of time trying to understand what was the issue in our code, and had to run my Play application in development mode in a production environment to get the cause error in the console.

cf. https://github.com/akka/akka/blob/release-2.4/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L693

**Comment by jrudolph** [comment]
The line you referenced seems to include the cause. The code also prints information to stderr. What do you propose to add above that?

In any case, in case of a fatal JVM error, Java code might just not be able to do anything because things might just be too broken to still work. E.g. the logging infrastructure might just not work any more.

**Comment by cpoissonnier** [comment]
It should, but the cause is not logged. It is printed in stderr, but it was not possible for me to get this information in Play Framework Production Mode.

I don't know how the markerLogging is supposed to work, but I should display the cause error, right? Unfortunately, that was not the case for me (but yes, maybe I did something wrong)

**Comment by ktoso** [comment]
As Johannes explained, this is an "everything is burning, end of the world" situation, we can't rely on the logging infra to be even alive anymore - which is why the error is printed to std-err as a last-resort.
