### ISSUE TITLE
Typed FutureRef not working with untyped adapter

### ISSUE THREAD

**Issue by mirmasej** [akka/akka#22640]
Version: 2.5.0-RC1

Summary: It is not possible, while using both typed and untyped AkkaSystems together in a way described below, which I assume was expected to work, create typed actors.
Minimal example (imports omitted for brevity):

```scala
import akka.actor.{ ActorSystem ⇒ UntypedSystem }
case class AMessage(replyTo: ActorRef[String])
val behavior = Stateless[AMessage] { (_, msg) ⇒ msg.replyTo ! "OK" }
val untypedSystem = UntypedSystem("untyped")
val typedSystem = ActorSystem.wrap(untypedSystem)
implicit val scheduler = untypedSystem.scheduler
implicit val timeout = Timeout(2 seconds)
val typedActorRef = ActorRef(typedSystem.systemActorOf(behavior, "typedActor"))
```
The following exception is thrown at the last line:
  
> java.lang.UnsupportedOperationException: only adapted untyped ActorRefs permissible (Actor[akka.typed.internal://future/#0] of class class akka.typed.internal.FutureRef)
  at akka.typed.adapter.package$.toUntyped(package.scala:30)
  at akka.typed.adapter.package$.sendSystemMessage(package.scala:37)
  at akka.typed.adapter.ActorRefAdapter.sendSystem(ActorRefAdapter.scala:14)

PS. Background discussion [here](https://github.com/akka/akka/issues/22174#issuecomment-288166020).

**Comment by patriknw** [comment]
The problem here is that the the `FutureRef` tries to `Watch` the `ref`, which here is an `ActorRefAdapter`. The adapter tries to `toUntyped` on both watcher and watchee, and that fails on the watcher since that is the `FutureRef`.

I'm not sure what is supposed to work or what is still to be implemented for the adapters.

To me it looks like the watch in `FutureRef` could be optional. The only purpose is to "replace" the target with a blackhole when it terminates. Why is that done?

If that is just a nice to have we could remove the watch altogether or skip it for `ActorRefAdapter` targets.

Thoughts @rkuhn ?

**Comment by rkuhn** [comment]
My wish would be to have some time to think through exactly how untyped and typed should be able to interact and how that should be implemented, in its entirety. Before that it is difficult to give a consistent answer.

**Comment by patriknw** [comment]
Looked some more at the `FutureRef` and see that the purpose of the watching is to propagate `DeathWatchNotification`. Is that correct? I'm thinking of delivery order of the `DeathWatchNotification` since this introduces an extra "actor" in-between. E.g. target actor sends one last reply message and then stops, then the reply is supposed to be delivered before `Terminated`.

I don't understand the rationale for why `sendSystem` isn't just delegating the messages to the target.

Also, it's unnecessary to watch the target if there is nobody watching the FutureRef.

**Comment by rkuhn** [comment]
That ordering guarantee is gone: since we don't have sender() anymore, Terminated only signifies that sending to that ref does not make sense anymore.

**Comment by patriknw** [comment]
`sender()` has nothing to do with that, AFAICS.
We have said that it should be possible to use Terminated as an end of conversation message.

Actor A has ref to actor B.
A watch B
A sends "give me your stuff" to B.
B sends msg 1 .. 100, and then stops itself to indicate that there is nothing more.
A should receive msg 100 before Terminated.

**Comment by rkuhn** [comment]
Yes, I'm aware of that, but unfortunately I was not able to implement those semantics in the new ActorSystemImpl without complicating things quite a bit.

The other reason for removing this guarantee is that it only works in the simple and direct case, it breaks down when forwarding is involved. Therefore the more reasonable guarantee is that a destination for which a Terminated has been received is invalid.

**Comment by patriknw** [comment]
This is a specific issue for `FutureRef`. I'm putting it back until we have the more general pieces of coexistence in place.

**Comment by patriknw** [comment]
closing, since FutureRef is removed for now
