### ISSUE TITLE
Akka persistence query: eventsByTags

### ISSUE THREAD

**Issue by Fristi** [akka/akka#22650]
Instead of using one tag I would like to specify multiple tags (`def queryEventsByTags(tags: Set[String]): Source[EventEnvelope2, NotUsed]`)

Currently we are using akka-persistence-query with one tag (`all`) and `collect` 2 events from a set of 8-10 events. The nice thing about the current query is: it's one periodic poll probably (I assume the Cassandra implementation does the same thing as the JDBC version (polling the database with a LIKE query?)).  I could use two `queryEventsByTag` and concat them, but that would introduce two (and so on) polling queries right? It would be more efficient if we could make it one query. Not so sure if all journal implementations could offer such a API.

WDYT?

**Comment by patriknw** [comment]
I think you should start by implementing this in a specific journal. Such additional capabilities don't have to go into the akka-persistence-query API.

**Comment by raboof** [comment]
In the case of Cassandra it will not make any difference because the tags are in different partitions so you would need multiple streams under the hood anyway.

It could indeed make sense for other journals. Are you planning to implement this feature in any specific journal? We'd be open to introducing the API in that case!
