### ISSUE TITLE
Source.unfoldResource may leak resources

### ISSUE THREAD

**Issue by avakhrenev** [akka/akka#22652]
Consider the following program:
```scala

import akka.actor.{Actor, ActorSystem, PoisonPill, Props}
import akka.stream.scaladsl.{Sink, Source}
import akka.stream.{ActorMaterializer, KillSwitches}

class MyActor extends Actor {
  implicit val materializer = ActorMaterializer()
  val killSwitch            = KillSwitches.shared("kill")

  override def preStart() =
    Source
      .unfoldResource[String, String]({ () =>
        println("## Opened")
        "resource"
      }, { _ =>
        Thread.sleep(1000L)
        Some("OnNext")
      }, _ => println("## Closed"))
      .via(killSwitch.flow[String])
      .runWith(Sink.foreach(m => self ! m))

  override def postStop() = {
    killSwitch.shutdown()
    super.postStop()
  }

  override def receive = {
    case any => println(s"Received $any")
  }
}

object Test extends App {
  implicit val system = ActorSystem()
  println("starting")
  val ref = system.actorOf(Props(classOf[MyActor]))
  Thread.sleep(5000L)
  println("killing the actor")
  ref ! PoisonPill
}
```

`## Closed` will never be printed

The key part is `ActorMaterializer()` capturing current actor's context as an `ActorRefFactory`. When the actor gets killed, no proper stream lifecycle methods are executed.

Akka version is 2.4.17

**Comment by johanandren** [comment]
The reason a combination of the fact that the materializer uses the actor context as its implicit `ActorRefFactory`, so it gets shutdown when the actor shutsdown and that `killSwitch.shutdown()` is async so it will not wait for the streams to actually have been shutdown, causing the stream to get abruptly killed with the materializer rather than shutdown.

There is a bug in there though, and that is that `UnfoldResourceSource` should make sure that the `close` logic has been invoked in its `postStop` hook.

**Comment by avakhrenev** [comment]
The issue is not specific to the `UnfoldResourceSource` stage only, it affects every `GraphStage`, which have interesting finalization logic described inside of `onDownstreamFinish`/`onUpstreamFinish`/`onUpstreamFailure`. Your proposed fix implies that every such `GraphStage` should repeat the same logic inside of `postStop`.

Why not to make graph interpreter call `onUpstreamFailure` and `onDownstreamFinish` when abrupt termination happens?

**Comment by johanandren** [comment]
That sounds very invasive, I don't know. @drewhk @patriknw any input?

**Comment by johanandren** [comment]
Note that regardless of this bug in `UnfoldResourceSource` (and possibly other stages) the more correct solution would be to have a shutdown message, rather than poisonpill, trigger stream shutdown using that, and then not stop the actor until the stream has shut down. Shutting down the stream by killing the materializer is like doing kill -9 on a stream. Doing that would avoid the bug to start with.

I rather lean towards that a stage should manage its resources correctly if it has resources. and `postStop` is that hook that always will be called.

**Comment by avakhrenev** [comment]
> the more correct solution would be to have a shutdown message, rather than poisonpill

I absolutely aree with you. But in real applications actors may unexpectedly terminate because of various reasons, not only because of scheduled stopping. The `PoisonPill` here is used to keep the example minimal. Probably it is a good thing, that crash of the actor also terminates all the streams it materializes, so even no `KillSwitch` required.

> and possibly other stages

Here is possibly incomplete list of such stages:

- `ActorOutputBoundary`
- `ActorRefBackpressureSinkStage`
- `HeadOptionStage`
- `InputStreamSinkStage`
- `LastOptionStage`
- `MonitorFlow`
- `newOnCompleteStage()`
- `SeqStage`
- ironically, `TerminationWatcher`
- `UnfoldResourceSourceAsync`

Seems like `postStop()` hook is treated as just a convenient place to have finalization logic if it is the same regardless of the cause of termination, rather than mandatory place where one should ensure no resources left unclosed. It is even [not mentioned in the docs](http://doc.akka.io/docs/akka/2.4/scala/stream/stream-customize.html)!

I find current behaviour of the interpreter very surprising and it would be pretty invasive to not change it.

Maybe I should dig deeper and come up with a pull request?

**Comment by johanandren** [comment]
Thanks for investigating those

* `ActorOutputBoundary` is very special and not affected by this problem
* `ActorRefBackpressureSinkStage` doesn't manage the resource (the `ActorRef` is passed in)
* The rest seems correct

I think we should have a discussion about this in the team before deciding how to act on it, so wait a bit with a PR, thanks.

Ping @patriknw @ktoso @2m
