### ISSUE TITLE
FAILED: ReplicatorDeltaSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22737]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4827/consoleFull

**Comment by gosubpl** [comment]
My _2¢_ theory: there seems to be a race condition inside the spec. Addition operations for `"B", "C", "D"` in lines 249-251 are allowed to happen without stabilising the CRDT at the `Set("a", "A")` state. First read in `ReplicatorDeltaSpec.scala:243` does return less than `Set("a", "A")`. Next read would be OK, but because of the additions we get more.

**Comment by gosubpl** [comment]
I will submit a PR today or later this week.

**Comment by patriknw** [comment]
thanks

**Comment by gosubpl** [comment]
Exact reason for the test failing is rather something like if you add the following starting line 241
```
      runOn(second, third, fourth) {
        Thread.sleep(500)
      }
```
The 'first read in does return...' above is not exactly true, as the consistency level is local, but the delay in read on any of the replicas apart from `first` resulting in seeing the update done on `first` is possible. This is fixed by the commit above.
