### ISSUE TITLE
Cluster configuration: akka.actor.ActorSelection$$anon$1 local class incompatible, serialVersionUID between IMB and Java VM

### ISSUE THREAD

**Issue by larreya** [akka/akka#22735]
With jboss versus IBM websphere server on cluster configuration, exception is thrown when establishing dialog:
java.io.InvalidClassException: akka.actor.ActorSelection$$anon$1; local class incompatible: stream classdesc serialVersionUID = -3019276466491037576, local class serialVersionUID = -2899751245216706739
Caused by: java.lang.ClassNotFoundException: scala.Serializable

Probable cause:
ActorSelection.scala defines anonymous class without defining serialVersionUID. Should be something like ?
    new ActorSelection with ScalaActorSelection {
      private val serialVersionUID = 1L   
      ...
    }

Detected in 2.3.9 but seems to be the same with master
Sorry if this issue is not submitted as it should be, i new to this kind of tool.

**Comment by raboof** [comment]
Hi @larreya, thanks for your report! You're indeed correct that we still use an anonymous inner class there. This might not be relevant anymore, however, as we've been moving to protobuf for serialization instead of relying on Java serialization. 

Indeed https://github.com/akka/akka/blob/master/akka-remote/src/main/protobuf/ContainerFormats.proto lists 'ActorSelection related formats', though I don't exactly see where serialization for `ActorSelection` itself is configured.

Could you test with the latest version? Also note that with the recent release of akka 2.5.0, akka 2.3 is now officially end-of-life - you might want to consider looking into upgrading (see http://doc.akka.io/docs/akka/2.4/project/migration-guide-2.3.x-2.4.x.html and http://doc.akka.io/docs/akka/2.5/project/migration-guide-2.4.x-2.5.x.html for migration guides)

**Comment by larreya** [comment]
hi @raboof , Thank you for your quick answer. I sent this issue because it seemed for me generic, but we are indirect users and depending on a software provider. I transmit your answer for future releases.

**Comment by raboof** [comment]
Hi @larreya - in fact I'm not sure where we actually ever send an `ActorSelection` - perhaps your software provider is sending them somewhere? I suspect they might need to define their own serialization for `ActorSelection` for that to work.

Anyway thanks for checking in with this issue, but as far as I can see it's not an Akka problem so I'll close it for now. If you have any further information pointing at an Akka problem feel free to re-open this issue (or create a new one).
