### ISSUE TITLE
maven binary for akka-remote_2.12_2.5.0.jar has wrong CNC version in AeronErrorLog

### ISSUE THREAD

**Issue by alapins** [akka/akka#22741]
Trying to connect to a remote actor using artery starts the AeronErrorLog class, which seems to be using an older version of the class file.  The source code says:
`
 if (CncFileDescriptor.CNC_VERSION != cncVersion)
`
(and CncFileDescriptor.CNC_VERSION = 6) but decompiling the class in the jar shows:
`
if(5 != this.cncVersion) {
`
which means that the library blows up, since the system is writing a CNC file with version 6, but the error listener must have version 5.

This seems to be the case for the 2.11 build also, since pointing to that version had the same error.

**Comment by patriknw** [comment]
You have tried to update to Aeron 1.2.4 or 1.2.5. That is not possible because the cnc version number is a compile time constant in Aeron, i.e. 5 is included in the Akka 2.5.0 class files because we built that with Aeron 1.2.3.

We will release Akka 2.5.1 soon with updated Aeron 1.2.5 dependency. Until then you have to stick to Aeron 1.2.3.

**Comment by alapins** [comment]
Thanks, that was it.
