### ISSUE TITLE
Shouldn't Delay stage be dynamic and function of the element itself?

### ISSUE THREAD

**Issue by arpanchaudhury** [akka/akka#22845]
While using the delay stage I found a use-case where delay for each element passing throw should be dynamic and a function of the element itself, i.e. ***ƒ(element).***

I have created a pull request modifying Delay class and adding a test case for the same.

Though it is not clear to me whether I should modify existing ***scaladsl*** and ***javadsl*** or add an independent stages like `delayDynamic(f: T ⇒ FiniteDuration, strategy: DelayOverflowStrategy)`

I request you to go through my changes and validate the use-case. I am open to incorporation your valuable suggestions.

**Comment by arpanchaudhury** [comment]
duplicate of #22846

**Comment by johanandren** [comment]
#22846 is the pull request, this is the ticket to track it (so reopening)

**Comment by johanandren** [comment]
Hey @arpanchaudhury, while waiting for review, could you please describe the use case. For me it is not obvious when this would be useful because of the buffer, it means that with elements `n`, `n'` and `n''`, element `n''` will actually be delayed `f(n) + f(n') + f(n'')` (given that there is no back pressure from downstream)?

**Comment by arpanchaudhury** [comment]
Hi @johanandren. 
Consider a stream of time-ordered elements where each element has an unique timestamp associated to it. The timestamp signifies its creation time and we are sending these elements to a message broker deployed on another data center. The only restriction is that the elements should arrive to the receiving data center when databases in both the data-centers are synced on or after the element timestamp. In this scenario, having a static delay duration won't help. Here we might need to different messages by different time duration. In this pull request I have tries to tackle similar scenario allowing the Delay stage to take a function from element to finite duration.

Yes, I agree that for n'' the actual delay will be `f(n) + f(n') + f(n'')` given they arrive at the same time. But if they arrive at different time delay of n'' would be `f(n) + f(n') + f(n'') - a - b` where a is arrival delay between n and n' and b is arrival delay between n' and n''.

**Comment by johanandren** [comment]
Not convinced this is general enough to be in streams core, I think the use case sounds rather narrow. WDYT @patriknw @ktoso

**Comment by arpanchaudhury** [comment]
Any thoughts on this @ktoso @patriknw?  Thanks.

**Comment by johanandren** [comment]
How does this stage compare to akka/akka-stream-contrib#89, would that cover your use case already (sorry I didn't notice the possible duplication before)?

**Comment by arpanchaudhury** [comment]
@johanandren Looks like akka/akka-stream-contrib#89 has quite similar requirements. The function introduced in PR https://github.com/akka/akka/pull/22846 can tackle it. But I doubt that having a fixed set of DelayStrategy can introduce the dynamism which is needed in my use-case.

**Comment by johanandren** [comment]
Since `DelayStrategy` is just a type around a `nextDelay(elem: T): FiniteDuration` (see the PR akka/akka-stream-contrib#90) which is exactly what this stage introduces, plus that it covers more use cases (stateful delay strategies as well). To have buffering with a strategy for overflow you could just put a `Flow.buffer` in front of that stage.  I'd propose we close this ticket and PR and you go with that stage instead.

**Comment by arpanchaudhury** [comment]
+1 to stateful delays. closing the issue an PR as duplicate of akka/akka-stream-contrib#89
