### ISSUE TITLE
IllegalArgumentException with identity flow

### ISSUE THREAD

**Issue by avakhrenev** [akka/akka#22899]
This code
```scala
Flow.fromSinkAndSource[Any, Int](
    Sink.ignore
  , Source
    .single(1)
    .via(Flow[Int])
)
```
leads to 
```
java.lang.IllegalArgumentException: Port GraphStages$Identity$.out(2108763062) cannot be accessed in this builder
        at akka.stream.impl.LinearTraversalBuilder.offsetOfModule(TraversalBuilder.scala:767)
        at akka.stream.impl.CompositeTraversalBuilder.add(TraversalBuilder.scala:1265)
        at akka.stream.impl.CompletedTraversalBuilder.add(TraversalBuilder.scala:460)
        at akka.stream.scaladsl.GraphDSL$Builder.add(Graph.scala:1102)
        at akka.stream.scaladsl.GraphApply.create(GraphApply.scala:42)
        at akka.stream.scaladsl.GraphApply.create$(GraphApply.scala:38)
        at akka.stream.scaladsl.GraphDSL$.create(Graph.scala:1035)
        at akka.stream.scaladsl.Flow$.fromSinkAndSourceMat(Flow.scala:329)
        at akka.stream.scaladsl.Flow$.fromSinkAndSource(Flow.scala:319)
```

Not sure what is going on here...

EDIT: akka version is 2.5.1

**Comment by johanandren** [comment]
Seems to be caused by the new materializer when the identity stage is triggered (`Flow[Int]`) and then the output port is used. You can likely workaround by avoiding having such an "empty" flow in there. Thanks for reporting and providing a reproducer!

**Comment by richard-imaoka** [comment]
It is probably due to [these two lines](https://github.com/akka/akka/blob/ccb587209f64f9cdc76ffc9368627defe9722fa1/akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala#L49#L50) - when I removed them, I did not see `IllegalArgumentException` from the above code snippet.

By `.via(Flow[Int])`, I am guessing the internal `TraversalBuilder` was not in a good state, and caused the exception afterwards when it was used (appended?) in `Flow.fromSinkAndSource`.

I'm still trying to understand how `TraversalBuilder` works. So if this needs to be fixed quickly, please fix it by the core team and I hope this could be a hint to the underlying issue.

If this can take some time to fix, I am happy to follow up from here.

**Comment by johanandren** [comment]
Thanks for researching it, the internals are complicated but if you are up to it then a PR would be welcome. We probably do not want to remove that, it is the optimisation that if something is run through the identity stage, then that is the same as not having a stage at all so we can use the empty flow. I think there are invalid assumptions being made elsewhere we need to look into.

**Comment by richard-imaoka** [comment]
Thanks for the advice. I'll try to submit a PR, which might take a few weeks.

If that is too long then please just ignore my attempt and fix this by the core team (or anyon else quicker than me.)

**Comment by johanandren** [comment]
Thanks, we'll make sure to ping you here if we start working on this so you don't do the work in parallel.

**Comment by richard-imaoka** [comment]
Sorry for the long comment... I am still working on this but let me record what I found so far. 

A possible solution is at the end.

## Analysis

In short, from the below code, `flow.shape` and `flow.traversalBuilder` got inconsistent on their `outlet`.

```scala
val single = Sink.single(1)
val identity = Flow[Int]

val flow = single.via(identity)
Flow.fromSinkAndSource[Any, Int](Sink.ignore, flow)
```
<image src="https://cloud.githubusercontent.com/assets/7414320/26598113/2320a6a6-45af-11e7-8680-80186f66a749.png" width=516 >

### Detailed analysis in case the above is not clear ...

As you can see in [Source's viaMat() method](https://github.com/akka/akka/blob/ccb587209f64f9cdc76ffc9368627defe9722fa1/akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala#L49#L50), it works as follows for `identity`.

```scala
val toAppend =
  if (flow.traversalBuilder eq Flow.identityTraversalBuilder)
    /**** this should be appended to Source's (single's) traversalBuilder ****/
    LinearTraversalBuilder.empty() 
```

```scala
/**** this is what Flow.fromSinkAndSource() would return ****/
new Source[T, Mat3](    
  traversalBuilder.append(toAppend, flow.shape, combine),
  SourceShape(flow.shape.out))
```

However, due to [append() method's isEmpty check](https://github.com/akka/akka/blob/ce7a7a2148517bf219799f472fc190b206b1ede8/akka-stream/src/main/scala/akka/stream/impl/TraversalBuilder.scala#L824#L826), 

```scala
if (toAppend.isEmpty) {
  /**** "copy()" is used (i.e.) toAppend = LinearTraversalBuilder.empty() is NOT appended  ****/
  /**** Instead, single.traversalBuilder is slightly modified as follows                                ****/
  copy(
    traversalSoFar = PushNotUsed.concat(LinearTraversalBuilder.addMatCompose(traversalSoFar, matCompose)))
} 
```

- The resulting `flow`'s `traversalBuilder` is in `LinearTraversalBuilder` (as what `single` had) [whose `outPort`](https://github.com/akka/akka/blob/ce7a7a2148517bf219799f472fc190b206b1ede8/akka-stream/src/main/scala/akka/stream/impl/TraversalBuilder.scala#L683) points to `single`'s `outlet`
- `flow`'s `shape` has the outlet pointing to `identity`'s outlet

Here we got **`traversalBuilder `and `shape `inconsistent**.

## A possible solution

* Add extra "is-identity-traversa- builder" check (if-clause) in  [append() method](https://github.com/akka/akka/blob/ce7a7a2148517bf219799f472fc190b206b1ede8/akka-stream/src/main/scala/akka/stream/impl/TraversalBuilder.scala#L824#L826)

* Then, remove [these two lines](https://github.com/akka/akka/blob/ccb587209f64f9cdc76ffc9368627defe9722fa1/akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala#L49#L50)

With this approach, we can still avoid running the full `append` method logic for `identity`, for optimization.

**Comment by drewhk** [comment]
Hm great analysis!

**Comment by drewhk** [comment]
Isn't the cleanest solution is to just fix `viaMat` to use the proper output port? : https://github.com/akka/akka/blob/ccb587209f64f9cdc76ffc9368627defe9722fa1/akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala#L56

I.e. probably just use:

```scala
  if (flow.traversalBuilder eq Flow.identityTraversalBuilder)
     this.asInstanceOf[...]
  else
    new Source[T, Mat3](
      traversalBuilder.append(toAppend, flow.shape, combine),
      SourceShape(flow.shape.out))
```

**Comment by richard-imaoka** [comment]
I tried this:
>this.asInstanceOf[Source[T, Mat3]]

but [GraphMatValueSpec](https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala#L232) failed 

`val (m1, m2) = Source.single(1).viaMat(Flow[Int])(Keep.both).to(Sink.ignore).run()`

with the following error, as `Keep.both` was not respected:

>[info]   java.lang.ClassCastException: akka.NotUsed$ cannot be cast to scala.Tuple2

Hmm I'll need to figure out how to convert it to the right materialization type...

**Comment by richardimaoka** [comment]
I submitted a pul request but it doesn't look like a very clean solution... if you could have a look and leave comments, that'll be much appreciated.

**Comment by drewhk** [comment]
I will. I had an idea how to solve this properly but had no time to PR.
