### ISSUE TITLE
serialization-bindings should be ordered

### ISSUE THREAD

**Issue by benmccann** [akka/akka#22941]
If an instance extends from multiple interfaces or traits then I believe Akka just prints out a warning and picks a serialization binding randomly. I would really like to see this be a list ordered by priority

E.g. instead of:

    serialization-bindings {
      "java.lang.String" = java
      "docs.serialization.Customer" = java
      "com.google.protobuf.Message" = proto
      "docs.serialization.MyOwnSerializable" = myown
      "java.lang.Boolean" = myown
    }

Maybe we could have:

    serialization-bindings [
      { "java.lang.String" = java },
      { "docs.serialization.Customer" = java },
      { "com.google.protobuf.Message" = proto },
      { "docs.serialization.MyOwnSerializable" = myown },
      { "java.lang.Boolean" = myown }
    ]

**Comment by johanandren** [comment]
That would not be possible because of how we register serializers in multiple `reference.conf` files that can be loaded in any order internally in Akka, in addition to be a very invasive change. If it wasn't for there being plenty of `Map`s used inside of serialization you could have used the new `akka.serialization.SerializationSetup` as allows you to define a function that returns a `Seq` where you could load your serializers in whatever order you'd like.

I think I'd recommend to try to not have multiple overlapping serializers if possible instead of changing this. Another way could be to define a specific marker trait to leverage the following aspect of serialization:
> In case of ambiguity, i.e. the message implements several of the configured classes, the most specific configured class will be used, i.e. the one of which all other candidates are superclasses.
(from here: http://doc.akka.io/docs/akka/2.5.1/scala/serialization.html#creating-new-serializers)
That's how we do it in Lagom (https://github.com/lagom/lagom/blob/e53bda5fd2f83aaa4cd639c9ad27d6053ede812f/jackson/src/main/scala/com/lightbend/lagom/serialization/Jsonable.scala#L15)

**Comment by patriknw** [comment]
@benmccann can you show an example of the specific classes that was the problems and perhaps we can advice. There are some tricks.

**Comment by benmccann** [comment]
This was actually motivated by wanting to remove `Jsonable` from Lagom and set Jackson as the default serializer without needing to use `Jsonable` - https://github.com/lagom/lagom/issues/744

There are perhaps still ways of ordering. E.g. we could set an integer priority with each serializer. Or we could just have a default serializer, which is potentially easier.

**Comment by patriknw** [comment]
but what was the problem with using
```
serialization-bindings {
  "java.io.Serializable" = none
  "java.lang.Object" = lagom-json
}
```
or 
```
serialization-bindings {
  "java.io.Serializable" = lagom-json
  "java.lang.Object" = lagom-json
}
```

You can also try to combine that with disabling the Java serializer altogether: http://doc.akka.io/docs/akka/2.4/java/remoting.html#Disabling_the_Java_Serializer

**Comment by benmccann** [comment]
I think it should generally work. I haven't tested it yet. The only concern I had is that this means folks can use only one serializer for their whole project. That might be fine in most scenarios as I don't know people will necessarily want to mix-and-match

**Comment by patriknw** [comment]
Of course you can have many serializers, you just need several marker interfaces. Closing this, you are welcome back if you can illustrate a concrete problem within the bounds of how akka serialization is designed.
