### ISSUE TITLE
possible memory leak when using sharding

### ISSUE THREAD

**Issue by tkesslerKedev** [akka/akka#23019]
![leak suspect1](https://cloud.githubusercontent.com/assets/7119677/26363868/b39d97ca-3fe2-11e7-9dd1-0f32a7ceff36.JPG)
![leak suspect2](https://cloud.githubusercontent.com/assets/7119677/26363886/cd43230c-3fe2-11e7-93d6-a0622a214e10.JPG)

We use akka 2.5.1 with cluster, sharding and cassandra persistence.

When executing load tests we find most of the heap being consumed by instances of akka.actor.LocalActorRef.

After several minutes of load test we see about 840k instances of LocalActorRef which seem not to be garbage collected.

Do you have any idea what could case such behavior?

**Comment by ktoso** [comment]
This simply means you're starting a lot of actors and not stopping them. Actors have explicit lifecycles - please read the docs: http://doc.akka.io/docs/akka/current/scala/actors.html#Actor_Lifecycle && http://doc.akka.io/docs/akka/current/scala/actors.html#stopping-actors-scala

You need to drill down into these actors and in the report and find out what exact instances those are (or paths / names, that's more useful), and then you can figure out where you have your leak. 

You may also want to try monitoring tooling that would show you this in useful ways: https://developer.lightbend.com/docs/cinnamon/latest/images/datadog-akka-screenboard.png (docs here https://developer.lightbend.com/docs/cinnamon/latest/home.html ), like counts of actors etc - pretty sure you'll see that you keep adding new ones and they never stop.

Github issues are not the right place really for assistance in debugging your system - please prefer to use the mailing list for support with your apps, and let's keep the issues for tracking actionable issues in akka itself. 

We don't have reason to suspect the leak is in Akka itself, there's no real way we can look into it without a reproducer from a ticket like this, and I hope my hint how to identify where you're leaking is helpful - so I'm going to close this issue. If you are able to confirm that it is a bug indeed please provide additional info here and we'll reopen (otherwise please use the mailing list https://groups.google.com/forum/#!forum/akka-user )

**Comment by tkesslerKedev** [comment]
that's the only way we create actor instances. Following code snippet is from the supervisor actor which creates the actor instances:

```
		final ClusterShardingSettings shardingSettings = ClusterShardingSettings.create(system);
		final ClusterSingletonManagerSettings singletonSettings = ClusterSingletonManagerSettings.create(system);
		clusterSharding = ClusterSharding.get(system);
		final MessageExtractor messageExtractor = new MessageExtractor(procConfig.getNumberOfShards());

		final Props pemSenderProps = Props.create(PemSender.class, httpClient, procConfig);
		Props pemSenderSupervisorProps = BackoffSupervisor.props(Backoff.onFailure(pemSenderProps, PEMSENDER_ACTOR, Duration.create(procConfig.getSupervisorMinRestartDelay(), TimeUnit.SECONDS),
				Duration.create(procConfig.getSupervisorMaxRestartDelay(), TimeUnit.SECONDS), 0.2).withSupervisorStrategy(strategy));
		pemSender = clusterSharding.start(PEMSENDER_ACTOR, pemSenderSupervisorProps, shardingSettings, messageExtractor);
		logger.debug("created actor: " + pemSender.path());
```

I've checked the logs, the creation of actors is executed only once, but 1000s of LocalActorRefs are in memory.

**Comment by patriknw** [comment]
Could you provide a minimized reproducer of the problem and we will look into it.
For example, how many different entities do you exercise in the test and when do you stop those?

**Comment by tkesslerKedev** [comment]
I'll try to extract a reproducer. I've added some debug logic printing the stack trace when new instances of the actor are created. This is the output:

INFO  09:11:35.285 [MonitoringMessageProcessor-akka.actor.default-dispatcher-23] d.d.r.s.m.MonitoringMessageParser - new instance of MonitoringMessageParser created:
java.lang.Thread.getStackTrace(Thread.java:1556)
de.dbschenker.rail.sresb.monitoringmessageprocessor.MonitoringMessageParser.<init>(MonitoringMessageParser.java:57)
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
akka.util.Reflect$.instantiate(Reflect.scala:65)
akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
akka.actor.Props.newActor(Props.scala:213)
akka.actor.ActorCell.newActor(ActorCell.scala:555)
akka.actor.ActorCell.create(ActorCell.scala:581)
akka.actor.ActorCell.invokeAll$1(ActorCell.scala:454)
akka.actor.ActorCell.systemInvoke(ActorCell.scala:476)
akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
akka.dispatch.Mailbox.run(Mailbox.scala:223)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by tkesslerKedev** [comment]
Do you have any idea why "Create" system messages are sent for each of our messages?

**Comment by tkesslerKedev** [comment]
I have found the cause...

```
public class MessageExtractor extends ShardRegion.HashCodeMessageExtractor {

	public MessageExtractor(int maxNumberOfShards) {
		super(maxNumberOfShards);
	}

	@Override
	public String entityId(Object entity) {
		return entity.getClass().getName() + entity.hashCode();
	}
}
```

We were using the HashCodeMessageExtractor to spread load over shards. But the entityId will be included into the actor Path so that the path differs for each message. The following snippet shows the code that works fine avoiding creating lots of actor instances:

```
public class MessageExtractor extends ShardRegion.HashCodeMessageExtractor {

	public MessageExtractor(int maxNumberOfShards) {
		super(maxNumberOfShards);
	}

	@Override
	public String entityId(Object entity) {
		return entity.getClass().getName();
	}
}
```

**Comment by patriknw** [comment]
Good that you found the problem, but sounds like you have misunderstood the concept of entityId. The entityId is something you extract from the message, e.g. a user-id, and for each unique entityId there will be one entity actor hosted by Cluster Sharding. E.g. send all messages for user "abc123" to a specific entity actor.

In that code you use the class name of the message, meaning that there will be one entity actor for each message class (probably not many), and different message classes will be sent to different entities.

**Comment by tkesslerKedev** [comment]
As far as I understood the behavior: The reason why so many actor instance had been created was, that the entityId is included into the actor path. Eliminating too many different entityIds solved the issue.
