### ISSUE TITLE
GraphDSL not working with mapConcat

### ISSUE THREAD

**Issue by patrykpacewicz** [akka/akka#23179]
Hi,

I'd like to write a function that would allow me to wrap `Flow[...]` in such a way that the outcome will be `Tuple2[In, Out]`, something like:

```scala
  def fun: Flow[In, Out, _] -> Flow[In, (In, Out), _]
```

I have successfully created working piece of code using `GraphDSL`.

```scala
  private def zipWithInput[In, Out, _](flow: Flow[In, Out, _]) = {
    Flow.fromGraph(GraphDSL.create() { implicit builder =>
      import GraphDSL.Implicits._

      val broadcast = builder.add(Broadcast[In](2))
      val zip = builder.add(Zip[In, Out]())

      broadcast.out(0) ~> zip.in0
      broadcast.out(1) ~> flow ~> zip.in1

      FlowShape(broadcast.in, zip.out)
    })
  }
```

I noticed that code I created is not working when `flow` inside the graph is using function ` mapConcat`. Example use case below.

```scala
import akka.actor.ActorSystem
import akka.stream.scaladsl._
import akka.stream._

object ExampleService extends App {
  implicit val system: ActorSystem = ActorSystem("actor-system")
  implicit val materializer: Materializer = ActorMaterializer()

  exampleOk.run() ; Thread.sleep(1000)
  exampleFail.run() ; Thread.sleep(1000)

  def exampleOk = Source(List("AAA", "BBB", "CCC"))
    .via(zipWithInput(simpleFlow))
    .mapConcat { case (prev, act) => act.map(prev -> _)}
    .to(Sink.foreach(println))

  def exampleFail = Source(List("AAA", "BBB", "CCC"))
    .via(zipWithInput(simpleFlow.mapConcat(a => a)))
    .to(Sink.foreach(println))

  private def simpleFlow = Flow[String]
    .map(key => {println(s"simpleFlow: ${Map("key" -> key)}"); key;})
    .map(_ => List("111", "222", "333"))
}
```

Is that a bug ? Or did I do something incorrectly?

**Comment by richard-imaoka** [comment]
Hi sorry to jump in, but I investigated this issue, and found this seems expected behavior.

Let me know if anything below is wrong or unclear.

## exampleOk

```scala
.via(zipWithInput(simpleFlow))
.mapConcat { case (prev, act) => act.map(prev -> _)}
```

This works ok, because `mapCocat` is outside the stage created by `zipWithInput`.
The `mapCocat` requires 3 demands (for `(AAA, 111)`,  `(AAA, 222)`,  `(AAA, 333)` ) from the downstream, to pull the next element (`BBB`) from the original source.

![image](https://user-images.githubusercontent.com/7414320/27518015-2a435afc-5a11-11e7-9839-5e098941f612.png)

## exampleFail

```scala
 .via(zipWithInput(simpleFlow.mapConcat(a => a)))
```

This does not work, because the inlet 1 and inlet 2 of `Zip` **need to send different number of demands** to pull the next element.

* The upper flow in the picture requires 1 demand to pull `AAA`, and only one more demand to pull `BBB`
* However, the lower flow requires 3 demands to pull `(AAA, 111)`, `(AAA, 222)`, `(AAA, 333)` before pulling `BBB` due to `mapConcat` in between

![image](https://user-images.githubusercontent.com/7414320/27518019-3ad1013a-5a11-11e7-8650-a0394343ae32.png)

**Comment by patriknw** [comment]
Seems answered.
Thanks @richardimaoka
