### ISSUE TITLE
Reachability observations

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23273]
I gathered a few observations on the reachability implementation I'd like to note down here. It might be that nothing needs to be changed but I guess we could add more (code) documentation if needed.

Observations (correct me if I read the code incorrectly):
 * There are three reachability states defined for an observer / subject pair: `Reachable` / `Unreachable` / `Terminated`
 * Reachability does not keep records for an observer for which all observed nodes are `Reachable`
 * (As documented) `Reachability`'s reachable/unreachable/terminated/change methods are only called by the observing node itself
 * `change` increments the version counter for the observer node, so, it is important that a node creates records only for its own observations
 * in `Reachability.merge` only that set of observer records are kept that have seen the highest version number.

Discussion:
 * It seems there's an implicit state, `Unknown`, that isn't represented explicitly. Instead, `Unknown` is always interpreted as `Reachable` afaiu. Is that never a problem in practice?
 * Is it guaranteed that a node has seen all records for an observer (or observer / subject pair)? Otherwise, it seems the merge logic might throw away data. E.g. two instances of `Reachability` are merged, one has seen records [1,2,4] and the other [1,2,3], then merge would choose [1,2,4] (because it has the highest version number) and record 3 would be lost.
   * I guess the answer is "yes, it is guaranteed that each node sees a complete consistent set of records per observer" because an observer doesn't publish single observation records but always the complete set of up-to-date records, i.e. if a record is missing it can only be because it was overridden by a newer observation.
   * The extra set of `Reachability.versions` is needed especially in the case that an observer doesn't publish any records (i.e. all observed nodes are currently reachable). In other cases, `versions` should contain the highest version of any of the published records.
 * Is `Record.version` redundant? It seems it is only read in serialization and for `toString`.

**Comment by patriknw** [comment]
Sounds right.

> It seems there's an implicit state, Unknown

You mean when nobody is observing a node, it's not possible to distinguish that from that from a healthy link? It is based on that there should be enough coverage by observing 5 other nodes (configurable if one want more), and it's not random 5.

> records [1,2,4] and the other [1,2,3]

The full table is always in the gossip, so I don't see a way to see  [1,2,4] because it would be [1,2,3, 4], but it was a long time I implemented this so I'm not up to date with the details

**Comment by jrudolph** [comment]
> You mean when nobody is observing a node, it's not possible to distinguish that from that from a healthy link?

Yes, basically. But not because no node is configured to observe another node, but because it *currently* is not (or has not yet) been observed. That could be a) at startup or b) while one observer is "letting slide its duties" for whatever reason or c) for some reason gossip doesn't reach us any more.

**Comment by jrudolph** [comment]
What about scalability of the reachability information? The number of edges is proportional to the square of number of nodes while the edges checked by heartbeats only grows linearly with the number of nodes (each node checks a fixed number of other nodes). That means that for small clusters it is likely that most links are checked, but for bigger ones not all links might be checked. E.g. with each node observing 5 others:

| Nodes | Edges | Checked | Coverage |
|-|-|-|-|
|3|3|all|100%|
|5|10|all|100%|
|10|45|all|100%|
|15|105|75|71%|
|20|190|100|53%|
|30|435|150|34%|
|100|4950|500|10%|

(For gossip it shouldn't be a problem: as long as the graph is well connected enough and the gossip paths are not convoluted (e.g. by choosing gossip nodes in a weird way) gossip should spread fast enough)

Another potential complication could be that gossip takes different paths then the heartbeats, but I haven't thought through what or if that means anything.

**Comment by patriknw** [comment]
Gossip and heartbeating are two different things. The information from failure detector, the `Reachability` table, is disseminated to other nodes with Gossip, but that's all connection between them.

The purpose has not been to know the status of each and every edge, but to know if a node is deemed unreachable  by someone. Finding when a node is:
a) crashed
b) unresponsive (GC, CPU overload)
c) separated because of network partition (typically a group of nodes are partitioned together)

I don't know if it matters for the discussion, but the choice of nodes to observe are not random. It orders the nodes and takes 5 neighbors, but the order is based on hashed address values to avoid only observing neighbors in same rack. https://github.com/akka/akka/blob/master/akka-cluster/src/main/scala/akka/cluster/ClusterHeartbeat.scala#L252

**Comment by jrudolph** [comment]
I see, so, right now it is very likely that a node that is completely failing or isolated is detected but not every single failing link.

In other words, the assumption is that if every node exchanges heartbeats successfully with 5+5 nodes incoming and outgoing, it is likely enough that it is still reachable.

I don't really know if that's reasonable. E.g. if there are 20 racks with 5 nodes, and only the intra-rack network is down for some reason, how would that be detected? And is that a reasonable setup and failure mode?

**Comment by patriknw** [comment]
You mean that it's too high risk that a node is not observed by any of the other nodes in the same rack and therefore such network failure would go undetected. Is this how such networks will fail (I don't know)? Will they still be reachable from outside the rack?

In practice I think it becomes an issue only if all nodes in the rack are not observed by any other node in the rack. Because after one has been detected that will be removed (if you use some downing) and then there is adjustments to the heartbeat ring.

Do you have suggestions of what to improve?

**Comment by jrudolph** [comment]
> You mean that it's too high risk that a node is not observed by any of the other nodes in the same rack and therefore such network failure would go undetected. Is this how such networks will fail (I don't know)? Will they still be reachable from outside the rack?

I don't really know if it is realistic. I just tried to come up with a scenario to clarify assumptions.

I think for now it's probably good enough for most cases. I'm going to close this issue. Thanks for all the input!
