### ISSUE TITLE
AbstractPersistentFSMBase onTransition multiple handlers not being triggered

### ISSUE THREAD

**Issue by agauci** [akka/akka#23296]
The Javadocs of AbstractPersistentFSMBase.onTransition(FSMTransitionHandlerBuilder) claim that "multiple handlers may be installed and every one of them will be called, not only the first one matching". However, the following code

`
onTransition(
   matchState(null, null, () -> System.out.println("Handler 1"))
   .state(null, null, () -> System.out.println("Handler 2"))
);
`

only outputs "Handler 1" on each transition, even though both handlers should match. Is this a bug, or is documentation outdated?

**Comment by patrox** [comment]
@agauci I have checked this issue (as it sounds quite strange), and I can confirm that it works just like you described - and I also think this is not the intended behaviour.

What's interesting is the fact that if you register the `TransactionHandler`s separately, it will work,
so your code would need to be rewritten as:

```
  onTransition(matchState(null, null, () -> System.out.println("Handler 1")));
  onTransition(matchState(null, null, () -> System.out.println("Handler 2")));
```

I'll try to create a test which will reproduce this behaviour.

**Comment by patrox** [comment]
After digging in a bit deeper, I think I already understand what's going on, as when you're passing multiple `TransactionHandler`s each of them is treated as `PartialFunction` which are combined here:

https://github.com/akka/akka/blob/master/akka-actor/src/main/java/akka/japi/pf/AbstractPFBuilder.java#L20-L25

But, if you take a look there - then combining `PartialFunction` works based on the first argument, which is a `Tuple2(null, null)` - and since it's already defined after first handled, then the second one is not called.

**Comment by agauci** [comment]
That indeed seems to be the case. I think we need clarification whether this behaviour is intended or not. As a consumer of the API, it does not seem correct to me.

**Comment by raboof** [comment]
We're phasing out PersistentFSM in favour of Persistence Typed - so we should rather focus on that.
