### ISSUE TITLE
BackoffSupervisor and restart documentation is confusing/inaccurate

### ISSUE THREAD

**Issue by npiguet** [akka/akka#23406]
Hello,

I've just spent a day figuring out why my actor's `preRestart()` and `postRestart()` methods were not called when my actor was restarted.

Turns out that while there is a very clear documentation of "What restarting means", the documentation for BackoffSupervisor uses the term "restart" all the time, but does not actually implement the documented restarting lifecycle. BackoffSupervisor doesn't "restart" actors, but actually "stops" them ASAP, and the "starts" them later, skipping all of the documented restart lifecycle steps.

The documentation of BackoffSupervisor (in /general/supervision.html) should be updated to reflect that fact, either by using an extra paragraph, by not using the term "restart" and/or by defining and using another term for that behavior.

Note that the API of BackoffSupervisor can take a SupervisionStrategy from which you must return `restart`, and then the actions taken by the supervisor is not a true restart. That is quite confusing.

**Comment by johanandren** [comment]
Hi @npiguet, thanks for reporting, you up for PR:ing such an improvement?

**Comment by richardimaoka** [comment]
Wasn't it because of difference between `Backoff.onStop` and `Backoff.onFailure`?
I saw a child created with `Backoff.onStop` execute `preRestart()` and `postRestart`, although one with `Backoff.onFailure` do not execute them as @npiguet described.

https://gist.github.com/richardimaoka/79321d28bcc2a7e95e4ccf0bddb85529

**Comment by guiangit** [comment]
First I want to give a huge thank you for the comments posted on this topic!  It was driving me nuts trying to understand what was wrong with my BackoffSupervisor.

As far as I can tell, BackoffSupervisor just has bugs - it doesn't work. I need the preRestart method to be called if I'm going to delegate the restart handling to a BackoffSupervisor, but the methods are _not_ called unless you use Backoff.onStop(), but then when I do this, (at least in my testing) there is no delay between the restarts! If I was a scala developer I might try to step thru the code and understand why the behavior is so flawed, but I'm not, so my best option is to write my own backoff-and-retry logic in java. That's fine, but this really makes me question the integrity and value of the whole Akka framework.

**Comment by patriknw** [comment]
Contribution to improve the documentation for the BackoffSupervisor is welcome.

For the record, in new Akka Typed actors backoff supervision is part of the normal supervision concept. That is not possible to implement with the untyped actors due to how supervision is implemented internally. Therefore we added `BackoffSupervisor` as a facility for this common pattern of having a parent actor that manages stop-backoff-start ("restart").

**Comment by patriknw** [comment]
> I need the preRestart method to be called if I'm going to delegate the restart handling to a BackoffSupervisor, but the methods are not called unless you use Backoff.onStop(), but then when I do this, (at least in my testing) there is no delay between the restarts!

I assume that you test that by throwing an exception in the child and that is not handled by `Backoff.onStop` and therefore handled by normal default supervision which means immediate restart. 

> I saw a child created with Backoff.onStop execute preRestart() and postRestart, although one with Backoff.onFailure do not execute them as @npiguet described.

That is because when using `Backoff.onFailure` the BackoffSupervisor (parent) will stop the child when an exception is caught, to be able to pause for the backoff period, and then start it again.

Perhaps you can use the `preStart` (or constructor) and `postStop` hooks instead?

**Comment by micheal-hill** [comment]
I'm not sure if this is the correct place for this; but with regards to `Backoff.onFailure`, there appears to be a few other gaps in documentation:
- `maxNrOfRetries` seems to be ignored. Setting a custom `SupervisorStrategy` which provides its own `maxNrOfRetries` works, but setting this parameter within `onFailure(maxNrOfRetries = ???)` doesn't do anything
- After `maxNrOfRetries` is exceeded, the failure is not escalated to the parent actor (unlike the regular failure behavior when not using the BackoffSupervisor)

**Comment by rocketmannot** [comment]
> makes

This is true for `onFailure` delay is not working - the supervisor immediately restarts the child actor with min backoff interval. I was able to debug to the place - where I understood that internally, backoff supervisor fails to calculate the count of retries - thus - number of retries always 0. And as the result of that back off interval is calculated incorrectly. I am not a scala dev, so can not proceed with  the fix.

**Comment by johanandren** [comment]
@rocketmannot I think what you are describing has recently been fixed #27590 (not in a release yet though)

**Comment by rocketmannot** [comment]
> @rocketmannot I think what you are describing has recently been fixed #27590 (not in a release yet though)
Yes, looks like this is the same issue. Thank you!
