### ISSUE TITLE
Documentation is insufficient for Flow.groupBy

### ISSUE THREAD

**Issue by unoexperto** [akka/akka#23461]
Could you guys explain how to use new `groupBy` in akka-streams ? [Documentation][1] seems to be quite useless. `groupBy` used to return `(T, Source)` but not anymore. Here is my example (I mimicked one from docs):

    Source(List(
      1 -> "1a", 1 -> "1b", 1 -> "1c",
      2 -> "2a", 2 -> "2b",
      3 -> "3a", 3 -> "3b", 3 -> "3c",
      4 -> "4a",
      5 -> "5a", 5 -> "5b", 5 -> "5c",
      6 -> "6a", 6 -> "6b",
      7 -> "7a",
      8 -> "8a", 8 -> "8b",
      9 -> "9a", 9 -> "9b",
    ))
      .groupBy(3, _._1)
      .map { case (aid, raw) =>
        aid -> List(raw)
      }
      .reduce[(Int, List[String])] { case (l: (Int, List[String]), r: (Int, List[String])) =>
      (l._1, l._2 ::: r._2)
    }
      .mergeSubstreams
      .runForeach { case (aid: Int, items: List[String]) =>
        println(s"$aid - ${items.length}")
      }

This simply hangs. Perhaps it hangs because number of substreams is lower than number of unique keys. But what should I do if I have infinite stream ? I'd like to group until key changes.

In my real stream data is always sorted by value I'm grouping by. Perhaps I don't need `groupBy` at all ?

  [1]: http://doc.akka.io/docs/akka/current/scala/stream/stream-cookbook.html#implementing-reduce-by-key

**Comment by johanandren** [comment]
Did you also look at the scaladoc of the `groupBy` method (which is quite extensible) but still find it insufficient, or did you just read the stream cookbook from the docs? http://doc.akka.io/api/akka/current/akka/stream/javadsl/Flow.html#groupBy[K](maxSubstreams:Int,f:akka.japi.function.Function[Out,K]):akka.stream.javadsl.SubFlow[In,Out@scala.annotation.unchecked.uncheckedVariance,Mat]

**Comment by johanandren** [comment]
Ups. Wrong link, this one is the scaladsl: http://doc.akka.io/api/akka/current/akka/stream/scaladsl/Flow.html#groupBy[K](maxSubstreams:Int,f:Out=>K):akka.stream.scaladsl.SubFlow[Out,Mat,FlowOps.this.Repr,FlowOps.this.Closed]

**Comment by richardimaoka** [comment]
The code snippet by @unoexperto actually fails due to this, which is described in scaladoc @johanandren referenced:

```
   * @param maxSubstreams configures the maximum number of substreams (keys)
   *        that are supported; if more distinct keys are encountered then the stream fails
```

You will see this result, by adding `watchTermination` to the code snippet and run it:

> failure a = java.lang.IllegalStateException: Cannot open substream for key '4': too many substreams open

```scala
...
...
.mergeSubstreams
.watchTermination()(Keep.both)
.runForeach { case (aid: Int, items: List[String]) =>
  println(s"$aid - ${items.length}")
}

import scala.concurrent.ExecutionContext.Implicits.global
a.onComplete{
  case Success(a) => println(s"success a = ${a}")
  case Failure(a) => println(s"failure a = ${a}")
}
Thread.sleep(2000)
```

On the other hand, I agree with @unoexperto that the documentation for `groupBy` is not very easy to understand. 

### Suggestion

What if I add a brand new page describing SubStream (`SubFlow`?) and relevant operations like `groupBy`? (i.e.) `paradox/scala/stream/substream.md`. 

I feel like SubStream/SubFlow is a bit difficult concept to understand, so a dedicated page with decent explanation + visualization [like this](http://doc.akka.io/docs/akka/current/scala/stream/stream-composition.html) would help. Then more concrete examples in [Streams Cookook](http://doc.akka.io/docs/akka/current/scala/stream/stream-cookbook.html#implementing-reduce-by-key) would be much easier to understand.

Happy to work on it if the akka team agrees.

**Comment by johanandren** [comment]
Sounds great to me!

**Comment by unoexperto** [comment]
Could you guys provide link to paradox/scala/stream/substream.md ? I couldn't find it.
