### ISSUE TITLE
Akka SLF4J logback : can not  print  function name (methods) and line number

### ISSUE THREAD

**Issue by michaelqxd** [akka/akka#23477]
i want to print function name (methods) and line number in the log file. this is my configure:
logback.xml
...
     <encoder>
         <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36}:%M\(%L\) - %msg%n</pattern>     </encoder>
 ...

and 

actor.confakka {   
    # JVM shutdown, System.exit(-1), in case of a fatal error,   
    # such as OutOfMemoryError 
    jvm-exit-on-fatal-error = off
    loglevel = "DEBUG"
    loggers = ["akka.event.slf4j.Slf4jLogger"]
}

use this configure, it can print log, but don't show the correct function name and line number as my expecting.

this is the log in log file:
18:31:13.222 [Akka-akka.actor.default-dispatcher-3] DEBUG o.t.s.a.session.SessionManagerActor:apply$mcV$sp(82) - Entering 
18:31:13.225 [Akka-akka.actor.default-dispatcher-3] DEBUG o.t.s.a.session.SessionManagerActor:apply$mcV$sp(82) - Entering 
18:31:13.228 [Akka-akka.actor.default-dispatcher-3] DEBUG o.t.s.a.session.SessionManagerActor:apply$mcV$sp(82) - [msrp] Creating session actor.

you can see, it always print function name as "apply$mcV$sp" and line number 82. 

this is only for log triggered from Akka actor, other part works fine.

then how can i print correct function name and line number for log triggered from Akka actor?

**Comment by johanandren** [comment]
This is not really related to Akka but has to do with Scala. `apply$mcV$sp` is how the function is encoded by Scala to run on the JVM, not sure you can do anything about this except for making the function a method instead and calling that rather than using an inline lambda, it should have the right line number though.

See for example: http://grokbase.com/t/gg/scala-user/141fv49b92/scalalogging-slf4j-anonymous-functions-inconsistent-class-method-names-in-log where someone asked pretty much the same question.

**Comment by johanandren** [comment]
Closing this as there was no more communication.

Please use the mailing list or the gitter channel for questions like this, thanks!

**Comment by AbishekDia** [comment]
You can try like following: 

public static String getCallingMethodName()
    {
        return Thread.currentThread().getStackTrace()[2].getMethodName();
    }
    
    private static String getCallingClassName()
    {
        return Thread.currentThread().getStackTrace()[2].getClassName();
    }
