### ISSUE TITLE
failed: FanInThroughputSpec - unknown compression table version

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23504]
```
[JVM-1] [WARN] [08/10/2017 07:12:49.108] [FanInThroughputSpec-akka.remote.default-remote-dispatcher-4] [InboundManifestCompression(akka://FanInThroughputSpec)] Inbound message from originUid [4619853411792460895] is using unknown compression table version. It may have been sent with compression table built for previous incarnation of this system. Versions activeTable: 13, nextTable: 14, incomingTable: 11
[JVM-1] [WARN] [08/10/2017 07:12:49.109] [FanInThroughputSpec-akka.remote.default-remote-dispatcher-4] [InboundManifestCompression(akka://FanInThroughputSpec)] Inbound message from originUid [4619853411792460895] is using unknown compression table version. It may have been sent with compression table built for previous incarnation of this system. Versions activeTable: 13, nextTable: 14, incomingTable: 11
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5164/consoleText

**Comment by patriknw** [comment]
We'll probably have to try to reproduce this with debug logging to understand what is going on.

**Comment by patriknw** [comment]
I think this is a real bug. Noticed it when doing one of the 50 node tests. See attached.
[log-compression-version.zip](https://github.com/akka/akka/files/1221976/log-compression-version.zip)

**Comment by ktoso** [comment]
I’ll look into it tomorrow then, thanks

—
Konrad `kto.so` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 14 August 2017 at 19:41:41, Patrik Nordwall (notifications@github.com)
wrote:

I think this is a real bug. Noticed it when doing one of the 50 node tests.
See attached.
log-compression-version.zip
<https://github.com/akka/akka/files/1221976/log-compression-version.zip>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/issues/23504#issuecomment-322158452>, or mute
the thread

**Comment by patriknw** [comment]
`ActorRefCompressionAdvertisementAck` is sent over the control stream, so even that is sent after the `changeActorRefCompression` in the `Encoder` it may overtake an ordinary message that is in flight with the old compression version. When the old message arrives the version has already been bumped on the receiving side. We only keep one old table.

I could reproduce this with FanInThroughputSpec when adding a `sleep(1)` in the `Encoder` of the ordinary message stream.

**Comment by ktoso** [comment]
Working on it - we'll keep more old tables in memory as a solution for now.
Other solutions wind up being too complex

**Comment by jrudolph** [comment]
Another instance: https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/811/consoleFull

**Comment by patriknw** [comment]
should be fixed in https://github.com/akka/akka/pull/23546
