### ISSUE TITLE
Configuration lists and environment variables

### ISSUE THREAD

**Issue by talpr** [akka/akka#23600]
Hi,

We use Akka for many of our applications/services and run them in Kubernetes, passing in environment-related information (host names, etc.) via environment variables. Many of these applications use akka-cluster and akka-persistence-cassandra, both of which require a list of nodes as part of their configuration. However, there is no way to pass these via environment variables, so we have to add code that manually parses the environment variable, creates a Config that only contains that, and falls back on the actual config file. (The suggested workaround is using system properties, but that doesn't really fit well with the way we run our applications)

This is not ideal for a couple of reasons:
It divides the config to separate places, instead of everything being contained in 1 file.
It's basically the same code, duplicated for every env variable / config setting we care about.
Now, this issue has been raised [several](https://github.com/typesafehub/config/pull/168) [times](https://github.com/typesafehub/config/issues/320) in Typesafe Config (even by @patriknw [once](https://github.com/typesafehub/config/issues/69)), and there is even a [merged PR](https://github.com/typesafehub/config/pull/427) to support passing lists via environment variables, but the library hasn't had a release in about a year, and there's no mention of when and if there will be a new one.

I think there are a couple of ways this issue can be handled:

1. A new release of Typesafe Config. This would be ideal, but I'm not sure Lightbend/Typesafe have the resources for this.
2. Allow these kinds of list properties in Akka (I don't know if there are others, but I assume so) to be configured via a string as well. For example, checking if the "seed-nodes" config exists, and if not falling back to parsing "seed-nodes-str" (or vice-versa). This would add some ugliness to the Akka codebase, but it will solve the problem without having to wait for Config. (And I don't mind making a PR for this, so it doesn't even require much resources from Lightbend).

**Comment by vvraskin** [comment]
+1 
We face the same issue with `akka.cluster.seed-nodes` variable.
I've tried 3 more or less reasonable options to specify the array via env vars or alike: typesafe application.conf reading from env vars, reading the env var from within the code and appending it during the runtime, pass a runtime parameter to JVM to override the config. Non of them worked as expected.  
Currently we parse the params as a list of IPs and then wrap them into the required array syntax, which is not the _cleanest_ solution, since it splits the config specification into several parts. 

Would be happy to contribute here if you provide some directions. 

Thanks, 
Vadim

**Comment by vvraskin** [comment]
+1
We face the same issue with the `akka.cluster.seed-nodes` parameter. I've tried 3 more or less reasonable ways to configure it from the outside using env vars or alike: configured typesafe `application.conf` to read it from the environment, parsed the env var containing the property from within the code, and specified the JVM option during the runtime that were overriding the default config. Non of them worked as expected. 
Currently our working solution is to read the seed IPs from within the code wrapping them into an array syntax. It does not look like the _cleanest_ way to provide the config, since we have to specify and parse the config in the several places. 

That would be great if you could prioritise this issue, or get some directions how I can contribute here. 

regards, Vadim.

**Comment by johanandren** [comment]
One option could be to add support for specifying the seed nodes completely programatically using the somewhat new [ActorSystemSetup](http://doc.akka.io/api/akka/current/akka/actor/setup/ActorSystemSetup.html) APIs instead of touching the way config is parsed.

**Comment by 2m** [comment]
There were a few another requests for a new release ([1](https://github.com/typesafehub/config/issues/465), [2](https://github.com/typesafehub/config/issues/472)). Lets coordinate in https://gitter.im/typesafehub/config and see what needs to be done in order to get the release out the door.

**Comment by talpr** [comment]
@2m Any updates on this? I saw a couple of messages about this on gitter, but nothing new since.
(Again, I would be fine contributing if there is anything necessary, but I obviously can't release a new version of config...)

**Comment by 2m** [comment]
New Config library version has been released and we have created PR to update Akka to the newly released version here: https://github.com/akka/akka/pull/23790

**Comment by raboof** [comment]
@talpr can you confirm merging #23790 is indeed sufficient to close this issue?

**Comment by talpr** [comment]
@raboof 
I tested config:1.3.2 stand-alone, and it works. Thanks!

**Comment by talpr** [comment]
Unfortunately, this didn't actually work. It was fine when I tested it locally, but it appears that Kubernetes filters out env variables with periods in them as invalid...

**Comment by 2m** [comment]
Looks like k8s have relaxed this requirement since 1.8: https://github.com/kubernetes/kubernetes/issues/2707

**Comment by talpr** [comment]
ahh, cool. we’re stuck on 1.7 for a now, but it’s good to know.

**Comment by adarshaj** [comment]
How exactly do we export the env variable that's a list? (can someone pls give an example with say seed-nodes?)

**Comment by ktoso** [comment]
Please don't hijack long closed issues to add general questions, @adarshaj.
Please use the https://discuss.akka.io mailing list for such general questions.
