### ISSUE TITLE
In typed cluster receptionist prune entries from nodes that have gone away without removing their own entries

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23683]
See https://github.com/akka/akka/pull/23677#discussion_r140252436

**Comment by patriknw** [comment]
We should also hook into CoordinatedShutdown and spread the removals to some other nodes before ddata replicator is stopped, as an optimization.

**Comment by patriknw** [comment]
A first cleanup attempt was done in PR https://github.com/akka/akka/pull/24589 but leaving this ticket open since it doesn't solve all issues.

If a node with same hostname:port joins again there is risk that we miss the removal of some refs that belongs to the old incarnation. I think we need a data structure that also includes the owning system's uid for each ref.

Another scenario to consider is when a registered actor is terminated, but the node is still up and running. That removal can also be "lost" and would result in a dead actor ref lingering around.

**Comment by johanandren** [comment]
@patriknw how could the removal be lost if the local receptionist watches the registered actor, and updates the ddata state, is there a case where `Terminated` gets lost locally??

**Comment by patriknw** [comment]
The removal from the ORMultiMap can be "lost" when merging with other concurrent updates. That is the semantics of ORSet and friends (observed remove / add wins over remove)

**Comment by johanandren** [comment]
Hmmm. Isn't that only if they'd add/remove the same actorref to the set? Shouldn't only the owning system do that?

**Comment by johanandren** [comment]
Ah, it's the leader/node-removed updates that remove on another node than the one the service lives.

**Comment by patriknw** [comment]
One more related ticket #24887, but closing this one.
