### ISSUE TITLE
Update Netty in Akka Remoting from 3.10.6 to 4.1.15

### ISSUE THREAD

**Issue by andrewkerr9000** [akka/akka#23733]
Netty 4 [no longer creates `ChannelEvent` objects](http://netty.io/wiki/new-and-noteworthy-in-4.0.html#channelhandler-with-no-event-object) and [introduces pooled buffers](http://netty.io/wiki/new-and-noteworthy-in-4.0.html#pooled-buffers), both of which reduce GC pressure, potentially significantly.

I also have the rather more selfish motivation that I want to reuse Netty 4 SSLHandler logic (relies on #23732).

As Netty 4 also changes the package (from `org.jboss.netty` to `io.netty`) it would be possible to have both Netty 3 and Netty 4 available as pluggable `Transport`s in Akka Remoting.

I have work in progress.

**Comment by patriknw** [comment]
The Netty based Akka remoting implementation is difficult to maintain and bugs are still discovered. (That has nothing to do with Netty.) That is one of the reasons we implemented the new remoting called Artery. Therefore I don't think we want to do any major changes to the remoting implementation and risking revealing or introducing more bugs.

**Comment by andrewkerr9000** [comment]
Which is a fair concern, and this sort of thing is a pain to test.

Encryption in Aeron (DTLS or otherwise) seems a way off, so Artery won't be useful to us for a long while yet.

**Comment by patriknw** [comment]
yes, we know that we must solve the encryption story

**Comment by guidomedina** [comment]
@andrewkerr9000 Have you thought of the idea of only encryption your application messages?
https://github.com/romix/akka-kryo-serialization supports AES encryption.

**Comment by guidomedina** [comment]
I saw your other SSL ticket, Kryo is still a valid option if you would like to extend its configuration to support other encryption algorithms.

**Comment by andrewkerr9000** [comment]
@guidomedina We wouldn't want to distribute shared secret keys, and implementing our own PKI seems a Bad Idea.

**Comment by guidomedina** [comment]
You could implement a custom AES that gets the key from somewhere, at the end of the day when you use SSL you still distribute your public/private key in the servers.

**Comment by guidomedina** [comment]
SSL will do as much magic as having a random and difficult to read AES key, you don't have to store it in your configuration, you could simply get such key at startup, I don't see what's the security issue there.

You could even have such generating service to change the key and your implementation to update it, I see possibilities, not drawbacks in such design.

**Comment by guidomedina** [comment]
Another aspect is the compression, serializers usually deliver a semi-compressed form of a message but encryption void such optimization so maybe having `AES+LZ4` could be a good thing.

You could have a service that generates an AES key for your cluster and then your cluster would simply download the `byte[]` to reconstruct the key via HTTP with SSL client.

Once that's done your AES key singleton instance will reside in-memory so you would never be exposing the generated keyword which was used to generate the AES key.

That's a solution that can be easily implemented in few hours, IMHO is better than to use Netty 3.x which generates so much garbage.

**Comment by andrewkerr9000** [comment]
We'd want Akka Cluster and Distributed Data messages encrypted too, and I'm not sure how that could be accomplished without specific support from Remoting.

Session keys should be randomly generated and unique to the session, so that if private keys are compromised historic sessions will not be as well, i.e. to provide forward secrecy.

Bootstrapping actor message level symmetric encryption by negotiating randomised keys over TLS is an interesting idea.

Also a potential general solution for Artery would be to implement a TLS-style handshake to perform mutual auth and negotiate a shared secret for AES over actors using a public-private key pairs and the Java Cryptography Architecture, and then use that secret to AES encrypt messages as you suggest.

My concern is that crypto is quite complex, often subtle and hard to test and therefore easy to get wrong, and mistakes could be catastrophic for security.

At the very least I'd want any solution to be audited by someone with domain expertise in public key crypto and JCA. I assume Lightbend would be able to find such a person.

**Comment by guidomedina** [comment]
I believe is quite possible to bind the super classes of cluster events and distributed data to Kryo.
That way cluster messages and distributed data will be encrypted.

**Comment by guidomedina** [comment]
All you need to do is change these values, to be confirmed if there are any drawbacks on binding these serializers to Kryo:
```
akka {
  # Protobuf serializer for cluster messages
  actor {
    serializers {
      akka-cluster = "akka.cluster.protobuf.ClusterMessageSerializer"
    }

    serialization-bindings {
      "akka.cluster.ClusterMessage" = akka-cluster
      "akka.cluster.routing.ClusterRouterPool" = akka-cluster
    }
    
    serialization-identifiers {
      "akka.cluster.protobuf.ClusterMessageSerializer" = 5
    }
    
  }
}
```

Distributed data:
```
# Protobuf serializer for cluster DistributedData messages
akka.actor {
  serializers {
    akka-data-replication = "akka.cluster.ddata.protobuf.ReplicatorMessageSerializer"
    akka-replicated-data = "akka.cluster.ddata.protobuf.ReplicatedDataSerializer"
  }
  serialization-bindings {
    "akka.cluster.ddata.Replicator$ReplicatorMessage" = akka-data-replication
    "akka.cluster.ddata.ReplicatedDataSerialization" = akka-replicated-data
  }
  serialization-identifiers {
    "akka.cluster.ddata.protobuf.ReplicatedDataSerializer" = 11
    "akka.cluster.ddata.protobuf.ReplicatorMessageSerializer" = 12
  }
}
```

**Comment by andrewkerr9000** [comment]
Thanks, I'll keep that in mind.

**Comment by guidomedina** [comment]
I was thinking of what you said about random key generation, think about it using the following steps and how secure and performant that could be:

- Start a light HTTPS Java server and using `SecureRandom` generate an AES key of 128, 192 or 256 bits and bind it to localhost only, you can use Akka HTTP or any other solution.
- Have some ACL via Apache HTTP or Nginx and/or firewall, the SSL part should be easier with Apache or Nginx IMHO.
- Have the AES bytes as base64 representation in memory.
- Start your Akka cluster which will get an instance of such key and also have it in memory.
- Bind these messages to Kryo and compress with LZ4.

The only drawback is that if the HTTP server crashes your cluster can't add more nodes if you don't restart the whole thing because the key is generated at startup, the benefits of it is that the key is never stored anywhere and to change it you only have to restart the HTTP Java server and the whole cluster.

Profit ;-)

**Comment by sergtezt** [comment]
> That is one of the reasons we implemented the new remoting called Artery.
Is there a way to use Artery with TCP?

**Comment by ktoso** [comment]
No, unless you use some software to tunnel UDP over TCP and direct the Artery connection through that.

**Comment by sergtezt** [comment]
Thanks, @ktoso  What would you recommend as production-ready high performance TCP transport for Akka?

**Comment by patriknw** [comment]
Solving the encryption story for Artery is on our radar. Plan-B if we can't solve it with Aeron (UDP) is to implement an alternative with TCP in Artery.

**Comment by guidomedina** [comment]
`akka-remote` with old `Netty 3.10.6` doesn't perform too bad, I even contributed to `Netty 3.10.6` so that when it is running with `Java 8` it would use the `Java 8` `ConcurrentMap` and not some old ported `ConcurrentMap` prior `Java 5` insertion, you can see that here:
https://github.com/netty/netty/issues?q=milestone%3A3.10.6.Final

I would say, benchmark it and determine if is good or not for your requirements, I would post some benchmark with 15 JVMs of price streaming but I migrated to Artery long time ago.

**Comment by guidomedina** [comment]
@patriknw yes, I found a wall when trying to sell `Aeron` driver to another project I'm working on, which leaves `Netty` only, the customer just wants TCP because he considers `Aeron` driver as a single point of failure, I don't but it is too difficult to convince people that it is actually the best they are going to get.

I believe the way to go would be to have a TCP implementation of Artery without `Netty` as you suggested.
