### ISSUE TITLE
Cannot down an inaccessible node from the cluster

### ISSUE THREAD

**Issue by acchaulk** [akka/akka#23754]
This is a similar issue to #18474. When a node is shutdown ungracefully, I am unable to remove it from the cluster. I was able to replicate this using the akka-sample-cluster-java , creating a two node cluster, forcibly killing a node, and trying to down it with the DELETE members cluster management api. 

Steps to replicate this problem and logs from the test can be found here: https://github.com/Cimpress-MCP/akka-samples/tree/cannot-down-inaccessible-node/akka-sample-cluster-java.

Am I missing an obvious step in how to down a node, or is there a larger issue here?

**Comment by johanandren** [comment]
The command you refer to:
```
curl -X DELETE localhost:19999/members/akka.tcp://ClusterSystem@127.0.0.1:2552
```
does a graceful leave (see https://github.com/akka/akka-management/blob/master/cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala#L105 ), which an unreachable node cannot do, because it is unreachable and gracefully leaving requires a few interaction between the node gracefully leaving and the rest of the cluster. Graceful leave is for a node in contact with the cluster that wants to shut down and hand over duties as efficient as possible.

What you want to do is to `Down` the node. That is done with a PUT request, described here in the management module docs: http://developer.lightbend.com/docs/akka-management/current/cluster-http-management.html#api-definition

**Comment by dr3s** [comment]
thanks for pointing out the obvious. If we had put as much time into
reading the manual as we did creating test code, we wouldn't have missed
such a simple thing.  would you accept a PR to warn (or error) on DELETE,
since the action can't be completed?

**Comment by johanandren** [comment]
Sounds like something to look into. I think that should go in the management project, so I opened a ticket there, closing this one.

**Comment by dr3s** [comment]
https://github.com/akka/akka-management/issues/47
