### ISSUE TITLE
Broken links in documentation (site)

### ISSUE THREAD

**Issue by Troxid** [akka/akka#23787]
Some links on the site are broken (https://doc.akka.io/docs/akka/current/scala/general/supervision.md#what-restarting-means):
```
Not Found
The requested URL /docs/akka/current/scala/general/supervision.md was not found on this server.
Apache/2.4.7 (Ubuntu) Server at doc.akka.io Port 80
```
One of them:
https://doc.akka.io/docs/akka/current/scala/actors.html#actor-lifecycle
1) "...more discussion about **what restart means**" ([source L400](https://github.com/akka/akka/blame/master/akka-docs/src/main/paradox/scala/actors.md#L400))
2) "...handled by the **Supervision Strategy** of actor’s.." ([source L399](https://github.com/akka/akka/blame/master/akka-docs/src/main/paradox/scala/actors.md#L399))

May be i will fix it, but i can't understand how works that doc engine.
I tried to change `md` to `html` (https://doc.akka.io/docs/akka/current/scala/general/supervision.md#what-restarting-means -> https://doc.akka.io/docs/akka/current/scala/general/supervision.html#what-restarting-means)   and it was work right. Should i will change `md` to `html` in the source or how is it right?

**Comment by raboof** [comment]
Thanks for noticing! To link to another markdown page we use [@ref links](http://developer.lightbend.com/docs/paradox/latest/features/linking.html) rather than 'raw' markdown links - the 2 other occurrances of "What Restarting Means" on that page actually looks like good examples.

If you could seek out places where this mistake was made and submit a PR to fix it that we'd highly appreciate it!
