### ISSUE TITLE
Tagging of events in Typed PersistentActor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23817]
Tagging of events can be done with event adapter, also with Akka Typed, but it's much boilerplate to create and configure event adapter just for tagging. With Typed the event can't be wrapped in `Tagged` because it's wrong type. Therefore we should have a function `Event => Seq[String]` for assigning tags in the `PersistentBehavior`.

**Comment by patriknw** [comment]
@chbatey issue for what we talked about yesterday

**Comment by richardimaoka** [comment]
Hi does this issue mean:
1. `EventAdapter` allows tagging by extending `EventAdapter` + configuration like [this](https://doc.akka.io/docs/akka/2.5.8/persistence.html?language=scala#event-adapters)
  1.1. and `toJournal` should be something like:
```scala
override def toJournal(event: Any): Any = Tagged(event, Set("aaa", "bbbb"))`
```
2. For BOTH typed and untyped actors, 1. is possible
3. However, that is 1. is what is called "boilerplate" here, and for typed actors, we want to define tagging inside behavior instead of `EventAdapter`

am I correct?

**Comment by patriknw** [comment]
Your understanding is correct

**Comment by patriknw** [comment]
@richardimaoka it would be great if you can contribute here, if you are interested

**Comment by richardimaoka** [comment]
Yes of course, happy to contribute!! 😃

**Comment by chbatey** [comment]
Thanks @richardimaoka 

Would you mind adding documentation for this? It'll be in `akka-docs/src/main/paradox/persistence-typed.md` you can add an example to the `akka/akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala` as the inmem journal doesn't support tagging.

Also should we not make the function `Event => Set[String]` ? Makes no sense to allow the same tag twice. 

Also what do we want to call the parameter? `taggingFunction` seems odd to me as it is obviously a function from the type signature. Other things are called handlers but you don't really "handle" tags, you create them. Maybe just `tagger`?
