### ISSUE TITLE
Classpath error at runtime with akka 2.5.6 && akkaHttp 10.0.10

### ISSUE THREAD

**Issue by allquantor** [akka/akka#23819]
It seems like a problem with backward compatibility.

**Preconditions**

- Have `akka 2.5.6` as dependency
- Have `akkaHttp 10.0.10` as dependency
- Create an akkaHttp "hello-world"
-  run

**Error**
An exception is thrown. See:
```
Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use akka-actor [2.5.6 (resolved from current classpath)] all other core Akka modules MUST be of the same version. External projects like Alpakka, Persistence plugins or Akka HTTP etc. have their own version numbers - please make sure you're using a compatible set of libraries.                 
Uncaught error from thread [classpath-error-showcase-akka.actor.default-dispatcher-3]: akka.actor.ActorCell.addFunctionRef(Lscala/Function2;)Lakka/actor/FunctionRef;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[classpath-error-showcase]
java.lang.NoSuchMethodError: akka.actor.ActorCell.addFunctionRef(Lscala/Function2;)Lakka/actor/FunctionRef;
	at akka.stream.stage.GraphStageLogic$StageActor.<init>(GraphStage.scala:142)
...
```
**Reproduce**

- Clone the showcase project from git [here](https://github.com/allquantor/akka-classpath-error-demo).
- Run `sbt run` to get the error.

_Post Scriptum:_
Changing the akka version to `2.4.19` resolves the problem.

**Comment by manonthegithub** [comment]
Aka-http uses under the hood akka 2.4.19 and this dependency is added to you project with akka 2.5.6, so there can be conflicts because of it. You should [exclude transitive dependencies with sbt](http://www.scala-sbt.org/0.13/docs/Library-Management.html#Exclude+Transitive+Dependencies) from akka-http and this should work fine as well.

**Comment by patriknw** [comment]
From the stack trace, GraphStage.scala 142 I can see that you are using
akka-stream 2.4.20. Add akka-stream 2.5.6 as dependency.
/Patrik
ons 18 okt. 2017 kl. 05:27 skrev Kirill Yankov <notifications@github.com>:

**Comment by markusjura** [comment]
`akka-stream` 2.4.19 is used which is pulled in by `akka-http` 10.0.10, see the following dependency tree:

```
classpath-error-showcase(master)> dependencyTree
[info] Updating {file:/Users/mj/workspace/akka-classpath-error-demo/}classpath-error-showcase...
[info] Resolving com.lucidchart#scalafmt-impl_2.12;1.12-1.0 ...
[info] Done updating.
[info] io.allquantor:classpath-error-showcase_2.12:0.1.0-SNAPSHOT [S]
[info]   +-com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.12:1.3.3 [S]
[info]   | +-org.scala-lang.modules:scala-xml_2.12:1.0.5 [S]
[info]   | +-org.scala-lang:scala-reflect:2.12.0 [S] (evicted by: 2.12.2)
[info]   | +-org.scala-lang:scala-reflect:2.12.2 [S]
[info]   |
[info]   +-com.typesafe.akka:akka-actor_2.12:2.5.6 [S]
[info]   | +-com.typesafe:config:1.3.1
[info]   | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   |
[info]   +-com.typesafe.akka:akka-http_2.12:10.0.10 [S]
[info]   | +-com.typesafe.akka:akka-http-core_2.12:10.0.10 [S]
[info]   |   +-com.typesafe.akka:akka-parsing_2.12:10.0.10 [S]
[info]   |   | +-com.typesafe.akka:akka-actor_2.12:2.5.6 [S]
[info]   |   |   +-com.typesafe:config:1.3.1
[info]   |   |   +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   |   |
[info]   |   +-com.typesafe.akka:akka-stream_2.12:2.4.19 [S]
[info]   |     +-com.typesafe.akka:akka-actor_2.12:2.5.6 [S]
[info]   |     | +-com.typesafe:config:1.3.1
[info]   |     | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   |     |
[info]   |     +-com.typesafe:ssl-config-core_2.12:0.2.1 [S]
[info]   |     | +-com.typesafe:config:1.2.0 (evicted by: 1.3.1)
[info]   |     | +-com.typesafe:config:1.3.1
[info]   |     | +-org.scala-lang.modules:scala-parser-combinators_2.12:1.0.4 [S]
[info]   |     |
[info]   |     +-org.reactivestreams:reactive-streams:1.0.0
[info]   |
[info]   +-com.typesafe.scala-logging:scala-logging_2.12:3.7.2 [S]
[info]   | +-org.scala-lang:scala-reflect:2.12.2 [S]
[info]   | +-org.slf4j:slf4j-api:1.7.25
[info]   |
[info]   +-org.apache.logging.log4j:log4j-api:2.9.1
[info]   +-org.apache.logging.log4j:log4j-core:2.9.1
[info]
[success] Total time: 1 s, completed Oct 19, 2017 9:14:28 AM
```

I was able to solve the runtime exception by adding `akka-stream` 2.5.3 as an explicit dependency, see https://github.com/allquantor/akka-classpath-error-demo/pull/1.

@allquantor and me were misinterpreting "backwards binary compatibility" so that it is safe to use both 2.5.x and 2.4.x at runtime. However, as stated on https://doc.akka.io/docs/akka/2.5/scala/common/binary-compatibility-rules.html?_ga=2.88652498.839645252.1508396602-1898155209.1502449763#mixed-versioning-is-not-allowed, it is not allowed to use mixed Akka versions in the project. So as long as we upgrade all Akka libraries to 2.5.3 we are safe which the PR https://github.com/allquantor/akka-classpath-error-demo/pull/1 did.

Thanks for the clarification. @patriknw The issue can be closed.
