### ISSUE TITLE
Stop unused Artery outbound streams

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23967]
As noticed by @mboogerd it's an oversight that we don't stop outbound streams when they are not used. They are stopped when quarantined (incl when cluster member is removed), but it would be good to stop unused streams to reduce resource consumption. 

If there are unacknowledged system messages the control stream should not be stopped until after a long timeout (see existing `give-up-system-message-after` config).

Slightly related to #21359

**Comment by mboogerd** [comment]
@patriknw I'm willing to help out, but I am facing some difficulties finding the right approach due to my unfamiliarity with Remoting/Artery.

1. Testability. For now I'm a little clueless how to test this. We are fixing something that is inherently very internal to Arterty (we can't detect from the outside that it is continuing idling). I can't find existing tests that would serve as a good template for setting up Artery such that it allows internal-state (AssociationRegistry) inspection. Do you have suggestions towards an approach?

2. I'm divided between implementing an association-wide-idle-timer and a per-channel-idle-timer. The former could involve an idle-flag per outbound-stream; once their conjunction is true, all streams complete. Alternatively, each channel can individually close when idle, but then also needs to be dynamically reopened (within the same Association) when re-used. The Association can be removed from the AssociationRegistry once `Association.streamsCompleted` completes. Do you have preferences?

3. A related issue is that the documentation of `Association.streamsCompleted` states that it's only reliable during shutdown. Also, if `runOutboundOrdinaryMessagesStream` is invoked with configuration value "outbound-lanes" exceeding 1, it looks like those streams won't have their materialized value registered in `streamMatValues`. What would be required to get a reliable check for shutdown?

**Comment by patriknw** [comment]
Thanks a lot for offering your help, @mboogerd . This is very deep internal into Artery and I have to think hard myself of how to solve this, and when I will have done that I have probably implemented most of it (at least in my head). Therefore I suggest that I will take this ticket and you can help out with reviewing and testing with real application. Do you have an urgent deadline?

**Comment by mboogerd** [comment]
That sounds good to me @patriknw. My 'real application' is very much WIP and even once released won't have 1000s of clients instantly, so no urgent deadlines. I'll be happy to review and test, just ping me when you're ready.

**Comment by patriknw** [comment]
ok, good. I can't make any promises when I can start on this, but it's something I want to fix independent of your request to make Artery ready for prime time.
