### ISSUE TITLE
Memory leak in long running stream related to ConcurrentAsyncCallback's

### ISSUE THREAD

**Issue by maxcom** [akka/akka#24046]
We have a long running stream that works fine in Akka 2.5.6. After update to 2.5.7, process runs out of memory after 5-10 minutes of processing. I see large number (~35000) of 
`GraphStageLogic.ConcurrentAsyncCallback` instances in heap dump. Each of them holds a reference to some data objects that was processed in past.

I do not have a clean reproducer yet.

Here is screenshot from Eclipse Memory Analyzer:

<img width="790" alt="2017-11-22 21 35 29" src="https://user-images.githubusercontent.com/69385/33144164-2b137c50-cfcd-11e7-800b-1f48fc7ce764.png">

and one more:

<img width="779" alt="2017-11-22 21 37 29" src="https://user-images.githubusercontent.com/69385/33144242-658cf51e-cfcd-11e7-9fa3-dddb954b1147.png">

**Comment by patriknw** [comment]
@maxcon Thanks for reporting, it looks like a serious regression. The async callbacks were changed in 2.5.7. A reproducer would be great.

**Comment by maxcom** [comment]
Here is the reproducer: https://github.com/maxcom/akka-streams-oom.

Process runs fine for at least 10 minutes on Akka 2.5.6, and runs of of memory on first minute in 2.5.7.

**Comment by patriknw** [comment]
Thanks!

**Comment by 2m** [comment]
With the new async callbacks we have started to store async callbacks in `asyncCallbacksInProgress` of the `GraphStageLogic` until graph stage is stopped.

Unfortunately streams of streams are implemented by using async callbacks, which never get released and thus OOM.

**Comment by johanandren** [comment]
To be more concrete, the issue here is `akka.stream.stage.GraphStageLogic.SubSinkInlet` which triggers the creation of one of those callbacks here: https://github.com/akka/akka/blob/3dc0adb4e9d7eb41d1fe7847dda61a0e01bd37fa/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L1250 

For `FlattenMerge` one is created per sub stream that is materialized, but as there is no way to signal that the `AsyncCallback` should be released/not kept around anymore when the sub sink has completed/canceled it stays in memory.

Problem is probably there for the opposite as well (`SubSourceOutlet`)

**Comment by t3hnar** [comment]
Hi guys, any estimate on fix?

**Comment by patriknw** [comment]
We will take a deep look at this tomorrow.
