### ISSUE TITLE
Support Java serialization for Akka Typed

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#24135]
Currently typed `ActorRef`s cannot be serialized with Java serialization. While Java serialization certainly is discouraged for real-world production cases, it is very convenient for demos and teaching. Therefore I suggest it should be enabled.

**Comment by patriknw** [comment]
I agree, since we don’t have a good drop in replacement yet. Can be done in same way as untyped ActorRef.

**Comment by durban** [comment]
Related issue: #19810.

**Comment by patriknw** [comment]
When sending ActorRef as the (top level) message it’s no problem, then Misc and protobuf will be used. Java serialization is needed when an ActorRef is enclosed inside another java.Serializable message.

Yes, ActorRef must implement readResolve and writeReplace as the untyped ActorRef.

**Comment by richardimaoka** [comment]
Hmm, could I get some advice on implementing `readResolve` and `writeReplace` in `trait akka.actor.typed.ActorRef`? Am I on a wrong direction?

## The approach I was thinking...

Like [#23696](https://github.com/akka/akka/pull/23696/files#diff-8199c71cb87c587e87b474fb3935774b), I was thinking to use `ActorRefResolver` inside the `readResolve` and `writeReplace` methods. 

However, single `ActorRefResolver` for one `ActorSystem` is enough, so instantiating `ActorRefResolver` inside `readResolve`/`writeReplace` is too costly?

```scala
trait ActorRef[-T] extends java.lang.Comparable[ActorRef[_]] with java.io.Serializable {
  ...
  ...
  @throws(classOf[java.io.ObjectStreamException])
  protected def writeReplace(): AnyRef = {
    ...
    val resolver = ActorRefResolver(system.toTyped) //instantiation inside method, too costly?
    resolver.toSerializationFormat(ref) //: String
  }

```

## How Java serialization works in akka

So we need a single `ActorRefResolver` instance, from **outside** `readResolve`/`writeReplace`.

Similarly, we need a single `ExtendedActorSystem` instance for Java serialization/deserialization, but that is already done as follows.

`ExtendedActorSystem` instance can be obtained from `object JavaSerializer`'s `JavaSerializer.currentSystem`

https://github.com/akka/akka/blob/0f0ea659880d6842d16308e97a922a64a5769fd0/akka-actor/src/main/scala/akka/serialization/Serializer.scala#L295

whose value is bound upon calling `toBinart` / `fromBinary`:

https://github.com/akka/akka/blob/0f0ea659880d6842d16308e97a922a64a5769fd0/akka-actor/src/main/scala/akka/serialization/Serializer.scala#L319

https://github.com/akka/akka/blob/0f0ea659880d6842d16308e97a922a64a5769fd0/akka-actor/src/main/scala/akka/serialization/Serializer.scala#L327

Then can we do something like `JavaSerializer.currentActorRefResolver`, similar to `JavaSerializer.currentSystem`? Actually not, because `JavaSerializer` is in the `akka-actor` package, so from `libraryDependencies`, `JavaSerializer ` doesn't know about `ActorRefResolver` inside `akka-actor-typed`. 

On the other hand, typed actor serialization uses `JavaSerializer` in `akka-actor`, so its `toBinary` / `fromBinary`, which doesn't know about `ActorRefResolver`, are the methods we have to use... I got stuck on this.

**Comment by patriknw** [comment]
@richardimaoka `ActorRefResolver` is an extension so it doesn't allocate a new instance each time. It creates an instance on the first access and then it's a hash map lookup. That is not extremely fast but good enough for Java serialization, which is anyway slow.

I think you should use the `currentSystem` in the same way as in untyped. See https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorRef.scala#L413
