### ISSUE TITLE
Persistent actor lease

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24147]
Persistence currently breaks in undetermined ways if multiple persistent actors run with the same persistence ids, with the event log likely to be corrupted.

Most journals are using a database that have some feature that could support a timed lease e.g. TTLed CAS, that could be used to prevent this in most cases.

A persistent actor could periodically re-new the lease to remain active.

* PA starts up and no actor has the lease
* PA gets lease but fails to renew due to database error/timeout
* PA gets a lease but on renew another actor has the lease
* Hard crash with the lease and restarting

**Comment by renatocaval** [comment]
Is that something to be added to the plugin spec? 

I'm thinking about the `akka-persistence-jdbc` plugin. This is something that it's not built-in for RDBMS, but that we could eventually implement in using a leasing table.

**Comment by ktoso** [comment]
It's not built-in anywhere out of the box, it's a feature to be developed with participation of the journals. Likely new API or trait to mark this capability.

**Comment by renatocaval** [comment]
Bring here a discussion initiated here: https://github.com/lightbend/platform-reconciliation/issues/2#issuecomment-353031768

Optimistic locking is similar to leasing, but not exactly the same. What I understood from the leasing, is that a persistent actor reserves the lease and as such another node can't get it and process new commands. 

With optimistic locking. A command could be resent to a node, not necessarily the one that is up-to-date, and still, be processed.

If a PA in a node is loaded up with version 5 and receives a command for version 6, it could restart the actor, replay the events up to 6 and accept the command. 

If it receives a command for version 4, then it's a failure and the user needs to resent the command.

**Comment by raboof** [comment]
@renatocaval in this proposal, how do we know the command is a 'command for version 6'? If you propose putting this information in the commands themselves, I think that can be an interesting feature, but quite different in terms of customer impact to the 'lease' idea above, so that'd deserve its own ticket.

If you mean this as an mostly-'under the hood' feature (replace 'persist event X with sequence number Y' with 'persist event X with sequence number Y, but only if the previous sequence number for this actor was Y-1'), this might indeed be an interesting alternative to consider here.

**Comment by renatocaval** [comment]
The lease approach would be transparent and offer an alternative or extra security for split brain scenarios. 

My initial idea was to only have a persistence plugin that could support optimistic locking (as opt-in) feature. It's on the user decide how to get to know the latest version (eg: using a read-side view). 

I didn't think about using sequence number Y-1 like you suggested. It seems a much better option because it makes it totally transparent and the user doesn't need to go around tracking version numbers. 

Ideally, this should be an opt-in feature because of the performances implications.

**Comment by patriknw** [comment]
Optimistic locking is typically used for preventing that several **users** are not overwriting each others updates. That can happen with only one PersistentActor instance also. That can't be handled completely transparently because the version number corresponding to when the data was read must be part of the command, so that it can be compared with currently stored version number when storing. That is another feature, which I think is an application level concern, since it can't be completely transparent. It's very simple to implement at the application level once you understand the concept of read-modify-update with concurrent users.

To protected against multiple PersistentActor writer the lease is much better than doing some CAS update for each event, because CAS means a heavy (Paxos) transaction in Cassandra.

**Comment by rigolepe** [comment]
I think that optimistic locking here is not meant to span over the query-side of the CQRS story, as @patriknw suggests. Incoming commands may originate from users that had a different view on the data. That's ok because all that matters is whether or not the command can be validated against the current state of the aggregate. 

I believe that optimistic locking in this issue is meant to avoid two actor instances representing the same aggregate  (on different hosts on a scaled-out setup) to process different commands and thus generate different events and persist them simultaneously on the journal. Since there is no natural contention in a database on append-only operations to a table (the journal), the events will be interleaved and likely to result in an inconsistent state for the actor on the next replay of those events. 

The classical answer to this problem is to use Cluster Sharding (see https://doc.akka.io/docs/akka/2.5/persistence.html#scaling-out). However, I believe that in many situations people want to be able to scale out their application without setting up an Akka cluster sharding solution. In this case, support from Akka in the `PersistentActor` class is necessary to implement optimistic locking. 

The main reason (imho) why Akka support is necessary is that we need to wrap the optimistic locking code atomically inside the persistence boundary of the `persist`, `persistAll`, `persistAsync` and the `persistAllAsync` methods of the `PersistentActor` class. What we need to do (atomically) before actually storing the events is: 

1. fetch a version number for the aggregate from the database, 
2. compare this version number with the in-memory version number of the aggregate, 
3. if the version is the same, store the events (e.g. persistAll) and increment te version number in the database

If another actor instance for this aggregate was doing the same simultaneously, then the database transaction of one of the two will fail (and that actor has to kill itself). If the version is not the same in step (3.), then the actor has to fail on that command and also kill itself, because it was already outdated to begin with.

One solution could be for Akka to maintain this version number by storing (and incrementing) it in each event as metadata (as an optional feature). The `PersistentActor` would then keep an in-memory instance of its version number that can be used to compare with the database version during `persistAll` as described above. The persistence implementation must then provide a way to attach a version number to each event.

Let me know if this makes sense, or if anyone sees a nicer solution, or even a solution that works with the current Akka persistence version...

**Comment by patriknw** [comment]
I'm closing this since we have added support for lease in Sharding and Singleton.
