### ISSUE TITLE
Remove typed ActorSystem implementation

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24149]
The new typed ActorSystem implementation is interesting but we will not have time to complete it in the initial scope of Akka Typed so we should remove it to avoid burning time on it until we can do it properly.

**Comment by rkuhn** [comment]
May I ask for a bit more context on the rationale? It would be good to know what you consider the “initial scope of Akka Typed” to be.

**Comment by patriknw** [comment]
The scope is to release something soon that can be used for building real applications. The features are pretty much covered of what we have implemented so far and described in the blog posts. Many small things missing and quality must be improved. Major missing things for this release are testkits and documentation. Also implementing the persistent actor as a real typed behavior is a major task, but necessary. All these things will fill up the budget we have for Akka Typed for the next 6 months. We think this is more important than implementing a new runtime.

Another reason is that we will have to maintain both typed and untyped for a long time ahead and we prefer to keep that cost as low as possible. As described in https://akka.io/blog/2017/05/06/typed-coexistence all cluster things require the untyped actor system so a new runtime would anyway not be useful for anything else than local actors.

**Comment by ktoso** [comment]
Phrasing the plan in a more positive light though: this plan means that we’ll actually be able to ship “usable Typed Actors (Akka Typed )” very very soon, putting it out there. I’d expect adoption and demand to kick in then, and once it’s shown adoption (pretty sure it will!) enough we can swap the underlying engine — I hope we’ld be able to pull that off without user-facing changes at all then, since we will still in the “step 1” have all the TypedActorSystem etc, just that it’ll delegate.

While I also would love to do step 1 and 2 at the same time, I think the phased approach here is pragmatic (and definitely (personally) would want to get to the step 2 sooner rather than never).

**Comment by rkuhn** [comment]
I do consider @patriknw’s response to be quite positive :-) My reason for asking was to persist the reasoning in this ticket, it is a good plan.

**Comment by ktoso** [comment]
Excellent, glad we’re aligned then! We’re pretty excited for basically “kicking-off 2018” with Typed :-)

**Comment by chbatey** [comment]
+1 really looking forward to getting the typed API prod ready and adopted and I think this makes it possible within a few months. Lots of people asking for it at scalax this week.

**Comment by gosubpl** [comment]
Someone mentioned to me that Lagom is going to move soon to Persistent Typed actors, so it totally makes sense to clean up the API first. But I think improved runtime implementation is also important, and I am sure that contributors will be happy to jump in to help moving it back as soon as the API stabilises.
