### ISSUE TITLE
Snapshots for typed PersistentActors

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24196]
Snapshots currently aren't implemented for typed persistent actors. See `PersistentActor.snapshot*` for proposed API

**Comment by richardimaoka** [comment]
Looking at https://doc.akka.io/docs/akka/2.5.7/persistence.html#snapshots, it seems like a common pattern for (untyped) snapshot is to check `lastSequenceNr` before calling `saveSnapShot`.

However, looking at (typed) [PersistentActor.scala](https://github.com/akka/akka/blob/0f0ea659880d6842d16308e97a922a64a5769fd0/akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/PersistentActor.scala), `lastSequenceNr` is not exposed.

Is there a plan/idea on how a typed persistent actor can check its `lastSequenceNr` ?
Maybe an idea is - currently the following two methods are defined as follows,

```scala
def snapshotOnState(predicate: State ⇒ Boolean): PersistentBehavior[Command, Event, State] = ???
def snapshotOn(predicate: (State, Event) ⇒ Boolean): PersistentBehavior[Command, Event, State] = ???
```
but for the parameters, instead of simply using the plain `State` type, we introduce something like `class InternalState[State]` which has a method like `def lastSequenceNr` ?

```scala
def snapshotOnState(predicate: InternalState[State] ⇒ Boolean): PersistentBehavior[Command, Event, State] = ???
def snapshotOn(predicate: (InternalState[State], Event) ⇒ Boolean): PersistentBehavior[Command, Event, State] = ???
```
