### ISSUE TITLE
@onMessage annotation

### ISSUE THREAD

**Issue by dcullender** [akka/akka#24249]
Thanks for building such an awesome product!

Just a thought: it may be worthwhile introducing an method level annotation ```@onMessage``` which tells akka that this method should be configured to be called when a message of it's parameter type is received.

In other words, we could have something like

```java
@onMessage
private void onMessage(MyType message) {
   // do amazing stuff
}
```
When the Actor starts up, it scans through it's methods and when it encounters such a method, it automatically configures it via the ReceiveBuilder (ie `receiveBuilder().match(MyType.class,this::onMessage)`)

If more than one parameter is setup in the method, or there is multiple methods with the same parameter type, an exception is thrown.

This has 3 benefits : 
1. It removes the boiler plate code for configuring the builder
2. When looking at an Actor class, we can easily identify which methods are used for message callbacks (really useful when an actor class grows in size)
3. When working with a Actor subtypes, this will greatly simplify the API by not having to expose the builder to different levels of the hierachy.

Hope this makes sense
Daniel

**Comment by patriknw** [comment]
Thanks for the suggestion, @dcullender . Did you change your mind, since you closed it?

I know that this may come very natural for developers coming from Spring and even though annotations is not our favorite tool in Akka, I think it's an idea worth considering. I think it can be built on top of the existing AbstractActor. Similar as we have the Javaslang sample: https://github.com/akka/akka-samples/tree/2.5/akka-sample-javaslang

Would you be interested in creating a pull request? I think it can start out as an example, similar as that javaslang sample.

**Comment by ktoso** [comment]
Yeah I too think that while such API looses much of the possibilities and style of usual Actor apps, it may be easier to "ease people into Akka" if they're used to such style... (i.e. I think we could definitely accept such proposal, be it as ApiMayChange for now and measure of people like it or not).

I wonder where such API should live.

**Comment by hepin1989** [comment]
If we add this, I would like to enable reflectasm and fallback to reflect/methodhandle thing for method invoking if that fail. to achieve performance?

**Comment by ktoso** [comment]
Yeah sure, that's not a problem. In any case, this could not live in akka-actor, but somewhere outside, and as such may depend on whatever it wants

**Comment by raboof** [comment]
For 'classic' actors it might be tricky to support [become/unbecome](https://doc.akka.io/docs/akka/current/actors.html?language=scala#become-unbecome) in such an API.

For the new typed API, however, we implement 'become' by returning the new behavior. This might fit more nicely: a method returning 'void' could be equivalent to `Actor.same()`, and returning a new `Behavior` would do the same as the current API.

I'd be curious to see how this turns out - indeed perhaps first as a separate library?

**Comment by ktoso** [comment]
I'd just say that it does not support become if one used that API.
We'd document that and say "that's an api to get you started but does not give you the full actor style or power", see the actual apis for that?

**Comment by rubenesk1** [comment]
How can I restore my messages

**Comment by ktoso** [comment]
This question seems unrelated to this ticket...? Please ask on the akka-user mailing list on chat.

**Comment by raboof** [comment]
I would be concerned that people might be tempted to instantiate the class that has these methods directly, and call those methods directly instead of by sending messages to the actor. Since there hasn't been activity for a while, I think we should close this issue for now.
