### ISSUE TITLE
Bulk Transfer Stream Refs (`SourceRef` and `SinkRef`)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24276]
Follow up to https://github.com/akka/akka/issues/24229

*bulk transfer* stream references --  which are intended to send over "huge messages" (as in, several megabytes, or even gigs if you'd like to do so). This is intended to solve the issue of "but I want to send a big file!". Those will be implemented using their dedicated, non-actor-messaging (plain TCP), protocol.

I have some initial designs but nothing committed yet. This should be done after we ship the normal ones.

**Comment by patriknw** [comment]
We discussed this a bit in a call and one idea by @jrudolph was that we simply send chunks of `ByteString` messages over the existing Actor message based implementation. For a stream of `ByteString` we can chunk into small messages and no reassembly is needed on the receiving side.

This can be done now already by chunking in user code, but perhaps it would be worth having the chunking built in. By having control of the chunk size we can use demand sizes that makes sense. Perhaps also have throttling built-in as an option (max X Bytes/s).

**Comment by jrudolph** [comment]
We could also add automatic framing even for the `ByteString` variant if that's what people might want.

**Comment by jrudolph** [comment]
No, I actually meant the `ByteString` one. Some people might want to have a stream where `ByteString`s actually are delimited the same way on both sides of the stream refs. But that's easy to do.

Chunking up non-ByteStrings would be the more important feature (because otherwise people will come up with non-solutions). How it would work would be not to rely on automatic remoting serialialization but to invoke it manually. So, the implementation would basically look like this (the API would stay the same as now):

```scala
val userSource: Source[T] = ???

userSource
  .mapAsync(n)(serializeToByteString)
  .via(framing)
  .via(chunking)
  // normal streamRef impl here using remoting
  .via(unframing)
  .mapAsync(deserializeFromByteString)
  // here it's a Source[T] again
```

In fact, I think this might well become the main (only?) implementation for StreamRefs, i.e. changing the type of the `payload` in `StreamRefsProtocol.SequencedOnNext` from `T` to `ByteString` and running the pipeline above for any type. This would also trivially cover the `ByteString` case.

Reassembly is done by the existing framing stage, am I missing something that would complicate that?

For `serializeToByteString`, we could use the wrapped serialization format (`SerializedMessage`), in that case nothing of the stream ref implementation would have to be changed. We could also adapt the handshake protocol to negotiate the serialization settings, so that we wouldn't have to include that for every frame.

With chunking and the existing backpressured StreamRef transport, I don't see the head-of-line blocking problem any more.

**Comment by patriknw** [comment]
I see what you mean now, serializing and chunking before Artery is involved. That's nice.

> negotiate the serialization settings

no, because different serializers may be used for different concrete element types, although all implements same upper type (extreme case `Any`).

shouldn't matter much since the frames are supposed to be much bigger than the extra meta data.

**Comment by jrudolph** [comment]
> no, because different serializers may be used for different concrete element types, although all implements same upper type (extreme case `Any`).

Yep, that's what I figured as well.

**Comment by patriknw** [comment]
Make sure we do any wire protocol changes before 2.6.0

**Comment by schrepfler** [comment]
In presence of some key-value store (CQRS scenario) one could also stick the message to the store and replace the actual message by a claim-check message.

**Comment by AkshayGudi** [comment]
I see the discussion here is regarding the chunking of huge data to be sent to second actor from first actor over stream.
As i can understand this is not implemented yet in core Akka functionality, can anyone please suggest where can i find the logic to send chunk of data from first actor to second actor over Stream and assemble the chunk in second actor.

Thanks in Advance

**Comment by patriknw** [comment]
My current thinking is that we should add this feature to [reliable delivery](https://github.com/akka/akka/pull/28155) and then also swap the implementation of StreamRefs to run on top of reliable delivery or have some other streams integration for reliable delivery.
