### ISSUE TITLE
Is this awaitAssert really necessary in DeviceGroupTest class in tutorial 4?

### ISSUE THREAD

**Issue by ccronemberger** [akka/akka#24329]
I am new to Akka and while reading the tutorial I had the idea of removing the call to awaitAssert and let the code within it execute directly and it worked for a number of times (in fact it did not fail).
I have tried to force a failure but without success.

https://github.com/akka/akka/blob/009214ae07708e8144a279e71d06c4a504907e31/akka-docs/src/test/java/jdocs/tutorial_4/DeviceGroupTest.java#L127

How can I make this fail?

**Comment by johanandren** [comment]
It is explained in the comment just above and was fixed after it failed in our CI-env. Race conditions can be hard or impossible to repeat depending on how slow or fast CPU you have, how many cores, what the weather is outside, so that would explain that you may not be able to reproduce it locally.

We try to use the issue tracker for bugs and feature tracking, please use the [gitter channel](https://gitter.im/akka/akka) or the [mailing list](https://groups.google.com/forum/#!forum/akka-user) for questions in the future, thanks!
