### ISSUE TITLE
Unable to cancel "groupBy" when all substreams cancel  

### ISSUE THREAD

**Issue by aserrallerios** [akka/akka#24370]
If a failure is raised *after* a `groupBy`, it'll never reach the upstream before the `groupBy`.

```scala
object Test extends App {

  implicit val system: ActorSystem                = ActorSystem()
  implicit val materializer: ActorMaterializer    = ActorMaterializer()
  implicit val executionContext: ExecutionContext = ExecutionContext.global

  var tick = 0

  Source
    .tick[Int](1 second, 1 second, 1)
    .map { _ =>
      tick += 1
      tick
    }
    .log("1")
    .buffer(100, OverflowStrategy.backpressure)
    .groupBy(10, identity)
    .log("2")
    .map(x => if (x == 10) throw new RuntimeException("foo") else x)
    .mergeSubstreams
    .log("3")
    .addAttributes(Attributes.logLevels(Logging.InfoLevel, Logging.InfoLevel, Logging.ErrorLevel))
    .runWith(Sink.ignore)
    .onComplete {
      case Failure(t) =>
        println(s"Stream completed with error", t)
      case Success(_) =>
        println(s"Stream completed successfully")
    }

  Thread.sleep(15000)

  system.terminate()

}
```

In this example you can see:
1. A failure is raised
2. the downstream "3" is properly completed
3. all substreams "2" (10 substreams in total) are properly cancelled 
4. "1" keeps working, pushing elements downstream

I would expect the whole stream to be cancelled upstream and all stages to be stopped.

Is this behaviour intended? I'm misusing `groupBy` or `mergeSubstreams`? There's some known limitation around it? It's a bug?

Thanks.

**Comment by johanandren** [comment]
The docs of `GroupBy` says: `downstream cancels and all substreams cancel` so if it doesn't (which this seems to indicate) I'd consider that a bug.

Also seems a bit strange that "3" "properly completes", I think the failure should propagate downstream and fail that as well, and up stream from the merge cancelling the other substreams.

**Comment by jrudolph** [comment]
First, we should note that there's no such thing as propagating errors from downstream to upstream. The only thing that a downstream can signal is cancellation. 

What does that mean for `groupBy`?
 * if the main downstream is cancelled, we'll eventually run into the problem that elements may arrive that we cannot handle, because we cannot create another substream. So, we could either directly shutdown when receiving cancellation on the downstream, or we could later skip elements that we cannot handle, or we could later fail if we receive elements that we cannot handle.
 * if one of the substreams is cancelled, we could either stop all processing (but should we really?), or just remove the stream and later when a new element for that key arrives either create a new substream for that key or skip elements for that key

@johanandren mentioned in which case `groupBy` would cancel. It seems it would try to do it rather late. But what it means in detail (i.e. which of the above options was chosen) isn't said.

**Comment by jrudolph** [comment]
That said, it seems the case explained in this ticket is exactly that "downstream cancels and all substreams cancel" doesn't work, so :+1: for fixing that.

**Comment by aserrallerios** [comment]
My approach in the PR is:

If the main downstream is cancelled, it'll wait ultill all substreams are cancelled, and then it'll cancel itself (on each substream cancel, it will try to complete the GB stage if the upstream is closed, or cancel the stage if the downstream is closed). If a new key was pending to be pushed downstream when the cancellation arribed, it'll be ignored. No new pulls will be signaled upstream.

**Comment by aserrallerios** [comment]
I think it fits your description pretty well, finish will be delayed until all pending (substreams) work is done, either when the downstream cancels or single substreams cancel.
