### ISSUE TITLE
Allow RestartFlow/RestartSink to restart only on failures

### ISSUE THREAD

**Issue by nachinius** [akka/akka#24421]
Currently it restarts when failing and when completing. Provide a way to only restart if the wrapped flow fails.

Similar to #23881 but on RestartFlow
Requested by @patriknw in https://github.com/akka/akka/pull/23911#issuecomment-360100856

I'm working on it

**Comment by ktoso** [comment]
Great, thanks 👍 
Perhaps the same should at the same time be added to the RestartSink so all have the same ops?

**Comment by nachinius** [comment]
@ktoso Maybe we could do it after, the RestartFlow looks good. May be in another ticket?

**Comment by ktoso** [comment]
Separate PR sounds good, would you want to give it a shot then as well? Reviewing the current one for now then

**Comment by patriknw** [comment]
@nachinius Merged the PR for RestartFlow. Keeping this ticket open for RestartSink also.

**Comment by nachinius** [comment]
cool

**Comment by nachinius** [comment]
Does it make sense for a RestartSink only on failures? Given that a sink can not emit failures, only cancels, there is no simple way (as far as I understand) to distinguish between a failure and a normal cancelation. Thoughts?

**Comment by ktoso** [comment]
Hmm, you're right, we can't act on just the reactive streams signals between stages there. I think it could still could be interesting to provide but we'd need to apply some trickery to pull it off... Technically we know the difference internally between a stage throwing an exception for example, and completing successfully, so we could use this signal for it. 

Since we (akka, the graph stage interpreter) knows if a stage has failed or just completed. It may be difficult to pull off. Feel free to try it out however don't feel obliged to PR this, you're right that it's much more tricky

**Comment by ktoso** [comment]
I'll make a separate ticket about the RestartSink

**Comment by ktoso** [comment]
Sink ticket here: https://github.com/akka/akka/issues/24451 
Closing this one for Flow as solved
