### ISSUE TITLE
Serializer for scala.util.Either

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#24627]
When using `scala.util.Either` in a serialized message, it currently relies on Java serialization.

Recommend adding to `MiscMessageSerializer` and handling in a way similar to `Status.Success`/`Status.Failure`.

**Comment by TimMoore** [comment]
Relates to #20507.

**Comment by txsmith** [comment]
I would like to pick this up as a first contribution. Would you accept a PR for this?

**Comment by patriknw** [comment]
Question is how far we should support general wrapper and collection types. We recommend against using general collection types as messages, and I’d say that Either falls into that category.

**Comment by TimMoore** [comment]
I take your point @patriknw, but arguably `Option` does too, and that's there.

Would you suggest using `Status.Success`/`Status.Failure` instead?

**Comment by ktoso** [comment]
> Would you suggest using Status.Success/Status.Failure instead?

Yes, since they carry at least some more meaning and are already used like this -- though arguably they're also being abused sometimes. They've been designed specifically for ask and similar things for a generic response like that. Apps rarely should ride on generic types like those, but introduce their own types

**Comment by guizmaii** [comment]
Hi,

IMO, `Status` is equivalent to `Try`, not to `Either`.
`Either` bring more informations than `Try` and thus is more useful/safe/simple to use in a lot of cases.

I don't want my function to return `Try[Value]` because It doesn't give any information about which errors can happen. There're infinite possibilities. 

With `Either[MyException, Value]`, `MyException` could be the "upper limit" of an ADT (
(`sealed trait MyException extend RuntimeException`, for example) and thanks to this the compiler could help me to find bugs when I implement handlers for that type (because he can check if I handle every case, etc.). 
Thanks to this I can implement safer code because I know that I handled every possible cases.
And I use Scala and not Java also because this language allows me to produce safer code.

So I don't understand why you are against this serializer. As I see this, `Status` is not an equivalent.


🙂
Jules

**Comment by ktoso** [comment]
Sending around a Try is equally as bad of an idea as sending around an Either.
Please do define well typed messages -- avoid sending around top level generic containers such as collections, eithers, tries, maps -- it makes debugging, tracking what's going on hard, and a reason why then people "blame akka" for type-unsafety -- do use proper well named types.

Imagine, what's more helpful "scala.collection.immutable.Map sent to user/deadLetters delivered to dead letters" or "my.domain.RadioSubscribers or sent to user/deadLetters delivered to dead letters" in debugging a system? I bet the proper name helps a lot more.

**Comment by guizmaii** [comment]
So, if I wrap my `Either` in a `MyCallAnwser` case class, the problem will be solved ?

**Comment by patriknw** [comment]
yes, and they you will provide your own serializer for the `MyCallAnwser`

**Comment by TimMoore** [comment]
Given the discussion, I'll close the issue. Thanks everyone for your feedback.
