### ISSUE TITLE
akka doc is hard to understand, no  flow diagram & picture to explain  theory , just so many words...

### ISSUE THREAD

**Issue by javait90** [akka/akka#24621]
akka doc is hard to understand, no  flow diagram & picture to explain  theory , just so many words...
there is no blueprint, nothing is exist. 
ps: 文档里面没有设计流程图.  都是文字，晦涩难懂啊.  
一图胜千言.

**Comment by ktoso** [comment]
In order for such comment to be productive: could you pinpoint what section you mean, and be more specific? What flow diagrams would you want and in which sections of the docs.

Generally I agree, and it’s a matter of creating those in a way that is useful, not just sprinkling them around randomly. 

Let’s try to rephrase this into an actionable ticket, otherwise it won’t be really done (neither by team or community).

**Comment by ktoso** [comment]
Ping, looking for some actionable feedback or closing.

**Comment by ktoso** [comment]
Closing as no actionable thing was provided.

Still, thanks for the feedback.
