### ISSUE TITLE
2.5.10 node joining 2.5.9 error

### ISSUE THREAD

**Issue by 412b** [akka/akka#24622]
during rolling upgrade on the staging environment we've run into an issue, when node running 2.5.10 fails to join 2.5.9 cluster with the following warning in 2.4.9 nodes' logs
`akka.remote.EndpointReader - Serializer not defined for message with serializer id [6] and manifest []. Transient association error (association remains live). Cannot find manifest class [akka.cluster.InternalClusterAction$InitJoin] for serializer with id [5].`

As I haven't found anything related to rolling upgrades warnings, seems like a possible regression to me.

**Comment by patriknw** [comment]
It’s a regression introduced by the cluster config checker. We should fix asap and release new patch.

InitJoin is now a class, previously it was an object. It tries to load the InitJoin class in 2.5.9 because that is what is sent from 2.5.10. That class doesn’t exist. Boom.

The cluster serializer is not a WithStringManifest serializer, and that’s why the full class names are used.

I think it must be changed to WithStringManifest but still use the full class names as manifests for compatibility, and use the old 2.5.9 InitJoin object class name for the InitJoin class.
