### ISSUE TITLE
materialized value of Flow.lazyInit must be a Future

### ISSUE THREAD

**Issue by swachter** [akka/akka#24670]
As of Akka 2.5.11 Flow.lazyInit has the following signature

```
def lazyInit[I, O, M](flowFactory: I ⇒ Future[Flow[I, O, M]], fallback: () ⇒ M): Flow[I, O, M]
```

The materialized value must be a Future because materialization happens before the flow is run. Therefore the materialized value cannot depend on whether there will be some input or not.

In addition, I propose to change the materialized value into a `Future[Option[M]]` because this indicates in a clearer way if the inner flow was eventually materialized or not. The fallback function could be omitted if an `Option` is used.

**Comment by ktoso** [comment]
> In addition, I propose to change the materialized value into a Future[Option[M]] because this indicates in a clearer way if the inner flow was eventually materialized or not. The fallback function could be omitted if an Option is used.

When would you complete the future then though?

**Comment by ktoso** [comment]
Thanks for the ticket, we have to fix the signature indeed, has to be a Future; I'm not sure about the option proposal, see above question

**Comment by ktoso** [comment]
FYI @gosubpl

**Comment by swachter** [comment]
The future would complete either when the inner flow is materialized with value Some(_) or with value None if onComplete / onError arrives before any element.

**Comment by gosubpl** [comment]
I will need to look into that. The decision to return `M` and not `Future[M]` or `Future[Option[M]]` was deliberate on my side (though I might have not consider all the aspects of how materialized values work). The reason I did this was to guarantee that the `Flow.lazyInit` is plug-in compatible with the internal flow. My use case depends on it, although, as most frequently in the case of flows, `M` is `NotUsed`, so I might have not spotted the issue with use-before-initalized. If we decide (or need - if it actually is a bug) to move to a different signature, there needs to be an adapter that will allow to build a resultant flow with a signature matching the internal one.
Yes, I am aware that we are losing some of the information about whether the internal flow has or has not been successfully initialised. And, as much as I love consistent APIs, I have deviated from the signature of `Sink.lazyInit` that materializes into a `Future` to keep the signatures matching.
@swachter if you were so kind and supplied a failing spec showing the blow up resulting of the `M` being used instead of `Future[M]` that would help me immensely.

**Comment by swachter** [comment]
@gosubpl The current implementation always uses an instance created by the fallback function as the materialized value.

```
    (stageLogic, matVal.getOrElse(zeroMat()))
```

**Comment by swachter** [comment]
This test case should fail:

```
  "materialized value of internal flow is returned" in assertAllStagesStopped {

    val ("inner") = Source
        .single(1)
        .viaMat(Flow.lazyInit[Int, Int, String](_ => Future.successful(Flow[Int].mapMaterializedValue(_ => "inner")), () => "fallback"))(Keep.right)
        .toMat(Sink.ignore)(Keep.left)
        .run()
  }
```

**Comment by gosubpl** [comment]
Thanks. Got it. In that case I would rather go with `Future[Option[M]]` as `fallback` forces requirement that `M` is a Monoid, i.e. has a neutral value that can be returned in `fallback`. `Option` has a natural neutral value of `None`.
Also, how about adding then a timeout parameter for the internal flow completion, so that then `.mapMaterializedValue` can be used to flatten the signature back to `M` without deadlocking the stream?

**Comment by swachter** [comment]
I do not understand what a monoid could contribute here (at least if the materialized value is immutable).

You can not use `mapMaterialized` value to transform the `Future[Option[M]]` because the future will never complete before the flow has materialized (i.e. there is a cyclic dependency).

After the flow has been materialized and is running you may wait for the future to complete. I.e. you can watch if the inner flow gets materialized within some specific time (=> Some), is not materialized because of completion, cancelation, (=> None), or is not materialized because of an exception (=> failed future because of  onError or failed inner flow materialization).

**Comment by ktoso** [comment]
> Thanks. Got it. In that case I would rather go with Future[Option[M]] as fallback forces requirement that M is a Monoid, i.e. has a neutral value that can be returned in fallback. Option has a natural neutral value of None.

As @swachter mentions; this has nothing to do with Monoids ;-) I like them as well, however... the reality of materialized values is this:

it's values, that very often, you would not be able to produce a "zero" for. It is `Control` or `Stats` objects that you want to influence or observe the stream with. Making up a zero for those is not practical, and sometimes not even possible -- if the Control object construction is private in an external lib

> Also, how about adding a timeout parameter to lazyInit for the internal flow completion, so that then .mapMaterializedValue can be used to flatten the signature back to M without deadlocking the stream?

this can be solved by attaching an idle timeout stage AFTER the element, please do not build in special handling of this into this stage.

**Comment by gosubpl** [comment]
Yes, I have just figured out the `.mapMaterializedValue` part. I'll be fine (I will just replace the materialized value with `NotUsed` to keep the signature constant, don't need to flatten anything for this case, since it is not used after all).
Regarding my comment about Monoids, the discussion *has very much to do with them*. By the definition of [Monoid](https://en.wikipedia.org/wiki/Monoid) the essential property of it is that it has "zero" (or identity or neutral element). This is forced by the `fallback` function, which, essentially is the "zero" of the Monoid. Because, as I agree with you @ktoso , Materialized Values rarely are able to produce a "zero", I would rather go for `Future[Option[M]]` as @swachter  proposed.

**Comment by ktoso** [comment]
I know Monoids ;-) I'm saying it does not relate to this discussion, as materialized values very rarely are monoids, they're not the same kind of values as values passed through streams are; they're often magical unique snowflakes :-)

Thanks for the discussion, looking forward to the `Future[Option[M]]` PR :)

**Comment by swachter** [comment]
BTW: I also give the implementation a shot. In the past I sometimes wished to switch back from the event based API to flows. Now, after getting familiar with `SubSinkiInlet` and `SubSourceOutlet` this is a nice execise.

**Comment by gosubpl** [comment]
Btw. @swachter you can take a look at `Sink.lazyInit` that uses the `Future[M]` setup (though sadly not `Future[Option[M]]`.
