### ISSUE TITLE
API docs for Flow, Source out of sync with source

### ISSUE THREAD

**Issue by danielyli** [akka/akka#24680]
https://doc.akka.io/api/akka/current/akka/stream/scaladsl/Flow.html and https://doc.akka.io/api/akka/current/akka/stream/scaladsl/Source.html both document an `ask` method that doesn’t exist in the source.

Also https://doc.akka.io/docs/akka/current/stream/stream-integrations.html#integrating-with-actors recommends `ask` as the go-to way of integrating actors with streams.

**Comment by ktoso** [comment]
It exists. Since 2.5.11 which is the docs you are browsing there. The docs are correct

Because https://github.com/akka/akka/blob/v2.5.11/akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala#L38

here it is:

https://github.com/akka/akka/blob/v2.5.11/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala#L886

**Comment by danielyli** [comment]
Excellent! I was on 2.5.9.

As a side note, isn’t it customary to increment the minor version when adding functionality in a backwards-compatible manner?

**Comment by ktoso** [comment]
That is not how Akka is versioned. Explained in depth: https://doc.akka.io/docs/akka/2.5/common/binary-compatibility-rules.html?language=scala

Bigger releases bump the minor, which are still compatible.

**Comment by danielyli** [comment]
Thanks for the explanation!
