### ISSUE TITLE
Typed Persistence: Implement deleting snapshots / events

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24698]
Currently there is no API for it, and I left ??? in the persistent bahavior for it

**Comment by ktoso** [comment]
Should we expose those on the persistence extension? It does not make much sense to expose those operations as `Effect` hmmm

**Comment by johanandren** [comment]
I think it should be an API separate from the typed persistent actors, as it is a separate concern. Konrad suggested something like `JournalCleanup().deletePersistenceId(…, until...)`

**Comment by patriknw** [comment]
Also remember to add the seqnr check when implementing deletes of events, https://github.com/akka/akka/issues/25487

**Comment by patriknw** [comment]
Would be nice to have an api that supported sequenced cleanup
* save snapshot
* delete old snapshots (keep a few old snapshots around)
* delete events prior to snapshots

For example with snapshotting every 100 events and keeping two snapshots

* save events 1-100
* save snapshot at 100
* save events 101-200
* save snapshot at 200
* save events 201-300
* save snapshot at 300
* delete events <= 100
* delete snapshots <= 100
* save events 301-400
* save snapshot at 400
* delete events <= 200
* delete snapshots <= 200

We already have the saving of snapshots every N events in place and I think the deletion of old events and snapshots should be there as well since they are triggered by the SaveSnapshotSuccess. It would be completely automatic and the only API would be some way of specifying how many snapshots to keep around and maybe a way to NOT delete events at all but only delete snapshots.

We could also have something external like the suggested `JournalCleanup`, but I think that is lower priority.

**Comment by helena** [comment]
@patriknw It seemed as though the sharding logic of `keepNrOfBatches` with `snapshotAfter` is useful in a more general sense WRT the snapshot algo, moving forward? Which is related to why I thought we may prefer to move the duplicated function to consolidated one in persistence which then typed could use. Thoughts?

**Comment by patriknw** [comment]
I think we should add this in Persistence Typed only. Good with some added value to encourage usage of new stuff. Trying to share that between the two different implementations will add more complexity than it is worth.

**Comment by patriknw** [comment]
and note that the usage from sharding will go away since we will probably deprecate/remove the persistence mode of sharding, in favor of only maintaining ddata mode

**Comment by tunesmith** [comment]
Hi, can you share more explanation on the reasoning behind deprecating/removing the persistence mode of sharding? I was under the impression that sharding persistence scaled out better than ddata.

**Comment by patriknw** [comment]
@tunesmith I replied in https://github.com/akka/akka/issues/26177#issuecomment-471426802

**Comment by johanandren** [comment]
I'm not sure if we can close this or if we should keep it open until the follow up PRs are in?
