### ISSUE TITLE
[Akka Typed] Future does not get executed with BehaviorTestKit

### ISSUE THREAD

**Issue by Dolly3g** [akka/akka#24703]
Future does not get executed with BehaviorTestKit.

For Example:
```
import akka.actor.typed.Behavior
import akka.actor.typed.scaladsl.{ActorContext, Behaviors}
import akka.testkit.typed.scaladsl.BehaviorTestKit
import org.scalatest.FunSuite
import scala.concurrent.{ExecutionContext, Future}

class MutableRoundRobin[T](ctx: ActorContext[T]) extends Behaviors.MutableBehavior[T] {

  implicit val ec: ExecutionContext = ctx.system.executionContext

  Future {
    println("Inside Future in BehaviorTestKit")
  }
  println("Outside Future in BehaviorTestKit")

  override def onMessage(msg: T): Behavior[T] = {
    this
  }
}

class TestMe extends FunSuite {
  test("should display Inside and Outside Future printlns.") {
    val behTestKit = BehaviorTestKit(Behaviors.mutable[String](ctx ⇒ new MutableRoundRobin[String](ctx)))
    Thread.sleep(1000)
  }
}

```
This test does not print "Inside Future in BehaviorTestKit".

**Comment by johanandren** [comment]
Related to #24686

**Comment by johanandren** [comment]
Note that the `BehaviorTestKit` is not meant for testing asynchronous things, for those we have the `ActorTestKit` so it is not 100% clear that this _should_ (or even is possible to make it) work. If we arrive at that it shouldn't work I think there should be a clear error message from the testkit when you try to use the execution context to schedule things.

**Comment by raboof** [comment]
We [do](https://github.com/akka/akka/blob/ede094a2c633fe5a76bd59607fd9a6eababad4c7/akka-testkit-typed/src/main/scala/akka/testkit/typed/internal/BehaviorTestKitImpl.scala#L84) evaluate all scheduled tasks after processing a message, so given that it might make sense to also run them after initialization?

If you have fairly complicated asynchronous code in your implementation and you want to treat those as 'implementation details' rather than testing them in depth, the [asynchronous testing](https://doc.akka.io/docs/akka/snapshot/typed/testing.html#asynchronous-testing) style might fit better.

**Comment by raboof** [comment]
In any case when you pass in your first message (`behTestKit.run("someMessage")`) it should then print `Inside Future in BehaviorTestKit`.

**Comment by johanandren** [comment]
Oh, i had missed the "controlled" execution context, yes, then I agree it should work.
