### ISSUE TITLE
ReceiveTimeout not triggered in some case

### ISSUE THREAD

**Issue by trobert** [akka/akka#24770]
In this example:
```
object TestApp extends App {
  val sys = ActorSystem()
  sys.actorOf(Props[MyActor])
}

class MyActor extends Actor {
  context.setReceiveTimeout(1.second)

  override def receive: Receive = {
    case Message ⇒
      println("Message")
    case ReceiveTimeout ⇒
      println("ReceiveTimeout")
      self ! Message
  }
}
// Breaks when Message extends NotInfluenceReceiveTimeout
object Message //extends NotInfluenceReceiveTimeout

```

As-is, it prints `Message` and `ReceiveTimeout` every seconds, which is expected behaviour.

However, if  change `Message` to extends `NotInfluenceReceiveTimeout`, it will only send a `ReceiveTimeout` only once. In my testing, it seems that sending a `NotInfluenceReceiveTimeout` on the reception of the `ReceiveTimeout` disable the receiveTimeout. 

Even if I add a `context.setReceiveTimeout(1.second)` after `println("Message")`, the second receiveTimeout is never triggered.

This was tested with akka 2.5.11.

**Comment by newca12** [comment]
The culprit is this optimization for non empty mailboxes
https://github.com/akka/akka/blob/d503cb0da3c8c3dab1ad5cae0ef250f87da4c00a/akka-actor/src/main/scala/akka/actor/dungeon/ReceiveTimeout.scala#L31-L32
If all messages in the mailbox implement NotInfluenceReceiveTimeout, there will be no reschedule as observed by @trobert.
The fix is very easy (removing the optimization for non empty mailboxes) but may have performance impact.
