### ISSUE TITLE
Akka event logging unnecessary ' started' while shutdown

### ISSUE THREAD

**Issue by anilkumarmyla** [akka/akka#24803]
While shutting down, this gets logged in DEBUG level, notice the unnecessary ` started` at the end of line
`[DEBUG] - from akka.event.EventStream-? in application-akka.actor.default-dispatcher-8 shutting down: StandardOutLogger started`

Fix goes into
`159 publish(Debug(simpleName(this), this.getClass, "shutting down: StandardOutLogger started"))`

**Comment by tometchy** [comment]
Why you find it unnecessary? Look at the code:

``` scala
  private[akka] def stopDefaultLoggers(system: ActorSystem): Unit = {
    @nowarn("msg=never used")
    val level = _logLevel // volatile access before reading loggers
    if (!(loggers contains StandardOutLogger)) {
      setUpStdoutLogger(system.settings)
      publish(Debug(simpleName(this), this.getClass, "shutting down: StandardOutLogger"))
    }
```

In my view this code means, that when we are in stop default loggers method, first thing which we do is checking if _StandardOutLogger_ is up and if it's not then we start it (!), that's why there was this _started_ keyword at the end of this debug log.

Yet bigger question is - why is StandardOutLogger started in _stopDefaultLoggers_ method?
