### ISSUE TITLE
Memory leak due to not removed ThreadLocal in akka.dispatch.forkjoin.ForkJoinPool$Submitter

### ISSUE THREAD

**Issue by martin-g** [akka/akka#24838]
This issue is similar to https://github.com/akka/akka/issues/17978.
The difference is that the ThreadLocal leak is detected in test environment, i.e. `sbt test`. 
The issue we have is that it is not possible to run few times (depends on MaxMetaspaceSize) `test` task in sbt session because it fails with OutOfMemoryError: Metaspace.

Please find attached a small demo project. 
It uses https://github.com/luchesar/sbt-leak-prevention which seems to be not released to any Maven/Ivy repo so you will have to build it locally: `sbt publishLocal`.
Then `sbt test` in the demo project will print:
```
[info] ThreadLocal of type java.lang.ThreadLocal: java.lang.ThreadLocal@4219e17f with value akka.dispatch.forkjoin.ForkJoinPool$Submitter@62834d58 of type akka.dispatch.forkjoin.ForkJoinPool$Submitter that is loaded by web app will be remove()d from Thread[pool-7-thread-3,5,main]
```

Looking at [akka.dispatch.forkjoin.ForkJoinPool](https://github.com/akka/akka/blob/master/akka-actor/src/main/java/akka/dispatch/forkjoin/ForkJoinPool.java#L1413) - its `static final ThreadLocal<Submitter> submitters;` is never `remove`d or `set(null)`.

[akka-class-loader-leak.zip](https://github.com/akka/akka/files/1870794/akka-class-loader-leak.zip)

**Comment by johanandren** [comment]
Just to sum up after looking at it for a bit: 

The thread local usage is exactly the same as done in the ForkJoinPool in the JDK, and is used to shard threads posting work to the internal queues in the FJP.

Inside of Akka there are in general few threads, and those are stopped when the actor system is shut down, so those leaked `Submitter`s would be released, then what is left is external threads interacting with the FJP.

The issue here is then that the `Submitter` class is kept in memory by the thread, which likely keeps the entire class loader from being garbage collected. And as every non-forked test run in sbt will probably load the class anew, that is one set of all classes per test run.

I'm not sure we can fix this in the FJP, for two reasons: 
1. We'd have to keep a list of all threads that ever posted work the the FJP (and keep those cleaned up) to be able to do it.
2. As it is, it is pretty much a verbatim copy of the Java 8 FJP (which we added to work around a performance degradation in the Java 9 one), and I'm not sure we want to have it diverge from the original Java 8 class.

It could perhaps be possible to add some workaround in the sbt project though, if you can somehow hook into sbt, iterate over the threads still left alive after a test has completed and clear that thread local. Or if it would somehow be possible to make sure sbt ran the test in a thread that is stopped when done.

**Comment by johanandren** [comment]
Hmm, I see `Submitter` it is package private, so there is actually no public-api way to clear the `ThreadLocal`. 

A workaround could be to create this:
```
package akka.dispatch.forkjoin {
  object ClearThreadLocal {
    def doIt(): Unit = {
      ForkJoinPool.submitters.remove()
    }
  }
}
```

and call it in `afterAll` of your test.

**Comment by martin-g** [comment]
Which version of JDK 8 do you mean ?
I use jdk1.8.0_91 and it doesn't use ThreadLocal. The current one also looks like _91: http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ForkJoinPool.java

I thought Akka uses some older version to be compatible with JDK 1.6/1.7.
The new version uses `ThreadLocalRandom.getProbe()` instead.

**Comment by johanandren** [comment]
I'm looking at  1.8.0_161 here, which still does that. 

Let's keep the issue open and see if we should backport something from upstream, or if we can think of a better solution.

**Comment by johanandren** [comment]
Correction, I must have been looking at an older version indeed. `_161` does not use the thread local.

**Comment by martin-g** [comment]
Oh, I closed it by mistake!

**Comment by martin-g** [comment]
Is there a way to tell Akka to use the one provided by the JDK ? I use Scala 2.12 and JDK 8.

**Comment by johanandren** [comment]
I think you should be able to do that wit a little work providing your own `ExecutorServiceFactoryProvider`. It will likely have performance implications though.

**Comment by patriknw** [comment]
Note that we use jsr166 source code, and backporting from jdk is probably not an option.

Some hack to cleanup the thread local would be nice though.

I think we should look into moving to standard jdk pool again. Probably a task for Akka 2.6.

**Comment by johanandren** [comment]
The problem with cleaning up the thread local is that it could be any given thread in the JVM posting work to the FJP, so we'd have to iterate over all of them on system shutdown.

**Comment by patriknw** [comment]
I see, do we know what external threads that are holding on to the ThreadLocal? Is it sbt test runner threads? Shouldn't the number of such threads be bounded? Would it be possible to reduce the size of the pool of such threads, to make them overwrite their ThreadLocal more often?

**Comment by patriknw** [comment]
or what would happen if we set the `submitters` to `null` when we shutdown the fjp?

**Comment by johanandren** [comment]
In the case of sbt it's one test-runner thread, but in the generic case I think it could be any user thread on the JVM that has posted work to the FJP (sending messages/scheduling futures or completion stages etc). `submitters` is the thread local, so we`d have to set that to null in a call on each thread that interacted with the FJP.

For sbt with non-forked tests this is what the workaround I posted https://github.com/akka/akka/issues/24838#issuecomment-378206163 does, as we know the test is executing on that thread where the `Submitter` leaked we can clear it in `afterAll`.

After the fact we may no longer have access to the same version of the `Submitter` class, since it was loaded anew in a new class loader and isn't equal/the same as the one used to write the thread local. I think it will then be impossible to clean it up (as the thread local is accessed with the type as the key).

**Comment by mkurz** [comment]
Does #26893, which has just been merged, fix this issue here?

**Comment by johanandren** [comment]
Good catch, I think it should, but I don't think anyone have verified that yet.

**Comment by jrudolph** [comment]
It seems the ThreadLocal is gone since http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/rev/f08ad5938709 from Sat, 02 Mar 2013 08:54:37. So, this should indeed be fixed in any JDK version of the ForkJoinPool for a long time.
