### ISSUE TITLE
Maybe add Materializer#terminate

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24835]
ActorMaterializer has a `shutdown: Unit` but not a `terminate` that would be more in line with the Future returning terminate in Akka Actor.

Should we make them more consistent?
This only exists nowadays:

```
  /**
   * Shuts down this materializer and all the stages that have been materialized through this materializer. After
   * having shut down, this materializer cannot be used again. Any attempt to materialize stages after having
   * shut down will result in an IllegalStateException being thrown at materialization time.
   */
  def shutdown(): Unit

```

Noticed when making an afterAll and suprised it did not return a Future

**Comment by patriknw** [comment]
Such signature is problematic for scaladsl/javadsl Future vs CompletionStage since this class is shared.

What would the Future mean? Many stages have Future materialized values and users may expect all those to be completed also before completing the Materializer's Future, but that is probably not something we can pull off.

**Comment by Captain1653** [comment]
This issue is quite old and without any activity.

Does it make sense to close it?

**Comment by johanandren** [comment]
Let's close it for now
