### ISSUE TITLE
missing Java example for jmm.md

### ISSUE THREAD

**Issue by ccronemberger** [akka/akka#24869]
In this page:

https://github.com/johanandren/akka/blob/master/akka-docs/src/main/paradox/general/jmm.md

I did not find the Java sample code.

Regards,
     Constantino

**Comment by Captain1653** [comment]
This issue is quite old. The sample Java code was added in [this PR](https://github.com/akka/akka/commit/0719de035beef49209367eca4496d02a969fad14#diff-fb628dd50e5723cb6cfa407a5521a2b0de8cbd4c02c048475f6649d3abc93ceb) .

Should this issue be closed?

<img width="300" height="200" alt="Screenshot 2023-08-25 at 23 48 20" src="https://github.com/akka/akka/assets/4740207/7cbcc63f-6097-4e3b-9761-3deb4936b63e">

**Comment by johanandren** [comment]
Yes, thanks
