### ISSUE TITLE
More convenient API for javadsl recoverWithRetries

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24888]
`PartialFunction` is cumbersome from Java, and I think a simple `Class` parameter would be sufficient for most cases.

**Comment by satansk** [comment]
Hi @patriknw , I'm working on this issue. From your comments, I add another `recoverWithRetries` which take a `Class` and a `Graph` instead of `PartialFunction`:

```Scala
  def recoverWithRetries[T <: Throwable](attempts: Int, clazz: Class[T], graph: Graph[SourceShape[Out], NotUsed]): javadsl.Flow[In, Out, Mat] = {
    val pf = new PFBuilder[T, Graph[SourceShape[Out], NotUsed]]()
      .`match`(clazz, new FI.Apply[T, Graph[SourceShape[Out], NotUsed]]() {
        override def apply(i: T): Graph[SourceShape[Out], NotUsed] = graph
      }).build()
    new Flow(delegate.recoverWithRetries(attempts, pf))
  }
```

I make a `PartialFunction` inside of `recoverWithRetries` and delegate the function to `new Flow(delegate.recoverWithRetries(attempts, pf))`, but I get a error message here:

```
Error:(1401, 52) type mismatch;
 found   : PartialFunction[T,akka.stream.Graph[akka.stream.SourceShape[Out],akka.NotUsed]]
 required: PartialFunction[Throwable,akka.stream.Graph[akka.stream.SourceShape[Out],akka.NotUsed]]
    new Flow(delegate.recoverWithRetries(attempts, pf))
```

When I modify the Scala dsl `recoverWithRetries` to this, the error disappeared:

```Scala
// from PartialFunction[Throwable ..] to PartialFunction[_ <: Throwable ..]
def recoverWithRetries[T >: Out](attempts: Int, pf: PartialFunction[_ <: Throwable, Graph[SourceShape[T], NotUsed]]): Repr[T] 
```

But I'm not sure if this is appropriate, could you give me some insight please?

And besides `recoverWithRetries`, `recover` and `recoverWith` may also need a more convenient counterpart.

Thanks :)

**Comment by huntc** [comment]
Nice!
