### ISSUE TITLE
Generalize type of coordinated shutdown tasks

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#25100]
[`CoordinatedShutdown` tasks](https://doc.akka.io/api/akka/current/akka/actor/CoordinatedShutdown.html#addTask(phase:String,taskName:String)(task:()=%3Escala.concurrent.Future[akka.Done]):Unit) have the type `() => Future[akka.Done]` (or [`Supplier<CompletionStage<akka.Done>>` in Java](https://doc.akka.io/japi/akka/current/akka/actor/CoordinatedShutdown.html#addTask-java.lang.String-java.lang.String-java.util.function.Supplier-)).

In contrast, Play's equivalent [`ApplicationLifecycle.addStopHook`](https://www.playframework.com/documentation/2.6.x/api/scala/index.html#play.api.inject.ApplicationLifecycle@addStopHook(hook:()=%3Escala.concurrent.Future[_]):Unit) defines stop hooks as `() => Future[_]`.

The value yielded by the future does not matter: all that coordinated shutdown does is wait for it to complete and then discards the value (ignoring some error handling). Asynchronous tasks that yield a value other than `Done` will need to add boilerplate to map the result to `Done`, just to satisfy the type checker.

It would be more convenient to allow any `Future[_]` to be returned from a shutdown task. This would be a backward-compatible change. `Done` can still be used when there is nothing else already at hand.

**Comment by patriknw** [comment]
@TimMoore Yesterday I actually did a subtle mistake when refactoring some code that wasn't using strict types of the futures. It resulted in hard to debug race conditions and would have been a compiler warning if the types had been specified. Minimized example:

```scala
    def doSomething(): Future[Done] = Future {
      println("doSomething")
      Done
    }

    def doSomethingElse(): Future[Done] = Future {
      Thread.sleep(3000)
      println("doSomethingElse")
      Done
    }

    def doThings(): Future[_] =
      doSomething().map(_ => doSomethingElse())

    doThings().foreach(_ => println("done"))
```

I want these things to be done in order "doSomething", "doSomethingElse", "done". Can you see what is wrong?

Yeah, it should be `flatMap` instead of `map`. It wouldn't compile if it was `Future[Done]` instead of `Future[_]`.

Correct code:
```scala
    def doSomething(): Future[Done] = Future {
      println("doSomething")
      Done
    }

    def doSomethingElse(): Future[Done] = Future {
      Thread.sleep(3000)
      println("doSomethingElse")
      Done
    }

    def doThings(): Future[Done] =
      doSomething().flatMap(_ => doSomethingElse())

    doThings().foreach(_ => println("done"))
```

I think that illustrates why it's better to be explicit with the types even though it adds a bit of boilerplate for mapping to `Done`. In the CoordinateShutdown API I think that boilerplate is fine and worth the extra safety, especially since it's not an API that is used at many places. You would add one or a few such task in your application.

**Comment by TimMoore** [comment]
Good example, thanks.
