### ISSUE TITLE
Add proxy option to IO(Tcp)

### ISSUE THREAD

**Issue by yangguang760** [akka/akka#25221]
I have searched the doc and code, no options for proxy are found.
Also, -DhttpProxy / -DhttpsProxy / -DsocksProxy vm options also not work.

**Comment by raboof** [comment]
As far as I can see a proxy at the TCP level does not seem possible, since there is not part of the protocol where the 'actual' destination can be specified.

We typically use the issue tracker only for bugs in the latest version and feature requests, so it might be better to explain what you are looking for in our chat (https://gitter.im/akka/akka) or forums (https://discuss.akka.io). I'll close this issue until we have a clearer idea of what is missing.
