### ISSUE TITLE
Typed ActorRef that silently ignores all messages

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25306]
To be used as replyTo when you don't care about the reply.

An option might be that it forwards to deadLetters but I think that should be a choice.

**Comment by sarahgerweck** [comment]
I would prefer a version that _doesn't_ go to deadLetters, because I'm explicitly choosing that I want to ignore the response. I'd maybe like to see some kind of fast path so that `!` doesn't put the message in a mailbox at all, as it seems like a low-cost check that might eliminate a significant amount of overhead in terms of queuing and discarding messages. (This might be accomplished in a number of ways.)

**Comment by patriknw** [comment]
Another situation where this would be useful is is when using `EventSourcedBehavior.withEnforcedReplies` and some commands don't have a reply. The messages must then still extends `ExpectingReply` and the `replyTo: ActorRef` must have some value even if it's not used. Something like this:

```
final case class CommandWithoutReply() extends ExpectingReply[Nothing] {
  override val replyTo: ActorRef[Nothing] = ActorRef.ignore
}
``` 

Current workaround for that is to use null, which is ok since it's not used.
```
override val replyTo: ActorRef[Nothing] = null
```

**Comment by patriknw** [comment]
Thinking some more, the above example is actually better with by throwing the exception since it's not supposed to be used. It can't really be used since the type is `Nothing` so it will not be possible to use:
```
case cmd @ CommandWithoutReply() =>
  Effect.reply(cmd)(...)
```
