### ISSUE TITLE
Rewrite Source.actorRef as GraphStage

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25324]
Also consider the issue with PoisonPill that was discovered in https://github.com/akka/akka/pull/25286

**Comment by lasekio** [comment]
It seems to be very similar to `Source.queue` unless support for backpressure, becouse of tell api I guess. Can we build on top of it somehow or you want it to be completely separated implementation?

**Comment by patriknw** [comment]
I think it’s worth to have it separate. It can probably make use of the ActorRef of the stage (if that can be returned as materialized value).

**Comment by lasekio** [comment]
I cant use stage actor in `GraphStageWithMaterializedValue`, because it is not initialized yet, during logic construction when we have to provide materialized value.

**Comment by nachinius** [comment]
@patriknw I took a look and found the following.

Current Source.actorRef uses a SourceModule instead of a GraphStageWithMaterializedValue. 
There is a reason for it. With SourceModule, there it has access to a MaterializationContext before it's being materialized, whereas with GraphStageWithMaterializedValue there is access to a similar context during the materialization phase itself.

I see basically two way so far,
a) altering the API GraphStageWithMaterializedValue.createLogicAndMaterializedValue, so it also receives somehow a materialize in which it can create the ActorRef
b) to materialize a Future[ActorRef] instead of a ActorRef. In this case, the actorRef is created in the GraphStageLogic.preStart()

By the way, what's the need for this refactoring?

**Comment by patriknw** [comment]
> By the way, what's the need for this refactoring?

Because it's implemented with the deprecated `akka.stream.actor.ActorPublisher` that we eventually (2.6.0) want to remove.

Seems related to https://github.com/akka/akka/issues/24372 where we also would prefer non-Future materialized value. We might have to come up with something new to be able to create such stages. Not sure what it would be right now.

**Comment by nachinius** [comment]
Since the `akka.stream.actor.ActorPublisher` is being removed soon, a lot of its functionality should be ported/implemented somewhere inside the `Source.ActorRef`, right? This actorRef is a stream publisher, and this is basically the job of ActorPublisher.  
Thus, would it make sense to keep of the `ActorPublisher` (or a simplified version) as an internal api?

**Comment by ktoso** [comment]
> Thus, would it make sense to keep of the ActorPublisher (or a simplified version) as an internal api?

I'd rather say no, since everything it can do a `GraphStage` can do and saver + fuseable.

**Comment by nachinius** [comment]
How do you connect the `GraphStage` with the `ActorRef`?

Every time there is demand, the GraphStage must check that `ActorRef` for messages, obtaining them if any, and pushing it out. I don't see how to do this, without implementing in the Actor behind the `ActorRef` some type of Subscriber. It may be possible to leverage a StageActor (not sure if it's intended for other things that are not watching), or some very advanced use of SourceRef. Thoughts?

**Comment by nvollmar** [comment]
I've prepared a sample implementation for graph actor ref source based on a distributed pubsub source I've implemented once: #26054

To exemplify the two issues already mention:
* stage actor ignores PoisonPill => either a dedicated message is required or stage actor's behaviour must be adapted (mapping poison pill to an internal message to be matched for example)
* stageActor can only be created in preStart which prevents us from returning the actor ref directly

**Comment by nvollmar** [comment]
I've updated PR #26054 with a possible implementation for it (with internal access to materializer)

**Comment by nvollmar** [comment]
@patriknw I've updated PR #26054 with a possible implementation for it (with internal access to materializer)
It still needs a little additional work to complete (side-effects in other tests, PoisonPill backwards compatible handling etc) but might be a way to replace the deprecated source.
