### ISSUE TITLE
Jenkins nightly builds don't run on jdk9

### ISSUE THREAD

**Issue by raboof** [akka/akka#25330]
https://jenkins.akka.io:8498/job/akka-nightly-jdk9/229/console
```
[error] /localhome/jenkinsakka/workspace/akka-nightly-jdk9/akka-actor/src/main/scala/akka/util/Unsafe.java:14:25: not found: value sun
[error]     public static final sun.misc.Unsafe instance;
```
Seems to work locally though.

Local JDK:
```
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)
```

a0 /usr/lib/jvm/jdk-9/bin/java:
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

**Comment by johanandren** [comment]
Moved forward from no sun misc to: 

```
[error] java.lang.NullPointerException
[error] 	at scala.tools.nsc.classpath.JrtClassPath$.apply(DirectoryClassPath.scala:142)
[error] 	at scala.tools.util.PathResolver$Calculated$.basis(PathResolver.scala:246)
[error] 	at scala.tools.util.PathResolver$Calculated$.containers$lzycompute(PathResolver.scala:257)
[error] 	at scala.tools.util.PathResolver$Calculated$.containers(PathResolver.scala:257)
[error] 	at scala.tools.util.PathResolver.containers(PathResolver.scala:273)
[error] 	at scala.tools.util.PathResolver.computeResult(PathResolver.scala:295)
[error] 	at scala.tools.util.PathResolver.result(PathResolver.scala:278)
[error] 	at scala.tools.nsc.backend.JavaPlatform.classPath(JavaPlatform.scala:23)
[error] 	at scala.tools.nsc.backend.JavaPlatform.classPath$(JavaPlatform.scala:22)
```

It somehow doesn't quite feel like a success.

**Comment by johanandren** [comment]
Installed OpenJDK 10 instead to get anywhere, seems like it helped. I wonder if that is enough, was there something specifically JDK 9 we needed to test?

**Comment by johanandren** [comment]
Meh, back to no sun misc

**Comment by johanandren** [comment]
Argh. Same for Oracle JDK 10.

**Comment by johanandren** [comment]
Should note that I mostly compile with JDK 10 on my machine.

**Comment by johanandren** [comment]
Building with Scala 2.11 gets us past that error, but it then fails with some other thing I don't understand: https://jenkins.akka.io:8498/job/akka-nightly-jdk9/248/console

**Comment by johanandren** [comment]
Related #757

**Comment by johanandren** [comment]
So, `-release 8` is the culprit. (@SethTisue is my hero for figuring this out)
Now, that is put there on purpose, because we want to support JDK 8, so why does it make `sun.misc` disappear from the classpath? 

Also, why haven't we noticed when releasing, that is when we really want the `--release 8` to apply, but we need to build with 9+ because of the Java 9+ specific RS classes.

**Comment by johanandren** [comment]
I figured out why it has been passing locally before, it is because the `-release 8` is only enabled on Scala 2.12 and we default to 2.11 still. Switching to 2.12 (`++2.12.6`) I get the same failure locally on my Mac and Java 10. Reintroducing the `-javabootclasspath`-"monkeying-around" pointing to an actual `rt.jar` of Java 8 seems to fix the problem.
