### ISSUE TITLE
Page scrolls automatically when switching between scala and java tabs in akka docs using FireFox

### ISSUE THREAD

**Issue by gtlcheung** [akka/akka#25365]
When you switch between the Java and Scala tabs to see the code examples on pages in the Akka docs [Version 2.5.14]
the page scrolls automatically, which makes it hard to see where you were. I am using FireFox 61.0.1
This behaviour occurs more often in the middle of a page.

**Comment by raboof** [comment]
I have noticed this as well: this is caused by the code snippets switching between Java and Scala, and some snippets are longer or shorter depending on the language. I also noticed this is pretty distracting in Firefox, while Chrome does a much better job at maintaining document location.

I'm not sure if there's anything we can do about this?
