### ISSUE TITLE
Make clearer recommendation in the 'shared leveldb' documentation section

### ISSUE THREAD

**Issue by raboof** [akka/akka#25441]
The 'shared leveldb' section (https://doc.akka.io/docs/akka/current/scala/persistence.html#shared-leveldb-journal) does mention it is not a production option and is replaced by another mechanism, but those are not very actionable recommendations at this point (e.g. pointing to the very generic https://akka.io/community).

It might be nice to give a little more specific guidance here.

**Comment by Captain1653** [comment]
This issue is quite old. LevelDB was deprecated in [this PR](https://github.com/akka/akka/pull/30213). 

There  are new links in the docs for alternatives:
* [Classic](https://doc.akka.io/docs/akka/current/persistence.html?language=scala#testing-with-leveldb-journal)
* [Plugins](https://doc.akka.io/docs/akka/current/persistence-plugins.html#local-leveldb-journal)

Should this issue be closed?

**Comment by johanandren** [comment]
Yes, let's close, thanks
