### ISSUE TITLE
Simplify ClusterSharding.spawn signature

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25480]
By comparing how to register a PersistentEntity in Lagom we should see if ClusterSharding is adding any unnecessary technical complexity in the API.

The current signature: 

https://github.com/akka/akka/blob/f3c5a32a984497e2e2d2a844e2043e611d04a444/akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/scaladsl/ClusterSharding.scala#L162-L168

* `behavior: String ⇒ Behavior[A]` - not much we simplify here. In Lagom the entityId is part of the PersistentEntity API, but in Akka we don't want to tie persistent actors to sharding only (and vice versa). We probably have to add another parameter to this factory to support passivation, see https://github.com/akka/akka/issues/24478#issuecomment-396852705

* `props: Props` - this should become optional since Props is rarely needed, only for custom dispatcher

* `typeKey: EntityTypeKey[A]` - this is needed. In Lagom this is in PersistentEntity API, and it's default implementation is [somewhat dangerous](https://www.lagomframework.com/documentation/1.4.x/scala/PersistentEntity.html#Refactoring-Consideration)

* `settings: ClusterShardingSettings` - should be optional

* `maxNumberOfShards:  Int` - this could perhaps be optional and be read from configuration (move to ClusterShardingSettings?). If read from config we must have a joining config checker to disallow different values in the cluster (full cluster stop/start required to change it).

* `handOffStopMessage: A` - this doesn't exist in Lagom and may be seen as a technical concern that is blurring the business logic in the entity. Would be nice to make it optional, but it would mean implementing something like a PoisonPill (handled by Akka and not user code) that also worked with persistent actors. For discussion.

cc @TimMoore @renatocaval

**Comment by TimMoore** [comment]
Here are a few of my thoughts:

- I think the name `spawn` doesn't really map to a user's mental model of what they're doing. In untyped, the equivalent is called `start`, which seems a little more natural to me.
- Naming the type parameter `A` doesn't reveal anything about what it means. Maybe `C` for "command" or `M` for "message"?
- `behavior` could be renamed to `create` or `createBehavior` to make it a little more obvious what it's for
- I agree that `props` should be optional if it will usually be empty. Could we even make the entity actors' dispatcher set through config?
- I agree that I wouldn't want to replicate the default type key behavior from Lagom, because most people are probably unaware that it exists and would probably not read or remember that section of the documentation at the point in time when they are refactoring. The best way to handle this is with template code that hardcodes the entity name at generation time, and includes a comment about what it means and why it can't change.
- Maybe it would be nice to improve the configuration so that you can have per-entity settings read from config using the entity type key as a namespace. Explicitly building and passing a `ClusterShardingSettings` instance should be rare.
- I agree that it makes sense to read the number of shards from config. It often makes sense to use different values in development and production. Keeping it in code doesn't prevent different values in the cluster (someone can change the code) so using the cluster config checker is a good idea anyway.
- It's a good idea to separate control messages from domain messages, but I think we need to come up with some realistic examples. Right now, this feels a little misaligned with other lifecycle concerns, such as completion of recovery, which is handled as a callback rather than a message.

More than this API, I think people have difficulty with learning the concept of cluster sharding and reasoning about its behavior, because it is quite different from how most traditional JVM architectures operate. We should try to create higher-level abstractions that make it easy to implement common patterns. I understand that we want sharding to be usable outside of persistent entities, and vice-versa, but there should be an easy way to use them together that doesn't require understanding them as separate concepts. Using them separately should be considered an advanced use case for unusual scenarios.

**Comment by patriknw** [comment]
Thanks for input. I agree with most of it.

> read from config using the entity type key as a namespace

I think it's enough to be able to create ClusterShardingSettings from Config, e.g. `ClusterShardingSettings(system.settings.config.getConfig("my-sharding-conf"). I think all our settings classes work in that way.

> separate control messages from domain messages

yes, this is a tricky one

> higher-level abstractions that make it easy to implement common patterns

Adding an API dependency from Sharding to Persistence to make that easier would be ok if we find anything that can be made easier to support that combination.

**Comment by patriknw** [comment]
We also discussed that it would be better to use a builder here than having lots of overloaded methods with the optional parameters.

**Comment by patriknw** [comment]
When doing this we should revisit the signature of ClusterSingleton also, so that it is consistent with sharding.

**Comment by jboner** [comment]
I think this is a lot better. Thanks.

**Comment by patriknw** [comment]
We also added the PersistentEntity in https://github.com/akka/akka/pull/25697
