### ISSUE TITLE
Deprecate akka.actor.TypedActor

### ISSUE THREAD

**Issue by raboof** [akka/akka#25516]
Since in 2.6 akka-actor-typed should be the mature replacement.

**Comment by politrons** [comment]
@raboof But I dont understand why one have to replace the other, when they are doing things completely different. In our case, we use typedActors since we have a Framework where using reflection in the initialization of the service, the consumer of the framework that create Java POJO are used to create typedActor, so those consumers have an actorSystem even without know Akka. They use just the POJO, and behind the communication is using Akka mailbox with Dispatcher for Bulkheading and so on.
So in case you deprecate this technology in favor of Akka typed, how can I have similar feature with the current Akka stack?.

Regartds

**Comment by hepin1989** [comment]
it's a delusion....

**Comment by yhpark** [comment]
@patriknw I recently stumbled upon the TypedActor with excitement until I found it's going to be deprecated. My concern comes from a practical/engineering perspective which is that using Akka in its current form forces developers to write code in a entirely Akka-flavored style so that codebase becomes strongly dependent to Akka or at least it becomes really difficult to separate business logic. Because I usually try hard to maintain my code decoupled from any specific framework, I've been really hesitant to transition our codebase to using Akka and many times I put an extra layer to put Akka Actor behind a OO style vanilla Scala interface. Hence, in my point of view, TypedActor looks like a decent solution I regret not knowing earlier.

Although I couldn't read the book you mentioned to @politrons (because [the content](https://livebook.manning.com/#!/book/reactive-design-patterns/chapter-5/8) is *obfuscated* due to copyright) I can imagine situations the 'transparent remoting' causing problems: (i) it pitfalls devs to make blocking remote calls (ii) and hinders the fact that the arguments and return values (within future) should be serializable. ( what else?)

But I still think that not making the whole codebase Akka-flavored is a comparable benefit. Also I could imagine we could prevent these usages when using TypedActor by enforcing stronger constraints. For instance we might enforce every method signature to return either `Unit` or `Future[_]` otherwise throw a compile-time error?

**Comment by patriknw** [comment]
Transparent remoting: Making remote invocations look the same as local method invocations.

To summarize the fallacy of transparent remoting:
* Was used in CORBA, RMI, and DCOM, and all of them failed. Those problems were noted by Waldo et al already in 1994 http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.41.7628
* Partial failure is a major problem. Remote calls introduce uncertainty whether the function was invoked or not. Typically handled by using timeouts but the client can't always know the result of the call.
* Latency of calls over network have several order of magnitudes longer latency than local calls, which can be more than surprising if encoded as an innocent looking local method call.
* Remote invocations also have much lower throughput due to the need of serializing the data and you can't just pass huge datasets in the same way.

Therefore explicit message passing is a good thing. It looks different from local method calls (`actorRef ! message`) and there is no misconception that sending a message will result in that it's processed instantaneously. The goal of location transparency is to unify message passing for both local and remote interactions, but it doesn't aim at making remote interactions look like local method calls.

That said, the implementation is encapsulated in one file so it shouldn’t be difficult for someone in the community to take responsibility of maintaining it as a separate project outside of Akka core. https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/TypedActor.scala

**Comment by patriknw** [comment]
Another answer we can incorporate some from: 
https://stackoverflow.com/questions/28516273/akka-typed-actors-in-java/28595723#28595723

**Comment by politrons** [comment]
But do you guys realice that you have a huge number of companies where they don’t have the expertise developers, but a big Infra to scale horizontally as much as we need, so performance not always is the best “go for it” but instead be responsive, Message driven, elastic and resilient, which right now thanks to typed actors we have, being used by developers that don’t know anything about Akka or Reactive 
Programing.

Don’t get me wrong, I’m use pure Akka typed in my day by day,  but for delivery teams we have this framework that use typed actors and our consumers use as POJO without know that they are coding in a reactive system. And that’s awesome feature.

**Comment by helena** [comment]
Add to Migration Guide

**Comment by politrons** [comment]
This means in Akka 2.6 TypedActors has been deprecated?

**Comment by patriknw** [comment]
It will be deprecated in 2.6.0 and probably deleted in 2.7.0, so it will stay around for several years.

**Comment by helena** [comment]
@patriknw when we merge https://github.com/akka/akka/issues/25516 let's close this. I will leave it open for now as it is related.
