### ISSUE TITLE
Materializer as End-User API: yay or nay?

### ISSUE THREAD

**Issue by viktorklang** [akka/akka#25559]
The introduction of [Materializer](https://doc.akka.io/api/akka/current/akka/stream/Materializer.html) to Akka Streams was to make it possible to create different *interpreters* of Akka Stream graphs. Given the currently available options (1—ActorMaterializer), it would seem as if the cost of having the Materializer API as an end-user visible API is higher than its benefits.

1: Users are exposed to it immediately—removing it would be one less thing to learn and understand.
2: Users are expected to `shutdown()` the Materializer, but it is unclear if that happens.
3: Optimizations in Akka Streams down the line might be made more difficult to implement because of binary compatibility.

I haven't looked into the problem in depth yet, but it sounds feasible to instead require `ActorRefFactory` (both ActorSystem and ActorContext are ActorRefFactories as implicit parameter—and then break out the ActorMaterializerSettings so that power users can control materialization through the settings.
The default configuration could be obtained through the ActorSystem, and then user could optionally override as such:

~~~scala
implicit val system = ActorSystem(…)
val result1 = runnableGraph.run() // materializes using `system`, using the default parameters for `system`
val result2 = runnableGraph.run(_.withDispatcher("my.io.dispatcher")) // materializes using `system`, using the default parameters for `system` but with the dispatcher overridden to "my.io.dispatcher"

class MyActor extends Actor {
  def receive = {
     case foo => runnableGraph.run(_.withDispatcher("my.io.dispatcher"))  // materializes using `context`, using the default parameters for `context`, falling back to `context.system` settings, but with the dispatcher overridden to "my.io.dispatcher"
  }
}
~~~

Thoughts?

**Comment by ktoso** [comment]
I agree that we can hide it from users.

In general the materializers lifecycle is bound to the ActorRefFactory it is created from. Users don't really "have to" call shutdown on the materializer but can ride on terminating the system (or actor), since any such shutdown call is a bit racy in terms with existing running streams anyway.

API wise it only is an incremental change I think, nothing we have to break to make it happen AFAICS.

**Comment by johanandren** [comment]
Somewhat related: #24895

**Comment by patriknw** [comment]
Let's look into this for Akka 2.6

**Comment by patriknw** [comment]
Here is my understanding of what we discussed. Please correct me or fill in more details @raboof @jrudolph .

* [ ] Allow Materializer settings through attributes
* [ ] `run` and `runWith` methods that takes (implicit for scaladsl) `ActorSystem` parameter
  * trouble with overloaded existing method that takes implicit Meterializer parameter in scaladsl, might be solvable with some magic implicit tricks
  * the ActorContext variant is not interesting, since running materializer as child of actor anyway has annoying shutdown problems so we should probably move away from that anyway
* [ ]  Promote `ActorMaterializer` capabilities to `Materializer` and deprecate `ActorMaterializer` (for future removal or making it internal)
* Not sure what we concluded regarding deprecating Materializer and related `run` methods?
  * Maybe too early to do that in 2.6 since it has big impact on downstream projects, such as Akka HTTP

**Comment by hepin1989** [comment]
gearpump?

**Comment by patriknw** [comment]
There is no active development, as far as I know.

**Comment by hepin1989** [comment]
https://youtu.be/y4clK9H_zq4?t=441 vs monix

**Comment by chbatey** [comment]
@raboof @jrudolph what was the plan to make this source and binary compatible? Adding a run that takes a Materializer for binary, but what about for src? What kind of implicit conversion were you thinking and where should it live?

**Comment by raboof** [comment]
We could introduce a new trait that is implemented both by `Materializer` and by `ActorSystem`, and use that:
```
  def run()(implicit val sys: ActorSystemOrMaterializer)
  // for bincompat
  private[stream] def run(val mat: Materializer)
```
Of course naming is hard ;).

**Comment by TimMoore** [comment]
> Of course naming is hard ;).

`Materializerable` 💥 👏
