### ISSUE TITLE
What was the reason for not using restart supervision by default in Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25571]
@rkuhn Could you share the original reason for this?

I'm not implying that I want to change it but wanted to capture your thoughts around the decision in case my guess is incorrect.

**Comment by rkuhn** [comment]
The primary motivation to make the default lifecycle as simple and easily understandable as possible, plus the failure–stop model is also prevalent in all distributed systems literature. Terminating upon failure is also consistent with Hewitt & Agha and it matches the behavior of Erlang.

Technically, failure–stop is preferable because it is strictly less complex to implement and uses less resources: holding on to the initial behavior by default certainly is not always warranted. Hence any strategy that goes beyond this very simple default is offered on an opt-in basis.

BTW: this ticket might as well live in akka-meta

**Comment by patriknw** [comment]
Thanks.

You are right about akka-meta. I created cross-reference https://github.com/akka/akka-meta/issues/82
