### ISSUE TITLE
Allow Logging with `=> String ` as parameter

### ISSUE THREAD

**Issue by idosu** [akka/akka#25613]
Hi,

There is 2 ways of writing logs
1. `logger.debug(s"Some $expensive message!")`
2. `logger.debug("Some {} message!", expensive)`

The second way is good when developing in Java, but in Scala I would like to use the first way but it is not optimal as the string will be evaluated even if the debug is disabled.

There are 2 ways to solve this
1. Add a overload with `=> String` parameter
a. If you are afraid of breaking backwards compatibility and/or slowing down the logging operations, you could set the parameter type to `() => String`
2. Convert the method to a `macro` which I don't like

Thanks,
Ido

**Comment by patriknw** [comment]
We originally choose the approach with message place holders `{}` because that has close to zero overhead, while `=>` allocates an object, the function.

For the rare cases when placeholders are not appropriate (e.g. simple `.toString` of the object is not enough) then the statement can be prefixed with `if (logger.isDebugEnabled)`

**Comment by idosu** [comment]
There is still the overhead of creating a new `Array`, as the `format` method is declared like so `def format(t: String, arg: Any*): String`.

You can still add `() => String` to allow usage without allocation alongside usage with allocation

**Comment by patriknw** [comment]
> creating a new Array

no, there are overloaded methods for up to 4 parameters

**Comment by patriknw** [comment]
you can add such method with an implicit if you prefer such api

**Comment by ktoso** [comment]
As Patrik said:

- there is no array involved up to 4 arguments
- use of by-name is expensive

> You can still add () => String to allow usage without allocation alongside usage with allocation

This _is_ allocation though already, since the function object has to be allocated. You can do so yourself if you want to via adding API via implicits to the logger.

Agree that not something we will do in core of Akka as of now.

**Comment by idosu** [comment]
> no, there are overloaded methods for up to 4 parameters - @patriknw 

True, but all of them call `format` which takes an `Array` as parameter.
https://github.com/akka/akka/blob/c759fcf91da49e9045250c7d609fee0a16daf666/akka-actor/src/main/scala/akka/event/Logging.scala#L1248
https://github.com/akka/akka/blob/c759fcf91da49e9045250c7d609fee0a16daf666/akka-actor/src/main/scala/akka/event/Logging.scala#L1311

**Comment by patriknw** [comment]
Wow, that was not what I expected. I created issue https://github.com/akka/akka/issues/25618
but it's not so bad because it's only done after the enabled check, and then there will be allocations anyway for constructing the final String

**Comment by ktoso** [comment]
Whoa good catch @idosu, thanks
