### ISSUE TITLE
Add JoinConfigCompatChecker for `number-of-shards` in Typed

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25667]

**Comment by renatocaval** [comment]
I can take that one. Are we duplicating the unit tests in Typed? 
We do have tests for it in untyped. I guess we need to duplicate it and port it to typed. Correct?

**Comment by patriknw** [comment]
Thanks @renatocaval
I’m not sure there is much to test here, at least not as a full cluster test. It’s an equals check.

**Comment by renatocaval** [comment]
In untyped, we added tests that effectively check that a node can't join a cluster if `akka.cluster.sharding.state-store-mode` is not the same. 

Maybe we went too far on those tests because we are testing not only the equality check, as you mentioned, but the whole join-config-check mechanism. 

We could rethink this approach and concentrate only on the check itself and that it is effectively declared in the config. We only need one test that can confirm that the join-config-check mechanism works as expected and we don't need to repeat that on each new checker we add.

**Comment by patriknw** [comment]
That was my thinking.

BTW, since we always have to support rolling upgrades when introducing a new check like this it should pass if the property is not defined on one side (both directions should be supported). Do we have that in place already and is that tested?

**Comment by renatocaval** [comment]
I don't recall. Probably not because we had a regression related to this. 

Another reason to have an extended test that verifies that the feature is correct regardless of any specific test.

**Comment by helena** [comment]
PLS BUILD
