### ISSUE TITLE
Enable passivate-idle-entity-after by default

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25782]
passivate-idle-entity-after was introduce in https://github.com/akka/akka/pull/25765 but we couldn't enable it by default in a 2.5 patch release, so this is to be done in 2.6.0

I think a decent default is a few minutes, let's say 5. The reason for enabling it by default is that users don't care/know about passivation and then resulting in all entities always being in memory.

**Comment by patriknw** [comment]
Remember to remove or amend this line in reference docs also "By default automatic passivation is disabled."

**Comment by zbynek001** [comment]
Is there maybe an issue for persistent shard and `passivate-idle-entity-after`?
I think it's missing update of `lastMessageTimestamp` before this line:

https://github.com/akka/akka/blob/d3adeb8e0dc164ebea47976fc82a6d73c4d99be4/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala#L607

Also i think the test is now not really testing if the passivation happens or not, since there is no watch or message on passivation

**Comment by helena** [comment]
@zbynek001 Do you mean these tests?
* This was pre-existing, testing on inactivity based on the setting, passivate: https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/test/scala/akka/cluster/sharding/InactiveEntityPassivationSpec.scala#L96
* This was added to check the now opt-in disable passivation, since passivate was on by default before https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/test/scala/akka/cluster/sharding/InactiveEntityPassivationSpec.scala#L96

If there is something we missed, as you note above, would you mind creating a bug ticket for us to isolate this?

**Comment by patriknw** [comment]
I noticed the same thing when working on something else there. So fixed in https://github.com/akka/akka/pull/26878/files#diff-a20f79d56dca318dd90db66ce5bc81beR623
