### ISSUE TITLE
Source.queue has unbounded memory use if consumer cannot keep up

### ISSUE THREAD

**Issue by brharrington** [akka/akka#25798]
Here is a sample program showing the problem (tested with akka 2.5.16):

```scala
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger

import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.OverflowStrategy
import akka.stream.ThrottleMode
import akka.stream.scaladsl.Keep
import akka.stream.scaladsl.Sink
import akka.stream.scaladsl.Source

import scala.collection.JavaConverters._
import scala.concurrent.Await
import scala.concurrent.duration._
import scala.util.Failure
import scala.util.Success

object Main {

  def main(args: Array[String]): Unit = {

    val N = 10e6.toInt
    val P = N / 10

    implicit val sys = ActorSystem()
    implicit val mat = ActorMaterializer()
    implicit val ec = scala.concurrent.ExecutionContext.global

    val counts = new ConcurrentHashMap[String, AtomicInteger]()

    def increment(id: String): Unit = {
      val v = counts.computeIfAbsent(id, _ => new AtomicInteger()).incrementAndGet()
      if (v % P == 0) {
        println(s"increment progress - $v")
      }
    }

    val queue = Source.queue[Int](10, OverflowStrategy.dropNew)
      .throttle(1, 1.seconds, 1, ThrottleMode.Shaping)
      .toMat(Sink.foreach(_ => increment("Processed")))(Keep.left)
      .run()

    for (i <- 0 until N) {
      if (i % P == 0) {
        println(s"offer progress - $i")
      }
      queue.offer(i).onComplete {
        case Success(r) => increment(r.toString)
        case Failure(t) => increment(t.getClass.getSimpleName)
      }
    }

    queue.complete()
    Await.ready(queue.watchCompletion(), Duration.Inf)

    counts.entrySet()
      .asScala
      .toList
      .sortWith(_.getKey < _.getKey)
      .foreach { entry =>
        println(f"${entry.getKey}%25s:  ${entry.getValue.get()}%,d")
      }

    Await.ready(sys.terminate(), Duration.Inf)
  }

}
```

My expectation is that the memory use would be small and stable. It would drop most of the elements because they are being offered to the queue much faster than the stream will be able to process them due to the throttle.

What I'm actually seeing is that the `QueueSource$Offer` messages are getting queued up in the unbounded message queue for an actor. These messages will then eventually get processed into the buffer for QueueSource. If you have enough memory, then this example will work, but you can arbitrarily make `N` larger or just make it an endless loop that offers data and it will run out of memory.

This can be mitigated by slowing down the updates to wait for the queue result future, e.g., something like:

```scala
  Source(0 until N)
      .mapAsync(1) { i =>
        if (i % P == 0) {
          println(s"offer progress - $i")
        }
        queue.offer(i).map(r => increment(r.toString))
      }
      .runWith(Sink.ignore)
```

However, it isn't clear from the docs that this must be done in order to safely use the queue. This also makes it difficult to use the queue as a means to get data to a stream from other sources. Ideally it wouldn't actually buffer any more elements than the amount specified when creating the source. The message queue for the actor seems like an implementation detail that the user shouldn't have to worry about.

**Comment by hepin1989** [comment]
I looked into the implementation too, Currently, there is no limitation of the max number of `asyncCallbacksInProgress`, that seems like some kind of leak.

**Comment by brharrington** [comment]
> I'd say that you should use `Source.queue` because you care about the `QueueOfferResult`

One could care about the result value for tracking purposes so that drops can be detected, but not want to throttle the publisher writing to the queue any more than necessary.

> Otherwise it's probably better to use `Source.actorRef`

It does seem to have better performance for a while, but if the publisher is too fast it quickly degrades due to GC in my tests. In some ways it is worse overall because there isn't an option to use the future to determine a sustainable rate for offering data to the queue.

**Comment by WayneWang12** [comment]
I'm wondering why the buffer cannot be full in this case. I've debugged this code and [bufferElem](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala#L61) never get into the overflow branch. That's strange.

**Comment by johanandren** [comment]
The intended use case is not to fire-and-forget as fast as you can though but rather to actually look at the result of the previous offer before offering anew, in a scenario where the stream failed or was abruptly terminated/stopped you would just keep offering elements that then would get lost if you do it like that. 

I think we should document better how it works and how it is intended to be used.

As a side note I think limiting it would be problematic, since any number of threads can post with the same `queue` instance, which means we would have to keep a cas/synchronized count somehow, which we spent quite a lot of effort not to do already since it was very bad for throughput. Keeping a per thread-outstanding-offers count could perhaps be possible but also trixy because thread local performance etc. Letting the user logic be where you limit is much better IMO and actually does allow users to have multiple concurrent outstanding offers if they like.

I don't think that netty limit has anything to do with this discussion, it rather looks like it is about limiting some form of recursion/nested calling.

**Comment by WayneWang12** [comment]
I don't think that's the case. If I can control it, then why should I use a `queue`?

There is a pattern called "Managed Queue Pattern" in @rkuhn's Reactive Design Patterns, which helps us to handle outside uncontrolled input source. I think this `queue` method should implement that pattern.

**Comment by johanandren** [comment]
The "managed queue pattern" is pretty much exactly what the `queue` does, as an outside consumer of such an API you only way to know if the work was enqueued to the "workQueue" is through a future, which is what the `Future[QueueOfferResult]` does.

The problem here is that you could fire off any number of requests to enqueue work (from one or more threads concurrently) and to limit that number of ongoing requests to enqueue.

**Comment by johanandren** [comment]
I'm not sure why you are claiming that, do you have a repeater for it? New elements are definitely being dropped when the buffer is full and the future is completed with `Dropped` for those when I run the sample, just as expected.

**Comment by rkuhn** [comment]
The underlying issue is that the actor implementing the `Source.queue` stage is assumed to have infinite throughput—it is the actor’s mailbox that is a leaking but inaccessible implementation detail.

**Comment by WayneWang12** [comment]
Yes. And I've debugged it as I've said [here](https://github.com/akka/akka/issues/25798#issuecomment-430477383). It's strange...

**Comment by WayneWang12** [comment]
@rkuhn Yes, implicit queueing. You've mentioned it in the book.

**Comment by jrudolph** [comment]
I created #29557 to finally fix this issue. @patriknw and @rkuhn already gave pretty good explanations about what's currently wrong (and has now been for quite a while).

Regarding @johanandren's comment:

> The intended use case is not to fire-and-forget as fast as you can though but rather to actually look at the result of the previous offer before offering anew, in a scenario where the stream failed or was abruptly terminated/stopped you would just keep offering elements that then would get lost if you do it like that.
> 
> I think we should document better how it works and how it is intended to be used.
> 
> As a side note I think limiting it would be problematic, since any number of threads can post with the same `queue` instance, which means we would have to keep a cas/synchronized count somehow, which we spent quite a lot of effort not to do already since it was very bad for throughput. Keeping a per thread-outstanding-offers count could perhaps be possible but also trixy because thread local performance etc. Letting the user logic be where you limit is much better IMO and actually does allow users to have multiple concurrent outstanding offers if they like.

It's been a long time and we never managed to clarify what queue can and should be used. You suggest to document away the current behavior which might have been an intermediate solution. On the other hand, the constraints of the current async callback implementation (which I am responsible for) are a fact even taking `Source.queue` out of the picture, so we should strive to fix them.

In any case, it would be the intuitive thing when `Source.queue` actually could be used to drop elements from a high-throughput upstream that cannot be throttled otherwise. AFAIK, we currently don't have a better mechanism that would allow ingesting such a stream in a safe way.

I'm closing this ticket in favor of the new tickets #29557 and #29558 I just created.

Thanks again for all the input and sorry for keeping it in this state for so long!
