### ISSUE TITLE
sbt fails to load when using 'git worktree'

### ISSUE THREAD

**Issue by raboof** [akka/akka#25813]
Steps to reproduce:

    cd /tmp
    git clone git@github.com:akka/akka
    cd akka
    git worktree add /tmp/akka2
    cd ../akka2
    sbt

This will produce:

```
[error] org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
[error]         at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1518)
[error]         at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:115)
[error]         at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:97)
[error]         at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:140)
[error]         at com.typesafe.sbt.git.JGit.hasUncommittedChanges(JGit.scala:89)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21(SbtGit.scala:123)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$21$adapted(SbtGit.scala:123)
[error]         at com.typesafe.sbt.git.DefaultReadableGit.withGit(ReadableGit.scala:42)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$20(SbtGit.scala:123)
[error]         at com.typesafe.sbt.SbtGit$.$anonfun$buildSettings$20$adapted(SbtGit.scala:123)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
```

**Comment by TimMoore** [comment]
This is a limitation of jgit:

- https://github.com/sbt/sbt-git/issues/110
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475

Depending on how Akka uses sbt-git, it might be simpler to remove it. AFAICT it's only used for branch detection in the Whitesource integration: https://github.com/akka/akka/blob/751a67ef42dc86fde6a66103fc17a0bf627a1546/project/Whitesource.scala#L22

I ended up removing similar code from Lagom because it didn't seem worth the trade-off to lose work tree support: https://github.com/lagom/lagom/pull/1224. Travis CI automatically sets the `TRAVIS_BRANCH` environment variable, so this is used instead.

Alternatively, sbt-git could be fixed so that jgit isn't used anywhere by default:

- https://github.com/sbt/sbt-git/blob/3dd1343ba8c2d77cda92080f65aab91331822a1a/src/main/scala/com/typesafe/sbt/git/ReadableGit.scala#L34-L43
- https://github.com/sbt/sbt-git/issues/160

**Comment by johanandren** [comment]
Just stumbled into this when I wanted to keep `release-2.5` in a worktree in parallel with 2.6/`master`. Annoying!

**Comment by raboof** [comment]
since sbt-dynver uses a git process instead of jgit it might fit nicely to combine https://github.com/dwijnand/sbt-dynver/issues/51 and #26675 and remove sbt-git

**Comment by raboof** [comment]
Pretty niche anyway, let's close this

**Comment by kcris** [comment]
still not fixed? I have the same issue

**Comment by johanandren** [comment]
We no longer use sbt-git in the Akka repo (but I think we still do in other Akka umbrella projects)

**Comment by johanandren** [comment]
I may be wrong, looks like it is pulled in transitively by some other plugin nowadays.

**Comment by raboof** [comment]
> So this is a problem with `jgit`? (which is used by `sbt-git`)

Yes

You could try updating to sbt-git 2.0.1 and using the `useReadableConsoleGit` option in ~/.sbt (https://github.com/sbt/sbt-git#jgit)
