### ISSUE TITLE
Enable scalafix on project

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#25837]
Should enable `scalafix` on Akka project.
At least for `unused import`s ,that's very annoying.

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/47694003-db46e000-dc36-11e8-809f-14672775e026.png)
Like remove unused imports by scalafix

**Comment by raboof** [comment]
Would be nice!

I think scalafix depends on the semanticdb compiler plugin which makes the build quite a bit slower, so I guess this should be behind a flag. Also, we should make sure the 'unused imports' fix does not remove imports from the documentation, because there we sometimes include duplicates to be able to include them in the code examples properly.

**Comment by hepin1989** [comment]
refs:https://github.com/akka/akka/issues/16334
Hope this will fix some of the `warn`

**Comment by hepin1989** [comment]
done，follow  up with https://github.com/akka/akka/issues/26045
