### ISSUE TITLE
Akka 2.5.18 build error in Eclipse

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25910]
Some Java code that is using Akka extensions don't compile with Akka 2.5.18 in Eclipse. This was due to a regression in Scala compiler 2.12.7, https://github.com/scala/bug/issues/11207

Note, similar build error also exists in IntelliJ, also before Akka 2.5.18, unless the Scala plugin is installed.

**Comment by raboof** [comment]
While indeed IntelliJ Ultimate has some cool additional features for Play, Akka and Scala.js, producing an ambigious method error is definitely not intended, also on the Community edition.

Though it is curious you're seeing it with IntelliJ and not Eclipse rather than vice-versa, hopefully the fix for scala/bug#11207 (to be released in scala 2.12.8, likely Akka 2.5.19) will fix all of these ambiguities.

**Comment by patriknw** [comment]
> Installing Scala plugin for Intellij does not help.

That is strange. I think I tried that with IntelliJ and Akka 2.5.18. (didn't use Java 11 though).
With the Scala plugin installed it was ok, but red squiggles without the plugin.

**Comment by hydbird** [comment]
> 
> 
> > Installing Scala plugin for Intellij does not help.
> 
> That is strange. I think I tried that with IntelliJ and Akka 2.5.18. (didn't use Java 11 though).
> With the Scala plugin installed it was ok, but red squiggles without the plugin.

I believe it's java 11's doing. Because if I'm not mistaken it was compiling on java 8 without error with Intellij with the Scala plugin installed.
