### ISSUE TITLE
Responding with stream created with StreamConverters.asOutputStream() causes responses to be truncated.

### ISSUE THREAD

**Issue by Vistritium** [akka/akka#25983]
When creating streaming response using `StreamConverters.asOutputStream` the returned data is sometimes truncated. Response code is ok.
I created simple example that reproduces this issue:
https://github.com/Vistritium/akka-http-stramconverters-asoutputstream-truncated/blob/master/src/test/scala/com/example/Test.scala
(it's only 73 lines of code)
When I create steam using other methods it works correctly. When using `StreamConverters.asOutputStream` it usually fails between 1st and 5th request.

There is no issue with akka-http-testkit, I have this issue with real application.

Akka version: 2.5.18
Akka-http version: 10.1.5

Full project showing the issue with failing test: https://github.com/Vistritium/akka-http-stramconverters-asoutputstream-truncated (5 files)

Additional details:
The test usually shows empty string response, but in real application this is usually truncated in half of the response, some data is sent and some data is dropped.
In the test the issue is usually happening between 1st and 5th request but in my app it happens less frequently: 1 in 50 or even 1 in 100 times.

**Comment by raboof** [comment]
Hmm, this could be a race between the `write()` going though the `dataQueue` and into the `downstreamCallback`, and the `close()` going directly to the `upstreamCallback`: what if `upstreamCallback` is called between the moment the data has been read from the dataQueue and the moment that the data is passed to the `downstreamCallback`?

@schmitch you seem to have done some work in this area, do you know how we intended to safeguard against this?

**Comment by schmitch** [comment]
hm... i actually touched the file a long time ago, so I'm not sure if I can be that helpful, but I will try.

if `flush()` would help, we could maybe also call flush before close, because just from looking it looks like that if `close()` is called, while the dataQueue is not empty it will drop it: https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala#L136

also is there any error which might get swallowed? i.e. inside the stream or when calling close?

**Comment by raboof** [comment]
Unfortunately flushing before closing does not reliably work either, since there is still a chance that both the flush and the close are handled before `downstreamCallback` is invoked with the data read from the queue.
