### ISSUE TITLE
Improve Stream performance?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26110]
Maybe we could do some performance optimization latter, as some competitor show interesting numbers in their keynote.

**Comment by johanandren** [comment]
I'd take a sales pitch for scalaz with more than just one grain of salt. A better reason for optimization would be if you had some concrete case which you can show is unreasonably slow, opening a ticket like this is close to trolling @hepin1989

**Comment by hepin1989** [comment]
The materialization could be optimized a little, @johanandren I could try these weekend.

**Comment by johanandren** [comment]
As I noted in chat, we spent quite a bit of work on optimizing both materialization and interpreter performance already, and there hasn't been any significant changes after that, so I wouldn't expect any general low hanging fruit.

Let us know if you figure something out.

**Comment by hepin1989** [comment]
The new number seems good:
![image](https://user-images.githubusercontent.com/501740/50165140-3d5ec000-031f-11e9-97dd-dbe8ec7e4c93.png)

https://gist.github.com/JD557/9756e4a97bc103122f72ecfd07e69a1f

**Comment by johanandren** [comment]
That's more like it!

**Comment by jrudolph** [comment]
A parser written like this, i.e. not involving any batching of incoming characters is not really a prime use case of akka-stream. It's great that the performance is competitive but batching chunks of characters would still improve it quite a bit more.

Closing this ticket since it doesn't offer any examples of bad performance or hints at what to improve concretely.
