### ISSUE TITLE
Consider vavr and immutables for Akka Typed Java "Functional Style"

### ISSUE THREAD

**Issue by chbatey** [akka/akka#26408]
We've previously avoided having an opinion on data classes and we've had our own builder APIs for pattern matching.

For the OO style of Java Typed I think it makes sense we have our own builder for receive but for Java users choosing the "Functional Style" perhaps we can remove our behavior builder and use `vavr` (formerly `Javaslang`) and `Immutables`?

I've ported the two into specs here: https://github.com/chbatey/akka-typed-varv/

The chatroom example is quite nice with varv I think:

https://github.com/chbatey/akka-typed-varv/blob/master/src/main/java/info/batey/akka/ChatRoom.java

We can then take advantage of their immutable collections.

I open this to discuss, I don't have a strong opinion either way yet. We have 4 APIs for Akka Typed and this would remove some surface area.

**Comment by patriknw** [comment]
I think it's more important to have a consistent look and feel between the OO and functional style (and persistence DSLs) within Akka and we can have that by having control of the builders.

Also, I don't think we should depend too  much on the success of Vavr. For example: "1.x will be a complete rewrite of Vavr"

However, it's great if we can support alternative builders such as Vavr and I think you have illustrated that we can?

btw, it's vavr not varv

Regarding collections that is an independent question and there we don't have any plans of providing anything ourselves. In Lagom we started with Immutables and then switched to Lombok mostly because it was easier to setup in IDEs I think. PCollections is also used in Lagom. https://www.lagomframework.com/documentation/1.4.x/java/Immutable.html
See https://github.com/akka/akka/issues/26072

**Comment by TimMoore** [comment]
Just to clarify, Immutables and Lombok are related more to immutable data classes (equivalent of Scala case classes, used for messages, events, etc.) rather than collections. @patriknw is correct about the reason for the change in default recommendation for Lagom users, but either can still be used.

Lagom does use [PCollections](https://pcollections.org/) but I believe some use vavr with it successfully as well. It's nice to provide some extra examples of how to optionally use these, but I don't think Akka should be opinionated about them.

**Comment by chbatey** [comment]
This as it was mainly about us having our own Matcher API rather than rely on another library in docs and examples. I wouldn't say we'd be relying on the success of vavr, but that one of the Java pattern matching libraries remains good enough that we don't need to build our own.

Regarding not being opinionated on data class generation I agree as that is a divisive topic. Some developers hate code generation not done manually in the IDE.

I think we should consider (again?) being opinionated (by that use one in our examples/samples) for immutable collections. The alternative is copying mutable collections which is verbose and very easy to accidentally leak a mutable reference. The same argument could be for data classes but I think it is better understood that how to make these mutable manually.

**Comment by patriknw** [comment]
Btw, how do they pull it off?
```
Match(message).of(
         Case($(instanceOf(PostMessage.class)), post ->
         Case($(instanceOf(NotifyClient.class)), notification ->
```

The code looks like it's creating the builder (allocating objects) each time, but it can't be that naive? Is it based on byte code generation?

**Comment by chbatey** [comment]
Just plain Java AFAIK. The cases could be re-used between invocations but that would hinder the readability.
