### ISSUE TITLE
Solution for handling signals in EventSourcedBehavior

### ISSUE THREAD

**Issue by s4nk** [akka/akka#26435]
I'm using `EventSourcedBehavior` and I need to handle `PostStop` signal in the actor. I used to use `Behaviors.tap` for that, but after the recent changes around `BehaviorInterceptor` and introduction of `Behaviors.intercept`, it doesn't seem to be possible anymore. I can't create an interceptor that would match the type of the persistent behavior because when it receives `InternalProtocol` messages it blows up with a `ClassCastExceptions` (similar problem as mentioned here https://github.com/akka/akka/pull/25575#issuecomment-419122704). I also can't use `BehaviorInterceptor[Any, Any]` and `widen` + `narrow` because internally `EventSourcedBehavior` is already using `widen` and `Widen can only be used one time in the same behavior stack`. Is there any other way of achieving this?

**Comment by johanandren** [comment]
Forwarding signals to the EventSourcedBehavior and providing an API for that was mentioned in 
https://github.com/akka/akka/issues/25428#issuecomment-466399254 to solve reacting to snapshot completion etc. so I think we will explore that soon, so that'd mean you can handle it there.

For the issue of internal protocol it can be solved by using an interceptor that overrides `interceptMessageType` (which was added specifically for being able to test event sourced behaviors which kind of lie about their protocol)

**Comment by s4nk** [comment]
Thanks! The `receiveSignal` proposal in #25428 sounds like a nice idea, the `interceptMessageType` workaround should do it in the meantime. Should this issue be closed then?

**Comment by johanandren** [comment]
Yeah, let's close this for now.
