### ISSUE TITLE
Allow zero for MergeHub.perProducerBufferSize

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#26589]
For a motivation see https://discuss.lightbend.com/t/how-to-shutdown-a-stream-prefixed-with-a-mergehub-source-without-loosing-elements/2696.

> `MergeHub.source` takes a bufferSize argument which cannot be zero. When using a kill switch like shown below, shutting down results in loosing the elements buffered in the source.
>
> Are there other ways to shutdown without loosing the buffered elements than the one shown below? If not, do you think it’s possible to change the implementation of MergeHub to allow for bufferSize zero?
> 
> ```scala
> MergeHub
>  .source[Foo](bufferSize)
>  .viaMat(KillSwitches.single)(Keep.both)
>  .via(processFoos)
>  .runWith(Sink.ignore)
> ```

**Comment by jrudolph** [comment]
Coming across this because of a different issue with MergeHub.

In general, it is an unrealistic assumption with streams that you can control buffers to a point where you know exactly where things are buffered and where not. When things are torn down because of a failure, there's always the chance of elements being dropped.

For a merge in particular, you cannot do without buffers. After all, a merge needs to consume from multiple producers, so you will have to expect to buffer at least one element per producers because you have to request from all of them concurrently because you don't know which will emit an element next.

So, I'm closing this as invalid, but feel free to keep discussing if my interpretation is wrong.
