### ISSUE TITLE
Strange interaction between zipLatest and an empty source

### ISSUE THREAD

**Issue by txsmith** [akka/akka#26711]
Hi!

I’ve got the following snippet:

```scala
def eval[A](stream: Source[A, NotUsed]): Seq[A] =
  Await.result(stream.runWith(Sink.seq), 10.seconds)

println(eval(Source.single(3) zipLatest Source.empty)) // 1
println(eval(Source.single(3) zipLatest Source(List()))) // 2
println(eval(Source(List()) zipLatest Source(List()))) // 3
```
When executed:

- the first `zipLatest` completes, printing an empty Vector.
- the second one times out, even though `Source(List())` individually does complete.
- the third one completes again.

According to the docs `zipLatest` should complete when any upstream completes. How come it does complete for `Source.empty` but not for some uses of `Source(List())`? Is this the intended behaviour?

**Comment by johanandren** [comment]
Looks like a bug to me, would you be up for trying to PR a fix?

**Comment by txsmith** [comment]
If I can find the time I'd be glad to make a PR, but I'm not sure if I will have time for this very soon.
Besides, now that I think of it, does it really make sense for zipLatest to complete when any upstream completes? If one of the streams completes but the other keeps emitting elements, zipLatest could potentially also keep emitting elements. This would be in line with e.g. `combineLatest` from Rx.

**Comment by johanandren** [comment]
Isn't this a special case of completing when any upstream completes - the case where one upstream completes without ever emitting anything,  in this scenario completing zip itself seems like the only reasonable thing to do. 

I think I'd expect it to complete eagerly even when it has seen an element, given that zip does that, but I'm sure you could argue the other way as well. Some other fan-in stages have a `eagerClose` parameter so that you can decide, so that could also be an option.

So maybe see the first part as the bug of this issue, and the second part we can split into a separate feature issue if we find that it would be useful.
