### ISSUE TITLE
Rolling update from Untyped to Typed Sharding

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26718]
With same entity types and keys.

Investigate if it's possible and document.

**Comment by patriknw** [comment]
Another important part of this is how to deal with `sender` vs the `replyTo: ActorRef` in the messages.

**Comment by ypxu** [comment]
Hi Patrik, I can confirm it's possible to migrate untyped to typed shard actors using rolling updates. Recently, we had migrated actors inside one application with 2 steps approach (akka version: `2.5.23`). 

* Rollout the application while setting the new nodes with `akka.cluster.configuration-compatibility-check.enforce-on-join = off` and make sure all nodes are in this state.
* Rollout again and set the new nodes with `akka.cluster.configuration-compatibility-check.enforce-on-join = on`. This works since the config from existing nodes will pass the compat check.

On one side, our actors are not persistent actors. That might make things easier. Hope that give you some data points. Looking forward to your opinions on this approach. Thanks!

**Comment by patriknw** [comment]
Thanks for sharing, and glad to hear that it works. We will try it out and write some kind of guide for how to do it.

**Comment by patriknw** [comment]
Related https://github.com/akka/akka/issues/27191

**Comment by patriknw** [comment]
I have tried this in https://github.com/akka/akka-samples/pull/110. See the separate commit messages.

@ypxu would be great if you can review that PR and see if it matches your findings.

**Comment by patriknw** [comment]
I have also tried things for Lagom in https://github.com/renatocaval/lagom-1.6-playground/pull/1

**Comment by ypxu** [comment]
@patriknw Sorry for late reply. The steps in your PR are more sophisticated than my previous attempt. That looks good. :)

**Comment by patriknw** [comment]
Given the example in https://github.com/akka/akka-samples/pull/110 and the follow up ticket #27342 to mention it in docs I consider this done.
