### ISSUE TITLE
Recommend Distributed Data mode for Cluster Sharding

### ISSUE THREAD

**Issue by TimMoore** [akka/akka#26723]
Currently, the documentation makes it sound like Distributed Data mode should only be used in an Akka Cluster with no database:

> The functionality when using the two modes is the same. If your sharded entities are not using Akka Persistence themselves it is more convenient to use the Distributed Data mode, since then you don’t have to setup and operate a separate data store (e.g. Cassandra) for persistence. Aside from that, there are no major reasons for using one mode over the the other.

In fact, we now recommend Distributed Data mode for most users. It is the default since Akka 2.5, and in Akka 2.6, persistence mode will be deprecated. The documentation should be updated to reflect this recommendation.

Related: #26177, #22600

**Comment by kuramakills** [comment]
Is it okay if I pick this issue as my first commit to the repo? As far as I'm understanding, I just need to update the documentation and recommend Distributed data mode, and make a note that with Akka 2.6, the persistence mode is going away.

**Comment by patriknw** [comment]
@kuramakills You are welcome to contribute. We have deprecated the persistence mode in https://github.com/akka/akka/pull/27585 and maybe the wording of this section changed, but if there are still something that should be clarified it would be great if you can improve that.

Otherwise you might find something suitable in
https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
or https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+label%3At%3Adocs

**Comment by helena** [comment]
Otherwise let's mark this as done, given the deprecation?

**Comment by TimMoore** [comment]
Yes, the snapshot docs are clear. Thanks!
