### ISSUE TITLE
Incorrect @deprecated tag in akka.pattern.BackoffSupervisor

### ISSUE THREAD

**Issue by mckeeh3** [akka/akka#26887]
With Java API getting a deprecated warning after changing from deprecated props method to non-deprecated props method. The BackoffSupervisor class is flagged with a @deprecated tag.

**Comment by johanandren** [comment]
Thanks for letting us know!

**Comment by TimMoore** [comment]
Copying my message from Slack:

I guess the intent was to deprecate the constructor rather than the class. The annotation is in the wrong place.

The problem here is Java interop: `BackoffSupervisor.props` is a static method on the `BackoffSupervisor` class, but the position of the @deprecated annotation means that the whole class was deprecated, not just the primary constructor. In Scala that would resolve to the singleton object rather the class, so it isn't flagged as deprecated.

I think the correct annotation would look like this:

```scala
final class BackoffSupervisor @deprecated("Use `BackoffSupervisor.props` method instead", since = "2.5.22") (...
```

**Comment by chbatey** [comment]
All of the constructors should be deprecated
