### ISSUE TITLE
Document Akka satellite project upgrade strategy

### ISSUE THREAD

**Issue by raboof** [akka/akka#26985]
After releasing a new version of Akka, we don't immediately bump the Akka version in sattelite projects (such as Akka HTTP, Management, gRPC, etc).

The reason for this is this will make it more low-friction for users to update those sattelite projects: say they are on akka 2.5.22 and akka-management 1.0.0, and we release akka-management 1.0.1 (still against 2.5.22) and akka 2.5.23. They can safely update to akka-managemenet 1.0.1 without updating to akka 2.5.23.

This is a bit of a mini-optimization (whenever a sattelite project wants to use a new Akka feature it will update its Akka dependency), but nice for users that do 'monorepo' or security vetting of new artifact versions.

Perhaps we should document this in https://doc.akka.io/docs/akka/2.5/common/binary-compatibility-rules.html

**Comment by helena** [comment]
I brought it up so I'll do it :-)

**Comment by TimMoore** [comment]
It might be worth elaborating the conditions for when the Akka dependency _is_ updated. I think this is what the Akka team has generally done in the past:

If an Akka satellite needs something from a new Akka minor release, it will branch a new minor release where the dependency is updated. The previous stable branch will enter the usual end-of-support lifecycle. For example, When Akka 2.5 was released, Akka HTTP 10.0.x continued to depend on Akka 2.4. Akka HTTP 10.1.x updated to Akka 2.5, but 10.0.x was maintained for backward compatibility for a period of time according to Lightbend support policy. We should maintain backward-compatible satellite branches for _at least_ as long as the support lifecycle for the previous stable version of Akka, but potentially longer (subject to the support lifecycle minimum commitments).

For example, when we create a hypothetical Akka HTTP 10.2 that depends on Akka 2.6, then Akka HTTP 10.1.x will be maintained for whichever is the latest of:

1. Two years from when 10.1.0 was released (our minimum support commitment)
2. One year from when 10.2.0 is released (to allow time for transition)
3. Until the end of support for Akka 2.5 (which itself is determined by the same guidelines, in this case ≥1 year from when Akka 2.6.0 is released, since it has already been over 2 years since 2.5.0)

Does that sound OK?

**Comment by helena** [comment]
WFM though I defer to my tenured team mates - @patriknw @johanandren @jrudolph WDYT?

**Comment by patriknw** [comment]
As far as I can see those descriptions by @raboof for patch versions and @TimMoore for minor version are correct. I might add that also for minor versions we try stay on building with previous minor as long as possible to avoid maintaining multiple branches.

Another reason for the patch releases is that it reduces the risk that a library dependency pulls in mismatch of versions for the core akka dependencies.

**Comment by raboof** [comment]
Jup sounds good.

Just a thought: with respect to support lifecycles, I wonder if we should be explicit that 'support' here means 'support for Lightbend customers' - this promise is less strict for the community, though of course generally community and customer interests will align just fine.

**Comment by TimMoore** [comment]
Good point, @raboof, but I agree that these typically align, when it comes to the maintenance and lifecycle of stable branches in the open source projects.

**Comment by ennru** [comment]
Yes, I thought about adding something in this area to Alpakka docs, as well.
What we have right now is https://doc.akka.io/docs/alpakka/current/release-notes/1.0.x.html#compatibility

**Comment by ennru** [comment]
For Alpakka things I added https://doc.akka.io/docs/alpakka/current/other-docs/versioning.html

**Comment by patriknw** [comment]
@ennru great, but why is the link to Akka 2.5.23? We should prefer using the non patch links, such as 2.5, 2.6 or current.
https://doc.akka.io/docs/akka/2.5.23/common/binary-compatibility-rules.html

**Comment by ennru** [comment]
Our extref links were full version, added https://github.com/akka/alpakka/pull/2004

**Comment by raboof** [comment]
Done in #28457

**Comment by ennru** [comment]
Great.
Created https://github.com/akka/alpakka/pull/2113

**Comment by raboof** [comment]
doc is at https://doc.akka.io//docs/akka/current/project/downstream-upgrade-strategy.html
