### ISSUE TITLE
Docs: make rolling restarts/upgrades/updates more prominent, easier to find 

### ISSUE THREAD

**Issue by helena** [akka/akka#27039]
https://doc.akka.io/docs/akka/current/project/rolling-update.html

- [x] Make easier and logical to find 
- [x] Do not duplicate anything WRT this https://doc.akka.io/docs/akka-management/current/bootstrap/index.html#rolling-updates 
- [x] Consolidate where we can 

Update - moving these into a separate ticket https://github.com/akka/akka/issues/27192
- [ ] Expand on recommendations, best practices, how to not shoot yourself in the foot with what we know about related to various providers/platforms
- [ ] links to samples

**Comment by helena** [comment]
I'll get things started.

**Comment by velvia** [comment]
Hmmm.  A few things would be great to document.
- What are the guarantees around ClusterSingleton during rolling upgrades?  Is it possible fro two to exist?  What can users do if they don't desire this?  
- What are strategies to keep two singletons from changing state?  Who is the real leader?
- What are possible gotchas w.r.t binary compatibility?
- What about state transitions?  Especially for stuff like distributed data and cluster sharding.  What can go wrong and what should users be aware of?

**Comment by patriknw** [comment]
@velvia some comments to your questions

> What are the guarantees around ClusterSingleton during rolling upgrades? Is it possible fro two to exist? What can users do if they don't desire this?

That shouldn't happen. It's important to use CoordinatedShutdown so that the different phases, including shutdown/startup of singleton are performed in right order.

For a normal rolling update it's using the graceful leaving-exiting-removed transitions so a  downing isn't used, but if something goes wrong it will fall back to downing and then the implementation of the downing provider is important for avoiding split brains with two separate clusters at the same time (and therefore multiple singletons).

I would be happy to look at logs if you suspect that this happened for you, but that should be a separate issue from this documentation task.

> What are strategies to keep two singletons from changing state? Who is the real leader?

I'm not sure I understand the question. Can you clarify?

For additional safety one can use the [distributed lease](https://doc.akka.io/docs/akka/current/coordination.html#lease).

General recommendation is to wait with the oldest node (singletons run on oldest) until last, because then there will only be one transition of the singleton.

**Comment by helena** [comment]
Actually, I think I will break this into two tickets, one the re-org, the second the added content - I'd like to expand input from some other team members on it and get the re-org in first.
