### ISSUE TITLE
config issue with sbt assembly

### ISSUE THREAD

**Issue by protheusfr** [akka/akka#27181]
Hello,

We try to package an application who intergrates an akka client (in Scala).
We use sbt assembly to package them in order to deploy it on a JBOSS server.

During the application startup we get the following message :

```
09:53:36,114 WARN  [org.keycloak.services] (default task-236) KC-SERVICES0013: Failed authentication: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
...
```
despite we have merged the config parameter in just one file 
 (in src/main/META-INF/references.conf) as described in https://doc.akka.io/docs/akka/2.5.6/scala/general/configuration.html#when-using-jarjar-onejar-assembly-or-any-jar-bundler and added `resourceDirectory in assembly := sourceDirectory.value / "META-INF"` in our `build.sbt`.

How to enforce sbt assembly to recognize this parameters for akka ?

**Comment by raboof** [comment]
This seems like a problem with your sbt-assembly configuration - perhaps it would be more suitable to ask this question at https://discuss.akka.io? It would be helpful to share your sbt configuration and the output of the 'assembly' task. Rather than bundling the reference.conf's "yourself" as you describe, it is probably better to leave this to sbt-assembly by using the `MergeStrategy.concat` (see also https://github.com/sbt/sbt-assembly#merge-strategy). I think we should add this to our documentation - I filed #24248 for that.

**Comment by raboof** [comment]
(let's follow up on https://discuss.akka.io if needed, closing the issue here)
