### ISSUE TITLE
[typed] Behavior.withTimers logs unwantedly

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#27218]
When using `Behavior.withTimers` we get log output at DEBUG level under the name/logger of the user class/object, e.g. "Cancel all timers" or "Start timer [] with generation []".

Usually Akka internal log output is not namespaced under the name/logger of user code, but somewhere else, e.g. "akka.cluster...".

I understand that this comes from using `ActorContext.log` and its way of resolving its source class. This might be a great feature, but at the same time it means that Akka internal logging should not use `ActorContext.log` to avoid mixing user logging and Akka internal logging.

**Comment by patriknw** [comment]
I see what you mean but I'm not sure the alternative would be better. It's often good to be able to correlate the logging from Akka with the same Lagger as from user code (they are from the same actor). E.g. logging from supervision.

By the way, "Start timer [] with generation []" has been removed, since it was too verbose.

**Comment by hseeberger** [comment]
> By the way, "Start timer [] with generation []" has been removed, since it was too verbose.

Good!

**Comment by chbatey** [comment]
I think we can close this as the verbose logging has been removed
