### ISSUE TITLE
akka remoting should support multiple remote host/port 

### ISSUE THREAD

**Issue by HuangXiaomeng** [akka/akka#27262]
Our cloud product need support multiple network env, e.g. vpc network, classic network.
Our solution is to use different vip(e.g. vpc vip, classic vip) to support it.
But akka only has one hostname/port pair, so we have to build multiple cluster for different network env. It's very waste of resources and times.

Any one can support this feature, my akka version is 2.4.20. I want this feature in 2.4.x too.

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/60697159-896bfd80-9f1b-11e9-91c7-a8f8677857ce.png)

**Comment by johanandren** [comment]
The external part is what canonically identifies a node in a cluster, changing this so that a node could have several would be a very invasive change in both remoting and cluster which I don't think we are interested in doing.

Did you consider some other means of inter-system communication, is the various network systems really one distributed system?

**Comment by johanandren** [comment]
BTW Akka 2.4 was [end of lifed 11 January 2018](https://akka.io/blog/news/2018/01/11/akka-2.5.9-released-2.4.x-end-of-life), so even if we'd consider this, we do not introduce new features in EOL:ed release branches.

I'll close this for now.
