### ISSUE TITLE
Only allocate shards on new nodes when a rolling update is in progress 

### ISSUE THREAD

**Issue by helena** [akka/akka#27368]
Depends on: Add awareness for in-progress rolling update #27300
Peer of: Disable rebalance during in-progress rolling update https://github.com/akka/akka/issues/27367

**Comment by patriknw** [comment]
It should avoid rebalance or new allocations to the old nodes during the rolling update. Currently, if you shutdown one old node it will likely move those shards to some of the other old nodes (that will soon also shutdown) instead of preferring moving those to new nodes.

The goal is to reduce the number of times a shard moves during a rolling update. Each move will introduce additional latency while moving and for EventSourcedBehavior additional load/latency when recovering the state.

It would have to allocate to old nodes if there are no new nodes, but if there are new nodes available it's better to use those.

Another example is when the periodic rebalance kicks in at the same time as rolling update. Would be better to disable rebalance during the rolling update, so that the stopped shards will start up on the new node without competing with rebalanced shards.

Given the `appVersion` from #27300 the allocation strategy can see if there is a rolling update in progress. More than one version in the Member Set. The `appVersion` also defines if a node is new or old.

**Example:**

3 nodes with 10 shards each, 30 shards in total.

An optimal scenario that we could achieve if we we are in control and know that it was a rolling update in progress:

* node-3 is stopped (youngest), those 10 shards are started on node-1 (oldest, now having 20 shards)
* node-4 is started
* node-2 is stopped, those 10 shards are started on node-4
* node-5 is started
* node-3 is stopped, those 20 shards are started on node-4 and node-5 (each having 15 shards)
* node-6 is started
* rebalance 5 shards from node-4 and 5 shards from node-5 to node-6 (but this can be done slowly)

Compare with current non-optimal scenario:

* node-3 is stopped (youngest), those 10 shards are started on node-1 and node-2 (each having 15 shards)
* node-4 started, rebalance 5 shards from node-2 and node-3 to node-4 (all having 10 shards again)
* node-2 stopped, those 10 shards are started on node-3 and node-4 (each having 15 shards)
* node-5 started, rebalance 5 shards from node-3 and node-4 to node-5 (all having 10 shards again)
* node-3 stopped, those 10 shards are started on node-4 and node-5 (each having 15 shards)
* node-6 started, rebalance 5 shards from node-4 and node-5 to node-6 (all having 10 shards again)

It could be even better if we could start a new node before stopping an old node.

**Comment by chbatey** [comment]
> It could be even better if we could start a new node before stopping an old node.

This is the case in k8s with a default deployment
