### ISSUE TITLE
put generated doc in a repo for offline usage

### ISSUE THREAD

**Issue by xieyuheng** [akka/akka#27441]
just like slick does https://github.com/slick/doc

**Comment by raboof** [comment]
We can't really use gh-pages because we want to use 301 redirects and that is not supported there (https://help.github.com/en/articles/redirects-on-github-pages).

What would be your use case for having the generated documentation in a repo? Would publishing a zip as discussed in #22728 be sufficient as well?

**Comment by xieyuheng** [comment]
Thanks for your reply and information.
A zip will be fine, I only wish to read docs offline.
