### ISSUE TITLE
Behavior testing of actor piping message to self

### ISSUE THREAD

**Issue by AndreyIlin** [akka/akka#27514]
I have the following snippet to describe problem I've faced with actor behavior testing:
```scala
class AkkaTest extends WordSpec {

  sealed trait Message

  case object OuterMessage extends Message

  case object SelfMessage extends Message


  val behavior = Behaviors.receivePartial[Message] {
    case (context, OuterMessage) =>
      val future = Future.successful(())

      context.pipeToSelf(future) {
        case Success(_) => SelfMessage
        case Failure(_) => SelfMessage
      }

      Behaviors.same

    case (_, SelfMessage) =>
      Behaviors.same
  }

  val kit = BehaviorTestKit(behavior)
  
  "behavior test kit" should {
    "assert received self message" in {
      kit.run(OuterMessage)
      kit.selfInbox.expectMessage(SelfMessage)
    }
  }
}
```
This test fails with the following error:
`assertion failed: expected: SelfMessage but received AdaptMessage(Success(()),AkkaTest$$anonfun$1$$Lambda$171/1478797373@6c1a5b54)`

It looks like an `AdapterActor` is not involved in the behavior testing flow and the message doesn't get adapted. 
In my real case behavior testing is the only way to check complex actor behavior in isolation, but can't do that for now.

**Comment by patriknw** [comment]
Currently there are quite a few shortcomings of the BehaviorTestKit, and as [documented](https://doc.akka.io/docs/akka/2.6/typed/testing.html#synchronous-behavior-testing) it will always have limitations. For example, interactions with Futures as in your example is asynchronous in by its nature and will probably be difficult to support. When running into these limitations I'd recommend to either help out and improve the BehaviorTestKit or use asynchronous testing.

The self message can be tested with `Behaviors.monitor` like this:

```scala
import scala.concurrent.Future
import scala.util.Failure
import scala.util.Success

import akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit
import akka.actor.typed.scaladsl.Behaviors
import org.scalatest.WordSpecLike

class AkkaTest extends ScalaTestWithActorTestKit with WordSpecLike {

  sealed trait Message

  case object OuterMessage extends Message

  case object SelfMessage extends Message

  val behavior = Behaviors.receivePartial[Message] {
    case (context, OuterMessage) =>
      val future = Future.successful(())

      context.pipeToSelf(future) {
        case Success(_) => SelfMessage
        case Failure(_) => SelfMessage
      }

      Behaviors.same

    case (_, SelfMessage) =>
      Behaviors.same
  }

  "test" should {
    "assert received self message" in {
      val probe = createTestProbe[Message]()
      val ref = spawn(Behaviors.monitor(probe.ref, behavior))
      ref ! OuterMessage
      probe.expectMessage(OuterMessage)
      probe.expectMessage(SelfMessage)
    }
  }
}
```

I'm closing this issue since similar is already reported in https://github.com/akka/akka/issues/25709 and/or issues linked there.
