### ISSUE TITLE
Behavior testing of actor spawning children from Behaviors.setup

### ISSUE THREAD

**Issue by AndreyIlin** [akka/akka#27515]
I have the following snippet to describe problem I've faced with actor behavior testing:
```scala
import akka.actor.testkit.typed.Effect.Spawned
import akka.actor.testkit.typed.scaladsl.BehaviorTestKit
import akka.actor.typed.scaladsl.Behaviors
import org.scalatest.WordSpec

class AkkaTest extends WordSpec {

  sealed trait Message

  case object OuterMessage extends Message

  val childName = "sweet child of mine"
  def childBehavior = Behaviors.setup[Message] { context =>
    // whatever business logic that requires context
    // e.g. starting expiration timer according to business logic using context.scheduleOnce
    Behaviors.receiveMessagePartial { case OuterMessage => Behaviors.same }
  }

  val parentBehavior = Behaviors.receivePartial[Message] {
    case (context, OuterMessage) =>
      context.spawn(childBehavior, childName) ! OuterMessage
      Behaviors.same
  }

  val kit = BehaviorTestKit(parentBehavior)

  "behavior test kit" should {
    "assert effect" in {
      kit.run(OuterMessage)
      kit.expectEffect(Spawned(childBehavior, childName))
    }
  }
}
```
This test fails with the following error:
```
assertion failed: expected: Spawned(Deferred(AkkaTest.scala:17), sweet child of mine, EmptyProps) but found Spawned(Deferred(AkkaTest.scala:17), sweet child of mine, EmptyProps)
```
However when I'm making `childBehavior` a `val` test passes.
But this is not applicable for my real-life case when I have a state machine where each different behavior has parameters that should be passed and I want to test such a behavior in isolation.

**Comment by patriknw** [comment]
@AndreyIlin That is because `kit.expectEffect` is using `equals` of `Spawned` and therefore relies on `equals` of the Behavior. `Behaviors.setup` in this case. Not much else it could do.

Instead you can use `expectEffectType[Spawned]` and then add more assertions on the returned `Spawed`, such as checking the `childName`.

We use github issues just for bugs and feature requests. Next time, please ask it on https://discuss.akka.io if you think it's more like a question than a bug report?
