### ISSUE TITLE
Akka Typed: combining Behaviors

### ISSUE THREAD

**Issue by manuelbernhardt** [akka/akka#27629]
I haven't found any way to do the following, so if there is already one, my apologies:

```
      Behaviors.receiveSignal {
        case (_, Terminated(ref)) =>
          // cry, mourne, and then do something else
          // ...
      } + Behaviors.receiveMessage {
        case p: PostCard =>
          // read it
          // ...
      }
```

Note sure about the `+`, it's just what came naturally to mind.

The point in the example above is just to make things clearer - to separate dealing with "infrastructure" signals and "application logic" messages. But more generally, I'd think this could be useful. What do you think?

**Comment by manuelbernhardt** [comment]
Hmm, so Konrad pointed me to the [scaladoc of the current release](https://doc.akka.io/api/akka/current/akka/actor/typed/Behavior.html#orElse(that:akka.actor.typed.Behavior[T]):akka.actor.typed.Behavior[T) which has an `orElse`, whilst the project I am building is on [2.6.0-M4](https://doc.akka.io/api/akka/2.6.0-M4/akka/actor/typed/Behavior.html#orElse(that:akka.actor.typed.Behavior[T]):akka.actor.typed.Behavior[T) which doesn't have an `orElse` (nor does 2.6.0-M6 apparently).

Is `orElse` going to be removed?

**Comment by johanandren** [comment]
Yes, we had to remove `orElse` because it was not safe. You can read more details in this issue: https://github.com/akka/akka/issues/26867

**Comment by patriknw** [comment]
It would be interesting to find a solution for this, but as Johan said we removed the initial `orElse` because it wasn't safe. We don't have the bandwidth to investigate a solution right now but ideas are welcome and we can hopefully come back to this after the 2.6.0 release.

When I removed `orElse` I investigated some alternatives, but none of them are perfect. See https://github.com/akka/akka/blob/master/akka-actor-typed-tests/src/test/scala/akka/actor/typed/OrElseSpec.scala

**Comment by vaslabs** [comment]
Would you be interested in having a dsl import like this
https://github.com/vaslabs/flerken/blob/master/scheduler/src/main/scala/flerken/AkkaExtras.scala#L8

perhaps with a few enhancements the syntax can be friendlier than
https://github.com/vaslabs/flerken/blob/master/scheduler/src/main/scala/flerken/PendingWorkStorage.scala#L116

it could be kept as
```
(behaviour1 :: otherBehaviour).toBehaviour
```
or my preference would be
behaviour1 | behaviour2

and potentially have it only available for Scala, as if I understand correctly the unsafeness was due to Java type system mechanics (?).

**Comment by patriknw** [comment]
Doesn't it supper from the same problem as the `orElse` we had to remove in https://github.com/akka/akka/pull/27252 ?

**Comment by vaslabs** [comment]
potentially but the idea is to enable it explicitly at least, this doesn't represent the community but I've never even used narrow the passed 3 years I'm using Akka. The point I'm trying to make is at least we give the option for orElse with the difference that instead of having it available in the standard API we have some import like
```
import akka.typed.scaladsl.behavior.unsafe.syntax._
```

**Comment by vaslabs** [comment]
Following your example in the OrElseSpec I tried to break it but due to wrapping with `List[A] and PartialFunction[A, Behavior[A]]` the typesafety looks enough.

The thing that breaks is when doing (based on the AkkaExtras example)

```
  val b1: PartialHandling[String] =
    _ => Behaviors.setup[Any] {
      ctx => ctx.self ! 1
      Behaviors.empty[Any]
    }.narrow[String]

  val b2: PartialHandling[String] = { msg =>
    println(s"# received $msg")
    Behaviors.same
  }
```

Which looks like it's mostly narrow's fault rather than orElse

Btw I'm debating in favour of or else because I have a codebase that uses it in some critical areas :)

**Comment by vaslabs** [comment]
I found some free time to give this a go, please let me know if you have plans on working on it, it will probably take me until Monday to have something tangible

**Comment by johanandren** [comment]
Nobody is working on this so feel free to investigate.

**Comment by vaslabs** [comment]
I haven't create this PR on the akka just want to get some early feedback.

This is a very crude API design , but I aimed at a PoC that demonstrates type relationships rather than going for something nice.

After reading the comments on here and on the original issue again I picked up on one comment, that the ctx.self doesn't know about narrow.

So on this first PoC I tried to expose the ActorContext to the combine method.

As I said the API I came up with is crude, compose if for composing functions
and combine to create a behavior out of those functions.

Anyway, here's some diff that demonstrates my first idea

https://github.com/vaslabs/akka/pull/1

Any feedback is appreciated, if you don't like the fundamentals of these solution I can work on some alternatives I'm thinking about.

**Comment by manuelbernhardt** [comment]
@vaslabs do you still happen to have this proof of concept somewhere? The repository link above doesn't seem to exist anymore. Thanks!

**Comment by vaslabs** [comment]
ha, it appears I've deleted the whole repo :man_facepalming: 

I have an email with he comments so I can recall the approach although I think it had an issue

This is the snippet I see in my email
```
+  def compose[T](behaviorA: T => Behavior[T], behaviorB: T => Behavior[T]): T => Behavior[T] = {
+      msg =>
+        val nextBehavior = behaviorA(msg)
+        if (Behavior.isUnhandled(nextBehavior))
+          behaviorB.apply(msg)
+        else
+          nextBehavior
```
And comment:
>You have now lost the composed behavior for the next message coming in and are only using the one returned from either behaviorA or behaviorB.
I think this is a really tricky aspect of it.

I think my approach was to make it look like function composition instead of orElse to be easier to distinguish and maybe stick it in an unsafe.syntax package 

If you think it's promising I can re-write it, I think it took me ~1 hour so not a lot, my tests were based on @patriknw 's work

**Comment by vaslabs** [comment]
Ah, I also remember why I gave up, it was because I started a different paradigm with behaviour where the actor is a "compiler" and the composition happens with 'mainstream' code (similar to free monad)

**Comment by Swoorup** [comment]
Isn't this now solved as in https://doc.akka.io/docs/akka/current/typed/style-guide.html
@vaslabs ?

**Comment by jlprat** [comment]
I would say, it was superseded by https://github.com/akka/akka/issues/29832
I didn't find this issue when creating that one. And as you say @Swoorup, the documentation is now showcasing how to combine different Behaviors.

**Comment by vaslabs** [comment]
tbh I was asking about this during migration from akka 2.5 to 2.6, that migration is long completed with a different approach, that's why I didn't chase this more
