### ISSUE TITLE
Typed persistence: automatic snapshotting without event/snapshot deletion

### ISSUE THREAD

**Issue by yufei-cai** [akka/akka#27636]
Is there any chance to extend retention criteria of #26533 such that automatic snapshotting is possible without deleting events or snapshots? I'd rather not hack `keepNSnapshots` so that the result of [deleteUpperSequenceNr](https://github.com/akka/akka/blob/master/akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/RetentionCriteriaImpl.scala#L29) is always negative.

Better would be the complete separation of retention and auto-snapshot conditions; snapshotting at regular time intervals is useful, for example, in addition to snapshotting at regular sequence numbers.

Motivation: Triggering deletions at a frequency proportional to the rate of events stressed our persistence layer an order of magnitude more than necessary. Eventually we had to [decouple cleanup from event persistence](https://github.com/eclipse/ditto/pull/446). Now that Typed Akka is adding more and more features we need, there may come a day when we have zero low-level persistence interaction in user code. Which is good.

**Comment by johanandren** [comment]
Snapshotting without deleting events is already possible (and perhaps what we expect most people will want to do anyway, keep the entire history) using `RetentionCriteria.snapshotEvery(numberOfEvents, keepNSnapshots)`. 

Since the snapshots are only used as an optimization, keeping all snapshots forever seems like a waste, wouldn't doing that pose a bigger problem than the overhead of deleting old/unused snapshots? Anyways, that is also currently possible but then you will have to use `EventSourcedBehavior.snapshotWhen()` instead and provide some logic for when snapshots are taken.

**Comment by yufei-cai** [comment]
`EventSourcedBehavior.snapshotWhen()` covers our use case. Thanks!

We are using MongoDB for persistence. Snapshot deletion translates to a delete-by-filter query, which is slow and locking. They are scheduled as separate cleanup tasks with low priority.
