### ISSUE TITLE
Require ActorContext in constructor of AbstractBehavior

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27689]
To enforce that it is used with `Behaviors.setup`. The main problem of not using `Behaviors.setup` would be when combined with restart supervision. Then a new instance wouldn't be created when restarted and it would hold same state as before the failure.

**Comment by WadeWaldron** [comment]
I think requiring the construction of an actor be done only inside a factory method of some kind is an important safety constraint. It's something that we had in Untyped with the Props factory. To my knowledge you couldn't construct an actor outside of Props or you would get a compile error (still don't know how that was achieved).

The benefit is that it ensures you don't do something like share the actor across multiple incarnations. And as you mention with restart it ensures that a new instance is being created every time, rather than re-using an old one.

If the easiest way to implement this requirement is by requiring an ActorContext which would force you to create the actor inside the Behaviors.setup, then I would be fine with that. If there are better alternatives that don't force the requirement of an ActorContext, that would be fine as well.

**Comment by patriknw** [comment]
in classic actors it is a runtime check via a ThreadLocal, not compiler error

**Comment by johanandren** [comment]
I think if we do it, it should be compile time, not runtime magics. 

But, my opinion is that the syntactic overhead of requiring an `ActorContext` being passed to super or such for every `AbstractBehavior` isn't justified by the risk that the same instance is shared. Writing an OO-style behavior is already quite verbose.

**Comment by patriknw** [comment]
We discussed this and decided to give it a try to add the mandatory context constructor parameter to AbstractBehavior, and complement it with some additional runtime checks.
