### ISSUE TITLE
Mixing Actor with other trait causes UninitializedFieldError

### ISSUE THREAD

**Issue by texasbruce** [akka/akka#27726]
Akka version: 2.5.17 (issue possibly applies to all versions)
Scala version: 2.12.8 (issue possibly applies to all versions)

I have a trait self defined as Actor:

```
trait TestActorT {
  this: Actor =>

  val ec = context.system.dispatcher
  def receive: Receive = { case _ => () }
}

class TestActor extends TestActorT with Actor
```

This will result an UninitializedFieldError:

> Uninitialized field: Scala\File\Path: 14
> akka.actor.ActorInitializationException: akka://actor/path:
>  exception during creation
>         ....
> 
> Caused by: scala.UninitializedFieldError: Uninitialized field: Scala\File\Path: 14
>         at com.package.TestActor.context(TestActor.scala:14)
>         ....

Obviously this is caused by Actor trait mixed after the trait that calls the context.

A possible simple solution is to define context as a lazy val:

Current code:

https://github.com/akka/akka/blob/8a25f186fa6628d3270ab3e5f62c2c30caf66976/akka-actor/src/main/scala/akka/actor/Actor.scala#L482

Change to:

    implicit lazy val context: ActorContext

**Comment by johanandren** [comment]
That's expected, just like with any class you'd mix a trait into, if you access fields that are populated in its constructor they will not be initialized yet. The solution would be to either make your `ec` `def` or `lazy` or make `TestActorT` a subclass of `Actor` so that its constructor will run after the `ActorConstructor`.

`lazy` causes synchronisation, so making the context lazy would incur a synchronization overhead in every access to `context` in every actor which would not be good.

**Comment by texasbruce** [comment]
@johanandren Right synchronization is a valid concern for this. I'm closing this issue.
