### ISSUE TITLE
Jackson class id typeinfo can be safe

### ISSUE THREAD

**Issue by jroper** [akka/akka#27969]
There's a warning in the Jackson docs that says:

> Don’t use @JsonTypeInfo(use = Id.CLASS) or ObjectMapper.enableDefaultTyping since that is a security risk when using polymorphic types.

While this warning is definitely good to have, it's a little broad. I believe `@JsonTypeInfo(use = Id.CLASS)` is no more unsafe than Akka serialization in general, as long as there are sufficient bounds on what's being deserialized. For example:

```
case class Foo(
  @JsonTypeInfo(use = Id.CLASS)
  value: Any
)
```

is unsafe, but:

```
sealed trait Bar
case class BarOne() extends Bar
case class BarTwo() extends Bar
case class Foo(
  @JsonTypeInfo(use = Id.CLASS)
  bar: Bar
)
```

Is completely safe, because Jackson will treat any class specified that doesn't extend `Bar` as an error, and because `Bar` is sealed, we know exactly what it will attempt to instantiate.

More generally, if I define a marker trait `MyJacksonSerializable`, which all my classes that are serializable by Jackson extend, and I configure an Akka serialization binding from that trait to the jackson serializer, then if I have this:

```
@JsonTypeInfo(use = Id.CLASS)
value: MyJacksonSerializable
```

The security implications are exactly the same for using the Akka Jackson serializer.

**Comment by patriknw** [comment]
You are probably right that if used correctly it's fine, but I think it's better that our recommendation is to stay away from that.

Users like you that understand the implications will figure this out anyway and others will mistakenly abuse it for the `Any` case if we say that it can be used for certain cases.

It's not only about security, it's also bad to have full class names in the json because it will break for refactoring (renaming classes). For the top level manifest in JacksonSerializer we have the migration support for this. Although possible, it might not be as obvious how to do such migrations for class names inside the json.

**Comment by patriknw** [comment]
Closing this, unless you have objections @jroper 

At some point we should maybe look into the PolymorphicTypeValidator in Jackson 2.10 https://medium.com/@cowtowncoder/jackson-2-10-safe-default-typing-2d018f0ce2ba
