### ISSUE TITLE
getAsyncCallback is not thread safe

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27999]
Highlight that in the API docs. The AsyncCallback itself is thread safe.

If I'm not reading it wrong we even use it in wrong way in TimerGraphStageLogic.scheduleOnce

**Comment by patriknw** [comment]
ok, it is mentioned at the end of the Scaladoc:
   * To be thread safe this method must only be called from either the constructor of the graph operator during
   * materialization or one of the methods invoked by the graph operator machinery, such as `onPush` and `onPull`.

**Comment by jrudolph** [comment]
One weird thing is that calling `getAsyncCallback` fails in the constructor. I though we had fixed that?

**Comment by johanandren** [comment]
@jrudolph that sounds strange, we do that all over the place in artery for example, do you have a concrete case where it failed?

**Comment by jrudolph** [comment]
> @jrudolph that sounds strange, we do that all over the place in artery for example, do you have a concrete case where it failed?

Failing in that regard would mean that an async callback would never be initialized and therefore never receive any callbacks. 

I think it would only ever happen if two async callbacks would be initialized at the same time from different threads before the interpreter is running (concurrently prepending to `callbacksWaitingForInterpreter`). This is quite unlikely indeed.

The easiest way to lift the restriction, would probably be guarding the access with a lock, synchronized, or CAS. That should be good enough because contention should be low because there shouldn't be too many async callbacks created per stage.

**Comment by johanandren** [comment]
Ah, I read it more as not possible/crashing than having a concurrency issue. I don't think we need to make that fool proof, just saying not to call it from different threads but instead require usage from the stream machinery makes sense to me (same expectation as for most things related to graph stages as well as actors).

**Comment by jrudolph** [comment]
And then fix TimerGraphStage to actually heed that advice?

Johan Andrén <notifications@github.com> schrieb am Mi., 20. Nov. 2019,
17:40:

**Comment by johanandren** [comment]
Yep, already done in the PR #28201
