### ISSUE TITLE
Simplify LazyFlow implementation

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28016]
The LazyFlow implementation contains logic for extracting the first element and basing the lazy flow on that from the initial factory that was contributed. We should rewrite the operator implementation to not have that logic (just lazy construction) and achieve the old signature by composition with `prefixAndTail`.

**Comment by johanandren** [comment]
I think this can be done when #28380 has been merged

**Comment by eyalfa** [comment]
CC: @jrudolph 
as discussed in 'hijacked' pr #28497 there are (at least) two applicable approaches:
1. implement `Flow.future` as a separate graph stage and then compose it with flatMapPrefix in order to implement `lazyFlow`
2. enhance flatMapPrefix to support an async version where the provided function returns a `Future[Flow]`

@jrudolph prefers the second option due to some performance related concerns with the first option, I personally prefer the first option as it seems simpler and resulting with two robust (relatively) simple graph stages.

let's discuss.

**Comment by johanandren** [comment]
I like composition over forcing it all into one operator, feels more clean and less risk of breaking something.

**Comment by eyalfa** [comment]
I'll start hacking into 'futureFlow' and see if it matures into a PR

**Comment by eyalfa** [comment]
loking at the scaladoc of `Flow.futureFlow`, it states: 

> * The materialized future value is completed with the materialized value of the future flow or failed with a
> * [[NeverMaterializedException]] if upstream fails or downstream cancels before the future has completed.

is the 'never materialized' behaviour a hard requirement? when working on `flatMapPrefix` I was requested by @jrudolph to buffer downstream cancellation and later propagate it to the inner flow (once materialized), the motivation behind this was that the inner flow may have its own logic for dealing with failures (i.e. recover) and back-pressure/downstream events (i.e. sinkAndSource). on the face of it, the same rationale applies here.

seems like [this](https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala#L50-L64) is the only test code referring to `futureFlow` and it tests only the happy case.

I think that most use-cases won't notice the difference as there's an inherent race condition between future's completion and upstream+downstream events, so there's no guarantee which code path intercepts these events.
However there are pathological use-cases where this is not the case, i.e. when the future flow is provided via a never completed promise. I personally believe this is probably present only in test code.

please advice.

**Comment by johanandren** [comment]
Tricky, perhaps as long as it is possible to observe non-materialization that is fine?

Note that it is also used to implement the deprecated `lazyInitAsync` which materializes an `None` if the stream was never materialized, I guess there's indirect test coverage among the tests for that as well.

**Comment by eyalfa** [comment]
the intention of this initiative is to implement `lazyFlow` in terms of `flatMapPrefix` and `futureFlow`, I think `lazyInitAsync` should be implemented on top of `lazyFlow` (which current impl actually does).

what do u mean by observing non-materialization? the mat-val will be a failed future in these cases, is this sufficient?
I think the only corner here is a never completing future, I think this can be addressed with an optional timeout and policy, like prefixAndTail does.

**Comment by johanandren** [comment]
So if changing this to be based on `flatMapPrefix` the original semantics with not materializing the inner flow on outer flow failures would change into materializing the inner flow and then failing it? If I got that right, perhaps that is fine.

I don't see a scenario where the inner flow wasn't materialized and we don't know about that from the stage, if we always materialize on "outer" stream failures the only scenario is abrupt stream termination (killing the materializer)?

**Comment by eyalfa** [comment]
> So if changing this to be based on `flatMapPrefix` the original semantics with not materializing the inner flow on outer flow failures would change into materializing the inner flow and then failing it? If I got that right, perhaps that is fine.
yes, exactly
> 
> I don't see a scenario where the inner flow wasn't materialized and we don't know about that from the stage, if we always materialize on "outer" stream failures the only scenario is abrupt stream termination (killing the materializer)?
not sure we're talking about the same thing, I mentioned a corner case where the future flow never completes, i.e. if the user code obtains the future from a promise which is never to be completed. can u please explain your concerns?

**Comment by eyalfa** [comment]
> So if changing this to be based on `flatMapPrefix` the original semantics with not materializing the inner flow on outer flow failures would change into materializing the inner flow and then failing it? If I got that right, perhaps that is fine.

yes, exactly
> 
> I don't see a scenario where the inner flow wasn't materialized and we don't know about that from the stage, if we always materialize on "outer" stream failures the only scenario is abrupt stream termination (killing the materializer)?

not sure we're talking about the same thing, I mentioned a corner case where the future flow never completes, i.e. if the user code obtains the future from a promise which is never to be completed. can u please explain your concerns?

**Comment by johanandren** [comment]
Ah, I see, I think we can see that case as a user concern.

**Comment by eyalfa** [comment]
turns out at least one operator could be 'converted' without waiting for `futureFlow`:
```
def lazyFlow[I, O, M](create: () => Flow[I, O, M]): Flow[I, O, Future[M]] =
    /*lazyFutureFlow(() => Future.successful(create()))*/ Flow[I].flatMapPrefixMat(0)(_ => create())(Keep.right)
```

others are a bit trickier:
```
def lazyInit[I, O, M](flowFactory: I => Future[Flow[I, O, M]], fallback: () => M): Flow[I, O, M] =
    /*Flow.fromGraph(new LazyFlow[I, O, M](flowFactory)).mapMaterializedValue(_ => fallback())*/ Flow[I]
    .flatMapPrefix(1){
      case Seq(a) => futureFlow(flowFactory(a)).mapMaterializedValue(_ => NotUsed)
      case Seq() => Flow[_].asInstanceOf[Flow[I, O, NotUsed]]
    }
    .mapMaterializedValue(_ => fallback())
```
* notice it has the same semantics as specified in the scaladoc

`lazyInitAsync` requires some careful thinking, I'll update soon

**Comment by eyalfa** [comment]
@johanandren ,
I'm seeing some test failures (`LazyFlowSpec`) related to the exception being thrown.
it seems that most of it boils down to FlatMapPrefix wrapping  exceptions with a `NeverMaterializedException` which causes tests to break.
Since `flatMapPrefix` is 'the new 'kid on the block'  and wasn't officially released yet, can we change some of these behaviours? specifically avoid wrapping exceptions thrown during nested flow materialization.
is this kind of a change acceptable? especially at this point?

**Comment by johanandren** [comment]
I think that's fine, if not wrapping makes more sense.

**Comment by eyalfa** [comment]
👍

**Comment by eyalfa** [comment]
dived a bit further into this, I've noticed that `flatMapPrefix` treats 'early' upstream and downstream failures differently:
1. downstream failures (cancellations actually) are buffered and later handled to the materialized flow.
2. upstream failures immediately causes the stage to be terminated.
* this applies to failures/cancellation **before** materializing the nested flow, anyway that seems unbalanced at this point as the materialized flow may incorporate some error handling logic, ie. by using a `recover` stage. I think this is a good time to change this behaviour.

regarding the wrapped exceptions, `flatMapPrefix`  wraps exception with a `NeverMaterializedException` in two cases: early upstream failure and failing to materialize the nested flow. I think the first case should actually trigger nested flow materialization and then hand over the exception to the materialized flow. if we decide against that we can at least subclass  `NeverMaterializedException` in order to identify this scenario.
I think we should keep wrapping any exceptions occurring during materialization with a `NeverMaterializedException` or even a more specific subclass in order to make it distinguishable for users and constructs built on top of flatMapPrefix.

**Comment by johanandren** [comment]
So what do you suggest, materialize inner flow also on upstream failure and pass the failure on?

**Comment by eyalfa** [comment]
I tend towards this approach, this is actually what I'm currently doing in `FutureFlow`. I think the reason I've implemented `flatMapPrefix` this way is because it kind of made sense that an upstream exception means 'I can't  grab this prefix for you'... perhaps this should be somehow configurable? i.e. advanced users (or the higher constructs built on top of `flatMapPrefix` will be able to control this behaviour via a param/attribute. WDUT?
on the other hand, most flows simply fail on upstream failure, this combined with the fact `flatMapPrefix` may provide the materialization function a shorter prefix then requested indicates that materializing and forwarding the upstream failure doesn't really break anything, it just enables more advanced use-cases and make the `flatMapPrefix` stage more 'transparent'.

all in all, I think `flatMapPrefix` should materialize the flow and forward the exception.

**Comment by johanandren** [comment]
I'm on the fence. @jrudolph any opinion?

**Comment by eyalfa** [comment]
@johanandren , and about wrapping the exceptions?

**Comment by johanandren** [comment]
I don't think it is worth having more specific exception subclasses, I don't expect that users will need to discern the two cases in logic and if they need to they can always look at the `cause` exception.

**Comment by eyalfa** [comment]
I've made some progress, still seeing some failures related to the exceptions exposed via matVal.

I suspect [this](https://github.com/akka/akka/blob/master/akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala#L129) specific (test) assertions contradicts the [docs](https://github.com/akka/akka/blob/66f4d3009866cd7aab0838303564382b45c0ae72/akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala#L647-L666) of `lazyFutureFlow`.
specifically, it seems as if the following statement from doc is not respected by the assertion:

> If the `create` function throws or returns a future that fails the stream is failed, in this case the materialized
> future value is failed with a [[NeverMaterializedException]].

notice that the test fails the factory method and expects the direct exception to be propagated via the matVal.

@johanandren , @jrudolph  ?

**Comment by eyalfa** [comment]
I think these two also makes the same violation:
[fail the flow when the future is initially failed](https://github.com/akka/akka/blob/66f4d3009866cd7aab0838303564382b45c0ae72/akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala#L142)
[fail the flow when the future is failed after the fact](https://github.com/akka/akka/blob/66f4d3009866cd7aab0838303564382b45c0ae72/akka-stream-tests/src/test/scala/akka/stream/scaladsl/LazyFlowSpec.scala#L158)

**Comment by johanandren** [comment]
I agree it looks like there is a mismatch there. Good if it was aligned with what the docs said.

**Comment by eyalfa** [comment]
these are currently the only failing three tests I see in this suite, so I guess it's legit to modify these specific assertions?
ps. can you think of any other relevant suite to test this? (I will of course add tests for `futureFlow`)

**Comment by jrudolph** [comment]
Done in #28729.
