### ISSUE TITLE
Timeouts when creating legacy system materializer

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#28037]
Lagom build is failing in Travis (but passing locally) with a timeout when creating a legacy system mateializer. 

This is happening inside akka-persistence-jdbc plugin that is still initializing its own Materializer. I will fix it there.

The timeout is configured to 20 seconds and it's failing.

<details>
<summary>travis stack trace</summary>
<pre>
[info] Caused by: java.util.concurrent.TimeoutException: Futures timed out after [20 seconds]

[info] 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)

[info] 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)

[info] 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)

[info] 	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:173)

[info] 	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)

[info] 	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:171)

[info] 	at scala.concurrent.Await$.result(package.scala:146)

[info] 	at akka.stream.SystemMaterializer.createAdditionalLegacySystemMaterializer(SystemMaterializer.scala:80)

[info] 	at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:76)

[info] 	at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:51)

[info] 	at akka.persistence.jdbc.query.scaladsl.JdbcReadJournal.<init>(JdbcReadJournal.scala:69)

[info] 	at akka.persistence.jdbc.query.JdbcReadJournalProvider.<init>(JdbcReadJournalProvider.scala:24)

[info] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[info] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

[info] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[info] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

[info] 	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)

[info] 	at scala.util.Try$.apply(Try.scala:213)

[info] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)

[info] 	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$instantiate$1(PersistencePlugin.scala:79)

[info] 	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$createPlugin(PersistencePlugin.scala:81)

[info] 	... 36 more

[info] 
</pre>
</details>

**Comment by dwijnand** [comment]
> Lagom build is failing in Travis

The failure is the PR validation upgrading Lagom to Akka 2.6.0-M8: https://travis-ci.com/lagom/lagom/jobs/246724420.

**Comment by johanandren** [comment]
Dale also repeated with timeout upped to 3 minutes.

**Comment by dwijnand** [comment]
3m failure https://travis-ci.com/dwijnand/lagom/builds/132532330#L2059

**Comment by johanandren** [comment]
All it does during that blocking ask is spawning a child actor and instantiating some objects, there is no way that would take 20s, and even less likely 3 minutes, so that must mean the request was never processed.

We have a set of tests in `ActorMaterializerSpec` that creates materializers and those work fine, and it is not possible to repeat this locally as far as I understand.

One theory I had was that it runs on a thread pool with only one thread and then blocks that, but I see now that it is `java.util.concurrent.ForkJoinPool` so that should spawn another thread triggered by the blocking context.

The only reason I can think of that there'd be no response would be if the `MaterializerGuardian` itself stopped, but that'd bring down all streams and the creation in itself is triggered by a stream `.map` interacting with the journal for the first time since system start.

A real head scratcher this one.

**Comment by johanandren** [comment]
Materializer mystery solved: 

N threads in default dispatcher, N user tasks on the default dispatcher wanting to use the persistence-query plugin, blocking on lazy-creation of the extension, the plugin impl tries to message `MaterializerGuardian` which also runs on default dispatcher, but that is starved, so never gets to process the message which the blocked threads are waiting for an answer to and all awaits times out.
