### ISSUE TITLE
Receptionist: support for actor de-registration 

### ISSUE THREAD

**Issue by tipame** [akka/akka#28123]
When using recetionist:

De-registration is implied by the end of the referenced Actor’s lifecycle

But in some cases it  needed to be explicitly unregistered before termination (for example if you want gracefuly shutdown actor without loss of messages allready sended to mailbox).

Scenario:
1) There are multiple nodes/actors handling message type;
2) There is router sending messages and listening recetionist;
3) Before node ternination: actor unregioistered (no more new messages sended to actor)
4) Actor handle all messages allready sended by router
5) Shutdown node/actor

Profit: no message loss on actor shutdown

**Comment by johanandren** [comment]
It could help a bit but it won't be water tight. The reason is that the receptionist registry of subscribers being eventually consistent (when used in a cluster). When the actor unsubscribes, there is no guarantee that the registered actor won't get more messages from other nodes until all nodes has seen the de-registration. If you want higher reliability you will anyway have to put some re-sending on top of the receptionist/group router.

**Comment by tipame** [comment]
For me main scenario is manual node upgrade:
1) new node start (two nodes handle messages)
2) manual unregister old node (actors continiue handle messages until all nodes has seen the de-registration)
3) manual stop old node

A'm allrady made a pull request #28124

**Comment by johanandren** [comment]
How do you implement "actors continiue handle messages until all nodes has seen the de-registration" ?

I think this addition can make sense regardless.

**Comment by tipame** [comment]
I not thinking about automation this process. In my case i just send unregistraction command from console (manualy) and wait for a while. May be some one implement programmatic logic (based on his system behavior).  I just wanna have possobility to do that.

**Comment by johanandren** [comment]
Looks like I missed closing this when merging.
