### ISSUE TITLE
Implement JournalPerfSpec.Cmd serialiser 

### ISSUE THREAD

**Issue by t3hnar** [akka/akka#28291]
Looks like
```scala
object JournalPerfSpec {
...
case class Cmd(mode: String, payload: Int)
...
}
```
relies on java serialiser, which is disabled in akka 2.6.0. 
Hence I cannot `simply` use `JournalPerfSpec` for testing custom plugins with akka 2.6.0 anymore

Could you *please* define dedicated serialiser for `Cmd` class? Or maybe there is better way to fix improve test?

```
13:43:58.912 WARN  a.s.DisabledJavaSerializer Outgoing message attempted to use Java Serialization even though `akka.actor.allow-java-serialization = off` was set! Message type was: [class akka.persistence.journal.JournalPerfSpec$Cmd]
13:43:58.912 ERROR a.p.j.JournalPerfSpec$BenchActor Failed to persist event type [akka.persistence.journal.JournalPerfSpec$Cmd] with sequence number [6] for persistenceId [p-16].
akka.serialization.DisabledJavaSerializer$JavaSerializationException: Attempted to serialize message using Java serialization while `akka.actor.allow-java-serialization` was disabled. Check WARNING logs for more details.

```

**Comment by johanandren** [comment]
Since how serialization is done is up to the persistence plugin (it could have storage specific serialization rather than use Akka serialization infra) it worked more by accident than intent while the Java serialization was automagically picked up.

Easiest way around it if a plugin uses the Akka serialization infra would be to use the new akka-serialization-jackson module https://doc.akka.io/docs/akka/current/serialization-jackson.html#serialization-with-jackson 

Won't be more work than adding a dependency and some test-config tying the class(es) to either the `jackson-json` or `jackson-cbor` serializers.

**Comment by t3hnar** [comment]
Thanks, @johanandren 
I've implemented a custom one 
https://github.com/evolution-gaming/kafka-journal/blob/master/tests/src/test/scala/akka/persistence/journal/PersistenceTckSerializer.scala#L10

**Comment by johanandren** [comment]
Looks good!

Let's keep this issue for documenting some recommendation on serializer for the tck somewhere.

**Comment by patriknw** [comment]
I think we should add an serializer for that, since it's most common to use Akka serialization for those and if a plugin is using another mechanism it will still work.
