### ISSUE TITLE
Could not addJvmShutdownHook, due to: Shutdown in progress

### ISSUE THREAD

**Issue by t3hnar** [akka/akka#28310]
After migrating to akka 2.6.0, I started to see following log entry during shutdown:

```
a.a.CoordinatedShutdown Could not addJvmShutdownHook, due to: Shutdown in progress
```

I'm not using `CoordinatedShutdown` directly, just call `actorSystem.terminate`. Also the only one thing I'm using from akka is `akka-http`

**Comment by patriknw** [comment]
That "Shutdown in progress" message comes from the JDK when trying to `Runtime.getRuntime.addShutdownHook` while the JVM is already terminating.

Do you call `actorSystem.terminate` from a jvm shutdown hook?

That shouldn't be needed, since CoordinatedShutdown is by default running by jvm shutdown hook, and CoordinatedShutdown ends by terminating the ActorSystem.

The difference between 2.5 and 2.6 is that ActorSystem.terminate now runs CoordinatedShutdown.

The warning is harmless, but would anyway be good to track down what the call chain looks like.

**Comment by t3hnar** [comment]
@patriknw seems like your guess is correct, I'm indeed shutting down all spawned resources from within shutdown hook, including ActorSystem. I close resources in correct order, so I'd rather would like to avoid akka shutting down itself automatically. Is that possible ?

**Comment by patriknw** [comment]
Then you can disable Akka's shutdown hook with
```
akka.jvm-shutdown-hooks = off
```
https://github.com/akka/akka/blob/master/akka-actor/src/main/resources/reference.conf#L95

**Comment by t3hnar** [comment]
Thanks

**Comment by patriknw** [comment]
Then I think we have confirmed that it is working as expected.
