### ISSUE TITLE
KillSwitch not work

### ISSUE THREAD

**Issue by lupingqiu** [akka/akka#28426]
```
def test(): RunnableGraph[(Future[Done], UniqueKillSwitch)]={
    val finalSink = Sink.ignore
    val switch = KillSwitches.single[Int]
    val finalFlow = Flow[Int].map{s=>
      if(s%1000==0) {
        println(s+"")
      }
      Thread.sleep(1000)
      s
    }
    RunnableGraph.fromGraph(GraphDSL.create(finalSink,switch)((_,_)) { implicit builder =>
      (sink, sw) =>
        import GraphDSL.Implicits._
        val s = Source(1 to Integer.MAX_VALUE)
        s ~> sw ~> finalFlow  ~> sink
        ClosedShape
    })
  }
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()
  implicit val ec = system.dispatcher
  val (f,kw) = test.run()

  Thread.sleep(3000)
  kw.shutdown()
  f.onComplete{
    case scala.util.Success(value)=> println("killed")
    case scala.util.Failure(e)=> println("error")
  }
```

this case can not kill the stream.

`val switch = KillSwitches.single[Int].async`  worked, but cpu will be high.

how to fix it

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

Please feel free to reopen or comment if you think your question is actually a bug.

I think the problem is because you have Thread.sleep in the map operation.
