### ISSUE TITLE
Quick start documentation doesn't match quick start in tech hub.

### ISSUE THREAD

**Issue by jeremysmitherman** [akka/akka#28432]
The sample project linked in https://doc.akka.io/docs/akka/current/typed/guide/tutorial_1.html does not match the instructions given.

**Comment by johanandren** [comment]
I see the package names has diverged. Is there anything else you noticed that doesn't match?

**Comment by CSerratore** [comment]
The are differences beyond just the package name. Imports have changed, and the ActorHierarchyExperiments class now extends ScalaTestWithActorTestKit, implying the tutorial is now somehow expected to be built and run as a test.

While I cannot suggest how best to reconcile the differences between the tutorial documentation and the referenced repository source code to reflect the _intended result_, I can suggest a simple interim fix:

Simply adding `package com.example` to the top of the code snippet in the documentation will allow it to compile and run. Removing the link to the repository source code would also remove any confusion due to the differences in the source code.
