### ISSUE TITLE
why akka IO Tcp Bind and Connect is deprecated  in akka 2.6.1

### ISSUE THREAD

**Issue by yuer2016** [akka/akka#28441]
Please use https://discuss.akka.io for questions instead of posting them to the issue tracker.
@silent("deprecated")
  final case class Connect(
      remoteAddress: InetSocketAddress,
      localAddress: Option[InetSocketAddress] = None,
      options: immutable.Traversable[SocketOption] = Nil,
      timeout: Option[FiniteDuration] = None,
      pullMode: Boolean = false)
      extends Command

**Comment by raboof** [comment]
> Please use https://discuss.akka.io for questions instead of posting them to the issue tracker.

Please do :)

> `@silent("deprecated")`

This does not mean `Connect` is deprecated, it means we want to 'silence' any deprecation warnings that might pop up while compiling `Connect`. We add this because `immutable.Traversable` is deprecated in Scala 2.13, but we cannot simply change the type because we promise this class will be binary compatible.

We'll probably keep it like this for 2.13, and when we start cross-compiling to Scala 3 introduce a type alias so 2.13 keeps using `immutable.Traversable`, but Scala 3 artifacts will use a replacement.

**Comment by yuer2016** [comment]
> > Please use https://discuss.akka.io for questions instead of posting them to the issue tracker.
> 
> Please do :)
> 
> > `@silent("deprecated")`
> 
> This does not mean `Connect` is deprecated, it means we want to 'silence' any deprecation warnings that might pop up while compiling `Connect`. We add this because `immutable.Traversable` is deprecated in Scala 2.13, but we cannot simply change the type because we promise this class will be binary compatible.
> 
> We'll probably keep it like this for 2.13, and when we start cross-compiling to Scala 3 introduce a type alias so 2.13 keeps using `immutable.Traversable`, but Scala 3 artifacts will use a replacement.

Thank you very much for your answer ！
