### ISSUE TITLE
Add statefulMap Flow operator

### ISSUE THREAD

**Issue by otto-dev** [akka/akka#28476]
As a more realistic follow-up to #28474, this is a request to add a `.statefulMap`  [operator](https://doc.akka.io/docs/akka/current/stream/operators/index.html). The equivalent of `statefulMapConcat`, except mapping 1-to-1 instead of 1-to-N.

I've looked at 14 of my high-level usages of non-standard GraphStages, and 11 of them are due to lacking `statefulMap`. (Another two I could rewrite using standard operators, and only one had its right to exist)

An argument can be made that having `.statefulMapConcat` is enough, but you might also say "we don't need `.map` since we already have `.mapConcat`." Among other things, an explicit 1-to-1 mapping function makes the code more readable, predictable and maintainable.

**Comment by patriknw** [comment]
It's always a delicate balance between adding more Streams operators for very specific usage or convenience compared to combining existing operators.

Here it's about the convenience (and performance benefit) of returning `element` instead of `List(element)`. I don't think wrapping the element adds much extra readability noise compared to the already additional complexity of introducing variable state.

Where would we stop? `statefulFilter`, `statefulCollect`, ...

For the more advanced custom stateful operators that falls between what can be achieved with `statefulMapConcat` and a full `GraphStage` I find the idea of a limited and simplified variant of GraphStage would be interesting, https://github.com/akka/akka/issues/24944

**Comment by otto-dev** [comment]
Thanks a lot for taking the time to respond.

> Where would we stop? `statefulFilter`, `statefulCollect`, ...

I understand this is meant as a negative example, but well, for my part, I wouldn't say no to those... I'd see myself using them :smile: There are only a couple more that would make the `statefulX` operator set complete.

What's the downside? I'm guessing, more cluttered collection of operators and higher maintenance burden.

**Comment by patriknw** [comment]
The downside is that the API will explode with variations of convenience. We are not against convenience when it's something commonly used and difficult to compose of other operators, but this proposal doesn't add enough value to be motivated.

Original and additional discussion in https://discuss.lightbend.com/t/state-inside-of-flow-operators/5717

**Comment by hepin1989** [comment]
@otto-dev I have updated a PR to take a try, would you like to give some input?
