### ISSUE TITLE
2.5.30 jar for Scala 2.13 contains unexpected class files

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28807]
```
λ unzip -Z -1 ~/.ivy2/cache/com.typesafe.akka/akka-actor_2.13/jars/akka-actor_2.13-2.5.30.jar
...
akka/util/TraversableOnceExtensionMethods$.class
akka/util/TraversableOnceExtensionMethods.class
...
```

but these classes are only defined for Scala < 2.13 (incidentally also in a weird file):

```
λ git grep TraversableOnceExtensionMethods origin/release-2.5 
origin/release-2.5:akka-actor/src/main/scala-2.13-/akka/util/ccompat/package.scala:  implicit def toTraversableOnceExtensionMethods[A](self: TraversableOnce[A]): TraversableOnceExtensionMethods[A] =
origin/release-2.5:akka-actor/src/main/scala-2.13-/akka/util/ccompat/package.scala:    new TraversableOnceExtensionMethods[A](self)
origin/release-2.5:akka-actor/src/main/scala-2.13-/akka/util/ccompat/package.scala:class TraversableOnceExtensionMethods[A](private val self: c.TraversableOnce[A]) extends AnyVal 
```

Here's the diff between class files in Scala 2.13 2.5.29 and 2.5.30:

```diff
--- /tmp/2.5.29-classes.txt	2020-03-25 16:41:44.106923255 +0100
+++ /tmp/2.5.30-classes.txt	2020-03-25 16:41:37.066916481 +0100
@@ -1662,0 +1663 @@
+akka/util/ByteString$$anon$1.class
@@ -1674,0 +1676 @@
+akka/util/ByteStringBuilder$$anon$2.class
@@ -1762,0 +1765,2 @@
+akka/util/TraversableOnceExtensionMethods$.class
+akka/util/TraversableOnceExtensionMethods.class
@@ -1771,0 +1776,3 @@
+akka/util/ccompat/CompatImpl$$anon$1.class
+akka/util/ccompat/CompatImpl$.class
+akka/util/ccompat/CompatImpl.class
@@ -1773,0 +1781,7 @@
+akka/util/ccompat/package$FactoryOps.class
+akka/util/ccompat/package$ImmutableSortedMapExtensions$.class
+akka/util/ccompat/package$ImmutableSortedMapExtensions.class
+akka/util/ccompat/package$ImmutableSortedSetOps$.class
+akka/util/ccompat/package$ImmutableSortedSetOps.class
+akka/util/ccompat/package$ImmutableTreeMapExtensions$.class
+akka/util/ccompat/package$ImmutableTreeMapExtensions.class
@@ -1774,0 +1789 @@
+akka/util/ccompat/package$SortedExtensionMethods.class
```

It seems to mostly coincide with the mima problems reported in #28736.

See also #28774.

**Comment by raboof** [comment]
Luckily the problem is reliably reproducible with `sbt clean; sbt -Dakka.genjavadoc.enabled=true +buildRelease`

The first commit that has the problem on the release-2.5 branch is 421fe99f44c1a823a2e80d1fd8bfe37dab1620a5. The problem does not occur on current master, nor when 1.3.6 was first introduced on the 2.6 tree in 90eac0f103.

Enabling `crossPaths` does seem to lead to a correct jar, though it might require changes to how things are published (or not - haven't tested).

I see 2 ways forward: rollback (part of) 421fe99f44c1a823a2e80d1fd8bfe37dab1620a5 on release-2.5 or enable `crossPaths` (incl. testing) on master and backport that to release-2.5.

**Comment by patriknw** [comment]
Isn't it likely that it is because of the sbt update from 1.2.8 to 1.3.6 in 421fe99 and we don't want to go back?

A 3rd alternative would be to change the release script to not use `+`, but build for the 3 Scala versions separately with clean inbetween.

Exploring the impact of changing crossPaths is something we can do in master.

**Comment by raboof** [comment]
> Isn't it likely that it is because of the sbt update from 1.2.8 to 1.3.6 in 421fe99 and we don't want to go back?

Yes, I think so as well.

> change the release script to not use +, but build for the 3 Scala versions separately with clean inbetween

`buildRelease` does a `publishSigned` and also puts the release into `target/releases`. I think indeed we don't actually use `target/releases` for this anymore (I don't think it does anything right now), so that seems like an attractive option.

> Exploring the impact of changing crossPaths is something we can do in master.

Agreed (seems it was already removed in 91c294b28601bda6e13a4becb98d4887e74e07e5 but then added back in 041c0abe649e23776d4d9d94f3d3ce50df844809, so something to look into)

**Comment by patriknw** [comment]
> I think indeed we don't actually use target/releases

It might be used for the doc rsync, but we could build with 2.13 last if that is what is used for docs.

**Comment by raboof** [comment]
> It might be used for the doc rsync, but we could build with 2.13 last if that is what is used for docs.

Correct, it's used for docs, but that's a completely separate step already anyway

**Comment by jrudolph** [comment]
> Isn't it likely that it is because of the sbt update from 1.2.8 to 1.3.6 in [421fe99](https://github.com/akka/akka/commit/421fe99f44c1a823a2e80d1fd8bfe37dab1620a5) and we don't want to go back?

The release notes for [1.3.6](https://github.com/sbt/sbt/releases/tag/v1.3.6) include this one:

> Fixes cross command + so the tasks run in parallel when possible #5329 / #5321 by `@eatkins`

That seems quite dangerous when `crossPaths := false`.

**Comment by jrudolph** [comment]
> > Fixes cross command + so the tasks run in parallel when possible #5329 / #5321 by `@eatkins`
> 
> That seems quite dangerous when `crossPaths := false`.

Though, I might be misunderstanding what that change meant in the first place.

**Comment by eed3si9n** [comment]
So if crossPath is false does that mean the same target directory is reused building different Scala versions? If so you should override the target setting or try to clean up in between?

**Comment by raboof** [comment]
Seems OK again on release-2.5 after splitting it up (e.g. 2.5.31), and on master with crossPaths
