### ISSUE TITLE
Don't depend on Jdk9+ paths from regular paths

### ISSUE THREAD

**Issue by raboof** [akka/akka#28803]
#28741 added some references to the build from regular tasks to Jdk9+-only paths.

That is fine there, since those were only used to populate the run-time classpath, and no Jdk9+-only classes were actually referenced from regular classes.

Still, to avoid the risk of accidentally adding a reference from a regular class to a Jdk9+-only class (which would work at compile time since we compile with jdk11, but throw an error at run time when loading the class on jdk8) I think we should remove those references, and make the tests/benchmarks that want to use the Jdk9+-only feature Jdk9+only themselves as well.

**Comment by patriknw** [comment]
I'm not sure I understand the suggestion

> Then any classes that want to exercise the Jdk9+ features would have to be placed in TestJdk9

For the JFR feature that is not really feasible because we might want to use the flight recorder when debugging any test, not only specific benchmark tests. I have found it very useful for reliable delivery.

Adding JDK9+ lib to the ordinary classpath is indeed too dangerous if we don't compile with JDK 8 only in some CI job. Currently I think we run many (too many) CI jobs with JDK 8 so it's currently not a problem?

Further, maybe we could put those JDK9 dependencies for JFR that were introduced by #28741 under a special flag (disabled by default). So if you need JFR you would have to enable the flag.

**Comment by raboof** [comment]
> For the JFR feature that is not really feasible because we might want to use the flight recorder when debugging any test, not only specific benchmark tests. I have found it very useful for reliable delivery.

Hmm, right. Then maybe just relying on the fact that we'll have at least one jdk8 CI job as long as we support jdk8 should be sufficient.

**Comment by patriknw** [comment]
That was our strategy for the release-2.5 branch when we switched to Scala 2.12 as default but still support 2.11.
