### ISSUE TITLE
add x-reference between akka.cluster.sharding.distributed-data and akka.cluster.distributed-data in the documentation

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka#28863]
there is a `distributed-data` section under both `akka.cluster` and `akka.cluster.sharding`. It would be great to link the other counterparty in each's documentation page.

Also good to warn the users that `durable.lmdb` set in `akka.cluster.distributed-data` won't be picked by `akka.cluster.sharding.distributed-data`. 

Or change the names so they don't look the same?

**Comment by johanandren** [comment]
In general we try to move forward with the new typed APIs and link back from the classic APIs for the same thing. 

For Cluster Sharding the cross linking is up top https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html with a common block on the classic page recommending using the new typed APIs for new projects. 

There are also links from the classic sharding state store modes section to the new APIs: https://doc.akka.io/docs/akka/current/cluster-sharding.html#sharding-state-store-mode 

Isn't this exactly what you are requesting, can you clarify what doc pages you find easy to mix up?


The settings in `akka.cluster.distributed-data` should be "inherited" (with the exceptions `durable.keys`, `majority-min-cap` and `max-delta-elements` since those has specific overrides for sharding) since version 1.4.0 of the config library, which was pulled into Akka in 2.6.0.

It is probably better to configure it specifically for sharding than to touch the default settings though, which is why that is what is mentioned in the docs:

> The settings for Distributed Data are configured in the section akka.cluster.sharding.distributed-data. It’s not possible to have different distributed-data settings for different sharding entity types.

**Comment by Zhen-hao** [comment]
> > The settings for Distributed Data are configured in the section akka.cluster.sharding.distributed-data. It’s not possible to have different distributed-data settings for different sharding entity types.

It is still confusing. should it be "Distributed Data specific to sharding"? Other distributed data should still be configured in `akka.cluster.distributed-data`. Or not?

**Comment by johanandren** [comment]
The reference config `akka.cluster.sharding.distributed-data` inherits the default distributed data config, but then overrides a few settings, see https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/resources/reference.conf#L188

In an application config you'd probably most often want to change application config specifically for sharding, so `akka.cluster.sharding.distributed-data`, but there can be cases where you want to change a setting for both sharding and your application usage of distributed data in one place.

**Comment by Zhen-hao** [comment]
ok. the most urgent question of me is whether the `durable.keys` under `akka.cluster.distributed-data` is still being used if I also add `durable.keys` under `akka.cluster.sharding.distributed-data`.
to put it differently, will `akka.cluster.sharding.distributed-data.durable.keys` override `akka.cluster.distributed-data.durable.keys`?

 should I move the keys from former to latter in order to keep all the keys?

**Comment by johanandren** [comment]
Since `durable-keys` is set/overriden in: https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/resources/reference.conf#L192 (as well as the other keys there), this means it is never inherited from `akka.cluster.distributed-data`.

The reason for not inheriting is that the keys for making sharding durable are not user specified but comes from Akka internals. The only reason you'd change `akka.cluster.distributed-data.durable-keys` is if you want to disable durable storage for the shard state and therefore want to set it to `[]`.

**Comment by Zhen-hao** [comment]
@johanandren thank you. I appreciate your help. but it is still not clear to me. it must be my English...

let me use an example.

Say I have `akka.cluster.distributed-data.durable-keys = ["apple"]` and I do see my distributed object "apple" persisted.
Now let me add `akka.cluster.sharding.distributed-data.durable.keys = ["shard-*"]`. 
Will "apple" still be persisted in the same directory set by `akka.cluster.distributed-data.durable.lmdb.dir`?

**Comment by johanandren** [comment]
I think it boils down to understanding how the config library resolves settings (you can read a lot more about that in the docs of that project: https://github.com/lightbend/config/blob/master/README.md )

If you set any of the distributed data config keys that are not listed in the sharding override block https://github.com/akka/akka/blob/master/akka-cluster-sharding/src/main/resources/reference.conf#L189 under `akka.cluster.distributed-data` in your `application.conf` those values will be inherited by the sharding replicator. 

This means setting `akka.cluster.distributed-data.durable.lmdb.dir` will change the value also for sharding. The `akka.cluster.sharding.distributed-data.durable-keys` already has the value `["shard-*"]` as default, and the only sensible thing to change it to would be `[]`, to disable durable store for the replicator used by sharding.

Note that if you do some custom loading/weaving of config using `ConfigFactory` in your code and passing the created `Config` instance when you start the `ActorSystem` that could behave differently depending on what you are doing, so if you do that you need to make sure to verify that it works as you expect.
