### ISSUE TITLE
scala 2.13 ByteString regression

### ISSUE THREAD

**Issue by tdroxler** [akka/akka#29005]
Hi everyone,

I noticed a regression on `ByteString` while updating scala from 2.12 to 2.13. I'm using akka 2.6.4

the following was working well in 2.12 
```scala
    val empty: ByteString = ByteString.empty
    val byte: Byte = Byte.MaxValue
    val result: ByteString = empty :+ byte
```
but fail in 2.13 with the error: 
```
type mismatch; 
found: IndexedSeq[Byte]    
required: akka.util.ByteString
```
In 2.12 it works because of the `CanBuildFrom` https://github.com/akka/akka/blob/bef03f85858782ae129657c322d267d0af0608c6/akka-actor/src/main/scala-2.12/akka/util/ByteString.scala#L150-L154
As `CanBuildFrom` is removed from 2.13, we now need to override some `appended/prepended/etc` functions to have correct types, otherwise it returns an `IndexedSeq`. It's well explained here https://docs.scala-lang.org/overviews/core/custom-collections.html#rna-sequences 
The `map` case is already done: https://github.com/akka/akka/blob/bef03f85858782ae129657c322d267d0af0608c6/akka-actor/src/main/scala-2.13/akka/util/ByteString.scala#L942 

Thx, cheers

**Comment by johanandren** [comment]
Thanks, if you'd be up for PR:ing a fix that would be great.

**Comment by johanandren** [comment]
After looking into this we decided it's not a good idea because (see #29033):

* Those operations are generally a bad idea with no good performance, it is better that it is a bit of a bother, hopefully that will make users shy away from doing per-byte ops like that.
* It would break binary and source compatibility, there may be user code relying on that already, while it always was the same cross 2.12 - 2.13 (where compatibility is not promised).

**Comment by tdroxler** [comment]
got it, thx :+1:

**Comment by hepin1989** [comment]
Would be better to add some comments in code
