### ISSUE TITLE
Investigate if we can support JFR on Openjdk8

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29078]
JFR was backported to OpenJDK 8, not sure if it is the full thing or a subset, we should check if we can allow the JFR metrics collection to work with that, it is currently only loaded on JDK 11.

Backport was added in openjdk8u262
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8239140

**Comment by chbatey** [comment]
I had a try of this with the latest JDK nightly.

It isn't built into the JDK by default, you need to pass the --enable-jfr flag at configure time. Meaning that we'd need to compile Akka with a JDK that has had that flag enabled. Perhaps we could put the flight recorder implementations in a single module that is built optionally? Otherwise every contributor would need a JFR enabled JDK, or JDK11. Maybe mandating JDK11 for contributing is fine?

At runtime we'd still have to do some reflection to load a noop as i don't think, unless the main distributions start enabling it, we can mandate a JFR enabled JDK8 for running Akka.

**Comment by raboof** [comment]
> Maybe mandating JDK11 for contributing is fine?

That seems fine to me.

**Comment by patriknw** [comment]
> Maybe mandating JDK11 for contributing is fine?

I agree, that should be fine

**Comment by Captain1653** [comment]
This issue is quite old. JDK 8 was dropped in [2.9.0-M2](https://github.com/akka/akka/pull/32127).

Should this issue be closed?

**Comment by patriknw** [comment]
I agree, thanks
