### ISSUE TITLE
Serialization. EventWithMetadata support 

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29260]
MultiDC persistence stores event metadata (originDC, vector clock) via the APC plugin's EventWithMetadata.

Should we have a generic way for plugins to support storing metadata or should the user event wrapped in something?

Wrapping in something has the advantage we don't need a new API for plugins to implement but the downside is that PersistentQuery will break for users as it will be events wrapped in a private type.

--edit Decided to support EventWithMetadata

--edit Changed away from EventWithMeta to putting it in the PersistentRepr

Metadata support for:
* [ ] Akka persistence
* [ ] APC
* [ ] JDBC
* [ ] Spanner
* [ ] Couchbase
* [ ] Serializer for PersistentRepr

**Comment by chbatey** [comment]
@patriknw would be good to get your opinion here

**Comment by johanandren** [comment]
When discussing this yesterday, I argued that we should go with a public API wrapper class instead of the path we took with MultiDC, so that plugins do not need changes to support active active.

**Comment by renatocaval** [comment]
The down side of a wrapper is that users can't read the journal anymore using DB queries.

The JDBC plugin persist the `PersistentRepr` wrapper, which is wrong and we plan to change. The main complain from users is that it make it impossible to have a look at the journal and read the payload. This is especially true for Lagom users because by default the events are persisted in json format. 

This will also be true for Akka users since we are now supporting Jackson and the chances that users use it as the serialization format for the journal exists.

Of course, we could also have the choice of serializing the wrapper with json. But then if the payload (user event) is not json, we will need to use base64 (or similar). 

So, ideally, I would use json for the wrapper if my event is also json. Proto if my payload is proto or any other binary format.

**Comment by patriknw** [comment]
I agree that it would be good to avoid wrapping of the event. I heard customer request to fix this in jdbc plugin just the other day. Better if we can define a general api for meta data that plugins can implement. There have been requests for meta data in other contexts previously.

**Comment by chbatey** [comment]
Okay let's add EventWithMetadata as a public API. We don't have to do all the plugins right away

**Comment by chbatey** [comment]
> The down side of a wrapper is that users can't read the journal anymore using DB queries.

I hadn't really thought of this, only that they could do it with persistent query if we made the wrapper public. But i can see why users would want to query see their serialization format in the database if they're using Json.

**Comment by chbatey** [comment]
We went with a different approach in the end, adding it to the PersistentRepr, we'll  still need to add support for each journal to take it out and persist it.
