### ISSUE TITLE
Provide ctx.actorBoundExecutionContext

### ISSUE THREAD

**Issue by mushtaq** [akka/akka#29360]
**Problem**

For the newcomers, it is not obvious that Future callbacks that modify mutable state inside an actor are not thread-safe. 
These callbacks can run concurrently with actor's message-handlers, leading to concurrency issues.

The preferred solution is to send a message to ctx.self from within such callbacks. 
But for simple use cases, this approach feels a bit too verbose.

**Proposed feature**

Allow user to import ctx.actorBoundExecutionContext which will guarantee that all Future callbacks will be run in the same thread-of-control as the actor messages.

**Woraround**

In the absence of a library provided solution, we have improvised a Behaviour extension as below. 
Complete working example is in [akka-actorbound-ec](https://github.com/mushtaq/akka-actorbound-ec) repo.

```scala
object BehaviourExtensions {

  def withActorBoundEc[T: ClassTag](factory: ExecutionContext => Behavior[T]): Behavior[T] = {
    Behaviors
      .setup[Any] { ctx =>
        Behaviors.intercept[Any, T](() => runnableInterceptor[T]) {
          factory(actorBoundEc(ctx.self))
        }
      }
      .narrow
  }

  private def runnableInterceptor[T: ClassTag]: BehaviorInterceptor[Any, T] = {
    new BehaviorInterceptor[Any, T] {
      def aroundReceive(ctx: TypedActorContext[Any], msg: Any, target: ReceiveTarget[T]): Behavior[T] =
        msg match {
          case x: Runnable => x.run(); Behaviors.same
          case x: T        => target(ctx, x)
          case _           => Behaviors.unhandled
        }
    }
  }

  private def actorBoundEc(actorRef: ActorRef[Runnable]): ExecutionContext = {
    new ExecutionContext {
      override def execute(runnable: Runnable): Unit     = actorRef ! runnable
      override def reportFailure(cause: Throwable): Unit = cause.printStackTrace()
    }
  }

}
```

**ExampleUsage**

```scala
object ExampleUsage {
  trait Msg
  case class Increment(requester: ActorRef[Done]) extends Msg
  case class GetTotal(requester: ActorRef[Int])   extends Msg

  val exampleBehaviour: Behavior[Msg] = BehaviourExtensions.withActorBoundEc { implicit actorBoundEc =>
    var total = 0

    Behaviors.receiveMessage {
      case Increment(requester) =>
        // this will use the actorBoundEc
        // actorBoundEc will send the callback as a 'Runnable' message to ctx.self
        // runnableInterceptor will handle that message sequentially with other actor messages
        Future {
          total += 1
          requester ! Done
        }
        Behaviors.same
      case GetTotal(requester) =>
        requester ! total
        Behaviors.same
    }
  }
}
```

**Test**

```scala
object Test {
  import ExampleUsage._
  implicit val timeout: Timeout = Timeout(5.seconds)

  implicit class Blocker[T](f: Future[T]) {
    def await: T = Await.result(f, timeout.duration)
  }

  def main(args: Array[String]): Unit = {
    val demo = ActorSystem(exampleBehaviour, "demo")
    import demo.executionContext
    implicit val schedule: Scheduler = demo.scheduler

    // concurrent increments
    Future.traverse(1 to 100000)(_ => demo.ask(Increment)).await

    val total = demo.ask(GetTotal)(timeout, demo.scheduler).await

    // should be 100000, no lost update
    println(total)
  }
}
```

**Comment by johanandren** [comment]
I don't think we will be interested in adding such a feature.

There are at least three strong reasons for this: 

 * It would blur the line between two quite different concurrency abstractions, increases complexity, and it is also fragile in that a simple implicit change in Scala will make it unsafe (some other execution context). 
 * That callbacks of futures cannot touch mutable state is not different inside actors from in general, to use futures a developer needs to understand this. Making this magically safe in one context would likely encourage developers to think that they safely could do the same outside
 * The single entry point into the consistent boundary of an actor should be messages going through the inbox, adding a side channel to schedule execution would make it an order of magnitude harder to grasp a given actor since it could have entrypoints spread out all over the actor definition.

For adapting async `Future`/`CompletionStage` values to messages the canonical way is `pipeTo` which is available both in [typed](https://doc.akka.io/docs/akka/current/typed/interaction-patterns.html#send-future-result-to-self) and [classic actor APIs](https://doc.akka.io/docs/akka/current/actors.html#ask-send-and-receive-future). The typed APIs has also made it less common to need futures in that it has a future-less `ActorContext.ask` which only deals with messages.

The general recommendation is to define any chains of future callbacks in methods outside of the actor functions/classes to avoid accidentally touching state (I thought we had this in the styleguide but it seems to be missing, we should add that).

**Comment by mushtaq** [comment]
@johanandren It is fair if Akka does not add it in the std lib for the reasons given. We will keep it as part of our utils.

BTW, I did not find much documentation on how to use `BehaviorInterceptor`. So I am curious to seek feedback akka team on the use of runnableInterceptor as above. It is working very well to ensure sequential execution of callbacks, but it will be good to hear if something is problematic.

**Comment by johanandren** [comment]
@mushtaq I don't see any other problems with your interceptor than the architectural/design ones noted in my previous comment.

**Comment by mushtaq** [comment]
Thanks @johanandren. You may close the issue.
