### ISSUE TITLE
Misleading API differences between Scheduler.scheduleOnce and .scheduleXXX (repeated versions)

### ISSUE THREAD

**Issue by makkarpov** [akka/akka#29414]
In `Scheduler.scala` method `scheduleOnce` has following signature (omitting the execution context):

```
final def scheduleOnce(delay: FiniteDuration)(f: => Unit): Cancellable
```

so you should call it via 

```
scheduler.scheduleOnce(...) {
  ... code ...
}
```

However, repeated `schedule...` methods (e.g. `scheduleAtFixedRate`) have the following signature:

```
def scheduleWithFixedDelay(initialDelay: FiniteDuration, delay: FiniteDuration)(runnable: Runnable): Cancellable
```

so you should call it via

```
scheduler.scheduleWithFixedDelay(..., ...) { () =>
  ...
}
```

The problem
==========

The problem arises when you acidentally call `scheduleOnce` with `() => ...` syntax. It will give no warnings, no errors, nothing at all, but task will be ignored silently (technically, lambda construction will be invoked). I spent a hour figuring out what is wrong and why my tasks don't get invoked.

I don't know how to fix it without breaking backward compatibility. I see the possible ways:

1. Deprecate repeated `scheduleXXX` methods once again and introduce new versions with `f: => Unit` syntax (I think that this syntax is cleaner than `Runnable`s)
2. Deprecate `scheduleOnce` method and introduce new version with `Runnable` syntax.
3. (very dirty hack) Make `scheduleOnce` accept `f: => Any` instead of `f: => Unit`. This should not break neither source nor binary compatibility. Then, save the return value from `f` and check if it is of type `scala.Function0`. If it is, then invoke that function.

**Comment by johanandren** [comment]
In general we have moved towards not using by-name in the Akka Scala APIs, and instead use explicit factory lambdas for such cases, because it avoids a whole set of problems like this. So I don't think we'd want to move in the other direction with this API. 

There already is a Scala API `scheduleOnce` that accepts `Runnable` so we could perhaps just deprecate the by-name method, but it feels quite invasive to do so in a patch release given that the method has been around since 2013.

Have you considered using the actor based scheduling APIs instead (`Behaviors.withTimers` in typed and `with Timers` in classic), those are what we recommend for most use cases nowadays as they tie the scheduled tasks to the lifecycle of the actor and is perhaps a bit more clear about on what execution context the logic is actually executed.

**Comment by makkarpov** [comment]
Okay, lambdas are good as well when they are consistent. But even though `scheduleOnce` has a runnable version, 'separate parentheses' syntax feature is rather nice. Currently `scheduleOnce` accepts runnable in same argument list as duration.

> Have you considered using the actor based scheduling APIs instead (Behaviors.withTimers in typed and with Timers in classic), those are what we recommend for most use cases nowadays as they tie the scheduled tasks to the lifecycle of the actor and is perhaps a bit more clear about on what execution context the logic is actually executed.

It's not actor-based code, so no luck here.

**Comment by patriknw** [comment]
I agree that there are some inconsistency between `scheduleWithFixedDelay` and `scheduleOnce`. I think the reason could have been that it isn't possible to have overloaded methods with second parameter list. Runnable was originally intended for Java and `f: => Unit` for Scala.

I don't think we can change this. API changes also cause trouble for users.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for 3 years.

Should this issue be closed?

**Comment by patriknw** [comment]
yes, api might not be perfect but we don't intend to change it
