### ISSUE TITLE
Enforce separation of leader and singleton roles

### ISSUE THREAD

**Issue by EkardNT** [akka/akka#29680]
I am using the singleton feature of the Akka Clustering library. I recently experienced an outage of my cluster where the root cause was that one of the cluster members became temporarily unreachable, and that cluster member happened to host both the leader and singleton roles. Although the cluster successfully elected a new leader, the new leader was unable to appoint a new singleton due to the failed member being unreachable. Once I explicitly marked the failed member as Down, the leader was able to appoint the singleton.

I understand why the leader was unable to appoint a new singleton while there was an unreachable node, and I understand why marking the unreachable node as Down fixed the problem. However, going forward, I'd like to prevent a single-member outage from causing a similar problem by enforcing that the leader and singleton roles are never assigned to the same cluster member, so long as there is more than 1 member in the cluster.

From examining the `Member.scala` code and documentation, I see that the `leaderStatusOrdering` is (mostly) based on address ordering, while the `ageOrdering` used in `ClusterSingletonManager.scala` is based on the Member's `upNumber`. I can't see an existing mechanism for allowing the user to plug in a different leader or singleton selection algorithm. The conceptually simplest solution that occurs to me is to make ClusterSingletonManager use `Member.leaderStatusOrdering.reverse()` instead of `ageOrdering`. That would guarantee the roles are separated as long as the cluster size is > 1. But, I'm not sure what other consequences making that change would have - among other things, the `OldestChangedBuffer` and similarly-named events in `ClusterSingletonManager.scala` would be misleadingly named.

I am willing to contribute a PR to make this change, but I'd like the Akka team's thoughts on the above possible approach and/or better ways of achieving this.

**Comment by octonato** [comment]
The solution for the issue you faced is not to change how things work internally in Akka, but to configure the a downing provider, more specifically the [Split Brain Resolver](https://doc.akka.io/docs/akka/current/split-brain-resolver.html#split-brain-resolver). It would have Downed the node for you.

Changing where the singletons leave has quite some impact in the internals of cluster sharding, so that's not a wise thing to do. 

Moreover, singletons there are often used to manage things so that's why you want it on the oldest node. If you reverse it, every new node added to a cluster will force the singletons to move. Just to give you one example of a case in which it makes sense to have singletons on the oldest node.

**Comment by EkardNT** [comment]
The split brain resolver does seem like it would solve my single-node-down issue in this case. I think in general it would be nice to have the ability to configure the singleton member selection logic, but as I can solve my issue with the split brain resolver I will close this issue. Thank you @octonato.
