### ISSUE TITLE
Reconsider cluster-sharding-shutdown-region coordianted shutdown timeout

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29711]
Coordinated shutdown gives regions 10s to shutdown but handover allows 60s and 55s for each entity to shutdown. This means that coordinated shutdown timesout before the user's entities shutdown have timed out.

Can we set one off the other or at least set the region shutdown timeout to be > than the handoff timeout?

Thoughts?

**Comment by johanandren** [comment]
Does it need to be matched, the region will continue the graceful shutdown after the coordinated shutdown continues and has a chance to complete, worst case the system shuts down before the region is done with its business (passing on buffered messages for example) and some messages are lost.

In a scenario where a user has really slow handoffs they can still tune the coordinated shutdown phase timeout, no?

**Comment by chbatey** [comment]
It isn't trivial to debug that it's slow shutdowns that have caused the error in coordinated shutdown as the hard off process won't log anything until the timeout (that will never happen as the node will have shutdown) is hit.

**Comment by chbatey** [comment]
(and takes DEBUG level logging + a sharding expert). If the timeouts were the otherway around it would be trivial to know what was going on.

**Comment by johanandren** [comment]
Trivial to know what was going on but would drop more messages, at least that's what I think is the tradeoff, unless you change the coordinated shutdown phase timeout to be very high like the region timeout?

Could it help with some form of informative logging "I'm still shutting down but did not complete within 10s" from the region?

**Comment by chbatey** [comment]
I don't think you'd drop more messages as coordinated shutdown stops the node right after its timeout.

I am suggesting setting region timeout to > handoff.

**Comment by johanandren** [comment]
Hmmm that may be ok. 

With a system under load though, wouldn't it potentially just keep putting messages in region buffer then restarting the shards until the timeout hits anyway? Also, isn't there often a SIGKILL triggered from for example k8 if the process does not stop fast enough after the SIGTERM, so that we'd just more likely just hit that and get an abrupt termination and need a downing from SBR then?

**Comment by patriknw** [comment]
I agree with the SIGTERM aspect. We should not have defaults that make that wait for too long.

Could we have a shorter timeout in the region when it's waiting for ack of the GracefulShutdownReq so that stops anyway after less than the coordinated shutdown timeout, with a more clear log message than we can have in coordinated shutdown.

**Comment by patriknw** [comment]
Better logging when timeout in graceful shutdown of shard region:
Currently it hits the 10 seconds timeout in the coordinated shutdown. If we would have shorter timeout in the region we could log a better message. Maybe also a warning in the shards when HandOffStopper takes longer than 5 seconds (< coordinated shutdown timeout).
