### ISSUE TITLE
Change typing ask and and askWithStatus in in AskPattern.Askable

### ISSUE THREAD

**Issue by hmf** [akka/akka#29713]
This is request to change the typing of at least 2 methods because they assume the request and response types are based on the ActorRef alone. More specifically the following response types are biased:

[def ask[Res](replyTo: ActorRef[Res] => Req)(implicit timeout: Timeout, scheduler: Scheduler): Future[Res]](https://github.com/akka/akka/blob/996f42483523093323c9d30cb41a6005adc38558/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala#L107)

[ def askWithStatus[Res](replyTo: ActorRef[StatusReply[Res]] => Req)(implicit timeout: Timeout, scheduler: Scheduler): Future[Res]](https://github.com/akka/akka/blob/996f42483523093323c9d30cb41a6005adc38558/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala#L125)

`Res` is set by `ActorRef[Res]`.

I thinks they should have the same typing as here:

[ def ask[Req, Res](target: RecipientRef[Req], createRequest: ActorRef[Res] => Req)(
      mapResponse: Try[Res] => T)(implicit responseTimeout: Timeout, classTag: ClassTag[Res]): Unit](https://github.com/akka/akka/blob/996f42483523093323c9d30cb41a6005adc38558/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala#L297)

and:

[def askWithStatus[Req, Res](target: RecipientRef[Req], createRequest: ActorRef[StatusReply[Res]] => Req)(
      mapResponse: Try[Res] => T)(implicit responseTimeout: Timeout, classTag: ClassTag[Res]): Unit](https://github.com/akka/akka/blob/996f42483523093323c9d30cb41a6005adc38558/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/ActorContext.scala#L306)

Without these changes, it will allow us to use the Asynchronous testing API consistently wether we use an `ActorContext` or `ActorRref` with *flipped* types.

I ran into this issue because I have 2 actors, say, `A` and `B`. Unlike the Akka idiom, actor `A` has `Behavior[B.Command]` and sends `A.Command`. And actor `B` is the symmetric opposite. 

Hope this makes some sense.

**Comment by johanandren** [comment]
I don't see why we would want to change that and I think the request is based on some form of misunderstanding of the API. (Or there is something missing from the description here)

For `ActorContext[T].ask` there already is a response type `T` which any response must be mapped to, since the response is sent back to the actor that asked. This is why there needs to be an adaptation, in most cases you have to turn that response message type into the actors own protocol.

The ask API in `AskPattern` generates a `Future[Res]`, which means the response is not limited by any external constraint other than what the actor responds with. If you wish to transform that `Res` type into something else you use the `map(Res => B)`  transformation methods on `Future`.

Note that the future API is primarily ment for interacting with actors from "the outside", it is good to avoid future composition inside of your actors if you can since it ie easy to accidentally close over mutable state that it is not safe to interact with. The `ActorContext.ask` runs its mapping logic on the actor thread upon receiving the response to avoid such accidents.

In tests you usually have no need to use ask at all, since using a `TestProbe[B]` and then `.expectMessage()` provides timeouts, there you can even use a `TestProbe[Any]` and narrow its `ActorRef` to the needed type for a specific interaction.

**Comment by hmf** [comment]
@johanandren I agree that I am misunderstanding the API. 

> Note that the future API is primarily me[a]nt for interacting with actors from "the outside"

I looked at this API because I want to test an actor. In my case I am trying to use `ActorContext.askWithStatus` to send a message that contains a:

```scala 
akka.actor.typed.ActorRef[akka.pattern.StatusReply[Command]]
``` 

> In tests you usually have no need to use ask at all, since using a TestProbe[B]...

However when I use:

```scala
    val probe: TestProbe[Command] = testKit.createTestProbe[Command]()
```

I have a:

```scala
akka.actor.typed.ActorRef[Command]
```
so I cannot send the message because I don't have the type. I was trying to send messages with `StatusReply` reference. While doing so I could net get the types to match. 

Chances are I am simply forcing a situation that does not make sense. Thanks for taking the time to analyze this.
