### ISSUE TITLE
[Typed TestKit] Akka Typed Synchronous Teskit doesn't seem to work with Supervision

### ISSUE THREAD

**Issue by jlprat** [akka/akka#29767]
I'm not sure if this is a bug or a missing feature of the typed synchronous testkit doesn't seem to work well with supervision strategies.

I created a small repro project so one could check and test this:
https://github.com/jlprat/repro-supervision-sync/

[Restart](https://github.com/jlprat/repro-supervision-sync/blob/main/src/main/scala/com/example/Restart.scala) is a behavior using `init` where the child actor is created that is completely encapsulated with `supervise`.
According to the docs, this child should be recreated when the parent is restarted.

I provided 2 tests, the [async one](https://github.com/jlprat/repro-supervision-sync/blob/main/src/test/scala/com/example/RestartAsyncTest.scala) works as expected, after restart one can see the logging side effect when creating the child again.
However, the [sync one](https://github.com/jlprat/repro-supervision-sync/blob/main/src/test/scala/com/example/RestartSyncTest.scala) fails when I assert for the presence of the `Spawn` effect after restarting.

**Comment by patriknw** [comment]
That's because supervision often involve some async interactions. `restartWithBackoff` obviously, but also `restart` when there are children because then it's "waiting" for the children to stop first.

I think this should just be added to the list of [limitations in the sync TestKit](https://doc.akka.io/docs/akka/current/typed/testing-sync.html).

Contributions to the sync TestKit and maybe removing some of the limitations are welcome, but it's not the core team's top priority.

**Comment by jlprat** [comment]
I could definitely add this to the list of limitation in the sync testkit.
I will take a look and see if I manage to extend the sync testkit to support supervision.

**Comment by jlprat** [comment]
Shall we keep this issue open in case one (maybe future me) wants to extend the Sync Testkit to support supervision? cc @johanandren

**Comment by johanandren** [comment]
I think we can create a new ticket the day someone wants to invest time in that, if that happens :)
