### ISSUE TITLE
Wire Protocol Compatibility section is missing in `Migration Guide 2.5.x to 2.6.x`

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#29865]
It's very clear that in https://doc.akka.io/docs/akka/2.5/project/migration-guide-2.4.x-2.5.x.html#wire-protocol-compatibility
but this section in https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html#remoting

**Comment by johanandren** [comment]
It's because default was the classic (netty) based remoting in 2.5 and artery in 2.6 and it is not possible to roll that upgrade as described in the first section there "Migrating from classic remoting to Artery". But perhaps worth noting that if you stay on the same remoting impl. it is wire compatible.

**Comment by hepin1989** [comment]
We distrusted akka 2.4.20 as part of the client...,so really hard to get them all upgraded.

**Comment by patriknw** [comment]
Then you would have to Akka classic remoting on the server side. If you ever change you should consider using gRPC or HTTP for such external clients.
