### ISSUE TITLE
Overlapping serialization config for EventSourcedBehaviorTestKit

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29904]
The testkit either uses an in mem store that does not serialize or one that serializes, based on the settings `akka.persistence.testkit.events.serialize` and `akka.persistence.testkit.snapshots.serialize` from the system config, but in parallel with this there is also the programmatic `SerializationSettings` which allows for "disabling" the event and state verification that happens in the testkit, before objects reach the journal. This confuses users somewhat since a test that has disabled verification still will end up serializing the events.

I wonder if we should make sure to align the journal settings with the `SerializationSettings` (a bit tricky to pass that over since the journal is loaded through the default persistence infra)?

**Comment by johanandren** [comment]
There was an additional, maybe more, surprising thing with the serialization flags addressed in #29905

**Comment by patriknw** [comment]
The intention was to not use the serialization in the in mem store and only use the checks in the EventSourcedBehaviorTestKit configured via SerializationSettings.

That's why `akka.persistence.testkit.events.serialize` is disabled here:

https://github.com/akka/akka/blob/dfc9d6e20f61045f3b838d7545dd63a74d208f9f/akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/EventSourcedBehaviorTestKit.scala#L38-L40

`akka.persistence.testkit.snapshots.serialize` should probably also be added there.

If that can still be abused in some way we could add a runtime check to ensure that the in mem serialization is disabled.
