### ISSUE TITLE
use scala.concurrent.Batchable instead of scala.concurrent.OnCompleteRunnable

### ISSUE THREAD

**Issue by xuwei-k** [akka/akka#29980]
akka use `scala.concurrent.OnCompleteRunnable` in `akka.dispatch.TaskInvocation` and `akka.dispatch.BatchingExecutor`.

- https://github.com/akka/akka/blob/0bf29fd2320b05214ae9f45cd186db5b5a276c44/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala#L43
- https://github.com/akka/akka/blob/0bf29fd2320b05214ae9f45cd186db5b5a276c44/akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala#L132

Scala 2.13.3 (or earlier version) `impl.Promise.Transformation` extends `OnCompleteRunnable`. but it removed since Scala 2.13.4 😢 

- https://github.com/scala/scala/blob/v2.13.3/src/library/scala/concurrent/impl/Promise.scala#L380
- https://github.com/scala/scala/blob/v2.13.4/src/library/scala/concurrent/impl/Promise.scala#L380
- https://github.com/scala/scala/commit/17ed7fc50e56ec2d95eb8483f530d9860f77874a

**Comment by johanandren** [comment]
Thanks for letting us know!

`scala.concurrent.Batchable` is only available in 2.13, right? That would mean we'd need to introduce separate sources for `AbstractDispatcher` and `BatchingExecutor` (or at least that logic) for 2.12 and 2.13

**Comment by dwijnand** [comment]
Or perhaps `scala.concurrent.BatchingExecutor` can be used in place of `akka.dispatch.BatchingExecutor` in 2.13?

**Comment by NthPortal** [comment]
@johanandren you can just add a single basic source with a type alias that's different per version. e.g.

```scala
// 2.12
private[dispatch] object ScalaBatching {
  type Batchable = scala.concurrent.OnCompleteRunnable
}
```

```scala
// 2.13
private[dispatch] object ScalaBatching {
  type Batchable = scala.concurrent.Batchable
}

**Comment by johanandren** [comment]
Clever, thanks for the hint.

**Comment by johanandren** [comment]
Some investigation results: `akka.dispatch.BatchingExecutor` and `akka.dispatch.Batchable` are both internal API, the only instance of our internal legacy `Batchable` is `TaskInvocation` which is final, so that should mean that we can indeed switch over to the stdlib one in 2.13 with parallell sources for `TaskInvocation`.

I do have a vague memory of some tests failing when I tried to do that earlier though (for https://github.com/akka/akka/issues/26383 and https://github.com/akka/akka/issues/26690), but perhaps worth giving that another shot.
