### ISSUE TITLE
Missing Tagged serializer

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30080]
When using event tagging in combination with Replicated EventSourcing, the class `akka.persistence.journal.Tagged` (and maybe others?) will no longer be a local instance but may cross processes so it needs to be serializable.

**Comment by johanandren** [comment]
I enabled tagging in the multi node test in `akka.cluster.sharding.typed.ReplicatedShardingSpec` which runs three nodes with separate journals and that passes, replicating tagged events between the nodes, without adding any serializer, so that is not an issue.

**Comment by johanandren** [comment]
Ok, so what should happen here is that the tagged event should not be sent across the wire at all, since wether the replica should tag the event or not is up to its tagger and not the sending replica, the event publishing support in sharding should unwrap tagged events and send the payload without the tags.

(Since eventPublishing is a low level feature of also EventSourcedBehavior allowing for other use cases than replicated entities event publish across the network the unwrapping does not belong there).

**Comment by ignasi35** [comment]
If we implement the unwrapping so the sending replica publishes only the payload it'd be good to add a good nice WANR in the logs or even fail so it's clear the tags will not be available on the receiving replica.

**Comment by johanandren** [comment]
A warning does not make any sense, local tags not being seen by the replica is the expected behavior. 

If you disable event publishing and only rely on following the event log the tags of a replica are not seen in the other replicas, fixing this makes it work the same if enabling the event publishing optimization (which really is just a way to see the event faster/with less replica db querying in the other replicas).
