### ISSUE TITLE
Akka 2.6 doesn't recover stream properly

### ISSUE THREAD

**Issue by limansky** [akka/akka#30104]
Recently I've tried to upgrade from Akka 2.5 to 2.6 and faced with an issue. I've created snippet to show the problem:

https://gist.github.com/limansky/3ec6c92912b0c156d6b43f8b939deeab

Steps to reproduce:
1. Run program.
2. Connect using telnet.
3. Send "aaaa".

Expected result (works fine with Akka 2.5.32):
Got reply:
```
ERROR: S = R!
Connection closed by foreign host.
```

Actual result (Akka 2.6.13):
Connection closed immediately:
```
Connection closed by foreign host.
```

**Comment by johanandren** [comment]
Thanks for reporting. I think it is a race condition wrt if the cancellation reaches TCP connection in or the element and completion reached out first. Needs more investigation though.

**Comment by johanandren** [comment]
The reason for this is that in Akka 2.6 failures are also passed upstream as a cancellation cause, when a failure reaches the TCP stage it tears the connection down. Best way to deal with this is to not rely on stream failure as a way to handle things that need to go in the protocol, but rather a way to tear things down when the unexpected happens.

So instead of letting a task that can fail, fail the entire stream, represent it as a stream value and complete the stream successfully on with that final error to the client:

```scala
Flow[ByteString]
        .via(Framing.delimiter(ByteString("\r\n"), 128))
        .map(_.utf8String)
        .mapAsync(1) { elem =>
          // lift a failed future into a Future[Try[String]] instead of failing the stream
          logic(elem).transform(aTry => Success(aTry))
        }
        // complete once we see a failure
        .takeWhile(_.isSuccess, inclusive = true)
        .flatMapConcat {
          case Success(s) =>
            Source(List(ByteString(s + "\n"), ByteString("-----------------\n")))
          case Failure(x) =>
            Source.single(ByteString(s"ERROR: ${x.getMessage}\n"))
        }
```

Note that there is likely an additional race condition in there though, even with 2.5, if the cancellation reaches the TCP by going upstream before the downstream logic has got a chance to execute, it would also tear the connection down unless you start the server with `halfClose = true`.

**Comment by limansky** [comment]
Hi @johanandren. Thank you for the workaround. 

However I'm still thinking that it's a bug, because the stream behavior shouldn't depend on the transport layer. So `recover` should work the in same way for all streams.

**Comment by johanandren** [comment]
It isn't about the stream depending on transport layer but the other way around, the TCP stream connector reacting on stream teardown behavior which can happen in three ways, with allowing half closed or not as an extra dimension - completion reaching the out first, cancellation reaching the in, and failure reaching either in or out. Recover kind of catches an upstream failure and hides it from downstream, but there is no way to do the same in the other direction.

@jrudolph is there something with the "new" cancellation strategies I am missing here?

**Comment by jrudolph** [comment]
> It isn't about the stream depending on transport layer but the other way around, the TCP stream connector reacting on stream teardown behavior which can happen in three ways, with allowing half closed or not as an extra dimension - completion reaching the out first, cancellation reaching the in, and failure reaching either in or out. Recover kind of catches an upstream failure and hides it from downstream, but there is no way to do the same in the other direction.

:+1:

With 2.5 it might have worked as expected in this particular case because there wasn't any more complex logic in the stream but it might also just be a lucky turn-out of the race condition.

If you want to avoid the race-condition you can try to set a cancellation strategy that delays cancellation for a while:

```scala
Flow[ByteString]
 . // your flow parts
 .addAttributes(Attributes(CancellationStrategy.AfterDelay(1.second, CancellationStrategy.FailStage)))
```

You could also try `bind(..., halfClose = true)` as @johanandren hinted. That would keep the connection open indefinitely, though, if the peer doesn't close the connection itself.

**Comment by limansky** [comment]
Hi,

  Sorry for delay. @jrudolph  I've just tested `CancellationStrategy.AfterDelay` and it fixes the problem for me. Thank you so much.
  
Should I close this issue?
