### ISSUE TITLE
Security vulnerability found on jackson-dataformat-cbor CVE-2020-28491

### ISSUE THREAD

**Issue by mrooneytrimble** [akka/akka#30126]
A security vulnerability has been found on the jackson-dataformat-cbor dependency. This is pulled in by "akka-serialization-jackson"

Details of the vulnerability

> This affects the package com.fasterxml.jackson.dataformat:jackson-dataformat-cbor from 0 and before 2.11.4, from 2.12.0-rc1 and before 2.12.1. Unchecked allocation of byte buffer can cause a java.lang.OutOfMemoryError exception.

Fixes 

> Upgrade to version com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.11.4, com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.12.1

Details of project

> akka version 2.6.13

**Comment by johanandren** [comment]
We have deferred upgrading from 2.10 since that might break binary compatibility, which we promise with Akka (https://github.com/akka/akka/pull/28970#issuecomment-671201057). But perhaps this security is that reason that makes it worth investigating.

It is likely possible to workaround in a given application by upgrading to 2.12 (someone mentioned that they got that working in https://github.com/akka/akka/issues/29072 )

**Comment by johanandren** [comment]
For the record, jackson tracker issue: https://github.com/FasterXML/jackson-dataformats-binary/issues/186
