### ISSUE TITLE
Flow.completionTimeout seems to not work when infinite loop is involved

### ISSUE THREAD

**Issue by basking2** [akka/akka#30134]
We have a `map()` stage in an Akka stream that processes a single element. That element can cause and infinite loop in the code in the body of the `map()` stage. To guard against this we appended after that state `completionTimeout(1.hour)` expecting to be notified with a `TimeoutException` that the stream was canceled. We never observed the timeout fire. 

Reading the documentation it really seems like this should be the case. 

I've setup a quick [Scala Test](https://github.com/basking2/akka-stream-test) that should timeout and `recover()` the flow with a value of `42`.

If our team has misunderstood the documentation, how can that be clarified? Or, is this indeed a bug?

Thank you!

**Comment by johanandren** [comment]
Blocking the stream indefinitely like that with a while(true) will make it so that no other operator ever gets to execute, so that is why you are not seeing the timeout working, so that is expected. Adding an async boundary between the infinite blocking operator and the downstream, will make them run on different actors so that the downstream can complete, it will however still stall the upstream actor forever, and the thread running it, so if you have several of those it will likely end up starving your dispatcher so that nothing in the actor system gets to execute.

You can find more about blocking in Akka in this section of the docs: https://doc.akka.io/docs/akka/current/typed/dispatchers.html#blocking-needs-careful-management

**Comment by basking2** [comment]
Thanks, @johanandren. My expectation was that evaluation of the timer result would have happened on another thread regardless of what the up-stream was doing. Your explanation makes sense, though, thank you!

I'll close this. Adding a line to the timer documentation similar to, "notice that this timer event is _on_ the flow, and so it will be evaluated when control of the flow's thread reaches this stage. If an upstream stage takes a long time your timer, you timer may not cancel the stream exactly when you expect it to."
