### ISSUE TITLE
preMaterialize should build a stream of materialized values

### ISSUE THREAD

**Issue by broij** [akka/akka#30146]
This feature request / bug report is related to akka-stream. 

Currently, the preMaterialize operator returns:
- the materialized value of the preMateriliazed sink;
- a reference to the pre-materilized sink.

My concern with that operator is that sinks are blueprints of computations, which means that the reference to the pre-materialized sink could be 'instantiated' several times.

Consider a situation where the operator Sink.last is used on a source which is then pre-materialized and whose pre-materilized sink is then ‘instantiated’ several times. In such a scenario, what would happen with the previously computed pre-materilized value? Would it wrap the last element of the first instantiation that completes? Something else? I don't think that the final user expect such a behavior anyway. To fix that ambiguïty, I suggest that this operator should return instead:
- a source of materialized values where the n_th element gives the materialized value of the n_th instantiation of the pre-materialized sink;
- a reference to the pre-materilized sink.

**Comment by johanandren** [comment]
I don't think this makes sense.

What `preMaterialize` does is create one segment of stream that starts running immediately, with a reactive streams subscriber or publisher in the "undefined" end, upon calling `preMaterialize`. So opposed to most other operator factory methods it does not really return a blueprint but is more like something inbetween an operator and `run()` on a `RunnableGraph`. The returned materialized value from `preMaterialize` is the materialized value from this already started stream island, so there will never be more than one of it.

The down/upstream that is then attached will for each materialization potentially result in a materialized value, which can be collected/sent somewhere etc. There is nothing stopping you from doing this with the current APIs, for the example you mentioned capturing the materialized value of each downstream and send it to some actor or put it in one single stream using the queue or actor ref operators for example.

(Additionally, since materialization is blocking, putting representing the materialized values as a `Source` would not make sense, what happens if that source is not run when the stream is materialized, would that block the materialization thread until the source is, and what about backpressure, or multiple materializations of that source.)

**Comment by broij** [comment]
> What preMaterialize does is create one segment of stream that starts running immediately, with a reactive streams subscriber or publisher in the "undefined" end, upon calling preMaterialize. So opposed to most other operator factory methods **it does not really return a blueprint but is more like something inbetween an operator and run() on a RunnableGraph**. The returned materialized value from preMaterialize is the materialized value from this already started stream island, so there will never be more than one of it.

What I mean is that the fact that it does not return a blueprint is a design problem since the documentation states that `Source`, `Flow` and `Sink` are blueprints. The user expects to build its stream by defining blueprints and composing them but ultimately he can't in some particular cases where a `preMaterialize` call happens. This is because, as you pointed out, once a stream is pre-materiliazed, it is not really a blueprint anymore. Ideally, all operators should return blueprints.

To be a little more explicit, when a stream that was previously pre-materialized is instanciated several times, it could lead to some "logical" issues from the user perspective. If he doesn't know the implementation detail enforcing that only the materialized value first instanciation will be given, as you explained, he could expect the program to crash or have a different behavior than what will actually happen. Take for instance a `Sink.seq` which is first preMaterialized, then composed with some other operators into a closed computation graph and then instanciated several times.

This is the reason why I suggest that this operator should be reworked.

> The down/upstream that is then attached will for each materialization potentially result in a materialized value, which can be collected/sent somewhere etc. There is nothing stopping you from doing this with the current APIs, for the example you mentioned capturing the materialized value of each downstream and send it to some actor or put it in one single stream using the queue or actor ref operators for example.

We agree on that.

> (Additionally, since materialization is blocking, putting representing the materialized values as a Source would not make sense, what happens if that source is not run when the stream is materialized, would that block the materialization thread until the source is, and what about backpressure, or multiple materializations of that source.)

You can allow the user to define a proper strategy to cope with these scenarios when using the operator (backpressure the next instanciation until its materiliazed value is consumed, drop the materialized value and instanciate, etc.). Also, I guess multiple materializations of such source should return a reference to the same "live" source. If the source doesn't fit, you can also preMaterialize to another data-structure (an iterator, a chain of promises). I guess that all those aspects are implementation details.

**Comment by johanandren** [comment]
I think that design decision is already done, a long time back, fulfilling some specific requirements (or specific tricky aspects, like the websocket API in Akka HTTP) and because of binary compatibility it is not something we can change easily. Adding a parallell method that does somewhat the same but has different such semantics (on top of not quite knowing how that would actually be possible to implement) would just make the APIs harder to digest. 

There are also several other operators which are not blueprints but will run partial streams (reactive stream interop operators, input/outputstream interop, MergeHub, BroadcastHub, networking streams, Akka HTTP streams, some of the Alpakka connectors for some examples), so changing `preMaterialize` would only fix that for a very specific corner of Akka Streams. I think the best we can do is to accept this as a fact and make sure to document clearly for such operators that they are not really blueprint and cannot be materialized many times.

For this reason I don't think that we'd want to expand APIs like this (except possibly for adding a `Flow.preMaterialize` which is discussed in #30074 )

Note that you can always add your own custom graph stages/operators in your own project or as a third part open source library, so if this is something you want to explore that is perfectly fine even if we do not want to change/extend the core stream APIs.

**Comment by johanandren** [comment]
Thanks for discussing this @broij, I'm closing the ticket as we don't expect to change anything.
