### ISSUE TITLE
Inconsistent behavior when applying the preMaterialize operator on Source.queue

### ISSUE THREAD

**Issue by broij** [akka/akka#30164]
The bug is related to akka-stream.

Consider the following snipet:
```
import akka.actor._
import `akka.stream._
import akka.stream.scaladsl._

implicit val system: ActorSystem = ActorSystem("QuickStart")
implicit val ec = system.dispatcher

val (queue, done) = Source.queue[Int](0, OverflowStrategy.backpressure).map { e =>
  System.err.println(e)
  e
}.toMat(Sink.foreach(_ => throw new Exception("Fake exception")))(Keep.both).run()
queue.offer(1).map(System.err.println)
queue.offer(2).map(System.err.println)
```

Its execution prints to the console:
>   Enqueued
>   1

The queue is thus closed after the exception is thrown.

Now consider this second snipet:
```
import akka.actor._
import akka.stream._
import akka.stream.scaladsl._

implicit val system: ActorSystem = ActorSystem("QuickStart")
implicit val ec = system.dispatcher

val (queue, source) = Source.queue[Int](0, OverflowStrategy.backpressure).preMaterialize()

source.map { e =>
  System.err.println(e)
  e
}.to(Sink.foreach(_ => throw new Exception("prout"))).run()
queue.offer(1).map(System.err.println)
queue.offer(2).map(System.err.println)
```

Its execution prints to the console:
>   Enqueued
>   Enqueued
>   1

This means the queue wasn't closed after the exception is thrown. I would expect the queue to close after that exception was thrown, just as it did when not pre-materialized.

**Comment by johanandren** [comment]
That is not a correct way to observe that the failure propagated upstream so it does not mean queue wasn't closed after the exception was thrown. 

Since the logic runs in another thread without any synchronization with the main thread there is no guaranteed ordering between the offer calls and the failure reaching the running source, even with the example without a prematerialized stream/async boundary. (And in addition to this there are buffers introduced when introducing an async boundary in the stream so it will request 16 elements immediately for the prematerialized case, by default)

**Comment by broij** [comment]
The queue was configured to use no buffers and to backpressure offers. I did expect the messages to be consumed one after the others since I didn't introduce any buffers downstream. If additional buffers are indeed introduced by preMaterialize the example is invalid.

**Comment by johanandren** [comment]
Yes, since `preMaterialize` creates a running island, there is a buffer in front of it (to lower the cost of passing work between threads).
