### ISSUE TITLE
RestartFlow is not restarted as expected in presence of async boundaries

### ISSUE THREAD

**Issue by andreaTP** [akka/akka#30249]
The behavior can be reproduced with this repro:
https://github.com/andreaTP/repro-restart-stream

Or even in this Scalafiddle:
https://scalafiddle.io/sf/lXKtnnu/2

Adding and removing the `async` boundary from the `Flow` change the behavior of the Restart:
 - without `async` the stream gets restarted as expected
 - with `async` the stream is not restarted

**Comment by johanandren** [comment]
It's actually as expected, although maybe not obvious:

`.async` introduces a buffer in front of the stream async island, with a default size of 16 elements. So the given sample code immediately demands 16 and pulls all 10 elements into the buffer in front of the async island, inside the restart flow, making the source complete. When it throws at 5 (or a random number) the rest of the elements already inside a buffer in the flow are lost. Since the restart flow already saw the input stream complete it does not restart the inner flow but instead completes.

You can make it behave the same as the non async one by tuning the input buffer down to 1 (but with bad stream throughput as a consequence) using `.withAttributes(Attributes.inputBuffer(1, 1))`.

**Comment by johanandren** [comment]
This is already noted in the API docs of RestartFlow, not sure if any clarification there would have helped:

```
   * The restart process is inherently lossy, since there is no coordination between cancelling and the sending of
   * messages. A termination signal from either end of the wrapped [[Flow]] will cause the other end to be terminated,
   * and any in transit messages will be lost.
```

**Comment by johanandren** [comment]
@andreaTP should we close this or do you have some idea about how we could improve docs around this?

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for 2 years.

Should this issue be closed?
