### ISSUE TITLE
ClusterSingletonManagerPreparingForShutdown: last nodes should shut down

### ISSUE THREAD

**Issue by raboof** [akka/akka#30307]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8817/consoleFull

ReadyForShutdown did not equal Removed 
```
[info] [JVM-3] - must last nodes should shut down (on node 'third', class akka.cluster.singleton.ClusterSingletonManagerPreparingForShutdownMultiJvmNode3) *** FAILED ***
[info] [JVM-3]   self member: Member(akka://ClusterSingletonManagerPreparingForShutdownSpec@localhost:42399, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterSingletonManagerPreparingForShutdownSpec.scala:159)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3642453419?check_suite_focus=true#step:5:25525

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4571827990?check_suite_focus=true#step:5:27754

**Comment by pvlugter** [comment]
Test has:

```scala
runOn(second) {
  Cluster(system).leave(address(second))
  Cluster(system).leave(address(third))
}
```

CI failure (that still has logs) shows second node shutting down, but third node doesn't receive leaving, gossip envelopes going to deadletters.

Similar failure can be reproduced easily by sleeping between the `leave` instructions, so that the second node exits before instructing the third node to leave, since these both come from the second node.

Assuming that simply flipping these will make the test robust: from the second node, first instruct the third node to leave, allowing this to be gossiped before leaving itself.

Haven't reproduced at the finer level (delaying a particular gossip message at the right place), but the gossip is triggered immediately on leave and should be sent before internal cluster actors are stopped.
