### ISSUE TITLE
Restart backoff source does not backoff if the source takes longer than the min backoff

### ISSUE THREAD

**Issue by hizumisen** [akka/akka#30310]
```scala
import akka.actor.ActorSystem
import akka.event.Logging.DebugLevel
import akka.stream.scaladsl.{RestartSource, Sink, Source}
import java.util.concurrent.Executors
import scala.concurrent.duration._
import scala.concurrent.{ExecutionContext, Future}
val system = ActorSystem()
system.eventStream.setLogLevel(DebugLevel)
val materializer = Materializer.createMaterializer(system)
val ec1 = ExecutionContext.fromExecutor(Executors.newCachedThreadPool())
RestartSource.withBackoff(RestartSettings(
  100.millis,
  1000.millis,
  0.2
))(() => Source.future(Future { Thread.sleep(1000); 1 }(ec1)))
  .runWith(Sink.ignore)(materializer)
```

prints this
```
[DEBUG] [06/10/2021 10:03:57.220] [default-akka.actor.default-dispatcher-4] [RestartWithBackoffSource(akka://default)] Last restart attempt was more than 100 milliseconds ago, resetting restart count
[DEBUG] [06/10/2021 10:03:57.225] [default-akka.actor.default-dispatcher-4] [RestartWithBackoffSource(akka://default)] Restarting graph in 109583581 nanoseconds
[DEBUG] [06/10/2021 10:03:58.358] [default-akka.actor.default-dispatcher-5] [RestartWithBackoffSource(akka://default)] Last restart attempt was more than 100 milliseconds ago, resetting restart count
[DEBUG] [06/10/2021 10:03:58.358] [default-akka.actor.default-dispatcher-5] [RestartWithBackoffSource(akka://default)] Restarting graph in 108899298 nanoseconds
[DEBUG] [06/10/2021 10:03:59.482] [default-akka.actor.default-dispatcher-4] [RestartWithBackoffSource(akka://default)] Last restart attempt was more than 100 milliseconds ago, resetting restart count
[DEBUG] [06/10/2021 10:03:59.482] [default-akka.actor.default-dispatcher-4] [RestartWithBackoffSource(akka://default)] Restarting graph in 114223714 nanoseconds
```

as you can seen for every backoff iteration the systems restarts leading to no backoff basically.

**Comment by johanandren** [comment]
As I understand it the `resetDeadline` was introduced to be able to avoid this, did you try specifying that rather than defaulting to the `minBackoff`?

(It was introduced with this issue #29291 )

**Comment by hizumisen** [comment]
Maybe I misunderstand the behaviour of this backoff.
For me the wait duration was between the end of a source and the start of the next one.
Therefore I was not expecting a reset but a wait of 100ms between the first `Future { Thread.sleep(1000); 1 }` and the second.

As I understand correctly the backoff duration is measured between two elements emit, is that correct?

**Comment by johanandren** [comment]
The operator keeps a counter for restarts that is used to calculate the exponential backoff, and also to limit the number of restarts it would try before giving up. 

What you see with that **debug** log entry is when that counter is reset. In other words when the next stop/fail/start is not counted as a consecutive restart but a new one. It is based on the `maxRestartsWithin` setting and is applied after a new source has been created and not failed within the `within` timeout for `maxRestartsWithin`, default if you do not specify it is `minBackoff`.

In your case that means that if a restart or failure happens after the `200ms` `minBackoff` (which it does since you sleep for a second) it is not seen as a consecutive restart.

If you want to count restarts over a longer time period as consecutive restarts you can tune that with `withMaxRestarts(count, within)`

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for 2 years.

Should this issue be closed?
