### ISSUE TITLE
Akka stream InputBuffer attribute for flow no longer applied since Akka 2.6.15

### ISSUE THREAD

**Issue by thjaeckle** [akka/akka#30325]
After updating to Akka 2.6.15 we encountered that a configured `InputBuffer` attribute for a `Flow` is no longer respected.

The following reproducer unit test works with Akka 2.6.14, but fails with Akka 2.6.15:
```java
import static org.assertj.core.api.Assertions.assertThat;

import org.junit.BeforeClass;
import org.junit.Test;

import akka.actor.ActorSystem;
import akka.stream.Attributes;
import akka.stream.javadsl.Flow;
import akka.stream.javadsl.Keep;
import akka.stream.javadsl.Source;
import akka.stream.testkit.TestPublisher;
import akka.stream.testkit.TestSubscriber;
import akka.stream.testkit.javadsl.TestSink;
import akka.stream.testkit.javadsl.TestSource;

public class ReproducerStreamingAttributesTest {

    private static ActorSystem system;

    @BeforeClass
    public static void init() {
        system = ActorSystem.create();
    }

    @Test
    public void testStreamAttributesInputBuffer() {
        final var runnableGraph = TestSource.<Integer>probe(system)
                .viaMat(Flow.<Integer>create()
                        .withAttributes(Attributes.inputBuffer(1, 1))
                        .map(x -> Source.single(String.valueOf(x))), Keep.left()
                )
                .flatMapConcat(x -> x)
                .toMat(TestSink.probe(system), Keep.both());
        final var materializedValue = runnableGraph.run(() -> system);
        final TestPublisher.Probe<Integer> sourceProbe = materializedValue.first();
        final TestSubscriber.Probe<String> sinkProbe = materializedValue.second();

        sinkProbe.ensureSubscription();
        sourceProbe.ensureSubscription();
        sinkProbe.request(1);
        assertThat(sourceProbe.expectRequest()).isEqualTo(1);

        sourceProbe.sendNext(42);
        sourceProbe.sendComplete();
        final String outcome = sinkProbe.expectNext();
        sinkProbe.expectComplete();
        assertThat(outcome).isEqualTo("42");
    }

}
```

For Akka 2.6.15, this test fails (at line `assertThat(sourceProbe.expectRequest()).isEqualTo(1);`) with:
```
org.junit.ComparisonFailure: 
Expected :1L
Actual   :16L
```

As the changelog of Akka 2.6.15 mentioned something with "Improvements around stream attributes" we figured that this probably broke the previous behavior.

Or do we expect something wrong in the test case?

**Comment by johanandren** [comment]
The input buffer attribute should only apply to an async boundary for that graph island, so the correct way to express it is not to set it on the `Flow<Integer>.create()` as there is no buffer there (that empty `Flow` operation is likely completely optimized away).

The attributes applies to the graph you call `.withAttributes` (or `.addAttributes`) on, so in this case, for the attribute to apply to the graph source it would have to be called on the graph returned by `.probe().withAttributes(...)`, `viaMat().withAttributes`, and so on, depending on how much of the final graph you'd want it to apply to.

It is curious that it used to work like this at all, I think the change in behavior could be a consequence of a bugfix for how the buffer attribute is picked up #30195 (not entirely sure how though). To sum it up: the new behavior is the correct one and the old is unintended.

**Comment by johanandren** [comment]
I'll close this unless you think there is some docs around this missing @thjaeckle ?

The most relevant existing docs I think would be at the end of this page:
https://doc.akka.io/docs/akka/current/stream/stream-composition.html#attributes
and also on this page:
https://doc.akka.io/docs/akka/current/stream/stream-rate.html

**Comment by thjaeckle** [comment]
@johanandren yes, go ahead and close it .. we'll have to look into where we relied on the old/wrong behavior then..

**Comment by Yannic92** [comment]
I think I still have some issues in understanding the change.

From [the documentation you linked](https://doc.akka.io/docs/akka/current/stream/stream-composition.html#attributes) I have the following statement:

>When it comes to hierarchic composition, attributes are inherited by nested modules, unless they override them with a custom value.

There is also an example code which shows a nested flow with a defined input buffer.
Below the example there is this statement:

> nestedFlow will inherit from nestedSink except the map operator which has again an explicitly provided attribute overriding the inherited one.

Now I'm not sure what happens when the sink of this example requests new input. Will the request be limited by the input buffer of the nested flow? Or is the default input buffer of the original source still applied?

A second question is: Why were you referring to async boundaries? In the example shown above I don't see any async boundary. Did I miss something?

**Comment by johanandren** [comment]
That sample is sadly a bit synthetic for `inputBuffer`, because the input attribute will not actually be used by the `map` as there is no buffer in the map operator and no asynchronous boundary, it only shows how you would set an (arbitrary) attribute specifically for that subsection of the graph, even though you had explicitly also set the same attribute further "out" in the graph. Attributes selected for an operator will be the "most specific" or "closest to the operator" in the graph. (I've created an issue to track improving that doc section: https://github.com/akka/akka/issues/30332 )

The `inputBuffer` attribute controls implicit buffers created by async boundaries, and in some cases, explicit internal buffers used by operators - any operator can read attributes and use them in a way that makes sense for that operator.

In this case an async boundary is introduced by the fact that the stream testkit probe is implemented as a Reactive Stream publisher under the hood, which always causes an async boundary - the publisher does not run in the same actor/stream execution engine as the stream operators.

The PR I referred #30195 to fixed a bug where `Source.fromPublisher().withAttributes(some-input-Buffer).map().etc()` would not correctly see that "most specific" input buffer attribute.

**Comment by Yannic92** [comment]
Thank you for the explanation.

**Comment by dssysolyatin** [comment]
@johanandren I have kind of similar problem after updating akka from 2.6.14 to 2.6.15. input buffer does not change for the async boundary. The following line does not work for me after updating akka:
```
worker.async(Dispatchers.DefaultBlockingDispatcherId, 1) 
```
The buffer size still is 16

Code of test is following:
```
package com.test.test

import akka.NotUsed
import akka.actor.ActorSystem
import akka.dispatch.Dispatchers
import akka.stream.FlowShape
import akka.stream.scaladsl.{Balance, Flow, GraphDSL, Merge, Sink, Source}
import org.scalatest.{Matchers, WordSpec}
import org.scalatest.concurrent.Eventually
import org.scalatest.time.{Millis, Span}

import java.util.concurrent.atomic.AtomicInteger
import scala.concurrent.duration.Duration
import scala.concurrent.{Await, Future, Promise}

class BalanceTestSpec extends WordSpec with Eventually with Matchers  {
  override implicit val patienceConfig: PatienceConfig = PatienceConfig(
    scaled(Span(2000, Millis)),
    scaled(Span(15, Millis))
  )

  "balance test" in {
    implicit val system: ActorSystem = ActorSystem("BalanceTestSpec")

    // if number of jobs < 16 test will print 0 and test will fail
    // if number of jobs > 16, then at least one foreach cycle will be executed but test still will fail
    val numberJobs = 16
    val numberWorkers = 2
    val numberTasksInProgress = new AtomicInteger(0)

    val promises = (0 until numberJobs).map(_ => Promise[Unit]).toVector
    val jobs: Source[Future[Unit], NotUsed] = Source
      .fromIterator(() => promises.iterator.map(_.future))

    val worker = Flow[Future[Unit]].map { f =>
      numberTasksInProgress.incrementAndGet()
      Await.result(f, Duration.Inf)
      numberTasksInProgress.decrementAndGet()
      ()
    }

    val flow = jobs
      .via(Flow.fromGraph(GraphDSL.create() { implicit b =>
        import GraphDSL.Implicits._

        val balancer = b.add(Balance[Future[Unit]](numberWorkers))
        val merge = b.add(Merge[Unit](numberWorkers))

        (1 to numberWorkers).foreach(_ => {
          balancer ~> worker.async(Dispatchers.DefaultBlockingDispatcherId, 1) ~> merge
        })

        FlowShape(balancer.in, merge.out)
      }))

    flow.runWith(Sink.ignore)

    (0 until numberJobs - 2).foreach { i =>
      println(i)
      eventually {
        numberTasksInProgress.get() should be (2)
      }

      promises(i).trySuccess(())
    }
  }
}
```


How can I change the async input buffer for this case?

**Comment by johanandren** [comment]
@dssysolyatin please try to create a minimal repeater with a single stream and a boundary that doesn't get the right buffer size, and open up a new issue attaching that.

**Comment by dssysolyatin** [comment]
@johanandren https://github.com/akka/akka/issues/30935
