### ISSUE TITLE
Avoid using marcospereira/action-surefire-report fork in nightly builds

### ISSUE THREAD

**Issue by marcospereira** [akka/akka#30568]
_Originally posted by @johanandren in https://github.com/akka/akka/pull/30551#discussion_r694672818_

**Comment by johanandren** [comment]
"Using a fork until we decide if this is useful and how to add it here safely"

So, once we decide it is useful, make it more official somehow.

**Comment by Captain1653** [comment]
This issue was fixed in [this PR](https://github.com/akka/akka/commit/f0095dd27483ab0cc6352c5cc4a16b611877ee80#diff-e780cb03e0575bf97176af613cf9b23d9337cc6a8d309a7475704fc756cfcce3R53) .

There are no more using this fork:
<img width="1360" alt="Screenshot 2023-09-10 at 19 02 19" src="https://github.com/akka/akka/assets/4740207/e94b1111-be15-48f1-a225-11ea3ed1a10a">

Should this issue be closed?

**Comment by johanandren** [comment]
Thanks @Captain1653
