### ISSUE TITLE
Allow finer control of onPersistFailure with when actor stops

### ISSUE THREAD

**Issue by amdelamar** [akka/akka#30596]
I'd like to be able to control the behavior of `persist()` call failure in my PersistentActor. Currently I get a CB timeout, and the actor stops abruptly.  In my project, calling `persist()` is a secondary purpose and not as important as the other primary function I want. Stopping the actor is not what I'd like to do if persistence fails.

```
2021-08-30 18:31:30,440 [ERROR] [my-example-system-akka.actor.default-dispatcher-4751] [com.amdelamar.example.MyActor] - Failed to persist event type [com.amdelamar.example.Message] with sequence number [16577921] for persistenceId [7].
akka.pattern.CircuitBreaker$$anon$13: Circuit Breaker Timed out.
```

I have this:

```scala
persist(message) { _ =>
  // do work
}
```

But I'd really like to have:

```scala
persist(message) {
  case Success(_) =>
    // do work
  case Failure(e) =>
    // log and move on, don't stop actor. (Optionally, I can call `context.stop(self)` if I deem it necessary.)
}
```

**Comment by patriknw** [comment]
This is not something we can add because it wouldn't be safe. If there is a timeout there is no way to know if the event was stored or not and therefore the consistency semantics of the persistent actor would be broken. It could end up in a different state after a restart than it has if it just ignores the timeout.

If persistence is a secondary concern in your application you should model that with two separate actors. First an ordinary actor that performs the primary effect and then delegates to a (child) persistent actor.

See also https://doc.akka.io/docs/akka/current/typed/persistence.html?_ga=2.168617700.4743060.1630514374-1466146766.1628579921#journal-failures
