### ISSUE TITLE
Replace Receive in AbstractBehavior with Behavior for Java 

### ISSUE THREAD

**Issue by FlorianSchaetz** [akka/akka#30739]
`AbstractBehavior `in Java has one very important drawback: You have to override `createReceive `as an entry point, which returns a Receive instead of a Behavior. This makes a lot of easy things hard:

- Starting with a stash (can be done via constructor injection, still annoying)
- Cannot start out supervising, since Behaviors.supervise will not return a Receive, only a Behavior

Is there really any need for this Receive in Akka Typed? Wouldn't it be more streamlined to rely soley on Behavior?

**Comment by johanandren** [comment]
The builder for the Java side is intended to somewhat provide the same convenience of `PartialFunction` from the Scala side rather than long if-instanceof-else-if-chains as message handlers, but also to align the typed API with the classic API, which has had that style for a long while. That `createReceive()` returns `Receive` rather than `Behavior` (even through `Receive` is a `Behavior` is to provide guidance to new users through the type system how to use the APIs.

Both supervising and accessing a stash is expected to be done through composition/injection just like setup and also is the same across Java and Scala APIs as well as OO and FP style actor APIs.

If you want a different setup because of some special needs (or personal taste) for initial behavior you should be able to extend `ExtensibleBehavior` directly instead.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for almost 2 years.

Should this issue be closed?
