### ISSUE TITLE
Sink.asPublisher fails with invalid error on timeout

### ISSUE THREAD

**Issue by worekleszczy** [akka/akka#30908]
Hello

I stumbled upon what I think is invalid error message when publisher created from `Sink.asPublisher(fanout = false)` times out. 

After executing
```
def test: Unit = {
	val publisher = Source.single("hello world").toMat(Sink.asPublisher(false))(Keep.right)
	.addAttributes(ActorAttributes.streamSubscriptionTimeout(1.second, StreamSubscriptionTimeoutTerminationMode.cancel))
	.run()
	Thread.sleep(2000)

	Source.fromPublisher(publisher).runWith(Sink.head).onComplete {
		case Success(value) => println(value)
		case Failure(ex) => println(ex.getMessage)
	}
}
```
function result in error `Sink.asPublisher(fanout = false) only supports one subscriber (which is allowed, see reactive-streams specification, rule 1.12)` instead of pointing to timeout being the real reason the operation failed. Another thing is that at this point I can't find rule `1.12` in reactivestreams specification - I guess that this should be updated to rule `1.11`.

**Comment by johanandren** [comment]
The reason for this that when you run `fromPublisher` with cancel mode and the subscription timeout hits the publisher is cancelled, through subscribing to it with a cancelling subscriber, when you later try to subscribe to it that is no longer possible because it was already subscribed to (and cancelled). So the error, while not very intuitive, is correct.

I think you are right about the rule number, I'll update that.
