### ISSUE TITLE
failed: EntityPassivationSpec in nightly build

### ISSUE THREAD

**Issue by octonato** [akka/akka#30952]
https://github.com/akka/akka/runs/4293593178?check_suite_focus=true
 
Failed on nightly build on the 23rd Nov, the day in which https://github.com/akka/akka/pull/30933 was merged. Some extra tweaking for CI needed? 

```scala
<-- [Passivation of least frequently used entities must passivate the least frequently used entities when the per-shard entity limit is reached] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (12 seconds) during expectMsgClass waiting for class akka.cluster.sharding.EntityPassivationSpec$Entity$Received)]
[info] - must passivate the least frequently used entities when the per-shard entity limit is reached *** FAILED *** (12 seconds, 428 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (12 seconds) during expectMsgClass waiting for class akka.cluster.sharding.EntityPassivationSpec$Entity$Received
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:553)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:552)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]   at akka.cluster.sharding.AbstractEntityPassivationSpec.expectReceived(EntityPassivationSpec.scala:125)
[info]   at akka.cluster.sharding.LeastFrequentlyUsedEntityPassivationSpec.$anonfun$new$32(EntityPassivationSpec.scala:486)
[info]   at akka.cluster.sharding.LeastFrequentlyUsedEntityPassivationSpec.$anonfun$new$32$adapted(EntityPassivationSpec.scala:485)
[info]   at scala.collection.immutable.List.foreach(List.scala:431)
[info]   at akka.cluster.sharding.LeastFrequentlyUsedEntityPassivationSpec.$anonfun$new$24(EntityPassivationSpec.scala:485)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by pvlugter** [comment]
I can see what this issue is from the logs, and some changes to the sharding state machine may be useful here.

One of the passivating entities has received new messages before terminating, and the messages get buffered. When it is actually terminated, it gets restarted and messages delivered. On this restart path it ends up tracking the entity creation and the message delivery as 2 accesses to this entity, while the usual path tracks the first message plus entity creation as just 1 access. Since this is the least frequently used strategy, the difference in expected frequency count changes the expectations for later passivations, while recency-based strategies won't be affected.

Could adjust the test to avoid this timing, but ideally it marks this as a single access for a restarted entity anyway. Looks like it could simply not immediately restart the entity but let that happen on message delivery, making this the same as first message delivery. But `getOrCreateEntity` is called multiple times on this restart and deliver buffer path, so need to make sure simplifying things in this way by removing those doesn't change behaviour for anything else. Alternatively could signal that it's a restarted state in some way to avoid recording the message delivery as a second access in this case.

**Comment by pvlugter** [comment]
Actually, I think I'll adjust this in a different way. Passivation strategies are not using the distinction between newly created entities and touched entities, so I'll simplify this instead. I'll look at reproducing and fixing next week.
