### ISSUE TITLE
Add context/attachment to akka.stream.stage.TimerGraphStageLogic#onTimer?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#30978]
```scala
  /**
   * Will be called when the scheduled timer is triggered.
   *
   * @param timerKey key of the scheduled timer
   */
  @throws(classOf[Exception])
  protected def onTimer(@unused timerKey: Any): Unit = ()
```

It would be great if the method can carray some context information about this scheduling

```scala
  /**
   * Will be called when the scheduled timer is triggered.
   *
   * @param timerKey key of the scheduled timer
   * @param attachment the attachment of this scheduling
   */
  @throws(classOf[Exception])
  protected def onTimer(@unused timerKey: Any, attachment: Any): Unit = ()
```

**Comment by hepin1989** [comment]
Seems I can achive it with the custom timerKey too.

**Comment by johanandren** [comment]
Yeah, you can use `timerKey` for that since it is `Any` as a workaround, or keep a local map of key->context.

Having such a per key context could be nice but it is problematic adding new methods to these traits while keeping binary compatibility, so not sure it is worth the effort given that workarounds are relatively straight forward.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments almost for 2 years.

Workarounds are relatively straight forward. 

Should this issue be closed?
