### ISSUE TITLE
Expose GetTopicStats for public use

### ISSUE THREAD

**Issue by JustinPihony** [akka/akka#31035]
In the scenario where you use the pubsub Topic and publish a message immediately after the first subscribe then the message will be lost ([due to the registration flow](https://github.com/akka/akka/blob/v2.6.18/akka-actor-typed/src/main/scala/akka/actor/typed/internal/pubsub/TopicImpl.scala#L98). As such, if you expose `GetTopicStats` then the consumer can wait for the instance size to match akin to [this test](https://github.com/akka/akka/blob/main/akka-actor-typed-tests/src/test/scala/akka/actor/typed/pubsub/LocalPubSubSpec.scala#L32). Otherwise they need to add a few ms wait, which is not optimal

**Comment by johanandren** [comment]
Sounds ok to make this public, for this and perhaps other use cases.

It could make sense to have some form of variation of `Publish` with an actor ref to pass the message to if there was no known subscribers rather than to dead letter?

Note that having observed that there is at least one subscriber is not enough for some form of delivery guarantee since the subscriber could disappear (stop, unsubscribe, node crash or unreachable) after observing that but before publishing a message or the message reaching it across nodes.
