### ISSUE TITLE
CVE-2021-22569 Update protobuf version

### ISSUE THREAD

**Issue by xuwei-k** [akka/akka#31069]
> An issue in protobuf-java allowed the interleaving of com.google.protobuf.UnknownFieldSet fields in such a way that would be processed out of order. A small malicious payload can occupy the parser for several minutes by creating large numbers of short-lived objects that cause frequent, repeated pauses. We recommend upgrading libraries beyond the vulnerable versions.

- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22569
- https://github.com/advisories/GHSA-wrvw-hg22-4m67
- https://github.com/akka/akka/blob/9d0684d875dc935efd8200cf6a6ac47113e24aa6/project/Dependencies.scala#L25

**Comment by mkurz** [comment]
Is there an ETA for akka 2.6.19?

**Comment by johanandren** [comment]
Thanks for letting us know, we are looking into if we can bump the dependency without wire compability issues.

Two important notes related to this: 
1. The shaded protobuf is just for the internal use of Akka, a user project using protobuf serialization should pull in protobuf as a library the "normal" way and can update the version they use themselves. 
2. Akka remoting ports should never be open to the public, somewhat mitigating the effect of this vulnerability since it requires a malicous user to be able to send protobuf messages for remoting to deserialize to exploit.

**Comment by ennru** [comment]
Updated with #31072
