### ISSUE TITLE
upgrade jackson

### ISSUE THREAD

**Issue by pjfanning** [akka/akka#31237]
I couldn't find an open issue but would it be possible to consider updating jackson in the akka 2.7 milestone (https://github.com/akka/akka/milestone/152)?

Jackson is used in akka-jackson-serialization and scala 3 support only exists in jackson 2.13.x (and above).

akka-jackson-serialization appears to be preconfigured to load jackson-module-scala despite the fact the dependency has been removed for akka scala 3 releases - see https://github.com/akka/akka/blob/main/akka-serialization-jackson/src/main/resources/reference.conf#L20

**Comment by raboof** [comment]
> I couldn't find an open issue

#31097 is related: I think jackson 2.13 can be used with Akka, but indeed we don't provide it as a transitive dependency.

> would it be possible to consider updating jackson in the akka 2.7 milestone (https://github.com/akka/akka/milestone/152)?

That makes sense to me, but note that we haven't even started planning 2.7 in earnest yet, so that might be some time out.

> Jackson is used in akka-jackson-serialization and scala 3 support only exists in jackson 2.13.x (and above).

We might have wiggle room here: since our Scala 3 artifacts are still experimental, perhaps we could depend on Jackson 2.13 for the Scala 3 artifacts. Of course this would introduce trouble when Jackson 2.11 and Jackson 2.13 would change in (source)incompatible ways, but so far this has been rather stable.

**Comment by pjfanning** [comment]
Thanks @raboof - I'll close this in favour of #31097

**Comment by patriknw** [comment]
@pjfanning could you open a PR that updates the Jackson version for Scala 3? I think the issue was about updating for all Scala versions, but that is not what we will do now.

**Comment by pjfanning** [comment]
@patriknw I'll have a look at creating a PR. I'm thinking that I'll update the scala3 version to 3.1.1 too - just not to have a dependency on a RC release of scala3 either (if that's ok).
