### ISSUE TITLE
Should add a timer to complete the stage if the completion is deferred?

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#31331]
When I was doing some defering of the upstream `completion` in https://github.com/akka/akka/pull/31330, I was thingking about what if the downstream never issue any more demonds anymore? Shold a upstream stage propagates the `upstreamFinished` timely ?

Should we add a timer which will sending the `onCompleted` to downstream after a configured time elapsed?eg:
```akka.stream.materializer.defer-completion-timeout```?

Currently I think we can combine with an `idleTimeout` to partially address this.

**Comment by johanandren** [comment]
If completing based on a timeout because of upstream completion without demand depends on the operator/stage in question and what it does, I don't think there can be a general completion-timeout like that. An operator where it does make sense can implement it with the existing timer support, a user stream use case where it makes sense can probably compose it with `backpressureTimeout` or `idleTimeout`.

**Comment by johanandren** [comment]
Let's close this since it seems you agree :)
