### ISSUE TITLE
Suspicious dead code in `SourceRefImpl`

### ISSUE THREAD

**Issue by mpdn** [akka/akka#31438]
I am investigating an issue in which streams in my application are being failed with an `SubscriptionWithCancelException.NoMoreElementsNeeded` exception. I stumbled upon some suspicious dead code, although I don't think its related to my initial issue, as I do not use stream refs.

But either way, the issue is here:

https://github.com/akka/akka/blob/3c3e8286e27564db894703ed00d371174a295a25/akka-stream/src/main/scala/akka/stream/impl/streamref/SourceRefImpl.scala#L422-L425

Here we match on `cause`, a `Throwable`, and check if it is an `SubscriptionWithCancelException`.

But the only places where this interface is implemented is these two:
https://github.com/akka/akka/blob/7abc41cf4e7e8827393b181cd06c5f8ea684e696/akka-stream/src/main/scala/akka/stream/impl/fusing/ActorGraphInterpreter.scala#L448
https://github.com/akka/akka/blob/7abc41cf4e7e8827393b181cd06c5f8ea684e696/akka-stream-testkit/src/main/scala/akka/stream/testkit/StreamTestKit.scala#L892-L894

Neither of which implements `Throwable`. So there is no class that implements both `Throwable` and `SubscriptionWithCancelException`, and thus that case can never be executed (reflection shenanigans notwithstanding)

It was probably meant to be `case _: SubscriptionWithCancelException.NonFailureCancellation => completeStage()` instead.

**Comment by johanandren** [comment]
Indeed, would you mind PR:ing a fix?

**Comment by Captain1653** [comment]
I can fix it, but I need some clarification:
1. Since it was added [here](https://github.com/qyl2021/scala-akka/commit/fc0c98e17aaf85def696c4d58ca3395e23c3cca8#diff-055591900aa37adebd8067e08e32779eb6508d03a706a09edaadbe01e04d9182) it works `case failure                            => failStage(failure) `. `failStage` for every `Throwable`.
2. This change `case _: SubscriptionWithCancelException.NonFailureCancellation => completeStage()` will change the logic above. For some `Throwable` will be `completionStage()`. Is it what we need? It's some "breaking change". 

 Did I get something wrong?

**Comment by johanandren** [comment]
I'd expect the intended logic would be to complete if the exception is a `akka.stream.SubscriptionWithCancelException.NonFailureCancellation` and fail for other exeptions

**Comment by Captain1653** [comment]
The PR was merged. Is it worth adding it to 2.6.20 milestone?

**Comment by johanandren** [comment]
Thanks, we missed that.
