### ISSUE TITLE
Feature request: `Sink.combine` for `Unzip`

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [akka/akka#31473]
We can use `Sink.combine` for some fan-out strategies like `Broadcast`:

```scala
Source(List(0, 1, 2))
  .to(
    Sink.combine(
      Sink.foreach[Int](left => println(s"left = ${left}")),
      Sink.foreach[Int](right => println(s"right = ${right}"))
    )(Broadcast[Int](_))
  )
  .run()
```

It would be neat if we can also use it with `Unzip`:

```scala
Source(List((0, "zero"), (1, "one"), (2, "two")))
  .to(
    Sink.combine(
      Sink.foreach[Int](left => println(s"left = ${left}")),
      Sink.foreach[String](right => println(s"right = ${right}"))
    )(Unzip[Int, String]())
  )
  .run()
```

However this is not currently possible because `Sink.combine` expects a `UniformFanOutShape` while `Unzip` is a `FanOutShape2`.

**Comment by johanandren** [comment]
Probably hard to abstract over since the fanout output-arity is represented by concrete FanoutShape classes. Alternative is to provide only one "combiner" for arity two but then the usefulness is much limited and could just as well be specifically a `Sink.unzip(left, right)`. 

I'm not entirely convinced that is common enough to warrant a custom operator given that it is already possible to use the GraphDSL to achieve that already today.

**Comment by Captain1653** [comment]
This issue is quite old. There are no new comments for 1 year.

There are some problems with this approach. Should this issue be closed? Maybe :)
