### ISSUE TITLE
Add an overloaded method for `scheduler.scheduleOnce` etc which accepts an Executor for JavaApi?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31653]
I have to wrap it as an ExecutionContext
For now:
```java
                    final Scheduler scheduler = actorSystem.getScheduler();
                    final ExecutionContext executor = sendMessageExecutorProvider.getExecutionContext(namespace);
                    return scheduler.scheduleOnce(
                        Duration.ofMillis(timeBeforeFlushInMills),
                        () -> {
                           //do something ...
                        },
                        executor);
```

**Comment by johanandren** [comment]
I think we expect it to be used with the dispatcher rather than some external executor, and the main choice should anyway not be the lambda based one but the Actor/timer ones leading to messages being sent and configuring what ex sends the message is not really important. So no real reason to make that more convenient IMO

**Comment by He-Pin** [comment]
OK, let's me closed this then.
