### ISSUE TITLE
Event Sourcing Issues with EventSourcedBehavior

### ISSUE THREAD

**Issue by 0bon** [akka/akka#32014]
When using `EventSourcedBehavior` to persist events (`Effect.persist`), from what I understand, this persistence mechanism is to internally maintain state and is not for consumption by other microservices.

This introduces a number of issues, since event sourcing is usually applicable to a group of services - those services can access and handle events by subscribing to topics on a message queue.

My current approach is to `Effect.persist(...).thenRun(pushToMessageQueue())` but this is very problematic. What if the MQ is down ? or some other issue emerges that prevents the event from being pushed onto the MQ. This will create data in inconsistencies which can cause serious accumulative effects overtime.

As it currently stands, I am having to build out an elaborate system of retries + using durable states in case the actorsystem crashes, and even then, there are still loopholes which could lead to data inconsistencies.

I think there needs to be a discussion about how this issue can be rectified in a more proper fashion. Below are some thoughts running through my mind:

1. Introduce transactions. If `thenRun` fails then rollback the `persist()` action. Ensuring atomicity is pretty standard with database transactions. Maybe something similar can be implemented here. Either all actions succeed or they all fail.
2. Create persistence plugins for backends that actually support event sourcing i.e. Eventstore. You might say there already is one, but it is outdated and no one from EvenstoreDB is giving it the much needed TLC. Kafka is bad news for ES and EventStore fixes many of the underlying issues and should be supported officially for  `EventSourcedBehavior`.  But in order for this to work the user should be able to define different streams and assign events to them respectively.

Option 1 is elegent, quick and shouldn't be too difficult to implementation. Option 2 would require a lot of ground work but would be more powerful since it reduces overhead and infrastructural needs.

**Comment by octonato** [comment]
The `Effect.persist` is indeed to persist the events for the current entity. The intention is not to use it to propagate events further down to other systems. For that, you should instead look at [Akka Projection](https://doc.akka.io/docs/akka-projection/current/). 

Akka Projection provides the necessary building blocks to consume the events and track what has been consumed or not. Furthermore, it allows you to distribute the load over different nodes. 

About your suggestions, transactions will only work if what you run in `thenRun` goes to the same database where the events are being persisted. You can't have a transaction across a database and some other system (eg: a broker, an external endpoint or a different type of db). 

So basically, option 1 is neither quick nor easy to implement. And even if we use the same DB or something like XA transactions, it's also not desirable because it will incur increased contention when writing to the journal. We are better served with writes on an append-only journal and reads done by Akka Projection.


About suggestion 2, I don't get what you mean by "backends that actually support event sourcing". Eventstore is certainly a good option for event sourcing, but there are many more alternatives. As you could noticed, there is not much interest in the community to develop a plugin for EventstoreDB. 

On the other hand, our community and customers have been using the existing plugins (Cassandra, JDBC and R2DBC) successfully. 

I suggest you consult our [Akka Guide](https://developer.lightbend.com/docs/akka-guide/microservices-tutorial/index.html). It has a comprehensive tutorial on how to build an event-sourced system using Akka Persistence on the write side and Akka Projection on the read side.

**Comment by octonato** [comment]
I'm closing this issue as it's more like a discussion topic. 
For help and discussions is better to use https://discuss.lightbend.com
