### ISSUE TITLE
Logger documentation probable issue.

### ISSUE THREAD

**Issue by krnkhanna** [akka/akka#32069]
Should it be context.log.info("Greeting {} for {}", n, message.whom), in place of context.log.info2("Greeting {} for {}", n, message.whom)
 in the documentation at: https://doc.akka.io/docs/akka/current/typed/actors.html (https://github.com/akka/akka/blob/9745f8857e38ef4b860d7785272103bfc6a868f0/akka-actor-typed-tests/src/test/scala/docs/akka/typed/IntroSpec.scala#L59)?

**Comment by leviramsey** [comment]
The Scala compiler often has issues selecting the intended `info` etc. message when there are two substitution arguments.  https://doc.akka.io/api/akka/current/akka/actor/typed/scaladsl/package$$LoggerOps.html (often pulled in as part of an `import akka.actor.typed.scaladsl._`) adds `info2` and friends.

**Comment by krnkhanna** [comment]
Hi @leviramsey, context.log is of type org.slf4j.Logger which don't have a method info2. I am new with Scala may be missing something here.

![image](https://github.com/akka/akka/assets/16244430/ed46f602-ce4e-430e-a422-5023aa98f41a)

**Comment by leviramsey** [comment]
Scala allows, effectively, methods to be added to classes via "extension methods" (see, for instance https://docs.scala-lang.org/tour/implicit-conversions.html).

In this case, the `LoggerOps` class is defined as

```
implicit class LoggerOps(val log: Logger) extends AnyVal {
  def info2(format: String, arg1: Any, arg2: Any): Unit = {
    log.info(format, arg1, arg2)
  }
}
```

So when the Scala compiler sees that you're calling `log.info2` it notices that there's no `info2` method in `Logger`.  It then searches to see if there's exactly one implicit conversion (one is implicitly (ha!) generated by marking a class with a single constructor which takes a single argument as an `implicit class`) pulled into scope to a class with a compatible `info2` method; if there is exactly one such conversion, the compiler will insert a call to that method, so the

```
context.log.info2("Greeting {} for {}", n, message.whom)
```

becomes

```
new LoggerOps(context.log).info2("Greeting {} for {}", n, message.whom)
```

Since `LoggerOps` extends `AnyVal` and nothing is being done with it that would actually require a heap allocation, the compiler effectively makes the `info2` a static method with an extra `Logger` argument, so it would look something like the Java for:

```
LoggerOps.info2(context.log, "Greeting {} for {}", n, message.whom) // static method call
```

This ability to add methods to existing classes at the use site is a great power in Scala and comes with great responsibility... it's really easy to use this in a way that impedes figuring out what's really happening.
