### ISSUE TITLE
Asktimeouts happening everytime there is scaling based on cpu usage

### ISSUE THREAD

**Issue by sulo-genius** [akka/akka#32498]
Hi

Currently clusters are configured in a way that is scales up/down based on cpu usage

However, everytime this happens we are observing asktimeouts for short duration.
Can this be avoided?

**Comment by johanandren** [comment]
Which Akka version and what cluster components are you using?

**Comment by sulo-genius** [comment]
Using 2.6.19

**Comment by johanandren** [comment]
Note that Akka 2.6 reached EOL in Oct 2023. I recommend that you upgrade to current versions and see if you can still observe a lot of timeouts and or try asking in the forums over at https://discuss.akka.io (Note that if you do post, provide more details about what you built, and what parts of Akka you use, and it will be more likely that you cat get an answer there)

If it turns out to be a bug or something that can be improved in Akka we can open a new issue with more details.
